<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Muhammad Khan Muneer">
<meta name="keywords" content="A/B test design, power analysis, minimum detectable effect, design feasibility, stratified randomisation, sample ratio mismatch, covariate balance, Welch t-test, Monte Carlo validation, Type I error, sequential monitoring, guardrail metric, Starbucks capstone, Python, scipy">
<meta name="description" content="A methods demonstration: how to design a trustworthy randomised experiment on a dataset that cannot supply a clean control arm. The constraint: only 6 of 17,000 customers received zero offers, so “offer vs no offer” is structurally impossible; the control outcome is observed 30-day spend and the treatment effect is injected synthetically, declared, then recovered with the truth hidden. The feasibility sweep: a USD 2 MDE needs ~52,000 customers per arm against a ~14,800 pool; USD 5 needs ~8,400; only MDE ≥ USD 7 (≈6% relative lift, 4,263 per arm) is deliverable — and filtering to transacting customers does not reduce the outcome SD. Validation before inference: 2,000 full-pipeline Monte Carlo runs give realised power 90.1% (Wilson 95% CI [88.1, 91.8]) and realised Type I error 3.5% ([2.5, 4.8]) — both guarantees confirmed empirically. The result: a one-sided Welch t-test recovers an observed lift of USD 8.95 against the injected USD 8.40 (6.5% error), t = 2.95, p = 0.0016, one-sided 95% lower bound USD 3.96; the transaction-count guardrail is silent (p = 0.39).">

<title>Designing an A/B Test the Data Cannot Support at Face Value: A Feasibility Sweep, a Monte-Carlo-Validated Design, and a Recovered Hidden Effect – Muhammad Khan Muneer</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-4d9afe2b8d18ee9fa5d0d57b5ed4214d.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-5af9b5ab1fa0c387551d40c1aacb317e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-ca0cfe78a00f84493d894d8af57a3a20.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-5af9b5ab1fa0c387551d40c1aacb317e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": true,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<link rel="stylesheet" href="../../styles/custom.css">
<meta property="og:title" content="Muhammad Khan Muneer — Data Science &amp; BI Portfolio">
<meta property="og:description" content="Engineering ML-driven analytics and automated decision systems.">
<meta property="og:image" content="https://mkhanmuneer.github.io/projects/starbucks-simulated-ab-test-design-feasibility-monte-carlo-validation/assets/fig7_recovery.png">
<meta property="og:site_name" content="M. Khan Muneer Portfolio">
<meta property="og:image:alt" content="A one-dimensional plot on a USD axis from zero to sixteen. A blue bar runs from the one-sided ninety-five percent lower bound at USD three point nine six to the recovered point estimate at USD eight point nine five. A red dashed line and diamond mark the injected truth at USD eight point four zero; a gold dotted line marks the pre-registered MDE at USD seven. A caption states the injected and recovered values and the p-value.">
<meta property="og:image:height" content="663">
<meta property="og:image:width" content="1547">
<meta name="twitter:title" content="Designing an A/B Test the Data Cannot Support at Face Value: A Feasibility Sweep, a Monte-Carlo-Validated Design, and a Recovered Hidden Effect – Muhammad Khan Muneer">
<meta name="twitter:description" content="A methods demonstration: how to design a trustworthy randomised experiment on a dataset that cannot supply a clean control arm. The constraint: only 6 of 17,000 customers received zero offers, so “offer vs no offer” is structurally impossible; the control outcome is observed 30-day spend and the treatment effect is injected synthetically, declared, then recovered with the truth hidden. The feasibility sweep: a USD 2 MDE needs ~52,000 customers per arm against a ~14,800 pool; USD 5 needs ~8,400; only MDE ≥ USD 7 (≈6% relative lift, 4,263 per arm) is deliverable — and filtering to transacting customers does not reduce the outcome SD. Validation before inference: 2,000 full-pipeline Monte Carlo runs give realised power 90.1% (Wilson 95% CI [88.1, 91.8]) and realised Type I error 3.5% ([2.5, 4.8]) — both guarantees confirmed empirically. The result: a one-sided Welch t-test recovers an observed lift of USD 8.95 against the injected USD 8.40 (6.5% error), t = 2.95, p = 0.0016, one-sided 95% lower bound USD 3.96; the transaction-count guardrail is silent (p = 0.39).">
<meta name="twitter:image" content="https://mkhanmuneer.github.io/projects/starbucks-simulated-ab-test-design-feasibility-monte-carlo-validation/assets/fig7_recovery.png">
<meta name="twitter:creator" content="@iMKhanMuneer">
<meta name="twitter:site" content="@iMKhanMuneer">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image:alt" content="A one-dimensional plot on a USD axis from zero to sixteen. A blue bar runs from the one-sided ninety-five percent lower bound at USD three point nine six to the recovered point estimate at USD eight point nine five. A red dashed line and diamond mark the injected truth at USD eight point four zero; a gold dotted line marks the pre-registered MDE at USD seven. A caption states the injected and recovered values and the p-value.">
<meta name="twitter:image-height" content="663">
<meta name="twitter:image-width" content="1547">
</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../index.html#featured-projects"> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/mkmuneer"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mkhanmuneer"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://x.com/iMKhanMuneer"> <i class="bi bi-twitter-x" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.kaggle.com/muhammadkhanmuneer"> <i class="bi bi-graph-up" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../index.html#contact"> 
<span class="menu-text">Contact</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract">Abstract</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#method" id="toc-method" class="nav-link" data-scroll-target="#method">Method</a>
  <ul class="collapse">
  <li><a href="#data-source" id="toc-data-source" class="nav-link" data-scroll-target="#data-source">Data source</a></li>
  <li><a href="#pre-registered-design" id="toc-pre-registered-design" class="nav-link" data-scroll-target="#pre-registered-design">Pre-registered design</a></li>
  <li><a href="#the-feasibility-sweep" id="toc-the-feasibility-sweep" class="nav-link" data-scroll-target="#the-feasibility-sweep">The feasibility sweep</a></li>
  <li><a href="#simulation-model" id="toc-simulation-model" class="nav-link" data-scroll-target="#simulation-model">Simulation model</a></li>
  <li><a href="#analysis" id="toc-analysis" class="nav-link" data-scroll-target="#analysis">Analysis</a></li>
  <li><a href="#software" id="toc-software" class="nav-link" data-scroll-target="#software">Software</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#feasibility-only-mde-usd-7-is-deliverable" id="toc-feasibility-only-mde-usd-7-is-deliverable" class="nav-link" data-scroll-target="#feasibility-only-mde-usd-7-is-deliverable">Feasibility: only MDE ≥ USD 7 is deliverable</a></li>
  <li><a href="#assignment-and-balance" id="toc-assignment-and-balance" class="nav-link" data-scroll-target="#assignment-and-balance">Assignment and balance</a></li>
  <li><a href="#the-simulated-outcome" id="toc-the-simulated-outcome" class="nav-link" data-scroll-target="#the-simulated-outcome">The simulated outcome</a></li>
  <li><a href="#sequential-monitoring" id="toc-sequential-monitoring" class="nav-link" data-scroll-target="#sequential-monitoring">Sequential monitoring</a></li>
  <li><a href="#design-validation-by-monte-carlo" id="toc-design-validation-by-monte-carlo" class="nav-link" data-scroll-target="#design-validation-by-monte-carlo">Design validation by Monte Carlo</a></li>
  <li><a href="#primary-test-and-guardrail" id="toc-primary-test-and-guardrail" class="nav-link" data-scroll-target="#primary-test-and-guardrail">Primary test and guardrail</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a>
  <ul class="collapse">
  <li><a href="#what-the-design-demonstrates" id="toc-what-the-design-demonstrates" class="nav-link" data-scroll-target="#what-the-design-demonstrates">What the design demonstrates</a></li>
  <li><a href="#the-counterfactual-limitation" id="toc-the-counterfactual-limitation" class="nav-link" data-scroll-target="#the-counterfactual-limitation">The counterfactual limitation</a></li>
  <li><a href="#other-limitations" id="toc-other-limitations" class="nav-link" data-scroll-target="#other-limitations">Other limitations</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Designing an A/B Test the Data Cannot Support at Face Value: A Feasibility Sweep, a Monte-Carlo-Validated Design, and a Recovered Hidden Effect</h1>
<p class="subtitle lead">A pre-registered experiment on a 14,825-customer pool with no true no-offer control — the feasibility sweep rejects the obvious USD 2–5 MDEs, the design commits to the tightest feasible USD 7, and 2,000 full-pipeline simulations confirm 90% power and a 3.5% false-positive rate before the primary Welch test recovers an injected USD 8.40 lift to within 6.5%.</p>
  <div class="quarto-categories">
    <div class="quarto-category">Experimental Design</div>
    <div class="quarto-category">A/B Testing</div>
    <div class="quarto-category">Power Analysis</div>
    <div class="quarto-category">Monte Carlo Simulation</div>
    <div class="quarto-category">Statistical Inference</div>
    <div class="quarto-category">Hypothesis Testing</div>
    <div class="quarto-category">Causal Inference</div>
    <div class="quarto-category">Marketing Analytics</div>
    <div class="quarto-category">Python</div>
  </div>
  </div>

<div>
  <div class="description">
    <p>A methods demonstration: how to design a trustworthy randomised experiment on a dataset that cannot supply a clean control arm. <strong>The constraint:</strong> only 6 of 17,000 customers received zero offers, so “offer vs no offer” is structurally impossible; the control outcome is observed 30-day spend and the treatment effect is injected synthetically, declared, then recovered with the truth hidden. <strong>The feasibility sweep:</strong> a USD 2 MDE needs ~52,000 customers per arm against a ~14,800 pool; USD 5 needs ~8,400; <strong>only MDE ≥ USD 7 (≈6% relative lift, 4,263 per arm) is deliverable</strong> — and filtering to transacting customers does <em>not</em> reduce the outcome SD. <strong>Validation before inference:</strong> 2,000 full-pipeline Monte Carlo runs give realised power 90.1% (Wilson 95% CI [88.1, 91.8]) and realised Type I error 3.5% ([2.5, 4.8]) — both guarantees confirmed empirically. <strong>The result:</strong> a one-sided Welch t-test recovers an observed lift of USD 8.95 against the injected USD 8.40 (6.5% error), t = 2.95, p = 0.0016, one-sided 95% lower bound USD 3.96; the transaction-count guardrail is silent (p = 0.39).</p>
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Muhammad Khan Muneer </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 2025</p>
    </div>
  </div>
  
    
  </div>
  

<div>
  <div class="keywords">
    <div class="block-title">Keywords</div>
    <p>A/B test design, power analysis, minimum detectable effect, design feasibility, stratified randomisation, sample ratio mismatch, covariate balance, Welch t-test, Monte Carlo validation, Type I error, sequential monitoring, guardrail metric, Starbucks capstone, Python, scipy</p>
  </div>
</div>

</header>


<section id="abstract" class="level2">
<h2 class="anchored" data-anchor-id="abstract">Abstract</h2>
<p>This is a methods demonstration: how to design a trustworthy randomised experiment on a dataset that cannot supply a clean control arm. The Starbucks/Udacity capstone data contains no genuine untreated pool — only 6 of 17,000 customers received zero offers during the observation window — so a real “offer sent” vs “no offer sent” comparison is structurally impossible. The design instead estimates the <em>incremental</em> effect of a candidate discount offer: the control arm’s outcome is observed 30-day spend (the “what they would have spent anyway” counterfactual) and the treatment arm’s outcome is observed spend plus a known injected lift plus noise, with the true lift declared before the test runs and hidden during analysis. A design-parameter sweep across three candidate substrates and five candidate minimum detectable effects (MDEs) rejects the obvious choices: a USD 2 MDE requires ~52,000 customers per arm against a ~14,800 pool, a USD 5 MDE requires ~8,400, and only an MDE of USD 7 or larger (≈6% relative lift, 4,263 per arm) is deliverable; the sweep also shows that filtering to transacting customers does not reduce the outcome standard deviation. Before the primary test, 2,000 full-pipeline Monte Carlo runs confirm both statistical guarantees: realised power of 90.1% (Wilson 95% CI [88.1%, 91.8%]) under the injected effect, and a realised Type I error rate of 3.5% ([2.5%, 4.8%]) under the null. The pre-registered one-sided Welch t-test then recovers an observed lift of USD 8.95 against the injected USD 8.40 — a 6.5% recovery error — with t = 2.95, one-sided p = 0.0016, and a one-sided 95% lower confidence bound of USD 3.96. The transaction-count guardrail shows no cannibalisation (p = 0.39). The contribution is the pipeline, not the effect: a feasibility-checked, Monte-Carlo-validated, guardrail-instrumented design procedure that catches the underpowered-experiment mistake before any budget is committed.</p>
<p><em>Keywords:</em> A/B test design, power analysis, minimum detectable effect, design feasibility, stratified randomisation, sample ratio mismatch, Welch t-test, Monte Carlo validation, Type I error, guardrail metric</p>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>A randomised experiment is the reference standard that observational inference concedes it cannot meet, so it is worth establishing that standard concretely before the next study in this project turns to a non-randomised rollout. The purpose here is not to discover whether a particular offer works — the effect is injected — but to demonstrate a design procedure that would produce a trustworthy answer if the effect were real.</p>
<p>Two features of the dataset force design decisions that a textbook example would skip. First, there is no untreated population: essentially every customer received at least one offer during the 30-day window, so the experiment cannot compare “offer” against “no offer” and must instead compare “candidate offer plus business-as-usual” against “business-as-usual alone”, with the increment injected. Second, the eligible pool is small — 14,825 customers with complete demographics — which makes the minimum detectable effect a binding constraint rather than a free parameter. The design therefore leads with a feasibility sweep: for each candidate MDE, compute the required sample size and check whether the pool can supply it, <em>before</em> committing to a number.</p>
<p>The analysis then proceeds as a pre-registered experiment: fix the hypotheses and the MDE, draw a stratified 50/50 sample, check the randomisation, inject the effect, validate the design’s power and false-positive guarantees by Monte Carlo, run the primary test with the truth hidden, and check a guardrail. Every step is reported against the realised constraints of the data rather than a default.</p>
</section>
<section id="method" class="level2">
<h2 class="anchored" data-anchor-id="method">Method</h2>
<section id="data-source" class="level3">
<h3 class="anchored" data-anchor-id="data-source">Data source</h3>
<p>The eligible pool is the 14,825 customers with complete demographics from <code>customer_features_gold</code>, a Gold-layer table produced by the project’s medallion ETL pipeline from the Starbucks / Udacity Data Scientist Nanodegree capstone simulated-offers data (distributed on Kaggle). The primary outcome is <code>total_spend</code> — observed spend over the 714-hour (29.75-day) observation window. The candidate treatment offer is the top-performing discount in <code>offer_performance_gold</code> by mean attributed spend per exposure: a USD 2 reward, USD 10 spend-threshold, 10-day discount delivered on all four channels, with a 96.8% view rate and a 70.2% completion rate in the rollout data.</p>
</section>
<section id="pre-registered-design" class="level3">
<h3 class="anchored" data-anchor-id="pre-registered-design">Pre-registered design</h3>
<p>The design is fixed before any outcome is simulated (Table 1). The primary metric is mean 30-day spend per customer. The null hypothesis is equal mean spend across arms; the alternative is that treatment exceeds control. The test is <strong>one-sided at α = 0.05</strong> — the business question is strictly whether the offer helps — with power set to the conventional <strong>80%</strong>. Assignment is stratified by age band × income band at a <strong>50/50</strong> split, which reduces estimator variance without introducing bias. Duration is 30 days, matched to the source window so the control arm’s observed spend covers the same horizon as the treatment arm’s counterfactual. A guardrail metric — mean transaction count — is pre-specified to catch the failure mode where a discount lifts <em>attributed</em> spend while cannibalising purchase frequency.</p>
<p><strong>Table 1</strong></p>
<p><em>Pre-Registered Experimental Design</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Element</th>
<th style="text-align: left;">Specification</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Primary metric</td>
<td style="text-align: left;">Mean 30-day spend per customer</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hypotheses</td>
<td style="text-align: left;">H₀: μ(treatment) = μ(control) · H₁: μ(treatment) &gt; μ(control)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Test</td>
<td style="text-align: left;">Welch’s <em>t</em>-test, one-sided (<code>alternative = "greater"</code>)</td>
</tr>
<tr class="even">
<td style="text-align: left;">α</td>
<td style="text-align: left;">0.05 (one-sided)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Power</td>
<td style="text-align: left;">0.80</td>
</tr>
<tr class="even">
<td style="text-align: left;">Minimum detectable effect</td>
<td style="text-align: left;">USD 7.00 (≈ 6% relative lift on the USD 117.03 substrate mean)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Outcome SD (design input)</td>
<td style="text-align: left;">USD 129.97 (all demographic customers)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sample size</td>
<td style="text-align: left;">4,263 per arm · 8,526 total</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Randomisation</td>
<td style="text-align: left;">Stratified by age band × income band, 50/50 within stratum</td>
</tr>
<tr class="even">
<td style="text-align: left;">Duration</td>
<td style="text-align: left;">30 days (matched to the observation window)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Guardrail</td>
<td style="text-align: left;">Mean transaction count per customer (no effect injected)</td>
</tr>
</tbody>
</table>
<p><em>Note.</em> The MDE is the output of the feasibility sweep (Table 2, Figure 1), not a default. Required <em>n</em> per arm follows the standard two-sample formula <em>n</em> = 2σ²(<em>z</em>₁₋α + <em>z</em>₁₋β)² / MDE².</p>
</section>
<section id="the-feasibility-sweep" class="level3">
<h3 class="anchored" data-anchor-id="the-feasibility-sweep">The feasibility sweep</h3>
<p>For three candidate substrates — all demographic customers (<em>n</em> = 14,825), transacting demographic customers (<em>n</em> = 14,492), and customers with 3+ transactions (<em>n</em> = 13,499) — and five candidate MDEs (USD 2, 3, 5, 7, 10), the required per-arm sample size is computed and flagged feasible only if twice that size fits within the substrate (Table 2, Figure 1). The sweep is the pre-registration artifact: it makes the MDE choice a consequence of what the data can support rather than a convenient number.</p>
</section>
<section id="simulation-model" class="level3">
<h3 class="anchored" data-anchor-id="simulation-model">Simulation model</h3>
<p>The control arm’s outcome is observed <code>total_spend</code>, unchanged. The treatment arm’s outcome is observed <code>total_spend</code> + a constant <strong>injected lift of USD 8.40</strong> + Gaussian noise with SD <strong>USD 5.00</strong>, clipped at zero. The injected lift is set at <strong>1.2 × MDE</strong>: an effect exactly at the MDE would be recovered only about half the time by construction, so the margin reflects the realistic “the true effect is a little larger than the smallest one I care about” scenario while leaving clear separation from the null. The noise SD is deliberately modest so that any failure to recover the injected lift is attributable to statistical limits rather than an aggressive noise assumption.</p>
</section>
<section id="analysis" class="level3">
<h3 class="anchored" data-anchor-id="analysis">Analysis</h3>
<p>Post-randomisation: a sample-ratio-mismatch (SRM) χ² test against the 50/50 target, and standardised mean differences (SMDs) for age, income, baseline spend, and baseline transaction count. Design validation: a realised-power curve (300 resamples at each of ten sample sizes) and a 2,000-run Monte Carlo (1,000 under the injected effect, 1,000 under a zero effect) reporting realised power and realised Type I error with Wilson 95% intervals. Primary test: a one-sided Welch t-test with a one-sided 95% lower confidence bound. Sequential monitoring is illustrated with a naive-CI peek plot, shown as a teaching diagnostic, not a decision rule.</p>
</section>
<section id="software" class="level3">
<h3 class="anchored" data-anchor-id="software">Software</h3>
<p>Python 3.10 with <code>scipy</code> (<code>ttest_ind</code>, <code>chisquare</code>), <code>statsmodels</code>, <code>numpy</code>, and <code>matplotlib</code>. All random steps are seeded (<code>np.random.seed(42)</code>, <code>np.random.default_rng(42)</code>); the pipeline reproduces bit-for-bit from the Gold table.</p>
</section>
</section>
<section id="results" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<section id="feasibility-only-mde-usd-7-is-deliverable" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="feasibility-only-mde-usd-7-is-deliverable">Feasibility: only MDE ≥ USD 7 is deliverable</h3>
<p>The sweep returns a clear verdict (Table 2, Figure 1). A USD 2 MDE is infeasible on every substrate — it needs roughly 52,000–54,000 customers per arm against pools of ~13,500–14,800. Even a USD 5 MDE needs ~8,400–8,600 per arm, which still exceeds the available pool once both arms are counted. The feasibility frontier sits at MDE ≥ USD 7: at that threshold ~4,260–4,400 per arm is required and every substrate can supply it with headroom.</p>
<p>Two findings from the sweep change the design that habit would have produced. First, the transacting-filter substrates do <strong>not</strong> reduce the outcome standard deviation — it holds near USD 130 across all three and in fact rises slightly when zero-spend customers are removed, because what is dropped is a low-variance region of the distribution, not a noise tail. Second, the “borrow a small MDE from common practice” default (USD 2 or USD 5) would have produced an infeasible design; the sweep caught it before execution. The design commits to the tightest feasible configuration: <strong>all demographic customers, MDE = USD 7</strong> (≈ 6% relative lift on the USD 117 substrate mean), <strong>α = 0.05 one-sided, power = 0.80</strong>, giving <strong>4,263 per arm</strong> (8,526 total) with ~42% of the pool left unused.</p>
<p><strong>Table 2</strong></p>
<p><em>Design-Parameter Sweep — Required Per-Arm Sample Size at α = 0.05 (One-Sided), 80% Power</em></p>
<div class="column-page-inset">
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Substrate</th>
<th style="text-align: right;">Pool</th>
<th style="text-align: right;">Mean spend</th>
<th style="text-align: right;">SD spend</th>
<th style="text-align: right;">MDE</th>
<th style="text-align: right;">Relative lift</th>
<th style="text-align: right;">Required <em>n</em> / arm</th>
<th style="text-align: left;">Feasible</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">All demographic</td>
<td style="text-align: right;">14,825</td>
<td style="text-align: right;">USD 117.03</td>
<td style="text-align: right;">USD 129.97</td>
<td style="text-align: right;">USD 2</td>
<td style="text-align: right;">1.71%</td>
<td style="text-align: right;">52,215</td>
<td style="text-align: left;">no</td>
</tr>
<tr class="even">
<td style="text-align: left;">All demographic</td>
<td style="text-align: right;">14,825</td>
<td style="text-align: right;">USD 117.03</td>
<td style="text-align: right;">USD 129.97</td>
<td style="text-align: right;">USD 3</td>
<td style="text-align: right;">2.56%</td>
<td style="text-align: right;">23,207</td>
<td style="text-align: left;">no</td>
</tr>
<tr class="odd">
<td style="text-align: left;">All demographic</td>
<td style="text-align: right;">14,825</td>
<td style="text-align: right;">USD 117.03</td>
<td style="text-align: right;">USD 129.97</td>
<td style="text-align: right;">USD 5</td>
<td style="text-align: right;">4.27%</td>
<td style="text-align: right;">8,355</td>
<td style="text-align: left;">no</td>
</tr>
<tr class="even">
<td style="text-align: left;">All demographic</td>
<td style="text-align: right;">14,825</td>
<td style="text-align: right;">USD 117.03</td>
<td style="text-align: right;">USD 129.97</td>
<td style="text-align: right;"><strong>USD 7</strong></td>
<td style="text-align: right;"><strong>5.98%</strong></td>
<td style="text-align: right;"><strong>4,263</strong></td>
<td style="text-align: left;"><strong>yes</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;">All demographic</td>
<td style="text-align: right;">14,825</td>
<td style="text-align: right;">USD 117.03</td>
<td style="text-align: right;">USD 129.97</td>
<td style="text-align: right;">USD 10</td>
<td style="text-align: right;">8.54%</td>
<td style="text-align: right;">2,089</td>
<td style="text-align: left;">yes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Transacting</td>
<td style="text-align: right;">14,492</td>
<td style="text-align: right;">USD 119.72</td>
<td style="text-align: right;">USD 130.22</td>
<td style="text-align: right;">USD 5</td>
<td style="text-align: right;">4.18%</td>
<td style="text-align: right;">8,388</td>
<td style="text-align: left;">no</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Transacting</td>
<td style="text-align: right;">14,492</td>
<td style="text-align: right;">USD 119.72</td>
<td style="text-align: right;">USD 130.22</td>
<td style="text-align: right;">USD 7</td>
<td style="text-align: right;">5.85%</td>
<td style="text-align: right;">4,280</td>
<td style="text-align: left;">yes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Transacting 3+</td>
<td style="text-align: right;">13,499</td>
<td style="text-align: right;">USD 126.38</td>
<td style="text-align: right;">USD 132.03</td>
<td style="text-align: right;">USD 5</td>
<td style="text-align: right;">3.96%</td>
<td style="text-align: right;">8,622</td>
<td style="text-align: left;">no</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Transacting 3+</td>
<td style="text-align: right;">13,499</td>
<td style="text-align: right;">USD 126.38</td>
<td style="text-align: right;">USD 132.03</td>
<td style="text-align: right;">USD 7</td>
<td style="text-align: right;">5.54%</td>
<td style="text-align: right;">4,399</td>
<td style="text-align: left;">yes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Transacting 3+</td>
<td style="text-align: right;">13,499</td>
<td style="text-align: right;">USD 126.38</td>
<td style="text-align: right;">USD 132.03</td>
<td style="text-align: right;">USD 10</td>
<td style="text-align: right;">7.91%</td>
<td style="text-align: right;">2,156</td>
<td style="text-align: left;">yes</td>
</tr>
</tbody>
</table>
</div>
<p><em>Note.</em> Abridged to the decision-relevant rows; the USD 2 and USD 3 rows are infeasible on all three substrates. SD does not fall — and slightly rises — under the transacting filters. Chosen design in bold.</p>
<p><strong>Figure 1</strong></p>
<p><em>Required Sample Size vs Minimum Detectable Effect, by Substrate</em></p>
<p><img src="assets/fig1_feasibility_sweep.png" class="img-fluid" alt="A log-scale line plot of required sample size per arm against MDE for three substrates. All three lines nearly coincide, falling from about 52,000 at MDE = 2 to about 2,000 at MDE = 10. A dashed horizontal line marks half the demographic pool (about 7,400 per arm); the MDE = 2, 3, and 5 points sit above it and are ringed red as infeasible; MDE = 7 is the first point below the line and is annotated as the tightest feasible design at 4,263 per arm."></p>
<p><em>Note.</em> The three substrate curves are nearly indistinguishable — filtering to transacting customers changes the required sample size by less than 3%.</p>
</section>
<section id="assignment-and-balance" class="level3">
<h3 class="anchored" data-anchor-id="assignment-and-balance">Assignment and balance</h3>
<p>Stratified assignment drew <strong>7,764</strong> customers (<strong>3,853</strong> treatment, <strong>3,911</strong> control) — <strong>762 short (8.9%)</strong> of the design target of 8,526. The shortfall is a consequence of the stratification rules: strata with fewer than four customers are dropped (meaningful randomisation is not possible below that), and oversized strata are capped so a few large cells do not dominate. Accepting the shortfall is preferable to relaxing the minimum-cell rule, which would reintroduce the variance the stratification exists to remove; at ~3,900 per arm the test remains above the threshold for the chosen MDE.</p>
<p>Both post-randomisation checks pass (Figure 2). The SRM test returns <strong>χ² = 0.43, p = 0.51</strong> — the realised split is within chance of 50/50. Covariate balance is tight: standardised mean differences are −0.026 for age, −0.018 for income, +0.019 for baseline transaction count, and +0.003 for baseline spend — all far inside the ±0.1 convention. The primary test can be read at face value.</p>
<p><strong>Figure 2</strong></p>
<p><em>Covariate Balance After Stratified Randomisation (Love Plot)</em></p>
<p><img src="assets/fig2_balance_love.png" class="img-fluid" alt="A Love plot of standardised mean differences between treatment and control for four covariates. All four points lie between −0.03 and +0.02, well within dashed reference lines at ±0.1. A footnote reports the sample-ratio-mismatch test: chi-square = 0.43, p = 0.51, the 3,853 / 3,911 split within chance of 50/50."></p>
<p><em>Note.</em> SMD = (mean treatment − mean control) / pooled SD. The ±0.1 lines are the conventional threshold for a covariate imbalance worth adjusting for.</p>
</section>
<section id="the-simulated-outcome" class="level3">
<h3 class="anchored" data-anchor-id="the-simulated-outcome">The simulated outcome</h3>
<p>Injecting the USD 8.40 lift plus noise into the treatment arm produced a treatment mean of <strong>USD 123.66</strong> and a control mean of <strong>USD 114.71</strong> — an observed lift of <strong>USD 8.95</strong> — with the medians shifting in the same direction (USD 91.30 vs USD 80.55) and the standard deviations essentially unchanged across arms (USD 133.63 vs USD 133.38), the expected signature of an additive constant lift on a heavy-tailed baseline (Figure 3).</p>
<p><strong>Figure 3</strong></p>
<p><em>Simulated 30-Day Spend by Arm</em></p>
<p><img src="assets/fig3_outcome_by_arm.png" class="img-fluid" alt="Two horizontal boxplots of 30-day spend, outliers beyond USD 400 hidden. The treatment box (mean USD 123.66, SD 133) sits slightly to the right of the control box (mean USD 114.71, SD 133). A double-headed arrow between the two dotted mean lines is labelled observed lift USD 8.95. Box widths and whisker spans are nearly identical."></p>
<p><em>Note.</em> The additive lift moves location, not spread — the two arms’ SDs differ by less than USD 1.</p>
</section>
<section id="sequential-monitoring" class="level3">
<h3 class="anchored" data-anchor-id="sequential-monitoring">Sequential monitoring</h3>
<p>The running treatment-effect estimate bounces within a wide naive confidence band at small samples — starting near USD 30, dipping toward USD 3 by ~600 enrolled, then converging to the injected USD 8.40 as the sample fills (Figure 4). A stakeholder who stopped at the first peek crossing zero would inflate Type I error substantially; one who stopped when the estimate first exceeded the MDE would cherry-pick the sample size. The design’s α budget is spent on a single pre-registered final test, not on the trajectory; a production rollout that genuinely needs interim looks would use α-spending (O’Brien–Fleming, Pocock) or a Bayesian stopping rule.</p>
<p><strong>Figure 4</strong></p>
<p><em>Running Treatment-Effect Estimate as the Sample Accumulates</em></p>
<p><img src="assets/fig4_sequential_peek.png" class="img-fluid" alt="A line plot of the running lift estimate against cumulative enrolled sample size, with a shaded naive 95% confidence band. The estimate starts near USD 30 with a band spanning roughly −10 to +70, narrows quickly, and converges toward a dotted reference line at the injected USD 8.40 by the full sample of about 7,700."></p>
<p><em>Note.</em> The confidence band is naive — using it to stop early would inflate α. Shown as a teaching diagnostic only.</p>
</section>
<section id="design-validation-by-monte-carlo" class="level3">
<h3 class="anchored" data-anchor-id="design-validation-by-monte-carlo">Design validation by Monte Carlo</h3>
<p>The realised-power curve rises from ~16% rejection at 250 per arm to <strong>~93% at the design point of 4,263 per arm</strong> (Figure 5). That the design-point value exceeds the nominal 80% is correct behaviour, not over-delivery: the 80% promise holds <em>at the MDE</em> (USD 7), and the simulation injects USD 8.40 (1.2 × MDE), which naturally produces higher power. Power below ~1,500 per arm collapses — at 500 per arm the test barely clears 26% — so a “smaller pilot” of this experiment would mostly fail to detect the real effect.</p>
<p>The 2,000-run full-pipeline Monte Carlo confirms both halves of the design’s promise (Figure 6, Table 3). Under the injected effect, the test rejected in <strong>90.1%</strong> of 1,000 runs (Wilson 95% CI [88.1%, 91.8%]) — above 80% for the 1.2 × MDE reason above. Under a zero effect, the false-positive rate was <strong>3.5%</strong> ([2.5%, 4.8%]) — <em>below</em> the nominal 5%, i.e.&nbsp;the test is slightly conservative, which is the benign direction. The p-value histograms make the story visual: heavily concentrated near zero under the alternative, roughly uniform on [0, 1] under the null — the expected shape for a correctly calibrated test.</p>
<p><strong>Figure 5</strong></p>
<p><em>Realised Power vs Sample Size per Arm</em></p>
<p><img src="assets/fig5_realised_power_curve.png" class="img-fluid" alt="A rising curve of realised rejection rate against sample size per arm, from about 0.16 at 250 to about 0.93 at the design point of 4,263. A dotted horizontal line marks the 80% nominal target; a dashed vertical line marks the design point, where the curve reads 93%."></p>
<p><em>Note.</em> 300 simulations per point. The curve would cross 80% near the MDE-equivalent effect; the injected effect is 1.2 × MDE, so the design point sits above.</p>
<p><strong>Figure 6</strong></p>
<p><em>Monte Carlo Validation — p-Value Distributions Under the Alternative and the Null</em></p>
<p><img src="assets/fig6_mc_validation.png" class="img-fluid" alt="Two histograms of simulated one-sided p-values over 1,000 runs each. Left, under the USD 8.40 alternative: mass piled up below 0.05, rejection rate 90.1%. Right, under the null: roughly uniform across [0, 1] with about 3.5% of runs below the shaded 0.05 rejection zone."></p>
<p><em>Note.</em> A spike near zero in the right panel would indicate a liberal test declaring spurious findings; its absence is the empirical confirmation the test is well-behaved.</p>
</section>
<section id="primary-test-and-guardrail" class="level3">
<h3 class="anchored" data-anchor-id="primary-test-and-guardrail">Primary test and guardrail</h3>
<p>The pre-registered one-sided Welch t-test recovered an observed lift of <strong>USD 8.95</strong> against the injected <strong>USD 8.40</strong> — a recovery error of USD 0.55 (<strong>6.5%</strong> of the true effect) — with SE USD 3.03, <strong>t = 2.95</strong>, one-sided <strong>p = 0.0016</strong> (about one-thirtieth of α), and a one-sided 95% lower confidence bound of <strong>USD 3.96</strong> (Figure 7, Table 3). The null of no effect is rejected decisively.</p>
<p>One caveat: the lower bound (USD 3.96) sits <em>below</em> the pre-registered MDE of USD 7. The test rejects the null of <em>no effect</em>, not the stricter null of “effect at least MDE-sized”; those are different hypotheses and the design pre-registered only the weaker one. Concluding the effect is at least MDE-sized would need a larger sample or a non-inferiority-style test.</p>
<p>The transaction-count guardrail is silent, as expected: treatment and control mean transactions are <strong>8.64</strong> and <strong>8.54</strong> (<em>p</em> = 0.39), nowhere near rejection. The simulation injected only a spend effect, so no cannibalisation signal should appear; the point is that the logic is instrumented to catch one if it did.</p>
<p><strong>Figure 7</strong></p>
<p><em>Injected vs Recovered Treatment Effect</em></p>
<p><img src="assets/fig7_recovery.png" class="img-fluid" alt="A one-dimensional plot on a USD axis from zero to sixteen. A blue bar runs from the one-sided ninety-five percent lower bound at USD three point nine six to the recovered point estimate at USD eight point nine five. A red dashed line and diamond mark the injected truth at USD eight point four zero; a gold dotted line marks the pre-registered MDE at USD seven. A caption states the injected and recovered values and the p-value."></p>
<p><em>Note.</em> The recovered estimate brackets the injected truth; the one-sided lower bound clears zero but not the MDE.</p>
<p><strong>Table 3</strong></p>
<p><em>Simulated Experiment — Results Summary</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Quantity</th>
<th style="text-align: left;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Assigned (treatment / control)</td>
<td style="text-align: left;">7,764 (3,853 / 3,911); 8.9% below the 8,526 target</td>
</tr>
<tr class="even">
<td style="text-align: left;">SRM test</td>
<td style="text-align: left;">χ² = 0.43, <em>p</em> = 0.51 — balanced</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Covariate SMDs (age / income / spend / transactions)</td>
<td style="text-align: left;">−0.026 / −0.018 / +0.003 / +0.019 — all |SMD| &lt; 0.03</td>
</tr>
<tr class="even">
<td style="text-align: left;">Simulated outcome mean (treatment / control)</td>
<td style="text-align: left;">USD 123.66 / USD 114.71</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Observed lift</td>
<td style="text-align: left;">USD 8.95 (injected USD 8.40; recovery error 6.5%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Welch <em>t</em>-test</td>
<td style="text-align: left;"><em>t</em> = 2.95, one-sided <em>p</em> = 0.0016</td>
</tr>
<tr class="odd">
<td style="text-align: left;">One-sided 95% lower bound</td>
<td style="text-align: left;">USD 3.96</td>
</tr>
<tr class="even">
<td style="text-align: left;">Monte Carlo realised power (1,000 runs)</td>
<td style="text-align: left;">90.1% (Wilson 95% CI [88.1%, 91.8%])</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Monte Carlo realised Type I error (1,000 runs)</td>
<td style="text-align: left;">3.5% (Wilson 95% CI [2.5%, 4.8%])</td>
</tr>
<tr class="even">
<td style="text-align: left;">Realised power at the design point (curve)</td>
<td style="text-align: left;">92.7%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Guardrail — mean transactions (treatment / control)</td>
<td style="text-align: left;">8.64 / 8.54, <em>p</em> = 0.39 — no cannibalisation</td>
</tr>
</tbody>
</table>
<p><em>Note.</em> All values reproduce exactly from the seeded pipeline.</p>
</section>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<section id="what-the-design-demonstrates" class="level3">
<h3 class="anchored" data-anchor-id="what-the-design-demonstrates">What the design demonstrates</h3>
<p>The procedure delivered what it was built for: an injected effect declared in advance was recovered to within 6.5% by a test whose power and false-positive guarantees had been empirically confirmed beforehand. The single most valuable step is the feasibility sweep. It caught that the obvious USD 2 MDE would have required ~52,000 customers per arm against a pool of ~14,800 — a design with essentially no chance of detecting anything short of a catastrophic effect. Running that experiment would have burned a quarter of rollout budget and produced a go/no-go decision on noise. Checking feasibility first cost minutes.</p>
</section>
<section id="the-counterfactual-limitation" class="level3">
<h3 class="anchored" data-anchor-id="the-counterfactual-limitation">The counterfactual limitation</h3>
<p>The control arm’s outcome is observed spend from customers who received <em>other</em> offers, not spend from a genuine no-offer holdout — because the data contains only 6 zero-offer customers. The experiment therefore estimates the <em>incremental</em> effect of one candidate offer on top of business-as-usual, and any real deployment of this design would need a randomised holdout baked into the offer-rollout tooling to anchor the counterfactual properly. This is a data limitation, stated plainly, not a flaw in the procedure.</p>
</section>
<section id="other-limitations" class="level3">
<h3 class="anchored" data-anchor-id="other-limitations">Other limitations</h3>
<p>The effect was injected with a homogeneous additive-plus-Gaussian model; real offer effects are heterogeneous across customers, which the next study in this project takes up with per-customer effect estimation. The USD 7 MDE, while the tightest feasible here, is a 6% relative lift — a business wanting to detect smaller effects would need a larger pool or a variance-reduction technique (CUPED with a pre-period covariate, or covariate adjustment in the test), neither of which the 30-day window supports. The sequential-monitoring section used naive intervals for illustration; a production rollout with interim looks needs formal α-spending. And the ~2,175 customers without demographics cannot be reached by demographic-stratified assignment, so the addressable pool is structurally capped.</p>
</section>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion">Conclusion</h3>
<p>A trustworthy experiment on this data is possible, but only after conceding that the control arm is a business-as-usual baseline rather than a true holdout, and after letting a feasibility sweep — not habit — set the minimum detectable effect. The reusable part is the pipeline: sweep → randomise → validate → test → guardrail, parameter-driven and Monte-Carlo-checked, which turns “we ran an A/B test” into “we produced evidence we can act on.”</p>
</section>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<p>Cohen, J. (1988). <em>Statistical power analysis for the behavioral sciences</em> (2nd ed.). Lawrence Erlbaum Associates.</p>
<p>Harris, C. R., Millman, K. J., van der Walt, S. J., Gommers, R., Virtanen, P., Cournapeau, D., Wieser, E., Taylor, J., Berg, S., Smith, N. J., Kern, R., Picus, M., Hoyer, S., van Kerkwijk, M. H., Brett, M., Haldane, A., del Río, J. F., Wiebe, M., Peterson, P., … Oliphant, T. E. (2020). Array programming with NumPy. <em>Nature, 585</em>, 357–362. https://doi.org/10.1038/s41586-020-2649-2</p>
<p>Kohavi, R., Tang, D., &amp; Xu, Y. (2020). <em>Trustworthy online controlled experiments: A practical guide to A/B testing</em>. Cambridge University Press. https://doi.org/10.1017/9781108653985</p>
<p>O’Brien, P. C., &amp; Fleming, T. R. (1979). A multiple testing procedure for clinical trials. <em>Biometrics, 35</em>(3), 549–556. https://doi.org/10.2307/2530245</p>
<p>Virtanen, P., Gommers, R., Oliphant, T. E., Haberland, M., Reddy, T., Cournapeau, D., Burovski, E., Peterson, P., Weckesser, W., Bright, J., van der Walt, S. J., Brett, M., Wilson, J., Millman, K. J., Mayorov, N., Nelson, A. R. J., Jones, E., Kern, R., Larson, E., … Vázquez-Baeza, Y. (2020). SciPy 1.0: Fundamental algorithms for scientific computing in Python. <em>Nature Methods, 17</em>, 261–272. https://doi.org/10.1038/s41592-019-0686-2</p>
<p>Welch, B. L. (1947). The generalization of “Student’s” problem when several different population variances are involved. <em>Biometrika, 34</em>(1–2), 28–35. https://doi.org/10.1093/biomet/34.1-2.28</p>
<p>Wilson, E. B. (1927). Probable inference, the law of succession, and statistical inference. <em>Journal of the American Statistical Association, 22</em>(158), 209–212. https://doi.org/10.1080/01621459.1927.10502953</p>
<p>Starbucks, &amp; Udacity. (2018). <em>Starbucks Capstone Challenge simulated offers dataset</em> [Data set]. Retrieved from Kaggle (I. Muliar, mirror). https://www.kaggle.com/datasets/ihormuliar/starbucks-customer-data</p>
<hr>
<p><em>Simulation study: the treatment effect was injected, not observed. The reported recovery, power, and Type I error describe the design’s behaviour under the stated simulation model; a real deployment would require a randomised no-offer holdout to anchor the counterfactual.</em></p>


<div id="contact" class="connect-section" style="text-align: center; padding: 50px 20px; background: #f9f9f9; border-radius: 15px; border: 1px solid #eaeaea; margin-top: 40px;">
<h3 style="color: #2c3e50; font-weight: 700; margin-bottom: 15px; border: none;" class="anchored">Let's Collaborate</h3>
<p style="color: #666; max-width: 650px; margin: 0 auto 30px auto; font-size: 1.05rem; line-height: 1.6;">Available for high-impact <strong>Business Intelligence, Power BI Engineering, and Advanced Data Analytics</strong> projects. Connect with me or hire me directly through the platforms below.</p>
<div style="display: flex; flex-wrap: wrap; justify-content: center; gap: 12px;">
<a href="https://www.linkedin.com/in/mkmuneer" class="btn btn-primary" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; text-decoration: none;"><i class="bi bi-linkedin"></i> LinkedIn</a>
<a href="https://github.com/mkhanmuneer" class="btn btn-dark" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; text-decoration: none;"><i class="bi bi-github"></i> GitHub</a>
<a href="https://www.kaggle.com/muhammadkhanmuneer" class="btn btn-info" target="_blank" rel="noopener" style="color: white; padding: 12px 25px; min-width: 150px; text-decoration: none;"><i class="bi bi-graph-up"></i> Kaggle</a>
<a href="https://www.upwork.com/freelancers/~018de8553286a1d00c" class="btn btn-outline-success" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; border-width: 2px; font-weight: 600; text-decoration: none;"><i class="bi bi-briefcase"></i> Upwork</a>
<a href="https://www.fiverr.com/neuronvision" class="btn btn-outline-success" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; border-width: 2px; font-weight: 600; text-decoration: none;"><i class="bi bi-lightning-charge"></i> Fiverr</a>
</div>
</div>

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/mkhanmuneer\.github\.io\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 Muhammad Khan Muneer</p>
</div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://www.upwork.com/freelancers/~018de8553286a1d00c">
<p>Hire on Upwork</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="https://www.fiverr.com/neuronvision">
<p>Hire on Fiverr</p>
</a>
  </li>  
</ul>
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mkhanmuneer">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/mkmuneer">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>