<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Muhammad Khan Muneer">
<meta name="keywords" content="exploratory data analysis, stroke risk factors, Wilson confidence interval, Mann-Whitney U, rank-biserial correlation, point-biserial correlation, Cramér’s V, confounding, age stratification, decile rate analysis, feature selection, class imbalance, biostatistics, Python">
<meta name="description" content="A rate-first exploratory analysis of stroke risk factors in a 5,110-patient cohort (4.87% prevalence). Age dominance: the within-decade stroke rate is near-zero to age 50 then rises to 21.5% past 80. Confounding: marital status tracks age at Cramér’s V = 0.75, explaining its apparent 4-fold rate elevation. Genuine nulls: gender and residence type return V = 0.00 against clean, balanced distributions. Signal ranking: age-derived terms lead every association metric; obesity and smoking sit near the floor.">

<title>Clinical Feature Profiling for Stroke: Age-Led Stroke-Rate Gradients, Confounder Identification, and Feature-Level Signal Quantification – Muhammad Khan Muneer</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-4d9afe2b8d18ee9fa5d0d57b5ed4214d.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-5af9b5ab1fa0c387551d40c1aacb317e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-ca0cfe78a00f84493d894d8af57a3a20.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-5af9b5ab1fa0c387551d40c1aacb317e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": true,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<link rel="stylesheet" href="../../styles/custom.css">
<meta property="og:title" content="Muhammad Khan Muneer — Data Science &amp; BI Portfolio">
<meta property="og:description" content="Engineering ML-driven analytics and automated decision systems.">
<meta property="og:image" content="https://mkhanmuneer.github.io/projects/clinical-feature-profiling-age-led-stroke-rate-gradients-confounder-identification-signal-quantification/assets/fig4_age_gradient_decade.png">
<meta property="og:site_name" content="M. Khan Muneer Portfolio">
<meta property="og:image:height" content="1048">
<meta property="og:image:width" content="1973">
<meta name="twitter:title" content="Clinical Feature Profiling for Stroke: Age-Led Stroke-Rate Gradients, Confounder Identification, and Feature-Level Signal Quantification – Muhammad Khan Muneer">
<meta name="twitter:description" content="A rate-first exploratory analysis of stroke risk factors in a 5,110-patient cohort (4.87% prevalence). Age dominance: the within-decade stroke rate is near-zero to age 50 then rises to 21.5% past 80. Confounding: marital status tracks age at Cramér’s V = 0.75, explaining its apparent 4-fold rate elevation. Genuine nulls: gender and residence type return V = 0.00 against clean, balanced distributions. Signal ranking: age-derived terms lead every association metric; obesity and smoking sit near the floor.">
<meta name="twitter:image" content="https://mkhanmuneer.github.io/projects/clinical-feature-profiling-age-led-stroke-rate-gradients-confounder-identification-signal-quantification/assets/fig4_age_gradient_decade.png">
<meta name="twitter:creator" content="@iMKhanMuneer">
<meta name="twitter:site" content="@iMKhanMuneer">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image-height" content="1048">
<meta name="twitter:image-width" content="1973">
</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../index.html#featured-projects"> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/mkmuneer"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mkhanmuneer"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://x.com/iMKhanMuneer"> <i class="bi bi-twitter-x" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.kaggle.com/muhammadkhanmuneer"> <i class="bi bi-graph-up" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../index.html#contact"> 
<span class="menu-text">Contact</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract">Abstract</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#method" id="toc-method" class="nav-link" data-scroll-target="#method">Method</a>
  <ul class="collapse">
  <li><a href="#data-source" id="toc-data-source" class="nav-link" data-scroll-target="#data-source">Data source</a></li>
  <li><a href="#variables-and-measures" id="toc-variables-and-measures" class="nav-link" data-scroll-target="#variables-and-measures">Variables and measures</a></li>
  <li><a href="#statistical-analysis" id="toc-statistical-analysis" class="nav-link" data-scroll-target="#statistical-analysis">Statistical analysis</a></li>
  <li><a href="#software" id="toc-software" class="nav-link" data-scroll-target="#software">Software</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#cohort-composition" id="toc-cohort-composition" class="nav-link" data-scroll-target="#cohort-composition">Cohort composition</a></li>
  <li><a href="#continuous-distributions-and-normality" id="toc-continuous-distributions-and-normality" class="nav-link" data-scroll-target="#continuous-distributions-and-normality">Continuous distributions and normality</a></li>
  <li><a href="#bmi-imputation-sensitivity" id="toc-bmi-imputation-sensitivity" class="nav-link" data-scroll-target="#bmi-imputation-sensitivity">BMI imputation sensitivity</a></li>
  <li><a href="#categorical-predictors-versus-stroke" id="toc-categorical-predictors-versus-stroke" class="nav-link" data-scroll-target="#categorical-predictors-versus-stroke">Categorical predictors versus stroke</a></li>
  <li><a href="#continuous-predictors-versus-stroke" id="toc-continuous-predictors-versus-stroke" class="nav-link" data-scroll-target="#continuous-predictors-versus-stroke">Continuous predictors versus stroke</a></li>
  <li><a href="#age-stratified-analysis" id="toc-age-stratified-analysis" class="nav-link" data-scroll-target="#age-stratified-analysis">Age-stratified analysis</a></li>
  <li><a href="#association-structure" id="toc-association-structure" class="nav-link" data-scroll-target="#association-structure">Association structure</a></li>
  <li><a href="#interaction-terms" id="toc-interaction-terms" class="nav-link" data-scroll-target="#interaction-terms">Interaction terms</a></li>
  <li><a href="#consolidated-feature-level-findings" id="toc-consolidated-feature-level-findings" class="nav-link" data-scroll-target="#consolidated-feature-level-findings">Consolidated feature-level findings</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a>
  <ul class="collapse">
  <li><a href="#age-is-the-organising-variable" id="toc-age-is-the-organising-variable" class="nav-link" data-scroll-target="#age-is-the-organising-variable">Age is the organising variable</a></li>
  <li><a href="#confounding-the-marital-status-result" id="toc-confounding-the-marital-status-result" class="nav-link" data-scroll-target="#confounding-the-marital-status-result">Confounding: the marital-status result</a></li>
  <li><a href="#genuine-nulls" id="toc-genuine-nulls" class="nav-link" data-scroll-target="#genuine-nulls">Genuine nulls</a></li>
  <li><a href="#shape-matters-as-much-as-strength" id="toc-shape-matters-as-much-as-strength" class="nav-link" data-scroll-target="#shape-matters-as-much-as-strength">Shape matters as much as strength</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations">Limitations</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Clinical Feature Profiling for Stroke: Age-Led Stroke-Rate Gradients, Confounder Identification, and Feature-Level Signal Quantification</h1>
<p class="subtitle lead">An exploratory analysis of a 5,110-patient cohort — univariate distributions, within-group rate structure, age stratification, and a full feature-versus-outcome association landscape.</p>
  <div class="quarto-categories">
    <div class="quarto-category">Exploratory Data Analysis</div>
    <div class="quarto-category">Biostatistics</div>
    <div class="quarto-category">Statistical Inference</div>
    <div class="quarto-category">Epidemiology</div>
    <div class="quarto-category">Feature Selection</div>
    <div class="quarto-category">Confounding Analysis</div>
    <div class="quarto-category">Clinical Research</div>
    <div class="quarto-category">Healthcare Analytics</div>
    <div class="quarto-category">Python</div>
  </div>
  </div>

<div>
  <div class="description">
    <p>A rate-first exploratory analysis of stroke risk factors in a 5,110-patient cohort (4.87% prevalence). <strong>Age dominance:</strong> the within-decade stroke rate is near-zero to age 50 then rises to 21.5% past 80. <strong>Confounding:</strong> marital status tracks age at Cramér’s <em>V</em> = 0.75, explaining its apparent 4-fold rate elevation. <strong>Genuine nulls:</strong> gender and residence type return <em>V</em> = 0.00 against clean, balanced distributions. <strong>Signal ranking:</strong> age-derived terms lead every association metric; obesity and smoking sit near the floor.</p>
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Muhammad Khan Muneer </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 2026</p>
    </div>
  </div>
  
    
  </div>
  

<div>
  <div class="keywords">
    <div class="block-title">Keywords</div>
    <p>exploratory data analysis, stroke risk factors, Wilson confidence interval, Mann-Whitney U, rank-biserial correlation, point-biserial correlation, Cramér’s V, confounding, age stratification, decile rate analysis, feature selection, class imbalance, biostatistics, Python</p>
  </div>
</div>

</header>


<section id="abstract" class="level2">
<h2 class="anchored" data-anchor-id="abstract">Abstract</h2>
<p>This exploratory analysis profiles 24 clinical and engineered features against incident stroke in a cross-sectional cohort of 5,110 patients (249 events; prevalence 4.87%, a 19.5:1 class imbalance). Because the imbalance makes raw counts uninformative, every predictor–outcome comparison is expressed as a within-group rate with a Wilson score 95% confidence interval, supported by Mann–Whitney <em>U</em> tests with rank-biserial effect sizes for continuous predictors, point-biserial correlations, bias-corrected Cramér’s <em>V</em> for categorical associations, and decile rate curves. Age is the dominant signal by every metric: the within-decade stroke rate is below 1% through age 50, then rises to 5.8% (50s), 16.5% (70s), and 21.5% (80+); the four-band age variable carries Cramér’s <em>V</em> = 0.25 against stroke, and the age rank-biserial correlation (|<em>r</em>| = 0.67) is three times the next-strongest continuous predictor. Hypertension and heart disease produce the sharpest binary splits (3.3-fold and 4.1-fold rate elevations, non-overlapping intervals). The apparent 4-fold elevation for ever-married status is an age artefact — marital status correlates with the age band at Cramér’s <em>V</em> = 0.75. Gender and residence type are genuine nulls (<em>V</em> = 0.00 against clean, balanced distributions). Glucose shows a threshold pattern (signal confined to the top two deciles, &gt; 140 mg/dL); BMI is weak and non-monotonic; smoking is confounded and 30.2% imputed. The analysis closes with a ranked feature-level findings table that defines the candidate set for downstream inferential and predictive modelling.</p>
<p><em>Keywords:</em> exploratory data analysis, stroke, Wilson confidence interval, Mann–Whitney <em>U</em>, Cramér’s <em>V</em>, confounding, age stratification</p>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Exploratory analysis of a clinical dataset has one job: to establish, before any model is fitted, which features carry signal against the outcome, how that signal is shaped, and which apparent effects are confounded. This study does that for stroke on a curated 24-feature analytical table of 5,110 patients. It answers four questions in order — how each feature is distributed, how the stroke rate varies within each feature’s levels or range, how the dominant predictor (age) restructures every other comparison, and how the whole feature space ranks by association strength with the outcome.</p>
<p>Four constraints established during data preparation govern every interpretation:</p>
<ol type="1">
<li><strong>Class imbalance.</strong> 249 stroke-positive patients in 5,110 give a 4.87% positive rate and a 19.5:1 negative-to-positive ratio. This is genuine clinical prevalence in a cross-sectional sample, not a defect. Its consequence is methodological: raw within-group counts are meaningless for comparison, so every predictor–outcome relationship in this study is reported as a within-group <em>rate</em> with an interval estimate.</li>
<li><strong>BMI imputation.</strong> 201 BMI values (3.93%) were modelled during preparation; a sensitivity check precedes any BMI-dependent claim.</li>
<li><strong>Smoking-status imputation.</strong> 1,544 smoking-status values (30.22%) were modelled with a random-forest classifier trained on the observed subpopulation. Every smoking-related result is treated as exploratory.</li>
<li><strong>Age as the presumptive dominant signal.</strong> Age was flagged upstream as the strongest univariate correlate; this analysis confirms it explicitly and then uses age as the primary stratification variable throughout.</li>
</ol>
</section>
<section id="method" class="level2">
<h2 class="anchored" data-anchor-id="method">Method</h2>
<section id="data-source" class="level3">
<h3 class="anchored" data-anchor-id="data-source">Data source</h3>
<p>The cohort is the open <em>Stroke Prediction Dataset</em> (fedesoriano, 2021): 5,110 patient records with demographic attributes, lifestyle indicators, medical history, and a binary stroke outcome. It was processed through a medallion-style extract–transform–load pipeline (raw → cleaned → imputed → feature-engineered); all cleaning, imputation, and feature construction was complete before this analysis began, and no transformation is applied here. The analytical table holds 5,110 rows and 24 columns: eleven raw or recoded clinical features, a pre-imputation BMI audit column, eight engineered feature columns (an age band, four flags, a log-glucose term, a squared-age term, an obesity and an underweight indicator), four interaction terms, and the binary outcome plus its integer encoding.</p>
</section>
<section id="variables-and-measures" class="level3">
<h3 class="anchored" data-anchor-id="variables-and-measures">Variables and measures</h3>
<p>The outcome is incident stroke (encoded 1/0). Continuous predictors are age, average glucose (mg/dL), BMI (kg/m²), and their engineered relatives: log-glucose, squared age, age × log-glucose, and age × BMI. Categorical predictors are hypertension, heart disease, ever-married status, work type (five levels), residence type, smoking status (three levels), gender, and a four-band age variable (young 0–29 y, mid 30–44 y, mature 45–59 y, senior 60–82 y). Binary flags are current-or-former smoker, obesity (BMI ≥ 30), underweight (BMI &lt; 18.5), elevated glucose (&gt; 140 mg/dL), the joint hypertension-and-elevated-glucose indicator, and the joint smoker-and-obese indicator.</p>
</section>
<section id="statistical-analysis" class="level3">
<h3 class="anchored" data-anchor-id="statistical-analysis">Statistical analysis</h3>
<p><strong>Rates and intervals.</strong> Within-group stroke rates were computed as proportions and paired with 95% Wilson score confidence intervals (Wilson, 1927), which retain correct coverage for proportions near zero — essential here given several near-zero group rates.</p>
<p><strong>Distribution shape.</strong> Each continuous feature was summarised (mean, median, standard deviation, skewness, kurtosis) and tested for normality with the D’Agostino–Pearson omnibus test (D’Agostino &amp; Pearson, 1973). Non-normality across all continuous features motivated non-parametric methods throughout.</p>
<p><strong>Continuous predictors versus outcome.</strong> Each continuous predictor was compared between stroke-positive and stroke-negative groups with a Mann–Whitney <em>U</em> test (Mann &amp; Whitney, 1947), reporting the rank-biserial correlation as a standardised effect size on a −1 to +1 scale (Kerby, 2014). Point-biserial correlations (Tate, 1954) against the integer outcome were computed for cross-feature ranking. Decile rate curves (stroke rate within each population decile of the predictor) characterise the <em>shape</em> of the relationship — monotonic, threshold, or non-monotonic.</p>
<p><strong>Categorical associations.</strong> Pairwise associations among categorical features, and between each categorical feature and the outcome, were quantified with bias-corrected Cramér’s <em>V</em> (Bergsma, 2013), placing pairs of differing cardinality on a common 0–1 scale. Cohen’s (1988) conventions frame <em>V</em> ≈ .10 as small, .30 as moderate, and ≥ .50 as large for these degrees of freedom. Spearman rank correlations (Spearman, 1904) describe monotonic association among continuous features.</p>
<p><strong>Association landscape.</strong> A single ranked view places every feature on one axis of association strength with the outcome: |point-biserial <em>r</em>| for continuous features and flags, Cramér’s <em>V</em> for categorical features.</p>
</section>
<section id="software" class="level3">
<h3 class="anchored" data-anchor-id="software">Software</h3>
<p>Analyses used Python with <code>SciPy</code> (Virtanen et al., 2020), <code>NumPy</code> (Harris et al., 2020), and <code>pandas</code> (The pandas development team, 2020); figures were produced with <code>Matplotlib</code> (Hunter, 2007).</p>
</section>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<section id="cohort-composition" class="level3">
<h3 class="anchored" data-anchor-id="cohort-composition">Cohort composition</h3>
<p>The outcome splits 4,861 stroke-negative (95.13%) against 249 stroke-positive (4.87%). Categorical predictor distributions (Table 1) are otherwise clean: no missing values outside the 201-row BMI audit gap, no zero-variance columns, and only one predictor — work type’s <em>never-worked</em> level (22 patients, 0.43%) — small enough to preclude inference. Gender is moderately skewed toward female patients (58.6%); residence type is near-balanced (50.8% urban); the four age bands each hold between 20% and 30% of the cohort, with <em>young</em> the largest despite being the lowest-risk band.</p>
<p><strong>Table 1</strong></p>
<p><em>Marginal Distributions of the Categorical Predictors (N = 5,110)</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Predictor</th>
<th style="text-align: left;">Level</th>
<th style="text-align: right;"><em>n</em></th>
<th style="text-align: right;">%</th>
<th style="text-align: left;">Level</th>
<th style="text-align: right;"><em>n</em></th>
<th style="text-align: right;">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Stroke (outcome)</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">4,861</td>
<td style="text-align: right;">95.13</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">249</td>
<td style="text-align: right;">4.87</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gender</td>
<td style="text-align: left;">Female</td>
<td style="text-align: right;">2,995</td>
<td style="text-align: right;">58.61</td>
<td style="text-align: left;">Male</td>
<td style="text-align: right;">2,115</td>
<td style="text-align: right;">41.39</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hypertension</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">4,612</td>
<td style="text-align: right;">90.25</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">498</td>
<td style="text-align: right;">9.75</td>
</tr>
<tr class="even">
<td style="text-align: left;">Heart disease</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">4,834</td>
<td style="text-align: right;">94.60</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">276</td>
<td style="text-align: right;">5.40</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ever married</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">3,353</td>
<td style="text-align: right;">65.62</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">1,757</td>
<td style="text-align: right;">34.38</td>
</tr>
<tr class="even">
<td style="text-align: left;">Residence type</td>
<td style="text-align: left;">Urban</td>
<td style="text-align: right;">2,596</td>
<td style="text-align: right;">50.80</td>
<td style="text-align: left;">Rural</td>
<td style="text-align: right;">2,514</td>
<td style="text-align: right;">49.20</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Work type</td>
<td style="text-align: left;">Private</td>
<td style="text-align: right;">2,925</td>
<td style="text-align: right;">57.24</td>
<td style="text-align: left;">Self-employed</td>
<td style="text-align: right;">819</td>
<td style="text-align: right;">16.03</td>
</tr>
<tr class="even">
<td style="text-align: left;">”</td>
<td style="text-align: left;">Child-care</td>
<td style="text-align: right;">687</td>
<td style="text-align: right;">13.44</td>
<td style="text-align: left;">Government</td>
<td style="text-align: right;">657</td>
<td style="text-align: right;">12.86</td>
</tr>
<tr class="odd">
<td style="text-align: left;">”</td>
<td style="text-align: left;">Never-worked</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">0.43</td>
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Smoking status</td>
<td style="text-align: left;">Never</td>
<td style="text-align: right;">3,104</td>
<td style="text-align: right;">60.74</td>
<td style="text-align: left;">Formerly</td>
<td style="text-align: right;">1,122</td>
<td style="text-align: right;">21.96</td>
</tr>
<tr class="odd">
<td style="text-align: left;">”</td>
<td style="text-align: left;">Currently</td>
<td style="text-align: right;">884</td>
<td style="text-align: right;">17.30</td>
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Age band</td>
<td style="text-align: left;">Young (0–29 y)</td>
<td style="text-align: right;">1,515</td>
<td style="text-align: right;">29.65</td>
<td style="text-align: left;">Senior (60–82 y)</td>
<td style="text-align: right;">1,376</td>
<td style="text-align: right;">26.93</td>
</tr>
<tr class="odd">
<td style="text-align: left;">”</td>
<td style="text-align: left;">Mature (45–59 y)</td>
<td style="text-align: right;">1,201</td>
<td style="text-align: right;">23.50</td>
<td style="text-align: left;">Mid (30–44 y)</td>
<td style="text-align: right;">1,018</td>
<td style="text-align: right;">19.92</td>
</tr>
</tbody>
</table>
<p><em>Note.</em> Smoking status is 30.22% imputed (see Method). One gender value (0.02%) was imputed to <em>female</em>.</p>
</section>
<section id="continuous-distributions-and-normality" class="level3">
<h3 class="anchored" data-anchor-id="continuous-distributions-and-normality">Continuous distributions and normality</h3>
<p>All five primary continuous features depart sharply from normality (Table 2; D’Agostino–Pearson <em>p</em> &lt; .001 in every case, expected at this sample size). Age is flat and near-symmetric — closer to uniform than Gaussian across the adult range (skew −0.14, kurtosis −0.99). Average glucose is strongly right-skewed (skew 1.57) with a visible secondary mode near 200 mg/dL (Figure 1) — a diabetic subpopulation embedded in the cohort, and the rationale for the &gt; 140 mg/dL flag. BMI is right-skewed and leptokurtic (skew 1.04, kurtosis 3.37), with a tail reaching 97.6. The log transform reduces glucose skew from 1.57 to 0.89 but cannot remove the bimodality, so log-glucose remains non-normal. Because no continuous feature is normal, all subsequent tests are non-parametric.</p>
<p><strong>Table 2</strong></p>
<p><em>Distributional Summary of the Continuous Features (N = 5,110)</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 16%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Feature</th>
<th style="text-align: right;"><em>M</em></th>
<th style="text-align: right;"><em>Mdn</em></th>
<th style="text-align: right;"><em>SD</em></th>
<th style="text-align: right;">Skew</th>
<th style="text-align: right;">Kurtosis</th>
<th style="text-align: center;">Range</th>
<th style="text-align: right;">Normality <em>p</em></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Age (y)</td>
<td style="text-align: right;">43.23</td>
<td style="text-align: right;">45.00</td>
<td style="text-align: right;">22.61</td>
<td style="text-align: right;">−0.14</td>
<td style="text-align: right;">−0.99</td>
<td style="text-align: center;">0.08–82.0</td>
<td style="text-align: right;">&lt; .001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Average glucose (mg/dL)</td>
<td style="text-align: right;">106.15</td>
<td style="text-align: right;">91.89</td>
<td style="text-align: right;">45.28</td>
<td style="text-align: right;">1.57</td>
<td style="text-align: right;">1.68</td>
<td style="text-align: center;">55.1–271.7</td>
<td style="text-align: right;">&lt; .001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">BMI (kg/m²)</td>
<td style="text-align: right;">28.96</td>
<td style="text-align: right;">28.20</td>
<td style="text-align: right;">7.78</td>
<td style="text-align: right;">1.04</td>
<td style="text-align: right;">3.37</td>
<td style="text-align: center;">10.3–97.6</td>
<td style="text-align: right;">&lt; .001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Log-glucose</td>
<td style="text-align: right;">4.60</td>
<td style="text-align: right;">4.53</td>
<td style="text-align: right;">0.36</td>
<td style="text-align: right;">0.89</td>
<td style="text-align: right;">0.16</td>
<td style="text-align: center;">4.03–5.61</td>
<td style="text-align: right;">&lt; .001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Squared age</td>
<td style="text-align: right;">2,379.8</td>
<td style="text-align: right;">2,025.0</td>
<td style="text-align: right;">1,952.3</td>
<td style="text-align: right;">0.61</td>
<td style="text-align: right;">−0.73</td>
<td style="text-align: center;">0.01–6,724</td>
<td style="text-align: right;">&lt; .001</td>
</tr>
</tbody>
</table>
<p><em>Note.</em> Normality is the D’Agostino–Pearson omnibus test. All five statistics reject normality.</p>
<p><strong>Figure 1</strong></p>
<p><em>Distributions of the Three Primary Continuous Features</em></p>
<p><img src="assets/fig1_continuous_distributions.png" class="img-fluid" alt="Three histograms with kernel-density overlays. Age is broad and near-flat. Average glucose is right-skewed with a small secondary hump near 200 mg/dL. BMI is right-skewed with a long upper tail."></p>
<p><em>Note.</em> Bars are density-normalised; the curve is a Gaussian kernel-density estimate. The secondary mass in the glucose panel near 200 mg/dL marks an embedded hyperglycaemic subpopulation.</p>
</section>
<section id="bmi-imputation-sensitivity" class="level3">
<h3 class="anchored" data-anchor-id="bmi-imputation-sensitivity">BMI imputation sensitivity</h3>
<p>The 201 imputed BMI rows (Table 3) have a higher mean (30.58 vs.&nbsp;28.89) and a materially narrower spread (<em>SD</em> 5.46 vs.&nbsp;7.85) than the 4,909 observed rows — the signature of a central-tendency imputation, which pulls values toward the middle and suppresses tails. At 3.9% of the cohort the effect on the full-sample distribution is minor (full-sample <em>M</em> = 28.96, <em>SD</em> = 7.78), so exploratory BMI findings below are described against the complete post-imputation data. The narrowing is flagged for downstream inferential work: BMI odds ratios and adjusted coefficients should be checked against an observed-only sensitivity analysis, since compressed imputed values can mildly inflate apparent group-level associations.</p>
<p><strong>Table 3</strong></p>
<p><em>BMI Distribution: Observed Versus Imputed Rows</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Slice</th>
<th style="text-align: right;"><em>n</em></th>
<th style="text-align: right;"><em>M</em></th>
<th style="text-align: right;"><em>SD</em></th>
<th style="text-align: right;"><em>Mdn</em></th>
<th style="text-align: right;">IQR</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Observed (<code>bmi_raw</code> present)</td>
<td style="text-align: right;">4,909</td>
<td style="text-align: right;">28.89</td>
<td style="text-align: right;">7.85</td>
<td style="text-align: right;">28.10</td>
<td style="text-align: right;">23.5–33.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Imputed</td>
<td style="text-align: right;">201</td>
<td style="text-align: right;">30.58</td>
<td style="text-align: right;">5.46</td>
<td style="text-align: right;">30.08</td>
<td style="text-align: right;">27.98–33.01</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Full post-imputation</td>
<td style="text-align: right;">5,110</td>
<td style="text-align: right;">28.96</td>
<td style="text-align: right;">7.78</td>
<td style="text-align: right;">28.20</td>
<td style="text-align: right;">23.7–33.1</td>
</tr>
</tbody>
</table>
<p><em>Note.</em> The imputed rows are higher on average and roughly 30% less variable than the observed rows.</p>
</section>
<section id="categorical-predictors-versus-stroke" class="level3">
<h3 class="anchored" data-anchor-id="categorical-predictors-versus-stroke">Categorical predictors versus stroke</h3>
<p>Within-group stroke rates (Figure 2, Table 4) separate three genuine signals from three non-signals. <strong>Age band</strong> is the clearest: a monotonic climb from 0.13% (young) to 13.15% (senior), with no confidence-interval overlap between any pair of adjacent bands — the senior rate is 2.7 times the cohort rate. <strong>Hypertension</strong> produces the sharpest binary split among clinical conditions (13.25% vs.&nbsp;3.97%, a 3.3-fold elevation, intervals clear). <strong>Heart disease</strong> shows the largest absolute gap (17.03% vs.&nbsp;4.18%, 4.1-fold); its positive-group interval is wide (13.05–21.91%) because only 276 patients are affected, but its lower bound still sits far above the negative group’s upper bound. <strong>Ever-married</strong> status appears to elevate risk 4-fold (6.56% vs.&nbsp;1.65%) — an effect the association analysis below shows to be age confounding. <strong>Gender</strong> (5.11% male vs.&nbsp;4.71% female) and <strong>residence type</strong> (5.20% urban vs.&nbsp;4.53% rural) show fully overlapping intervals and no signal. <strong>Work type</strong> spans a wide range, but its structure tracks the age composition of each category — <em>self-employed</em> (oldest, 7.94%) highest, <em>child-care</em> (youngest, 0.29%) lowest. <strong>Smoking status</strong> ranks formerly-smoked (7.75%) above currently-smokes (5.32%) above never-smoked (3.70%), a pattern consistent with former smokers being older; the 30.2% imputation rate keeps this exploratory.</p>
<p><strong>Table 4</strong></p>
<p><em>Within-Group Stroke Rates for the Categorical Predictors, With Wilson 95% Confidence Intervals</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 21%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Predictor</th>
<th style="text-align: left;">Level</th>
<th style="text-align: right;"><em>n</em></th>
<th style="text-align: right;">Stroke rate</th>
<th style="text-align: center;">95% CI</th>
<th style="text-align: left;">vs.&nbsp;cohort (4.87%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Age band</td>
<td style="text-align: left;">Young</td>
<td style="text-align: right;">1,515</td>
<td style="text-align: right;">0.13%</td>
<td style="text-align: center;">[0.04, 0.48]</td>
<td style="text-align: left;">far below</td>
</tr>
<tr class="even">
<td style="text-align: left;">”</td>
<td style="text-align: left;">Mid</td>
<td style="text-align: right;">1,018</td>
<td style="text-align: right;">0.79%</td>
<td style="text-align: center;">[0.40, 1.54]</td>
<td style="text-align: left;">below</td>
</tr>
<tr class="odd">
<td style="text-align: left;">”</td>
<td style="text-align: left;">Mature</td>
<td style="text-align: right;">1,201</td>
<td style="text-align: right;">4.83%</td>
<td style="text-align: center;">[3.75, 6.19]</td>
<td style="text-align: left;">at cohort rate</td>
</tr>
<tr class="even">
<td style="text-align: left;">”</td>
<td style="text-align: left;">Senior</td>
<td style="text-align: right;">1,376</td>
<td style="text-align: right;">13.15%</td>
<td style="text-align: center;">[11.47, 15.04]</td>
<td style="text-align: left;">far above</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hypertension</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">4,612</td>
<td style="text-align: right;">3.97%</td>
<td style="text-align: center;">[3.44, 4.57]</td>
<td style="text-align: left;">below</td>
</tr>
<tr class="even">
<td style="text-align: left;">”</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">498</td>
<td style="text-align: right;">13.25%</td>
<td style="text-align: center;">[10.55, 16.51]</td>
<td style="text-align: left;">far above</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Heart disease</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">4,834</td>
<td style="text-align: right;">4.18%</td>
<td style="text-align: center;">[3.65, 4.78]</td>
<td style="text-align: left;">below</td>
</tr>
<tr class="even">
<td style="text-align: left;">”</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">276</td>
<td style="text-align: right;">17.03%</td>
<td style="text-align: center;">[13.05, 21.91]</td>
<td style="text-align: left;">far above</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ever married</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">1,757</td>
<td style="text-align: right;">1.65%</td>
<td style="text-align: center;">[1.15, 2.36]</td>
<td style="text-align: left;">below</td>
</tr>
<tr class="even">
<td style="text-align: left;">”</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">3,353</td>
<td style="text-align: right;">6.56%</td>
<td style="text-align: center;">[5.77, 7.45]</td>
<td style="text-align: left;">above (age-confounded)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gender</td>
<td style="text-align: left;">Female</td>
<td style="text-align: right;">2,995</td>
<td style="text-align: right;">4.71%</td>
<td style="text-align: center;">[4.01, 5.53]</td>
<td style="text-align: left;">overlaps cohort</td>
</tr>
<tr class="even">
<td style="text-align: left;">”</td>
<td style="text-align: left;">Male</td>
<td style="text-align: right;">2,115</td>
<td style="text-align: right;">5.11%</td>
<td style="text-align: center;">[4.25, 6.13]</td>
<td style="text-align: left;">overlaps cohort</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Residence type</td>
<td style="text-align: left;">Rural</td>
<td style="text-align: right;">2,514</td>
<td style="text-align: right;">4.53%</td>
<td style="text-align: center;">[3.79, 5.42]</td>
<td style="text-align: left;">overlaps cohort</td>
</tr>
<tr class="even">
<td style="text-align: left;">”</td>
<td style="text-align: left;">Urban</td>
<td style="text-align: right;">2,596</td>
<td style="text-align: right;">5.20%</td>
<td style="text-align: center;">[4.41, 6.12]</td>
<td style="text-align: left;">overlaps cohort</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Work type</td>
<td style="text-align: left;">Self-employed</td>
<td style="text-align: right;">819</td>
<td style="text-align: right;">7.94%</td>
<td style="text-align: center;">[6.28, 9.99]</td>
<td style="text-align: left;">above</td>
</tr>
<tr class="even">
<td style="text-align: left;">”</td>
<td style="text-align: left;">Private</td>
<td style="text-align: right;">2,925</td>
<td style="text-align: right;">5.09%</td>
<td style="text-align: center;">[4.35, 5.95]</td>
<td style="text-align: left;">overlaps cohort</td>
</tr>
<tr class="odd">
<td style="text-align: left;">”</td>
<td style="text-align: left;">Government</td>
<td style="text-align: right;">657</td>
<td style="text-align: right;">5.02%</td>
<td style="text-align: center;">[3.60, 6.97]</td>
<td style="text-align: left;">overlaps cohort</td>
</tr>
<tr class="even">
<td style="text-align: left;">”</td>
<td style="text-align: left;">Child-care</td>
<td style="text-align: right;">687</td>
<td style="text-align: right;">0.29%</td>
<td style="text-align: center;">[0.08, 1.06]</td>
<td style="text-align: left;">far below</td>
</tr>
<tr class="odd">
<td style="text-align: left;">”</td>
<td style="text-align: left;">Never-worked</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">0.00%</td>
<td style="text-align: center;">[0.00, 14.87]</td>
<td style="text-align: left;">uninformative</td>
</tr>
<tr class="even">
<td style="text-align: left;">Smoking status</td>
<td style="text-align: left;">Never</td>
<td style="text-align: right;">3,104</td>
<td style="text-align: right;">3.70%</td>
<td style="text-align: center;">[3.10, 4.43]</td>
<td style="text-align: left;">below</td>
</tr>
<tr class="odd">
<td style="text-align: left;">”</td>
<td style="text-align: left;">Currently</td>
<td style="text-align: right;">884</td>
<td style="text-align: right;">5.32%</td>
<td style="text-align: center;">[4.02, 7.00]</td>
<td style="text-align: left;">overlaps cohort</td>
</tr>
<tr class="even">
<td style="text-align: left;">”</td>
<td style="text-align: left;">Formerly</td>
<td style="text-align: right;">1,122</td>
<td style="text-align: right;">7.75%</td>
<td style="text-align: center;">[6.33, 9.47]</td>
<td style="text-align: left;">above</td>
</tr>
</tbody>
</table>
<p><em>Note.</em> CI = Wilson score interval. Smoking rows are exploratory (30.22% imputed).</p>
<p><strong>Figure 2</strong></p>
<p><em>Within-Group Stroke Rate by Level for Eight Categorical Predictors (Wilson 95% CI)</em></p>
<p><img src="assets/fig2_categorical_stroke_rates.png" class="img-fluid" alt="Eight small horizontal bar panels of within-group stroke rate with error bars and a dashed line at the 4.87 percent cohort rate. Age band, hypertension, heart disease, ever-married, and formerly-smoked bars clear the reference line; gender, residence type, and most work-type levels straddle it."></p>
<p><em>Note.</em> Dashed line marks the 4.87% cohort rate. Blue = confidence interval clears the cohort rate; red = interval straddles it. Bars are sorted within panel by rate.</p>
</section>
<section id="continuous-predictors-versus-stroke" class="level3">
<h3 class="anchored" data-anchor-id="continuous-predictors-versus-stroke">Continuous predictors versus stroke</h3>
<p>Ranking by rank-biserial effect size (Table 5): age (|<em>r</em>| = 0.67) ≫ average glucose (|<em>r</em>| = 0.22) = log-glucose (0.22) &gt; BMI (0.14). Only age carries a large effect; glucose and BMI are real but modest. The decile rate curves (Figure 3) show three distinct shapes. Age is cleanly monotonic — near-zero through the third decile, then rising to 20.65% in the top decile (ages 75–82). Glucose is a threshold relationship — deciles 1–8 (55–120 mg/dL) all sit near the cohort rate, and the signal appears only in decile 9 (6.27%) and decile 10 (13.31%). BMI is non-monotonic — an inverted U peaking in the middle deciles (7.75% at BMI 27–28) and declining at both extremes; the low rate in the bottom decile reflects the youth of underweight patients, not protection. Log-glucose reproduces the glucose <em>U</em> statistic and <em>p</em>-value exactly, because a monotone transform leaves rank-based tests unchanged.</p>
<p><strong>Table 5</strong></p>
<p><em>Continuous Predictors Versus Stroke: Mann–Whitney U and Correlations</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Predictor</th>
<th style="text-align: right;"><em>U</em></th>
<th style="text-align: right;"><em>p</em></th>
<th style="text-align: right;">Rank-biserial <em>r</em></th>
<th style="text-align: right;">Point-biserial <em>r</em></th>
<th style="text-align: left;">Rate-curve shape</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Age</td>
<td style="text-align: right;">1,010,125.5</td>
<td style="text-align: right;">&lt; .001</td>
<td style="text-align: right;">−0.669</td>
<td style="text-align: right;">.245</td>
<td style="text-align: left;">monotonic</td>
</tr>
<tr class="even">
<td style="text-align: left;">Squared age</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">.275</td>
<td style="text-align: left;">monotonic (accelerating)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Age × log-glucose</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">.258</td>
<td style="text-align: left;">monotonic</td>
</tr>
<tr class="even">
<td style="text-align: left;">Age × BMI</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">.213</td>
<td style="text-align: left;">monotonic</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Average glucose</td>
<td style="text-align: right;">739,150.0</td>
<td style="text-align: right;">&lt; .001</td>
<td style="text-align: right;">−0.221</td>
<td style="text-align: right;">.132</td>
<td style="text-align: left;">threshold (top 2 deciles)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Log-glucose</td>
<td style="text-align: right;">739,150.0</td>
<td style="text-align: right;">&lt; .001</td>
<td style="text-align: right;">−0.221</td>
<td style="text-align: right;">.117</td>
<td style="text-align: left;">threshold (identical ranks)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">BMI</td>
<td style="text-align: right;">692,674.5</td>
<td style="text-align: right;">&lt; .001</td>
<td style="text-align: right;">−0.145</td>
<td style="text-align: right;">.039</td>
<td style="text-align: left;">non-monotonic (inverted U)</td>
</tr>
</tbody>
</table>
<p><em>Note.</em> Rank-biserial <em>r</em> is signed by the test’s group ordering; magnitude is what matters. All associations are significant at α = .05. Engineered age terms are shown with point-biserial <em>r</em> only.</p>
<p><strong>Figure 3</strong></p>
<p><em>Stroke Rate by Population Decile of Age, Average Glucose, and BMI</em></p>
<p><img src="assets/fig3_continuous_decile_rates.png" class="img-fluid" alt="Three line charts of stroke rate across ten deciles. Age rises smoothly and monotonically to about 21 percent. Average glucose is flat near the cohort rate through decile 8 then jumps in deciles 9 and 10. BMI rises to a mid-range peak near 8 percent then falls."></p>
<p><em>Note.</em> Dashed line marks the 4.87% cohort rate. The three shapes — monotonic, threshold, inverted-U — are the qualitative signatures that drive feature-engineering choices (a squared-age term, a glucose threshold flag).</p>
</section>
<section id="age-stratified-analysis" class="level3">
<h3 class="anchored" data-anchor-id="age-stratified-analysis">Age-stratified analysis</h3>
<p>Resolving age to ten-year bands (Figure 4) sharpens the gradient the four-band view compresses: the within-decade stroke rate is at or below 1% through the fifth decade (0.9% at 30–39, 1.6% at 40–49), then accelerates — 5.8% (50–59), 7.6% (60–69), 16.5% (70–79), 21.5% (80+). The acceleration point is the sixth-to-seventh decade transition, and the senior band alone (n = 1,376) carries 181 of 249 events. Stratifying by hypertension within age band (Figure 5, Table 6) shows an <strong>additive</strong> pattern: hypertension raises the rate within every band, and the absolute elevation is largest where the baseline is already high (+6.1 points in the senior band, +3.9 in mature, +1.5 in mid). The young band has only 11 hypertension-positive patients and cannot support inference.</p>
<p>Within-band distributions of the two key continuous predictors (Figure 6) reveal how age carries co-varying risk. The senior band’s average-glucose interquartile range (95.3 mg/dL) is roughly three times that of the other bands (30–40 mg/dL) and extends deep into the hyperglycaemic range — older patients are over-represented in the high-age <em>and</em> high-glucose risk dimensions simultaneously. BMI shows the opposite: the senior band has the most compressed BMI distribution (IQR 7.0) while the young band is the most dispersed and outlier-heavy (skew 2.04). Age is therefore not one predictor among many but the axis around which the others must be read.</p>
<p><strong>Table 6</strong></p>
<p><em>Stroke Rate by Age Band and Hypertension Status</em></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Age band</th>
<th style="text-align: right;">No hypertension</th>
<th style="text-align: left;"></th>
<th style="text-align: right;">Hypertension</th>
<th style="text-align: left;"></th>
<th style="text-align: right;">Absolute gap</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: right;">rate</td>
<td style="text-align: left;"><em>n</em></td>
<td style="text-align: right;">rate</td>
<td style="text-align: left;"><em>n</em></td>
<td style="text-align: right;">(points)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Young</td>
<td style="text-align: right;">0.13%</td>
<td style="text-align: left;">1,504</td>
<td style="text-align: right;">0.00%</td>
<td style="text-align: left;">11</td>
<td style="text-align: right;">— (n too small)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mid</td>
<td style="text-align: right;">0.72%</td>
<td style="text-align: left;">973</td>
<td style="text-align: right;">2.22%</td>
<td style="text-align: left;">45</td>
<td style="text-align: right;">+1.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mature</td>
<td style="text-align: right;">4.36%</td>
<td style="text-align: left;">1,055</td>
<td style="text-align: right;">8.22%</td>
<td style="text-align: left;">146</td>
<td style="text-align: right;">+3.9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Senior</td>
<td style="text-align: right;">11.85%</td>
<td style="text-align: left;">1,080</td>
<td style="text-align: right;">17.91%</td>
<td style="text-align: left;">296</td>
<td style="text-align: right;">+6.1</td>
</tr>
</tbody>
</table>
<p><em>Note.</em> The elevation from hypertension is roughly constant in fold-change but grows in absolute points as the baseline rate rises — an additive interaction with age.</p>
<p><strong>Figure 4</strong></p>
<p><em>Within-Decade Stroke Rate Across the Age Range (Wilson 95% CI)</em></p>
<p><img src="assets/fig4_age_gradient_decade.png" class="img-fluid" alt="A line of within-decade stroke rate against age band. The line hugs zero through the 20s and 30s, lifts gently through the 40s and 50s, then climbs steeply: 7.6 percent in the 60s, 16.5 percent in the 70s, 21.5 percent past 80. A shaded band marks the confidence interval; a shaded region highlights the 60-plus acceleration zone."></p>
<p><em>Note.</em> Marker fill encodes rate. Shaded band = Wilson 95% CI; shaded region = the post-60 acceleration zone. Ten-year resolution exposes an inflection the four-band variable hides.</p>
<p><strong>Figure 5</strong></p>
<p><em>Stroke Rate by Age Band, Split by Hypertension Status</em></p>
<p><img src="assets/fig5_age_hypertension.png" class="img-fluid" alt="Grouped bars of stroke rate for the four age bands, each split into no-hypertension and hypertension. Both series rise steeply with age; the hypertension bar is higher within every band, and the gap widens in absolute terms toward the senior band."></p>
<p><em>Note.</em> The young/hypertension cell (n = 11) is shown for completeness but carries no inferential weight.</p>
<p><strong>Figure 6</strong></p>
<p><em>Average Glucose and BMI Distributions Within Each Age Band</em></p>
<p><img src="assets/fig6_within_band_boxplots.png" class="img-fluid" alt="Two panels of box plots by age band. Average glucose spread widens markedly in the senior band and shifts upward. BMI spread is widest in the young band and most compressed in the senior band."></p>
<p><em>Note.</em> Outliers suppressed for legibility. The senior band concentrates high-age and high-glucose risk together; BMI variance moves the opposite way.</p>
</section>
<section id="association-structure" class="level3">
<h3 class="anchored" data-anchor-id="association-structure">Association structure</h3>
<p>Among continuous features (Figure 7), the high Spearman correlations are by design — age with squared age (ρ = 1.00), average glucose with log-glucose (ρ = 1.00), age with age × glucose (ρ = 0.99) and age × BMI (ρ = 0.92). These are engineered redundancies to be resolved by feature selection, not multicollinearity to be pruned blindly. The only notable <em>empirical</em> correlation is age with BMI (ρ = 0.37) — older patients here carry higher BMI.</p>
<p>Among categorical features (Figure 8, Table 7), the dominant pair is <strong>ever-married × age band (Cramér’s <em>V</em> = 0.75)</strong> — a large association confirming marital status functions as an age proxy in this cohort, and the explanation for its apparent stroke-rate elevation in Table 4. Work type also tracks the age band (<em>V</em> = 0.39), as do heart disease (<em>V</em> = 0.28) and hypertension (<em>V</em> = 0.28) — clinical conditions accumulate with age. Against the outcome itself, the ranking is age band (<em>V</em> = 0.25, moderate) &gt; heart disease (0.13) &gt; hypertension (0.13) &gt; ever-married (0.11), with gender and residence type at exactly 0.00 and smoking at 0.07.</p>
<p>The consolidated association landscape (Figure 9) places every feature on one axis. The top five are all age-derived (squared age 0.28, age × glucose 0.26, age band 0.25, age 0.25, age × BMI 0.21); a middle tier of cardiovascular and glucose features sits between 0.11 and 0.13; obesity (0.02), residence type (0.01), and gender (0.00) form the floor.</p>
<p><strong>Table 7</strong></p>
<p><em>Selected Cramér’s V Associations (Bias-Corrected)</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Pair</th>
<th style="text-align: right;">Cramér’s <em>V</em></th>
<th style="text-align: left;">Reading</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Ever married × age band</td>
<td style="text-align: right;">0.750</td>
<td style="text-align: left;">large — marital status is an age proxy</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ever married × work type</td>
<td style="text-align: right;">0.567</td>
<td style="text-align: left;">large — overlapping life-stage categories</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Work type × age band</td>
<td style="text-align: right;">0.391</td>
<td style="text-align: left;">moderate</td>
</tr>
<tr class="even">
<td style="text-align: left;">Heart disease × age band</td>
<td style="text-align: right;">0.282</td>
<td style="text-align: left;">moderate — conditions accrue with age</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hypertension × age band</td>
<td style="text-align: right;">0.278</td>
<td style="text-align: left;">moderate</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Age band × stroke</strong></td>
<td style="text-align: right;"><strong>0.247</strong></td>
<td style="text-align: left;"><strong>moderate — strongest categorical predictor</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Heart disease × stroke</td>
<td style="text-align: right;">0.134</td>
<td style="text-align: left;">small</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hypertension × stroke</td>
<td style="text-align: right;">0.127</td>
<td style="text-align: left;">small</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ever married × stroke</td>
<td style="text-align: right;">0.107</td>
<td style="text-align: left;">small (age-confounded)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Work type × stroke</td>
<td style="text-align: right;">0.094</td>
<td style="text-align: left;">negligible</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Smoking status × stroke</td>
<td style="text-align: right;">0.074</td>
<td style="text-align: left;">negligible (and 30% imputed)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Residence type × stroke</td>
<td style="text-align: right;">0.007</td>
<td style="text-align: left;">null</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gender × stroke</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: left;">null</td>
</tr>
</tbody>
</table>
<p><em>Note.</em> Cohen’s conventions: <em>V</em> ≈ .10 small, .30 moderate, ≥ .50 large at these degrees of freedom.</p>
<p><strong>Figure 7</strong></p>
<p><em>Spearman Correlation Matrix of the Continuous and Engineered Features</em></p>
<p><img src="assets/fig7_spearman_matrix.png" class="img-fluid" alt="A 7-by-7 correlation heatmap. Blocks of near-1.0 correlation link age with squared age, age with the age interaction terms, and average glucose with log-glucose. Age-BMI is a moderate 0.37; other off-design pairs are weak."></p>
<p><em>Note.</em> The ρ ≈ 1 blocks are engineered relationships (a squared term, a log term, two products of age). Age × BMI (ρ = 0.37) is the only substantial empirical correlation.</p>
<p><strong>Figure 8</strong></p>
<p><em>Bias-Corrected Cramér’s V Matrix of the Categorical Features and the Outcome</em></p>
<p><img src="assets/fig8_cramers_v_matrix.png" class="img-fluid" alt="A 9-by-9 Cramér's V heatmap. The brightest off-diagonal cell is ever-married by age band at 0.75. The stroke row peaks at age band (0.25) and is 0.00 for gender and residence type."></p>
<p><em>Note.</em> The ever-married × age-band cell (0.75) is the confounding structure behind the marital-status rate elevation in Table 4.</p>
<p><strong>Figure 9</strong></p>
<p><em>Every Feature Ranked by Association Strength With Stroke</em></p>
<p><img src="assets/fig9_association_landscape.png" class="img-fluid" alt="A horizontal bar ranking of about 21 features by association strength with stroke. The top five bars — squared age, age-by-glucose, age band, age, age-by-BMI — are the longest, near 0.21 to 0.28. Heart disease, average glucose, high-glucose flag, and hypertension form a middle group near 0.13. Gender is zero at the bottom."></p>
<p><em>Note.</em> Green = |point-biserial <em>r</em>| (continuous features and flags); blue = Cramér’s <em>V</em> (categorical features). The two metrics are not identical in scale but rank features consistently: age-derived terms lead, obesity and gender sit at the floor.</p>
</section>
<section id="interaction-terms" class="level3">
<h3 class="anchored" data-anchor-id="interaction-terms">Interaction terms</h3>
<p>The four engineered interaction terms (Table 8) split cleanly. The two continuous ones carry meaningful signal — age × log-glucose (point-biserial <em>r</em> = 0.26) marginally exceeds raw age (0.25), and age × BMI (0.21) lifts the weak BMI signal by weighting it toward older patients. The two binary ones are weaker but interpretable: the joint hypertension-and-elevated-glucose flag (178 patients, 3.5%) marks the highest single-point categorical rate in the whole analysis — 16.85% versus 4.44% — while the joint smoker-and-obese flag is the weakest term (<em>r</em> = 0.04) and additionally inherits the smoking imputation caveat.</p>
<p><strong>Table 8</strong></p>
<p><em>Interaction Terms Versus Stroke</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Term</th>
<th style="text-align: left;">Definition</th>
<th style="text-align: right;">Point-biserial <em>r</em></th>
<th style="text-align: right;"><em>p</em></th>
<th style="text-align: left;">Rate contrast</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Age × log-glucose</td>
<td style="text-align: left;">continuous product</td>
<td style="text-align: right;">.258</td>
<td style="text-align: right;">&lt; .001</td>
<td style="text-align: left;">—</td>
</tr>
<tr class="even">
<td style="text-align: left;">Age × BMI</td>
<td style="text-align: left;">continuous product</td>
<td style="text-align: right;">.213</td>
<td style="text-align: right;">&lt; .001</td>
<td style="text-align: left;">—</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hypertension × high glucose</td>
<td style="text-align: left;">both conditions present (<em>n</em> = 178)</td>
<td style="text-align: right;">.106</td>
<td style="text-align: right;">&lt; .001</td>
<td style="text-align: left;">16.85% vs.&nbsp;4.44% (3.8×)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Smoker × obese</td>
<td style="text-align: left;">both conditions present (<em>n</em> = 926)</td>
<td style="text-align: right;">.040</td>
<td style="text-align: right;">.004</td>
<td style="text-align: left;">6.70% vs.&nbsp;4.47% (1.5×)</td>
</tr>
</tbody>
</table>
<p><em>Note.</em> The hypertension × high-glucose flag produces the highest observed within-group rate in the categorical analysis.</p>
</section>
<section id="consolidated-feature-level-findings" class="level3">
<h3 class="anchored" data-anchor-id="consolidated-feature-level-findings">Consolidated feature-level findings</h3>
<p>Table 9 collapses the results above into one decision surface. Three exclusion candidates emerge for downstream modelling: <strong>gender</strong> (<em>V</em> = 0.00) and <strong>residence type</strong> (<em>V</em> = 0.01) are genuine nulls against clean, balanced distributions; <strong>log-glucose</strong> is a redundant monotone transform of average glucose (ρ = 1.00, identical ranks). Age and its engineered relatives are the credentialled signal; hypertension, heart disease, and the hypertension × glucose flag are the credentialled clinical predictors; BMI, smoking, and their flags are retained only as weak or confounded candidates.</p>
<p><strong>Table 9</strong></p>
<p><em>Feature-Level Findings Summary</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Feature</th>
<th style="text-align: left;">Type</th>
<th style="text-align: left;">Effect size vs.&nbsp;stroke</th>
<th style="text-align: left;">Direction / verdict</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Age</td>
<td style="text-align: left;">continuous</td>
<td style="text-align: left;">rank-biserial |<em>r</em>| = 0.67 (large); <em>r</em>ₚᵦ = .25</td>
<td style="text-align: left;">monotonic; dominant signal</td>
</tr>
<tr class="even">
<td style="text-align: left;">Squared age</td>
<td style="text-align: left;">continuous</td>
<td style="text-align: left;"><em>r</em>ₚᵦ = .27</td>
<td style="text-align: left;">accelerating age term; select against raw age</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Age × log-glucose</td>
<td style="text-align: left;">interaction</td>
<td style="text-align: left;"><em>r</em>ₚᵦ = .26</td>
<td style="text-align: left;">strongest engineered term</td>
</tr>
<tr class="even">
<td style="text-align: left;">Age × BMI</td>
<td style="text-align: left;">interaction</td>
<td style="text-align: left;"><em>r</em>ₚᵦ = .21</td>
<td style="text-align: left;">lifts weak BMI signal</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Age band</td>
<td style="text-align: left;">ordinal</td>
<td style="text-align: left;"><em>V</em> = 0.25 (moderate)</td>
<td style="text-align: left;">strongest categorical predictor; mandatory stratifier</td>
</tr>
<tr class="even">
<td style="text-align: left;">Heart disease</td>
<td style="text-align: left;">binary</td>
<td style="text-align: left;"><em>V</em> = 0.13; 17.03% vs.&nbsp;4.18%</td>
<td style="text-align: left;">4.1× rate elevation; small positive group (<em>n</em> = 276)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Average glucose</td>
<td style="text-align: left;">continuous</td>
<td style="text-align: left;">rank-biserial |<em>r</em>| = 0.22; <em>r</em>ₚᵦ = .13</td>
<td style="text-align: left;">threshold effect above ~140 mg/dL</td>
</tr>
<tr class="even">
<td style="text-align: left;">High-glucose flag</td>
<td style="text-align: left;">binary flag</td>
<td style="text-align: left;"><em>r</em>ₚᵦ = .13</td>
<td style="text-align: left;">captures the threshold; &gt; 140 mg/dL</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hypertension</td>
<td style="text-align: left;">binary</td>
<td style="text-align: left;"><em>V</em> = 0.13; 13.25% vs.&nbsp;3.97%</td>
<td style="text-align: left;">3.3× rate elevation; sharpest binary split</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hypertension × high glucose</td>
<td style="text-align: left;">interaction</td>
<td style="text-align: left;"><em>r</em>ₚᵦ = .11; 16.85% vs.&nbsp;4.44%</td>
<td style="text-align: left;">highest single-group rate; retain</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ever married</td>
<td style="text-align: left;">binary</td>
<td style="text-align: left;"><em>V</em> = 0.11; 6.56% vs.&nbsp;1.65%</td>
<td style="text-align: left;">apparent 4× elevation is age confounding (<em>V</em> vs.&nbsp;age band = 0.75)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Work type</td>
<td style="text-align: left;">multi-level</td>
<td style="text-align: left;"><em>V</em> = 0.09</td>
<td style="text-align: left;">gradient tracks age composition</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Smoking status</td>
<td style="text-align: left;">multi-level</td>
<td style="text-align: left;"><em>V</em> = 0.07; formerly 7.75%</td>
<td style="text-align: left;">exploratory only — 30.22% imputed</td>
</tr>
<tr class="even">
<td style="text-align: left;">BMI</td>
<td style="text-align: left;">continuous</td>
<td style="text-align: left;">rank-biserial |<em>r</em>| = 0.14; <em>r</em>ₚᵦ = .04</td>
<td style="text-align: left;">weak, non-monotonic; 201 imputed</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Smoker × obese</td>
<td style="text-align: left;">interaction</td>
<td style="text-align: left;"><em>r</em>ₚᵦ = .04; 6.70% vs.&nbsp;4.47%</td>
<td style="text-align: left;">weakest term; imputation caveat</td>
</tr>
<tr class="even">
<td style="text-align: left;">Residence type</td>
<td style="text-align: left;">binary</td>
<td style="text-align: left;"><em>V</em> = 0.01</td>
<td style="text-align: left;">null — exclude</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gender</td>
<td style="text-align: left;">binary</td>
<td style="text-align: left;"><em>V</em> = 0.00</td>
<td style="text-align: left;">null — exclude</td>
</tr>
</tbody>
</table>
<p><em>Note.</em> <em>r</em>ₚᵦ = point-biserial correlation with the integer outcome. Odds ratios and adjusted effects are deferred to the inferential study.</p>
</section>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<section id="age-is-the-organising-variable" class="level3">
<h3 class="anchored" data-anchor-id="age-is-the-organising-variable">Age is the organising variable</h3>
<p>Age leads every metric applied — the largest rank-biserial correlation (three times the next predictor), the strongest categorical <em>V</em> against the outcome, and the top five slots in the consolidated association landscape once its engineered relatives are counted. The ten-year gradient locates the clinically relevant inflection at the sixth-to-seventh decade, and the within-band distributions show <em>why</em> age is so dominant: the senior band concentrates high-glucose risk alongside high-age risk. The practical consequence is that age is not an ordinary covariate to include but the axis every other comparison must be read against, and any downstream feature-importance analysis that does not hold age fixed will misattribute age’s signal to its correlates.</p>
</section>
<section id="confounding-the-marital-status-result" class="level3">
<h3 class="anchored" data-anchor-id="confounding-the-marital-status-result">Confounding: the marital-status result</h3>
<p>Ever-married status shows a clean 4-fold within-group rate elevation in isolation (6.56% vs.&nbsp;1.65%), which a naive read would treat as a risk factor. The categorical association matrix contradicts that read directly: marital status correlates with the age band at Cramér’s <em>V</em> = 0.75, the largest association in the dataset. The never-married group is predominantly young, and its low stroke rate reflects age, not marital state. This is the single clearest confounding structure in the cohort and the reason an inferential study must age-adjust marital status before quantifying any effect.</p>
</section>
<section id="genuine-nulls" class="level3">
<h3 class="anchored" data-anchor-id="genuine-nulls">Genuine nulls</h3>
<p>Gender and residence type both return Cramér’s <em>V</em> = 0.00 against the outcome, on top of clean, balanced marginal distributions and fully overlapping rate intervals. These are not artefacts of small samples or skewed groups — they are informative negatives, and both features are exclusion candidates for downstream modelling. The smoking-status association (<em>V</em> = 0.07) is directionally plausible but rests on 30.2% imputed values and cannot be promoted past exploratory.</p>
</section>
<section id="shape-matters-as-much-as-strength" class="level3">
<h3 class="anchored" data-anchor-id="shape-matters-as-much-as-strength">Shape matters as much as strength</h3>
<p>The three continuous predictors carry three different relationship shapes: age is monotonic, glucose is a threshold effect confined to its top two deciles, and BMI is a weak inverted U. Those shapes, not just the effect sizes, justify the engineered features — a squared-age term for the acceleration, a &gt; 140 mg/dL flag for the glucose threshold — and they tell a downstream modeller where linear terms will and will not suffice.</p>
</section>
<section id="limitations" class="level3">
<h3 class="anchored" data-anchor-id="limitations">Limitations</h3>
<p>The study is cross-sectional and exploratory: it quantifies association and shape, not causation, and reports no adjusted effects. Several groups are small (heart-disease positives <em>n</em> = 276; hypertension × glucose <em>n</em> = 178; never-worked <em>n</em> = 22), producing wide intervals or, in one case, no possible inference. Smoking is 30.2% imputed and BMI 3.9% imputed, with the imputed BMI values measurably narrower than observed ones. All engineered interaction terms are near-collinear with age by construction and must be selected among, not stacked.</p>
</section>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion">Conclusion</h3>
<p>In this 5,110-patient cohort, age and its engineered relatives are the dominant stroke signal; hypertension, heart disease, and co-occurring hypertension-and-hyperglycaemia are the credentialled clinical predictors; marital status is an age artefact; and gender and residence type carry no signal at all. The feature-level findings table is the handoff: it defines which features enter inferential odds-ratio analysis and predictive modelling, and which are set aside on the evidence assembled here.</p>
</section>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<p>Bergsma, W. (2013). A bias-correction for Cramér’s V and Tschuprow’s T. <em>Journal of the Korean Statistical Society, 42</em>(3), 323–328. https://doi.org/10.1016/j.jkss.2012.10.002</p>
<p>Cohen, J. (1988). <em>Statistical power analysis for the behavioral sciences</em> (2nd ed.). Lawrence Erlbaum Associates.</p>
<p>D’Agostino, R., &amp; Pearson, E. S. (1973). Tests for departure from normality: Empirical results for the distributions of b₂ and √b₁. <em>Biometrika, 60</em>(3), 613–622. https://doi.org/10.1093/biomet/60.3.613</p>
<p>fedesoriano. (2021). <em>Stroke prediction dataset</em> [Data set]. Kaggle. https://www.kaggle.com/datasets/fedesoriano/stroke-prediction-dataset</p>
<p>Harris, C. R., Millman, K. J., van der Walt, S. J., Gommers, R., Virtanen, P., Cournapeau, D., Wieser, E., Taylor, J., Berg, S., Smith, N. J., Kern, R., Picus, M., Hoyer, S., van Kerkwijk, M. H., Brett, M., Haldane, A., del Río, J. F., Wiebe, M., Peterson, P., … Oliphant, T. E. (2020). Array programming with NumPy. <em>Nature, 585</em>, 357–362. https://doi.org/10.1038/s41586-020-2649-2</p>
<p>Hunter, J. D. (2007). Matplotlib: A 2D graphics environment. <em>Computing in Science &amp; Engineering, 9</em>(3), 90–95. https://doi.org/10.1109/MCSE.2007.55</p>
<p>Kerby, D. S. (2014). The simple difference formula: An approach to teaching nonparametric correlation. <em>Comprehensive Psychology, 3</em>, Article 1. https://doi.org/10.2466/11.IT.3.1</p>
<p>Mann, H. B., &amp; Whitney, D. R. (1947). On a test of whether one of two random variables is stochastically larger than the other. <em>The Annals of Mathematical Statistics, 18</em>(1), 50–60. https://doi.org/10.1214/aoms/1177730491</p>
<p>Spearman, C. (1904). The proof and measurement of association between two things. <em>The American Journal of Psychology, 15</em>(1), 72–101. https://doi.org/10.2307/1412159</p>
<p>Tate, R. F. (1954). Correlation between a discrete and a continuous variable: Point-biserial correlation. <em>The Annals of Mathematical Statistics, 25</em>(3), 603–607. https://doi.org/10.1214/aoms/1177728730</p>
<p>The pandas development team. (2020). <em>pandas-dev/pandas: Pandas</em> (Version latest) [Computer software]. Zenodo. https://doi.org/10.5281/zenodo.3509134</p>
<p>Virtanen, P., Gommers, R., Oliphant, T. E., Haberland, M., Reddy, T., Cournapeau, D., Burovski, E., Peterson, P., Weckesser, W., Bright, J., van der Walt, S. J., Brett, M., Wilson, J., Millman, K. J., Mayorov, N., Nelson, A. R. J., Jones, E., Kern, R., Larson, E., … SciPy 1.0 Contributors. (2020). SciPy 1.0: Fundamental algorithms for scientific computing in Python. <em>Nature Methods, 17</em>, 261–272. https://doi.org/10.1038/s41592-019-0686-2</p>
<p>Wilson, E. B. (1927). Probable inference, the law of succession, and statistical inference. <em>Journal of the American Statistical Association, 22</em>(158), 209–212. https://doi.org/10.2307/2276774</p>
<hr>
<p><em>Analytical workflow and figures by the author. This is an exploratory study; associations reported here are not adjusted for confounding and do not support causal claims.</em></p>


<div id="contact" class="connect-section" style="text-align: center; padding: 50px 20px; background: #f9f9f9; border-radius: 15px; border: 1px solid #eaeaea; margin-top: 40px;">
<h3 style="color: #2c3e50; font-weight: 700; margin-bottom: 15px; border: none;" class="anchored">Let's Collaborate</h3>
<p style="color: #666; max-width: 650px; margin: 0 auto 30px auto; font-size: 1.05rem; line-height: 1.6;">Available for high-impact <strong>Business Intelligence, Power BI Engineering, and Advanced Data Analytics</strong> projects. Connect with me or hire me directly through the platforms below.</p>
<div style="display: flex; flex-wrap: wrap; justify-content: center; gap: 12px;">
<a href="https://www.linkedin.com/in/mkmuneer" class="btn btn-primary" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; text-decoration: none;"><i class="bi bi-linkedin"></i> LinkedIn</a>
<a href="https://github.com/mkhanmuneer" class="btn btn-dark" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; text-decoration: none;"><i class="bi bi-github"></i> GitHub</a>
<a href="https://www.kaggle.com/muhammadkhanmuneer" class="btn btn-info" target="_blank" rel="noopener" style="color: white; padding: 12px 25px; min-width: 150px; text-decoration: none;"><i class="bi bi-graph-up"></i> Kaggle</a>
<a href="https://www.upwork.com/freelancers/~018de8553286a1d00c" class="btn btn-outline-success" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; border-width: 2px; font-weight: 600; text-decoration: none;"><i class="bi bi-briefcase"></i> Upwork</a>
<a href="https://www.fiverr.com/neuronvision" class="btn btn-outline-success" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; border-width: 2px; font-weight: 600; text-decoration: none;"><i class="bi bi-lightning-charge"></i> Fiverr</a>
</div>
</div>

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/mkhanmuneer\.github\.io\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 Muhammad Khan Muneer</p>
</div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://www.upwork.com/freelancers/~018de8553286a1d00c">
<p>Hire on Upwork</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="https://www.fiverr.com/neuronvision">
<p>Hire on Fiverr</p>
</a>
  </li>  
</ul>
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mkhanmuneer">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/mkmuneer">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>