<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Muhammad Khan Muneer">
<meta name="keywords" content="stroke screening, binary classification, class imbalance, SMOTE, class weighting, hyperparameter tuning, ROC-AUC, precision-recall, Youden’s J, clinical impact analysis, number needed to screen, calibration, Brier score, SHAP, elastic net, XGBoost, LightGBM, Python, scikit-learn">
<meta name="description" content="A binary stroke-screening pipeline benchmarked end to end. Champion: a regularised linear model (GLMNET / Elastic Net) wins on ranking — test ROC-AUC 0.841 vs.&nbsp;XGBoost 0.821 and LightGBM 0.808 — despite being the simplest architecture. Class weighting is the load-bearing fix: recall jumps from ~0.04 to ~0.80 from tier 1 to tier 2; SMOTE adds only an increment. Named trade-off: GLMNET ranks best but calibrates worst (Brier 0.178 vs.&nbsp;~0.043) — acceptable for a binary flag, not for risk communication. Widest operating range: GLMNET holds recall to a 0.6 threshold; the tree models collapse by 0.3.">

<title>Clinical Stroke-Screening Model Benchmarking: Champion Selection, Threshold Profiling, and a Calibration Trade-off – Muhammad Khan Muneer</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-4d9afe2b8d18ee9fa5d0d57b5ed4214d.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-5af9b5ab1fa0c387551d40c1aacb317e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-ca0cfe78a00f84493d894d8af57a3a20.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-5af9b5ab1fa0c387551d40c1aacb317e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": true,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<link rel="stylesheet" href="../../styles/custom.css">
<meta property="og:title" content="Muhammad Khan Muneer — Data Science &amp; BI Portfolio">
<meta property="og:description" content="Engineering ML-driven analytics and automated decision systems.">
<meta property="og:image" content="https://mkhanmuneer.github.io/projects/clinical-stroke-screening-model-benchmarking-champion-selection-threshold-profiling-calibration/assets/fig8_pipeline_diagram.png">
<meta property="og:site_name" content="M. Khan Muneer Portfolio">
<meta property="og:image:alt" content="Five boxes left to right: Gold features (5,110 x 24), Preprocess (21 predictors, ordinal encode, stratified 80/20 split), 3-tier baseline (unweighted to weighted to weighted + SMOTE), Tune (5x50 CV, three models, SMOTE in-fold), Champion + export (GLMNET, SHAP, calibration, clinical impact, manifest).">
<meta property="og:image:height" content="594">
<meta property="og:image:width" content="2132">
<meta name="twitter:title" content="Clinical Stroke-Screening Model Benchmarking: Champion Selection, Threshold Profiling, and a Calibration Trade-off – Muhammad Khan Muneer">
<meta name="twitter:description" content="A binary stroke-screening pipeline benchmarked end to end. Champion: a regularised linear model (GLMNET / Elastic Net) wins on ranking — test ROC-AUC 0.841 vs.&nbsp;XGBoost 0.821 and LightGBM 0.808 — despite being the simplest architecture. Class weighting is the load-bearing fix: recall jumps from ~0.04 to ~0.80 from tier 1 to tier 2; SMOTE adds only an increment. Named trade-off: GLMNET ranks best but calibrates worst (Brier 0.178 vs.&nbsp;~0.043) — acceptable for a binary flag, not for risk communication. Widest operating range: GLMNET holds recall to a 0.6 threshold; the tree models collapse by 0.3.">
<meta name="twitter:image" content="https://mkhanmuneer.github.io/projects/clinical-stroke-screening-model-benchmarking-champion-selection-threshold-profiling-calibration/assets/fig8_pipeline_diagram.png">
<meta name="twitter:creator" content="@iMKhanMuneer">
<meta name="twitter:site" content="@iMKhanMuneer">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image:alt" content="Five boxes left to right: Gold features (5,110 x 24), Preprocess (21 predictors, ordinal encode, stratified 80/20 split), 3-tier baseline (unweighted to weighted to weighted + SMOTE), Tune (5x50 CV, three models, SMOTE in-fold), Champion + export (GLMNET, SHAP, calibration, clinical impact, manifest).">
<meta name="twitter:image-height" content="594">
<meta name="twitter:image-width" content="2132">
</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../index.html#featured-projects"> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/mkmuneer"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mkhanmuneer"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://x.com/iMKhanMuneer"> <i class="bi bi-twitter-x" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.kaggle.com/muhammadkhanmuneer"> <i class="bi bi-graph-up" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../index.html#contact"> 
<span class="menu-text">Contact</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract">Abstract</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#method" id="toc-method" class="nav-link" data-scroll-target="#method">Method</a>
  <ul class="collapse">
  <li><a href="#data-and-feature-set" id="toc-data-and-feature-set" class="nav-link" data-scroll-target="#data-and-feature-set">Data and feature set</a></li>
  <li><a href="#preprocessing-and-split" id="toc-preprocessing-and-split" class="nav-link" data-scroll-target="#preprocessing-and-split">Preprocessing and split</a></li>
  <li><a href="#baseline-evaluation-three-tiers" id="toc-baseline-evaluation-three-tiers" class="nav-link" data-scroll-target="#baseline-evaluation-three-tiers">Baseline evaluation — three tiers</a></li>
  <li><a href="#hyperparameter-tuning-and-champion-selection" id="toc-hyperparameter-tuning-and-champion-selection" class="nav-link" data-scroll-target="#hyperparameter-tuning-and-champion-selection">Hyperparameter tuning and champion selection</a></li>
  <li><a href="#clinical-impact-metrics" id="toc-clinical-impact-metrics" class="nav-link" data-scroll-target="#clinical-impact-metrics">Clinical-impact metrics</a></li>
  <li><a href="#calibration-and-explainability" id="toc-calibration-and-explainability" class="nav-link" data-scroll-target="#calibration-and-explainability">Calibration and explainability</a></li>
  <li><a href="#software-and-reproducibility" id="toc-software-and-reproducibility" class="nav-link" data-scroll-target="#software-and-reproducibility">Software and reproducibility</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#class-weighting-is-the-load-bearing-intervention" id="toc-class-weighting-is-the-load-bearing-intervention" class="nav-link" data-scroll-target="#class-weighting-is-the-load-bearing-intervention">Class weighting is the load-bearing intervention</a></li>
  <li><a href="#the-tuned-champion-glmnet-on-ranking" id="toc-the-tuned-champion-glmnet-on-ranking" class="nav-link" data-scroll-target="#the-tuned-champion-glmnet-on-ranking">The tuned champion: GLMNET on ranking</a></li>
  <li><a href="#clinical-operating-profile" id="toc-clinical-operating-profile" class="nav-link" data-scroll-target="#clinical-operating-profile">Clinical operating profile</a></li>
  <li><a href="#the-calibration-trade-off-named" id="toc-the-calibration-trade-off-named" class="nav-link" data-scroll-target="#the-calibration-trade-off-named">The calibration trade-off, named</a></li>
  <li><a href="#feature-attributions-diverge-by-architecture" id="toc-feature-attributions-diverge-by-architecture" class="nav-link" data-scroll-target="#feature-attributions-diverge-by-architecture">Feature attributions diverge by architecture</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a>
  <ul class="collapse">
  <li><a href="#why-the-simplest-model-won" id="toc-why-the-simplest-model-won" class="nav-link" data-scroll-target="#why-the-simplest-model-won">Why the simplest model won</a></li>
  <li><a href="#the-trade-off-is-a-deployment-decision-not-a-defect" id="toc-the-trade-off-is-a-deployment-decision-not-a-defect" class="nav-link" data-scroll-target="#the-trade-off-is-a-deployment-decision-not-a-defect">The trade-off is a deployment decision, not a defect</a></li>
  <li><a href="#screening-implications" id="toc-screening-implications" class="nav-link" data-scroll-target="#screening-implications">Screening implications</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations">Limitations</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Clinical Stroke-Screening Model Benchmarking: Champion Selection, Threshold Profiling, and a Calibration Trade-off</h1>
<p class="subtitle lead">Five architectures, three imbalance-correction tiers, a tuned three-model finalist round, and an evidence-based-medicine read on how the champion would behave as a screening tool — on 5,110 patients at 4.9% stroke prevalence.</p>
  <div class="quarto-categories">
    <div class="quarto-category">Machine Learning</div>
    <div class="quarto-category">Classification</div>
    <div class="quarto-category">Imbalanced Classification</div>
    <div class="quarto-category">Model Evaluation</div>
    <div class="quarto-category">Model Calibration</div>
    <div class="quarto-category">Model Explainability</div>
    <div class="quarto-category">Hyperparameter Tuning</div>
    <div class="quarto-category">Gradient Boosting</div>
    <div class="quarto-category">Clinical Research</div>
    <div class="quarto-category">Healthcare Analytics</div>
    <div class="quarto-category">Python</div>
  </div>
  </div>

<div>
  <div class="description">
    <p>A binary stroke-screening pipeline benchmarked end to end. <strong>Champion:</strong> a regularised linear model (GLMNET / Elastic Net) wins on ranking — test ROC-AUC 0.841 vs.&nbsp;XGBoost 0.821 and LightGBM 0.808 — despite being the simplest architecture. <strong>Class weighting is the load-bearing fix:</strong> recall jumps from ~0.04 to ~0.80 from tier 1 to tier 2; SMOTE adds only an increment. <strong>Named trade-off:</strong> GLMNET ranks best but calibrates worst (Brier 0.178 vs.&nbsp;~0.043) — acceptable for a binary flag, not for risk communication. <strong>Widest operating range:</strong> GLMNET holds recall to a 0.6 threshold; the tree models collapse by 0.3.</p>
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Muhammad Khan Muneer </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 2026</p>
    </div>
  </div>
  
    
  </div>
  

<div>
  <div class="keywords">
    <div class="block-title">Keywords</div>
    <p>stroke screening, binary classification, class imbalance, SMOTE, class weighting, hyperparameter tuning, ROC-AUC, precision-recall, Youden’s J, clinical impact analysis, number needed to screen, calibration, Brier score, SHAP, elastic net, XGBoost, LightGBM, Python, scikit-learn</p>
  </div>
</div>

</header>


<section id="abstract" class="level2">
<h2 class="anchored" data-anchor-id="abstract">Abstract</h2>
<p>This study benchmarks a binary stroke-screening pipeline from a 21-predictor feature matrix through champion selection and a clinical-workflow assessment, on a held-out test set of 1,022 patients (50 stroke-positive; 4.9% prevalence, a 19.5:1 imbalance). Five architectures — logistic regression, Elastic Net (GLMNET), random forest, XGBoost, LightGBM — were evaluated across three imbalance-correction tiers: unweighted, cost-sensitive class weighting, and class weighting with in-fold SMOTE. Three finalists (GLMNET, XGBoost, LightGBM) then underwent a 5-fold, 50-iteration randomised hyperparameter search inside a SMOTE pipeline, scored on ROC-AUC. <strong>GLMNET emerged as the champion</strong> with a test ROC-AUC of 0.841, ahead of XGBoost (0.821) and LightGBM (0.808) — the simplest architecture winning on ranking quality, consistent with an additive, age-driven risk structure that a regularised linear boundary captures without overfitting the majority-class manifold. Class weighting is the load-bearing intervention: recall rose from roughly 0.04 (unweighted) to roughly 0.80 (weighted); SMOTE added only an increment. A nine-threshold clinical-impact sweep showed GLMNET holding useful sensitivity across a 0.10–0.70 threshold span while the tree models compress into a narrow low-probability band. A calibration analysis names an explicit trade-off: GLMNET ranks patients best but calibrates worst (Brier 0.178 vs.&nbsp;~0.043 for the tree models) — acceptable for a binary flag, not for absolute risk communication. SHAP attributions reveal divergent importance hierarchies — <code>age_squared</code> dominates GLMNET, <code>age_bmi</code> dominates both tree models — with cross-architecture agreement only at the low-signal tail.</p>
<p><em>Keywords:</em> stroke screening, class imbalance, SMOTE, hyperparameter tuning, clinical impact analysis, calibration, SHAP</p>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Notebook four of a six-part stroke-risk series turns the preceding analyses into a working classifier. The exploratory and inferential stages established that stroke risk in this cohort is overwhelmingly age-driven and largely additive; this study tests whether that structure is better captured by a regularised linear model or by tree ensembles, and profiles the winner as a screening tool.</p>
<p>Three questions organise the work. <strong>Which imbalance correction matters?</strong> — evaluated across three tiers so the marginal value of each intervention is visible. <strong>Which architecture ranks patients best?</strong> — a tuned finalist round scored on ROC-AUC, the metric that stays interpretable under a 19.5:1 imbalance. <strong>How would the champion behave in a clinic?</strong> — a threshold sweep in evidence-based-medicine terms (sensitivity, specificity, likelihood ratios, number needed to evaluate), plus a calibration check, because a model that ranks well can still produce probabilities that do not correspond to observed event rates.</p>
</section>
<section id="method" class="level2">
<h2 class="anchored" data-anchor-id="method">Method</h2>
<section id="data-and-feature-set" class="level3">
<h3 class="anchored" data-anchor-id="data-and-feature-set">Data and feature set</h3>
<p>The input is the project’s Gold analytical table (5,110 patients, 4.9% stroke prevalence), produced by an upstream medallion ETL pipeline with zero missingness. Feature engineering expanded the base columns to <strong>21 predictors</strong> across four families (Table 1): base demographics and clinical indicators, age transformations (<code>age_squared</code>, a four-level <code>age_bucket</code>), metabolic and lifestyle flags (log-glucose, a &gt; 140 mg/dL flag, obesity and underweight flags, a combined-smoker flag), and four interaction terms (<code>age_glucose</code>, <code>age_bmi</code>, <code>hypertension × high-glucose</code>, <code>smoker × obese</code>). The identifier and a redundant composite column were dropped.</p>
<p><strong>Table 1</strong></p>
<p><em>The 21-Predictor Modelling Matrix</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Family</th>
<th style="text-align: left;">Features</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Base demographics &amp; clinical</td>
<td style="text-align: left;">gender, age, hypertension, heart disease, ever married, work type, residence type, average glucose, BMI, smoking status</td>
</tr>
<tr class="even">
<td style="text-align: left;">Age transformations</td>
<td style="text-align: left;">age², age band (young / mid / mature / senior)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Metabolic &amp; lifestyle flags</td>
<td style="text-align: left;">log-glucose, high glucose (&gt; 140 mg/dL), obese (BMI ≥ 30), underweight (BMI &lt; 18.5), current-or-former smoker</td>
</tr>
<tr class="even">
<td style="text-align: left;">Interaction terms</td>
<td style="text-align: left;">age × log-glucose, age × BMI, hypertension × high-glucose, smoker × obese</td>
</tr>
</tbody>
</table>
<p><em>Note.</em> Eight low-cardinality categoricals were ordinal-encoded (unknown → −1); no high-cardinality categoricals remained after identifier removal, so target encoding was not exercised.</p>
</section>
<section id="preprocessing-and-split" class="level3">
<h3 class="anchored" data-anchor-id="preprocessing-and-split">Preprocessing and split</h3>
<p>A stratified 80/20 split allocated 4,088 patients to training and <strong>1,022 to a held-out test set</strong> (50 stroke-positive), preserving the population positive rate in both partitions — non-negotiable at 4.9% prevalence, where a random split risks an unrepresentative test set. All 21 predictors passed through as a fully numeric, zero-missing matrix.</p>
</section>
<section id="baseline-evaluation-three-tiers" class="level3">
<h3 class="anchored" data-anchor-id="baseline-evaluation-three-tiers">Baseline evaluation — three tiers</h3>
<p>Five architectures were trained under three successive imbalance corrections: (1) <strong>unweighted</strong> — raw class distribution, the performance floor; (2) <strong>class-weighted</strong> — <code>class_weight="balanced"</code> for the models that support it, <code>scale_pos_weight ≈ 19.5</code> for XGBoost, with each model’s decision threshold moved to its Youden’s <em>J</em> optimum (the ROC point maximising sensitivity + specificity − 1); (3) <strong>class-weighted + SMOTE</strong> — synthetic minority oversampling applied <em>inside</em> each cross-validation fold via an imbalanced-learn pipeline, so synthetic samples never leak into validation or test data.</p>
</section>
<section id="hyperparameter-tuning-and-champion-selection" class="level3">
<h3 class="anchored" data-anchor-id="hyperparameter-tuning-and-champion-selection">Hyperparameter tuning and champion selection</h3>
<p>The three finalists — GLMNET, XGBoost, LightGBM — each ran <code>RandomizedSearchCV</code> with <strong>5-fold stratified cross-validation and 50 iterations</strong> inside a SMOTE pipeline (750 fits total), scored on ROC-AUC. GLMNET’s pipeline included a <code>StandardScaler</code> so the elastic-net penalty operates evenly across feature scales. Each tuned model was then evaluated on the test set at its Youden threshold. Random forest was excluded after consistent bottom-tier baseline performance; unregularised logistic regression was excluded as a special case of GLMNET with no tuning surface.</p>
</section>
<section id="clinical-impact-metrics" class="level3">
<h3 class="anchored" data-anchor-id="clinical-impact-metrics">Clinical-impact metrics</h3>
<p>Each tuned model was swept across nine decision thresholds (0.10–0.90), reporting sensitivity, specificity, positive and negative predictive value, positive and negative likelihood ratios (LR+, LR−), miss rate, and the <strong>number needed to evaluate</strong> (NNE — high-risk patients a clinician must investigate to find one true stroke).</p>
</section>
<section id="calibration-and-explainability" class="level3">
<h3 class="anchored" data-anchor-id="calibration-and-explainability">Calibration and explainability</h3>
<p>Calibration was assessed with decile-binned reliability curves and the <strong>Brier score</strong> (mean squared error between predicted probability and outcome; lower is better). SHAP values were computed with a <code>LinearExplainer</code> for GLMNET and <code>TreeExplainer</code> for the tree models, and summarised as per-patient attributions and mean absolute importance.</p>
</section>
<section id="software-and-reproducibility" class="level3">
<h3 class="anchored" data-anchor-id="software-and-reproducibility">Software and reproducibility</h3>
<p>Python with <code>scikit-learn</code> 1.2.2, <code>imbalanced-learn</code> 0.10.1, <code>xgboost</code> 1.7.6, <code>lightgbm</code> 4.3.0, <code>shap</code> 0.44.1. The tuned pipelines, the exact held-out test set, and the clinical-impact and calibration tables are persisted as artefacts; every figure and table in this article was recomputed from those artefacts, and all recomputed values matched the original run. The end-to-end pipeline is shown in Figure 8.</p>
<p><strong>Figure 8</strong></p>
<p><em>The Benchmarking Pipeline, End to End</em></p>
<p><img src="assets/fig8_pipeline_diagram.png" class="img-fluid" alt="Five boxes left to right: Gold features (5,110 x 24), Preprocess (21 predictors, ordinal encode, stratified 80/20 split), 3-tier baseline (unweighted to weighted to weighted + SMOTE), Tune (5x50 CV, three models, SMOTE in-fold), Champion + export (GLMNET, SHAP, calibration, clinical impact, manifest)."></p>
<p><em>Note.</em> Shown after the Method sections it summarises; the three-tier baseline and the tuning round are described above.</p>
</section>
</section>
<section id="results" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<section id="class-weighting-is-the-load-bearing-intervention" class="level3">
<h3 class="anchored" data-anchor-id="class-weighting-is-the-load-bearing-intervention">Class weighting is the load-bearing intervention</h3>
<p>The three-tier baseline (Figure 1, Table 2) makes the intervention hierarchy unambiguous. <strong>Unweighted</strong>, three of five models — GLMNET, random forest, XGBoost — detected <em>zero</em> stroke cases in the test set, scoring ~95% accuracy by predicting the majority class for every patient; logistic regression and LightGBM each detected 2 of 50 (recall 0.04). <strong>Class-weighted</strong>, every model jumped to recall 0.70–0.80 — from 2 detections to 35–40 — at the cost of accuracy falling to 72–84% as false positives surged (logistic regression: 155 false positives against 39 true positives, precision 0.20). ROC-AUC converged into a narrow 0.800–0.837 band, confirming the discriminative signal is accessible to every architecture once the imbalance is corrected. <strong>Adding SMOTE</strong> produced only an increment: GLMNET’s ROC-AUC rose to 0.839 (the best baseline value), XGBoost to 0.820, while recall stayed in the 0.70–0.78 range.</p>
<p><strong>Table 2</strong></p>
<p><em>Three-Tier Baseline Results (Held-Out Test Set, 50 Stroke-Positive of 1,022)</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: center;">Unweighted recall / ROC-AUC</th>
<th style="text-align: center;">Class-weighted recall / ROC-AUC</th>
<th style="text-align: center;">+ SMOTE recall / ROC-AUC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Logistic regression</td>
<td style="text-align: center;">0.04 / 0.833</td>
<td style="text-align: center;">0.78 / 0.837</td>
<td style="text-align: center;">0.70 / 0.819</td>
</tr>
<tr class="even">
<td style="text-align: left;">GLMNET (Elastic Net)</td>
<td style="text-align: center;">0.00 / 0.635</td>
<td style="text-align: center;">0.80 / 0.837</td>
<td style="text-align: center;">0.78 / <strong>0.839</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Random forest</td>
<td style="text-align: center;">0.00 / —</td>
<td style="text-align: center;">0.70 / 0.812</td>
<td style="text-align: center;">0.74 / 0.795</td>
</tr>
<tr class="even">
<td style="text-align: left;">XGBoost</td>
<td style="text-align: center;">0.00 / 0.813</td>
<td style="text-align: center;">0.80 / 0.803</td>
<td style="text-align: center;">0.78 / 0.820</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LightGBM</td>
<td style="text-align: center;">0.04 / 0.805</td>
<td style="text-align: center;">0.76 / 0.800</td>
<td style="text-align: center;">0.78 / —</td>
</tr>
</tbody>
</table>
<p><em>Note.</em> Class-weighted and SMOTE tiers evaluate at each model’s Youden’s <em>J</em> threshold. Unweighted GLMNET’s ROC-AUC of 0.635 reflects near-degenerate predictions from an unscaled elastic net under the imbalance. Random forest and logistic regression were not advanced to tuning.</p>
<p><strong>Figure 1</strong></p>
<p><em>Baseline Progression Across the Three Imbalance-Correction Tiers</em></p>
<p><img src="assets/fig1_baseline_progression.png" class="img-fluid" alt="Two line charts. Left: test-set recall for five models rises sharply from near zero (unweighted) to about 0.7–0.8 (class-weighted), then holds roughly flat with SMOTE. Right: ROC-AUC converges into a narrow 0.80–0.84 band once class weighting is applied; unweighted GLMNET starts far below at 0.635."></p>
<p><em>Note.</em> The step from tier 1 to tier 2 is transformative; the step from tier 2 to tier 3 is marginal. Class weighting, not SMOTE, is the intervention that makes these models clinically usable.</p>
</section>
<section id="the-tuned-champion-glmnet-on-ranking" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="the-tuned-champion-glmnet-on-ranking">The tuned champion: GLMNET on ranking</h3>
<p>The randomised search (Table 3) produced three tuned models whose test-set behaviour separates cleanly (Table 4, Figures 2 and 3). <strong>GLMNET is the champion on ranking</strong>: test ROC-AUC <strong>0.841</strong> vs.&nbsp;XGBoost 0.821 vs.&nbsp;LightGBM 0.808, and the best F1 (0.337). It reached this with heavy regularisation (<code>C = 0.001</code>, near-Lasso <code>l1_ratio = 0.9</code>) — the elastic net, with scaled features, performing genuine feature selection rather than overfitting minority-class noise. XGBoost leads on precision–recall (PR-AUC 0.288 vs.&nbsp;GLMNET’s 0.246) and, with LightGBM, on raw recall — both detect 41 of 50 cases at their aggressive Youden thresholds (~0.04–0.09) versus GLMNET’s 35 of 50 at a 0.61 threshold — but at markedly lower precision (0.12–0.14 vs.&nbsp;0.22). The ROC curves (Figure 3) show GLMNET’s curve lying above the tree models at nearly every false-positive rate: the linear model spreads its discrimination across a wider probability range.</p>
<p><strong>Table 3</strong></p>
<p><em>Hyperparameter Search: Best Configuration per Finalist (5-Fold CV, 50 Iterations, SMOTE Pipeline)</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 28%">
<col style="width: 28%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: center;">Best CV ROC-AUC</th>
<th style="text-align: center;">Tuning time</th>
<th style="text-align: left;">Key hyperparameters</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">GLMNET (Elastic Net)</td>
<td style="text-align: center;">0.838</td>
<td style="text-align: center;">0.6 min</td>
<td style="text-align: left;"><code>C = 0.001</code>, <code>l1_ratio = 0.9</code> (+ StandardScaler)</td>
</tr>
<tr class="even">
<td style="text-align: left;">XGBoost</td>
<td style="text-align: center;">0.825</td>
<td style="text-align: center;">2.7 min</td>
<td style="text-align: left;">300 trees, lr 0.03, depth 4, subsample 0.9, colsample 0.8, γ 0.1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LightGBM</td>
<td style="text-align: center;">0.821</td>
<td style="text-align: center;">2.0 min</td>
<td style="text-align: left;">500 trees, lr 0.03, depth 6, 15 leaves, subsample 0.7, colsample 0.9</td>
</tr>
</tbody>
</table>
<p><em>Note.</em> Micro-timing beforehand projected the full 750-fit suite at ~15 min; memory was flat at ~621 MB. Shallow tree depths (4, 6) confirm the ensembles also need regularisation to avoid the majority-class manifold.</p>
<div class="column-page-inset">
<p><strong>Table 4</strong></p>
<p><em>Tuned Model Performance on the Held-Out Test Set (at Youden Threshold)</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;">ROC-AUC</th>
<th style="text-align: right;">PR-AUC</th>
<th style="text-align: right;">Youden threshold</th>
<th style="text-align: right;">Sensitivity</th>
<th style="text-align: right;">Precision</th>
<th style="text-align: right;">F1</th>
<th style="text-align: center;">TP / FP / FN</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>GLMNET (Elastic Net)</strong> — champion</td>
<td style="text-align: right;"><strong>0.841</strong></td>
<td style="text-align: right;">0.246</td>
<td style="text-align: right;">0.615</td>
<td style="text-align: right;">0.70</td>
<td style="text-align: right;">0.222</td>
<td style="text-align: right;"><strong>0.337</strong></td>
<td style="text-align: center;">35 / 123 / 15</td>
</tr>
<tr class="even">
<td style="text-align: left;">XGBoost</td>
<td style="text-align: right;">0.821</td>
<td style="text-align: right;"><strong>0.288</strong></td>
<td style="text-align: right;">0.094</td>
<td style="text-align: right;">0.82</td>
<td style="text-align: right;">0.141</td>
<td style="text-align: right;">0.240</td>
<td style="text-align: center;">41 / 250 / 9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LightGBM</td>
<td style="text-align: right;">0.808</td>
<td style="text-align: right;">0.250</td>
<td style="text-align: right;">0.036</td>
<td style="text-align: right;">0.82</td>
<td style="text-align: right;">0.119</td>
<td style="text-align: right;">0.208</td>
<td style="text-align: center;">41 / 303 / 9</td>
</tr>
</tbody>
</table>
<p><em>Note.</em> TP/FP/FN counted at each model’s Youden threshold on the 1,022-patient test set (50 positives). The tree models’ recall edge (41 vs.&nbsp;35 detections) costs roughly twice the false positives.</p>
</div>
<p><strong>Figure 2</strong></p>
<p><em>Tuned Model Comparison Across Four Test-Set Metrics</em></p>
<p><img src="assets/fig2_tuned_comparison.png" class="img-fluid" alt="Grouped bar chart. GLMNET (blue) is highest on ROC-AUC (0.841) and F1 (0.337). XGBoost (red) is highest on PR-AUC (0.288) and ties LightGBM on recall (0.82) versus GLMNET's 0.70."></p>
<p><em>Note.</em> GLMNET wins ranking (ROC-AUC) and balance (F1); the tree models win raw recall and precision–recall area.</p>
<p><strong>Figure 3</strong></p>
<p><em>ROC and Precision–Recall Curves for the Three Tuned Models</em></p>
<p><img src="assets/fig3_roc_pr_curves.png" class="img-fluid" alt="Left: ROC curves; the GLMNET curve (bold blue) sits above XGBoost and LightGBM across most of the false-positive range. Right: precision–recall curves, all three well above the 0.049 prevalence line, XGBoost highest in the mid-recall region."></p>
<p><em>Note.</em> GLMNET (bold) dominates the ROC space; XGBoost holds a slight precision–recall edge at moderate recall.</p>
</section>
<section id="clinical-operating-profile" class="level3">
<h3 class="anchored" data-anchor-id="clinical-operating-profile">Clinical operating profile</h3>
<p>The nine-threshold sweep (Figure 4, Table 5, Figure 5) is where the champion choice is decided. <strong>GLMNET keeps a usable profile across a wide threshold span.</strong> At 0.10 it reaches sensitivity 1.00 (every case caught) at zero specificity and NNE 20.4; at 0.50, sensitivity 0.82 / specificity 0.74 / LR+ 3.15 / NNE 7.2; at 0.60 — near its Youden optimum — sensitivity 0.70 / specificity 0.86 / LR+ <strong>4.93</strong> / NNE <strong>4.9</strong>. An LR+ near 5 raises post-test probability by a clinically useful margin. The <strong>tree models compress</strong>: LightGBM manages only sensitivity 0.64 at threshold 0.10 and detects 3 of 50 cases by 0.50; XGBoost falls to sensitivity 0.40 by threshold 0.30 and to a mathematically-precise-but-useless sensitivity 0.04 (LR+ ∞, 2 cases) at 0.60. The mechanism is probability spread: GLMNET’s outputs occupy the full [0, 1] interval, so moving the threshold trades sensitivity for specificity smoothly; the tree models concentrate their positive mass below 0.10, leaving no useful operating range above it (Figure 5).</p>
<p><strong>Table 5</strong></p>
<p><em>Clinical-Impact Metrics at Representative Thresholds</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Model @ threshold</th>
<th style="text-align: right;">Sensitivity</th>
<th style="text-align: right;">Specificity</th>
<th style="text-align: right;">PPV</th>
<th style="text-align: right;">LR+</th>
<th style="text-align: right;">NNE</th>
<th style="text-align: right;">Cases detected (of 50)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">GLMNET @ 0.10</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.049</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">20.4</td>
<td style="text-align: right;">50</td>
</tr>
<tr class="even">
<td style="text-align: left;">GLMNET @ 0.50</td>
<td style="text-align: right;">0.82</td>
<td style="text-align: right;">0.74</td>
<td style="text-align: right;">0.139</td>
<td style="text-align: right;">3.15</td>
<td style="text-align: right;">7.2</td>
<td style="text-align: right;">41</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GLMNET @ 0.60</td>
<td style="text-align: right;">0.70</td>
<td style="text-align: right;">0.86</td>
<td style="text-align: right;">0.202</td>
<td style="text-align: right;">4.93</td>
<td style="text-align: right;">4.9</td>
<td style="text-align: right;">35</td>
</tr>
<tr class="even">
<td style="text-align: left;">XGBoost @ 0.10</td>
<td style="text-align: right;">0.80</td>
<td style="text-align: right;">0.75</td>
<td style="text-align: right;">0.142</td>
<td style="text-align: right;">3.21</td>
<td style="text-align: right;">7.1</td>
<td style="text-align: right;">40</td>
</tr>
<tr class="odd">
<td style="text-align: left;">XGBoost @ 0.30</td>
<td style="text-align: right;">0.40</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">20</td>
</tr>
<tr class="even">
<td style="text-align: left;">LightGBM @ 0.10</td>
<td style="text-align: right;">0.64</td>
<td style="text-align: right;">0.84</td>
<td style="text-align: right;">0.168</td>
<td style="text-align: right;">3.91</td>
<td style="text-align: right;">6.0</td>
<td style="text-align: right;">32</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LightGBM @ 0.50</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">3</td>
</tr>
</tbody>
</table>
<p><em>Note.</em> NNE = number needed to evaluate to find one true stroke. GLMNET is the only model with a non-trivial profile above threshold 0.10.</p>
<p><strong>Figure 4</strong></p>
<p><em>GLMNET Champion — Clinical Operating Profile Across the Threshold Sweep</em></p>
<p><img src="assets/fig4_glmnet_threshold_sweep.png" class="img-fluid" alt="Line chart for GLMNET. Sensitivity falls smoothly from 1.0 to about 0.35 as the threshold rises from 0.1 to 0.7; specificity and PPV rise; NNE (right axis, dashed) falls from ~20 toward ~4. A shaded band marks the 0.5–0.6 operating region."></p>
<p><em>Note.</em> Left axis: sensitivity, specificity, PPV. Right axis: NNE. Shaded band = the 0.5–0.6 region around the Youden optimum, where LR+ ≈ 3–5 and NNE ≈ 5–7.</p>
<p><strong>Figure 5</strong></p>
<p><em>Useful Operating Range: Sensitivity vs.&nbsp;Threshold for All Three Tuned Models</em></p>
<p><img src="assets/fig5_operating_range.png" class="img-fluid" alt="Three sensitivity-versus-threshold curves. GLMNET stays above 0.7 sensitivity until threshold 0.6; XGBoost and LightGBM drop below 0.4 by threshold 0.3 and to near zero by 0.5."></p>
<p><em>Note.</em> The width of a model’s usable band, not its peak recall, is what makes it deployable as an adjustable screening tool.</p>
</section>
<section id="the-calibration-trade-off-named" class="level3">
<h3 class="anchored" data-anchor-id="the-calibration-trade-off-named">The calibration trade-off, named</h3>
<p>Ranking quality and calibration are separate properties, and the tuned models split on the second one sharply (Figure 6, Table 6). <strong>LightGBM (Brier 0.043) and XGBoost (0.044) are well calibrated</strong> — their reliability curves track the diagonal. <strong>GLMNET (Brier 0.178) is not</strong> — it overestimates risk across the mid-probability range, a direct consequence of spreading probability mass to widen the operating range. The trade-off is explicit: GLMNET is the better <em>screener</em> (best ranking, widest usable range, interpretable relative to its threshold); the tree models are the better <em>probability estimators</em> (their predicted probabilities correspond to observed event rates). For a binary high-risk flag — this pipeline’s deployment target — GLMNET’s calibration gap is acceptable. For risk communication or shared decision-making, the tree models would be the stronger choice.</p>
<p><strong>Table 6</strong></p>
<p><em>Calibration: Brier Scores (Lower Is Better)</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;">Brier score</th>
<th style="text-align: left;">Reading</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">LightGBM</td>
<td style="text-align: right;">0.043</td>
<td style="text-align: left;">well calibrated — tracks the diagonal</td>
</tr>
<tr class="even">
<td style="text-align: left;">XGBoost</td>
<td style="text-align: right;">0.044</td>
<td style="text-align: left;">well calibrated</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GLMNET (Elastic Net)</td>
<td style="text-align: right;">0.178</td>
<td style="text-align: left;">mis-calibrated — overestimates mid-range risk</td>
</tr>
</tbody>
</table>
<p><em>Note.</em> GLMNET’s high Brier score coexists with its best ROC-AUC — ranking and calibration are independent, and this pipeline optimised for ranking.</p>
<p><strong>Figure 6</strong></p>
<p><em>Reliability Curves and Brier Scores for the Three Tuned Models</em></p>
<p><img src="assets/fig6_calibration.png" class="img-fluid" alt="Calibration plot. XGBoost and LightGBM curves hug the perfect-calibration diagonal. The GLMNET curve sits well below it — predicted probabilities far exceed observed stroke rates until the very top bin."></p>
<p><em>Note.</em> Decile-binned. The dashed diagonal is perfect calibration.</p>
</section>
<section id="feature-attributions-diverge-by-architecture" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="feature-attributions-diverge-by-architecture">Feature attributions diverge by architecture</h3>
<p>SHAP summaries (Figure 7, Table 7) show the linear champion and the tree models learned <em>different</em> representations of the same signal. <strong>GLMNET is dominated by <code>age_squared</code></strong> — its SHAP spread is an order of magnitude wider than any other feature — followed by <code>age_glucose</code> and raw <code>age</code>; <code>age_bmi</code> was effectively zeroed out by the near-Lasso penalty. <strong>Both tree models are dominated by <code>age_bmi</code></strong>, with <code>age_glucose</code> and the discretised <code>age_bucket</code> next for XGBoost, while LightGBM elevates <code>residence_type</code> and <code>work_type</code> (socioeconomic proxies) — a divergence between the two ensembles that marks that signal as real but fragile. All three models agree that <code>smoker_obese</code>, <code>hyper_glucose</code>, <code>bmi_obese</code>, and <code>glucose_high</code> carry little independent signal — agreement at the tail, across different inductive biases, is the strongest evidence those interaction/threshold features are genuinely weak.</p>
<div class="column-page-inset">
<p><strong>Table 7</strong></p>
<p><em>Top SHAP Features per Tuned Model (by Mean Absolute Attribution)</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Rank</th>
<th style="text-align: left;">GLMNET (linear)</th>
<th style="text-align: left;">XGBoost</th>
<th style="text-align: left;">LightGBM</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: left;">age²</td>
<td style="text-align: left;">age × BMI</td>
<td style="text-align: left;">age × BMI</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: left;">age × log-glucose</td>
<td style="text-align: left;">age × log-glucose</td>
<td style="text-align: left;">residence type</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: left;">age</td>
<td style="text-align: left;">age band</td>
<td style="text-align: left;">work type</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: left;">smoking status</td>
<td style="text-align: left;">smoking status</td>
<td style="text-align: left;">age band</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Shared tail (all weak)</td>
<td style="text-align: left;">smoker × obese, hypertension × high-glucose, obese flag, high-glucose flag</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
<p><em>Note.</em> GLMNET routes the age signal through <code>age²</code>; the tree models route it through <code>age × BMI</code>. Both are valid encodings of the same underlying age-driven risk.</p>
</div>
<p><strong>Figure 7</strong></p>
<p><em>SHAP Attributions: GLMNET Champion Summary and Cross-Model Importance</em></p>
<p><img src="assets/fig7_shap.png" class="img-fluid" alt="Left: SHAP beeswarm for GLMNET; age-squared has a vastly wider spread than any other feature. Right: normalised mean-absolute-SHAP bars for the three models side by side, showing age-squared leading GLMNET while age-by-BMI leads both tree models."></p>
<p><em>Note.</em> Left — per-patient SHAP values for GLMNET (colour = feature value). Right — mean |SHAP| per feature, normalised within each model for a shared scale.</p>
</section>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<section id="why-the-simplest-model-won" class="level3">
<h3 class="anchored" data-anchor-id="why-the-simplest-model-won">Why the simplest model won</h3>
<p>GLMNET’s win on ranking is not an accident of tuning — it follows from the risk structure the earlier notebooks established. Stroke risk in this cohort is dominated by age and is close to additive; feature engineering handed the linear model direct terms for the non-linear (<code>age_squared</code>) and interaction (<code>age_glucose</code>) components of that relationship. Under heavy regularisation on scaled features, the elastic net selected those terms and discarded the rest. The tree ensembles spent their splitting budget rediscovering the same age structure and, lacking the linear model’s smooth extrapolation, spread their predictions less evenly — which is exactly why their operating range collapsed. This is a case where matching model complexity to signal complexity beats raw capacity.</p>
</section>
<section id="the-trade-off-is-a-deployment-decision-not-a-defect" class="level3">
<h3 class="anchored" data-anchor-id="the-trade-off-is-a-deployment-decision-not-a-defect">The trade-off is a deployment decision, not a defect</h3>
<p>GLMNET ranks best and calibrates worst; the tree models do the reverse. Neither is globally superior — the right choice depends on what the output feeds. A screening pipeline that flags patients for follow-up needs good <em>ordering</em> and a usable threshold, which GLMNET provides. A tool that shows a patient “your stroke risk is 12%” needs <em>calibrated probabilities</em>, which the tree models provide. Naming this explicitly, rather than reporting a single leaderboard number, is what lets a downstream team pick correctly.</p>
</section>
<section id="screening-implications" class="level3">
<h3 class="anchored" data-anchor-id="screening-implications">Screening implications</h3>
<p>At its 0.60 operating point, the champion catches 70% of stroke cases with an NNE near 5 and an LR+ near 5 — an efficient profile for a high-volume primary-care screen. Pushed to threshold 0.10 it catches everything at the cost of flagging every patient; the adjustable range between those points is the practical value of the model. The tree models offer no such dial.</p>
</section>
<section id="limitations" class="level3">
<h3 class="anchored" data-anchor-id="limitations">Limitations</h3>
<p>The test set holds only 50 stroke-positive patients, so all minority-class metrics carry wide sampling uncertainty (a single misclassification moves recall by 0.02). Evaluation is single-split, not repeated cross-validation, and on one cohort — external validation is required before any clinical use. The Youden threshold optimises a statistical criterion, not a cost-weighted clinical objective; a real deployment would set the threshold from the local cost of a missed stroke versus an unnecessary follow-up. SHAP importance is model-internal and does not establish causal effect. GLMNET’s calibration gap means its raw probabilities must not be reported as risk percentages without recalibration (e.g.&nbsp;Platt scaling or isotonic regression on a held-out set).</p>
</section>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion">Conclusion</h3>
<p>A regularised linear model is the champion stroke screener for this cohort — best ranking (ROC-AUC 0.841), widest usable operating range, and interpretable — while the gradient-boosted ensembles are the better-calibrated probability estimators. Class weighting, not synthetic oversampling, is the intervention that converts any of these architectures from a 95%-accurate-and-useless classifier into a working screening tool. The tuned pipelines, preprocessing infrastructure, SHAP values, and clinical-impact tables are persisted for the downstream fairness audit and deployment.</p>
</section>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<p>Caruana, R., &amp; Niculescu-Mizil, A. (2006). An empirical comparison of supervised learning algorithms. <em>Proceedings of the 23rd International Conference on Machine Learning</em>, 161–168. https://doi.org/10.1145/1143844.1143865</p>
<p>Chawla, N. V., Bowyer, K. W., Hall, L. O., &amp; Kegelmeyer, W. P. (2002). SMOTE: Synthetic minority over-sampling technique. <em>Journal of Artificial Intelligence Research, 16</em>, 321–357. https://doi.org/10.1613/jair.953</p>
<p>Chen, T., &amp; Guestrin, C. (2016). XGBoost: A scalable tree boosting system. <em>Proceedings of the 22nd ACM SIGKDD International Conference on Knowledge Discovery and Data Mining</em>, 785–794. https://doi.org/10.1145/2939672.2939785</p>
<p>Ke, G., Meng, Q., Finley, T., Wang, T., Chen, W., Ma, W., Ye, Q., &amp; Liu, T.-Y. (2017). LightGBM: A highly efficient gradient boosting decision tree. <em>Advances in Neural Information Processing Systems, 30</em>, 3146–3154.</p>
<p>Lemaître, G., Nogueira, F., &amp; Aridas, C. K. (2017). Imbalanced-learn: A Python toolbox to tackle the curse of imbalanced datasets in machine learning. <em>Journal of Machine Learning Research, 18</em>(17), 1–5.</p>
<p>Lundberg, S. M., &amp; Lee, S.-I. (2017). A unified approach to interpreting model predictions. <em>Advances in Neural Information Processing Systems, 30</em>, 4765–4774.</p>
<p>Pedregosa, F., Varoquaux, G., Gramfort, A., Michel, V., Thirion, B., Grisel, O., Blondel, M., Prettenhofer, P., Weiss, R., Dubourg, V., Vanderplas, J., Passos, A., Cournapeau, D., Brucher, M., Perrot, M., &amp; Duchesnay, É. (2011). Scikit-learn: Machine learning in Python. <em>Journal of Machine Learning Research, 12</em>, 2825–2830.</p>
<p>Youden, W. J. (1950). Index for rating diagnostic tests. <em>Cancer, 3</em>(1), 32–35. https://doi.org/10.1002/1097-0142(1950)3:1&lt;32::AID-CNCR2820030106&gt;3.0.CO;2-3</p>
<p>Zou, H., &amp; Hastie, T. (2005). Regularization and variable selection via the elastic net. <em>Journal of the Royal Statistical Society: Series B, 67</em>(2), 301–320. https://doi.org/10.1111/j.1467-9868.2005.00503.x</p>
<p>fedesoriano. (2021). <em>Stroke prediction dataset</em> [Data set]. Kaggle. https://www.kaggle.com/datasets/fedesoriano/stroke-prediction-dataset</p>
<hr>
<p><em>Model pipeline and figures by the author. All test-set metrics are single-split and single-cohort; external validation is required before any clinical use.</em></p>


<div id="contact" class="connect-section" style="text-align: center; padding: 50px 20px; background: #f9f9f9; border-radius: 15px; border: 1px solid #eaeaea; margin-top: 40px;">
<h3 style="color: #2c3e50; font-weight: 700; margin-bottom: 15px; border: none;" class="anchored">Let's Collaborate</h3>
<p style="color: #666; max-width: 650px; margin: 0 auto 30px auto; font-size: 1.05rem; line-height: 1.6;">Available for high-impact <strong>Business Intelligence, Power BI Engineering, and Advanced Data Analytics</strong> projects. Connect with me or hire me directly through the platforms below.</p>
<div style="display: flex; flex-wrap: wrap; justify-content: center; gap: 12px;">
<a href="https://www.linkedin.com/in/mkmuneer" class="btn btn-primary" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; text-decoration: none;"><i class="bi bi-linkedin"></i> LinkedIn</a>
<a href="https://github.com/mkhanmuneer" class="btn btn-dark" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; text-decoration: none;"><i class="bi bi-github"></i> GitHub</a>
<a href="https://www.kaggle.com/muhammadkhanmuneer" class="btn btn-info" target="_blank" rel="noopener" style="color: white; padding: 12px 25px; min-width: 150px; text-decoration: none;"><i class="bi bi-graph-up"></i> Kaggle</a>
<a href="https://www.upwork.com/freelancers/~018de8553286a1d00c" class="btn btn-outline-success" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; border-width: 2px; font-weight: 600; text-decoration: none;"><i class="bi bi-briefcase"></i> Upwork</a>
<a href="https://www.fiverr.com/neuronvision" class="btn btn-outline-success" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; border-width: 2px; font-weight: 600; text-decoration: none;"><i class="bi bi-lightning-charge"></i> Fiverr</a>
</div>
</div>

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/mkhanmuneer\.github\.io\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 Muhammad Khan Muneer</p>
</div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://www.upwork.com/freelancers/~018de8553286a1d00c">
<p>Hire on Upwork</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="https://www.fiverr.com/neuronvision">
<p>Hire on Fiverr</p>
</a>
  </li>  
</ul>
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mkhanmuneer">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/mkmuneer">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>