<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Muhammad Khan Muneer">
<meta name="keywords" content="medallion architecture, ETL pipeline, random forest imputation, MICE, mixed-type imputation, sentinel encoding, missing data, feature engineering, data validation, Parquet, stroke dataset, Python, scikit-learn">
<meta name="description" content="A three-layer medallion ETL pipeline for a stroke-risk dataset. Heterogeneous missingness: 201 true bmi NaNs from CSV ingestion versus 1,545 sentinel-encoded gaps (&quot;Other&quot;, &quot;Unknown&quot;) that masquerade as valid categories. Sequential RF imputation: BMI → gender → smoking status, each imputed column feeding the next, resolving all 1,746 gaps. Leakage audit: the outcome was (imprecisely) a candidate predictor — quantified at ≤ 1.3% splitting weight in every imputer and disclosed rather than hidden. Output: a validated 5,110 × 24 Gold Parquet consumed by every downstream notebook.">

<title>Sequential Random-Forest Imputation and a Medallion ETL Pipeline for Mixed-Type Clinical Data – Muhammad Khan Muneer</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-4d9afe2b8d18ee9fa5d0d57b5ed4214d.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-5af9b5ab1fa0c387551d40c1aacb317e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-ca0cfe78a00f84493d894d8af57a3a20.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-5af9b5ab1fa0c387551d40c1aacb317e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": true,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<link rel="stylesheet" href="../../styles/custom.css">
<meta property="og:title" content="Muhammad Khan Muneer — Data Science &amp; BI Portfolio">
<meta property="og:description" content="Engineering ML-driven analytics and automated decision systems.">
<meta property="og:image" content="https://mkhanmuneer.github.io/projects/sequential-random-forest-imputation-medallion-pipeline-mixed-type-clinical-data/assets/fig5_imputer_feature_importance.png">
<meta property="og:site_name" content="M. Khan Muneer Portfolio">
<meta property="og:image:alt" content="Three horizontal bar charts of random-forest feature importances, one per imputer. In every panel the stroke bar (red) is the shortest, at rank 8/8, 9/9, and 9/10; avg_glucose_level and age are the longest bars in all three.">
<meta property="og:image:height" content="888">
<meta property="og:image:width" content="2972">
<meta name="twitter:title" content="Sequential Random-Forest Imputation and a Medallion ETL Pipeline for Mixed-Type Clinical Data – Muhammad Khan Muneer">
<meta name="twitter:description" content="A three-layer medallion ETL pipeline for a stroke-risk dataset. Heterogeneous missingness: 201 true bmi NaNs from CSV ingestion versus 1,545 sentinel-encoded gaps (&quot;Other&quot;, &quot;Unknown&quot;) that masquerade as valid categories. Sequential RF imputation: BMI → gender → smoking status, each imputed column feeding the next, resolving all 1,746 gaps. Leakage audit: the outcome was (imprecisely) a candidate predictor — quantified at ≤ 1.3% splitting weight in every imputer and disclosed rather than hidden. Output: a validated 5,110 × 24 Gold Parquet consumed by every downstream notebook.">
<meta name="twitter:image" content="https://mkhanmuneer.github.io/projects/sequential-random-forest-imputation-medallion-pipeline-mixed-type-clinical-data/assets/fig5_imputer_feature_importance.png">
<meta name="twitter:creator" content="@iMKhanMuneer">
<meta name="twitter:site" content="@iMKhanMuneer">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image:alt" content="Three horizontal bar charts of random-forest feature importances, one per imputer. In every panel the stroke bar (red) is the shortest, at rank 8/8, 9/9, and 9/10; avg_glucose_level and age are the longest bars in all three.">
<meta name="twitter:image-height" content="888">
<meta name="twitter:image-width" content="2972">
</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../index.html#featured-projects"> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/mkmuneer"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mkhanmuneer"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://x.com/iMKhanMuneer"> <i class="bi bi-twitter-x" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.kaggle.com/muhammadkhanmuneer"> <i class="bi bi-graph-up" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../index.html#contact"> 
<span class="menu-text">Contact</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#pipeline-architecture" id="toc-pipeline-architecture" class="nav-link" data-scroll-target="#pipeline-architecture">Pipeline architecture</a></li>
  <li><a href="#raw-ingestion-and-audit" id="toc-raw-ingestion-and-audit" class="nav-link" data-scroll-target="#raw-ingestion-and-audit">Raw ingestion and audit</a>
  <ul class="collapse">
  <li><a href="#type-and-structure" id="toc-type-and-structure" class="nav-link" data-scroll-target="#type-and-structure">Type and structure</a></li>
  <li><a href="#the-missingness-surface" id="toc-the-missingness-surface" class="nav-link" data-scroll-target="#the-missingness-surface">The missingness surface</a></li>
  <li><a href="#numeric-distributions-and-the-target" id="toc-numeric-distributions-and-the-target" class="nav-link" data-scroll-target="#numeric-distributions-and-the-target">Numeric distributions and the target</a></li>
  </ul></li>
  <li><a href="#bronze-layer-structural-cleaning" id="toc-bronze-layer-structural-cleaning" class="nav-link" data-scroll-target="#bronze-layer-structural-cleaning">Bronze layer — structural cleaning</a></li>
  <li><a href="#silver-layer-business-logic-cleaning" id="toc-silver-layer-business-logic-cleaning" class="nav-link" data-scroll-target="#silver-layer-business-logic-cleaning">Silver layer — business-logic cleaning</a></li>
  <li><a href="#gold-layer-imputation-and-feature-engineering" id="toc-gold-layer-imputation-and-feature-engineering" class="nav-link" data-scroll-target="#gold-layer-imputation-and-feature-engineering">Gold layer — imputation and feature engineering</a>
  <ul class="collapse">
  <li><a href="#sequential-random-forest-imputation" id="toc-sequential-random-forest-imputation" class="nav-link" data-scroll-target="#sequential-random-forest-imputation">Sequential random-forest imputation</a></li>
  <li><a href="#feature-engineering" id="toc-feature-engineering" class="nav-link" data-scroll-target="#feature-engineering">Feature engineering</a></li>
  </ul></li>
  <li><a href="#before-and-after-impact" id="toc-before-and-after-impact" class="nav-link" data-scroll-target="#before-and-after-impact">Before-and-after impact</a></li>
  <li><a href="#validation" id="toc-validation" class="nav-link" data-scroll-target="#validation">Validation</a></li>
  <li><a href="#carry-forward-findings" id="toc-carry-forward-findings" class="nav-link" data-scroll-target="#carry-forward-findings">Carry-forward findings</a></li>
  <li><a href="#tools-and-references" id="toc-tools-and-references" class="nav-link" data-scroll-target="#tools-and-references">Tools and references</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Sequential Random-Forest Imputation and a Medallion ETL Pipeline for Mixed-Type Clinical Data</h1>
<p class="subtitle lead">Turning a raw 5,110-row healthcare CSV into a validated, fully imputed, feature-engineered Gold layer — with a Bronze → Silver → Gold contract and an explicit read on heterogeneous missingness.</p>
  <div class="quarto-categories">
    <div class="quarto-category">Data Engineering</div>
    <div class="quarto-category">ETL Pipeline</div>
    <div class="quarto-category">Medallion Architecture</div>
    <div class="quarto-category">Imputation</div>
    <div class="quarto-category">Missing Data</div>
    <div class="quarto-category">Data Quality</div>
    <div class="quarto-category">Feature Engineering</div>
    <div class="quarto-category">Data Validation</div>
    <div class="quarto-category">Clinical Research</div>
    <div class="quarto-category">Healthcare Analytics</div>
    <div class="quarto-category">Python</div>
  </div>
  </div>

<div>
  <div class="description">
    <p>A three-layer medallion ETL pipeline for a stroke-risk dataset. <strong>Heterogeneous missingness:</strong> 201 true <code>bmi</code> NaNs from CSV ingestion versus 1,545 sentinel-encoded gaps (<code>"Other"</code>, <code>"Unknown"</code>) that masquerade as valid categories. <strong>Sequential RF imputation:</strong> BMI → gender → smoking status, each imputed column feeding the next, resolving all 1,746 gaps. <strong>Leakage audit:</strong> the outcome was (imprecisely) a candidate predictor — quantified at ≤ 1.3% splitting weight in every imputer and disclosed rather than hidden. <strong>Output:</strong> a validated 5,110 × 24 Gold Parquet consumed by every downstream notebook.</p>
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Muhammad Khan Muneer </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 2026</p>
    </div>
  </div>
  
    
  </div>
  

<div>
  <div class="keywords">
    <div class="block-title">Keywords</div>
    <p>medallion architecture, ETL pipeline, random forest imputation, MICE, mixed-type imputation, sentinel encoding, missing data, feature engineering, data validation, Parquet, stroke dataset, Python, scikit-learn</p>
  </div>
</div>

</header>


<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<p>This is the extract–transform–load (ETL) stage of a six-notebook stroke-risk project. It has one job: turn the raw Kaggle CSV — 5,110 patient records, 12 columns — into a fully imputed, feature-engineered analytical table that the exploratory, inferential, modelling, and clustering notebooks can each load without re-running any upstream logic. The pipeline produces that table through a <strong>three-layer medallion architecture</strong> (Bronze → Silver → Gold), where each layer has a strict contract, a distinct fault-isolation boundary, and a persisted Parquet snapshot any consumer can reload independently.</p>
<p>The finding that shapes the whole pipeline is that the dataset’s missingness is <strong>structurally heterogeneous</strong>. <code>bmi</code> carries 201 true <code>NaN</code> values from CSV parsing. <code>gender</code> and <code>smoking_status</code> carry <em>sentinel-encoded</em> gaps — the strings <code>"Other"</code> and <code>"Unknown"</code> — that appear as ordinary categories in any null count and would be silently modelled as real levels. Conflating the two forms produces wrong null counts, wrong imputation targets, and a Gold layer that misrepresents what was observed versus what was inferred. The layered design surfaces and resolves the heterogeneity explicitly: Bronze normalises structure, Silver replaces sentinels with true nulls, and Gold resolves all <strong>1,746</strong> missing values (201 + 1 + 1,544) through a sequential random-forest imputation that respects the mixed-type nature of the targets, followed by feature engineering that adds 11 analytical columns.</p>
</section>
<section id="pipeline-architecture" class="level2">
<h2 class="anchored" data-anchor-id="pipeline-architecture">Pipeline architecture</h2>
<p>Each layer knows strictly more about the data than the one before it. Bronze knows what the data <em>looks like</em>; Silver knows what it <em>means</em>; Gold produces the <em>analytical surface</em>. The contract for each layer — and, just as important, what each layer must <strong>not</strong> do — is fixed (Figure 1, Table 1).</p>
<p><strong>Figure 1</strong></p>
<p><em>The Bronze → Silver → Gold Medallion Pipeline</em></p>
<p><img src="assets/fig1_medallion_architecture.png" class="img-fluid" alt="Four boxes left to right: RAW (source CSV, 5,110 x 12, 0.081 MB), BRONZE (structural cleaning, 5,110 x 12, 0.086 MB), SILVER (business logic, 5,110 x 13, 0.095 MB), GOLD (analytical, 5,110 x 24, 0.224 MB), with an arrow onward to downstream notebooks."></p>
<p><em>Note.</em> Each arrow adds knowledge, never rows. The Parquet size grows only from nullable-dtype metadata (Bronze), the <code>bmi_raw</code> audit column (Silver), and the 11 engineered features plus filled values (Gold).</p>
<p><strong>Table 1</strong></p>
<p><em>Layer Contracts in the Medallion Pipeline</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Layer</th>
<th style="text-align: left;">Knows</th>
<th style="text-align: left;">Does</th>
<th style="text-align: left;">Must not do</th>
<th style="text-align: left;">Persisted as</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Raw</td>
<td style="text-align: left;">nothing</td>
<td style="text-align: left;">byte-for-byte snapshot of the source CSV</td>
<td style="text-align: left;">—</td>
<td style="text-align: left;"><code>stroke_raw.parquet</code> (0.081 MB)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bronze</td>
<td style="text-align: left;">physical structure</td>
<td style="text-align: left;">column rename, dtype enforcement, <code>id</code> → string, primary-key dedup check</td>
<td style="text-align: left;">replace sentinels, recode flags, derive columns</td>
<td style="text-align: left;"><code>stroke_bronze.parquet</code> (0.086 MB)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Silver</td>
<td style="text-align: left;">domain meaning</td>
<td style="text-align: left;">sentinel → <code>NaN</code>, 0/1 → <code>"Yes"</code>/<code>"No"</code>, label standardisation, <code>object</code> → <code>category</code>, <code>bmi_raw</code> audit trail</td>
<td style="text-align: left;">impute, derive cross-column features, drop rows</td>
<td style="text-align: left;"><code>stroke_silver.parquet</code> (0.095 MB)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gold</td>
<td style="text-align: left;">analytical intent</td>
<td style="text-align: left;">sequential RF imputation, 11 engineered features, intermediate-column cleanup</td>
<td style="text-align: left;">drop rows, touch Bronze or Raw</td>
<td style="text-align: left;"><code>stroke_gold.parquet</code> (0.224 MB)</td>
</tr>
</tbody>
</table>
<p><em>Note.</em> Row count is invariant at 5,110 across every layer — the single <code>gender = "Other"</code> row is retained throughout and its value resolved by imputation.</p>
</section>
<section id="raw-ingestion-and-audit" class="level2">
<h2 class="anchored" data-anchor-id="raw-ingestion-and-audit">Raw ingestion and audit</h2>
<p>The source CSV loads as 5,110 rows × 12 columns and is written to Parquet <strong>before any transformation</strong> as an immutable lineage anchor. A structural audit then runs against the untouched frame; no cleaning happens here, only diagnosis.</p>
<section id="type-and-structure" class="level3">
<h3 class="anchored" data-anchor-id="type-and-structure">Type and structure</h3>
<p>Four columns arrive with semantic type mismatches: <code>hypertension</code>, <code>heart_disease</code>, and <code>stroke</code> ingest as <code>int64</code> despite being binary flags, and <code>id</code> ingests as <code>int64</code> despite being a non-arithmetic identifier. Five string columns (<code>gender</code>, <code>ever_married</code>, <code>work_type</code>, <code>Residence_type</code>, <code>smoking_status</code>) are physically <code>object</code> but carry no categorical structure. One column violates the naming convention: <code>Residence_type</code> is the only Pascal-case name in an otherwise snake_case schema — a silent join-key hazard, since pandas merges are case-sensitive. No duplicate rows, no zero-variance columns, no identical column pairs.</p>
</section>
<section id="the-missingness-surface" class="level3">
<h3 class="anchored" data-anchor-id="the-missingness-surface">The missingness surface</h3>
<p>Missingness takes two structurally distinct forms (Figure 2, Table 2). Only <code>bmi</code> carries <strong>true <code>NaN</code></strong> — 201 rows (3.93%), created when pandas’ CSV parser recognised the <code>"N/A"</code> token and coerced the column to float (the R pipeline preserved the string; the Python <code>BMI_SENTINEL</code> replacement step is therefore a no-op here). <code>gender</code> and <code>smoking_status</code> carry <strong>sentinel strings</strong>: one <code>"Other"</code> value in <code>gender</code>, and 1,544 <code>"Unknown"</code> values in <code>smoking_status</code> — 30.22% of the dataset. The <code>"Unknown"</code> gap is deterministic missingness (smoking history not collected or not disclosed), not missing-at-random, and conflating <code>"Unknown"</code> with <code>"Never-Smoked"</code> would corrupt any model that uses smoking as a predictor.</p>
<p>The raw <code>work_type</code> and <code>smoking_status</code> labels are also inconsistent — <code>"Private"</code>, <code>"Self-employed"</code>, <code>"Govt_job"</code>, <code>"children"</code>, <code>"Never_worked"</code> mix casing, hyphens, underscores, and abbreviations — which Silver standardises.</p>
<p><strong>Table 2</strong></p>
<p><em>The Three Missingness Populations Entering the Gold Imputer</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Column</th>
<th style="text-align: left;">Form</th>
<th style="text-align: right;">Count</th>
<th style="text-align: right;">% of 5,110</th>
<th style="text-align: left;">Raw encoding</th>
<th style="text-align: left;">Resolved at</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>bmi</code></td>
<td style="text-align: left;">true <code>NaN</code></td>
<td style="text-align: right;">201</td>
<td style="text-align: right;">3.93</td>
<td style="text-align: left;">float <code>NaN</code> (from <code>"N/A"</code>)</td>
<td style="text-align: left;">Gold — RF regressor</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>gender</code></td>
<td style="text-align: left;">sentinel string</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.02</td>
<td style="text-align: left;"><code>"Other"</code></td>
<td style="text-align: left;">Silver → <code>NaN</code>; Gold — RF classifier</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>smoking_status</code></td>
<td style="text-align: left;">sentinel string</td>
<td style="text-align: right;">1,544</td>
<td style="text-align: right;">30.22</td>
<td style="text-align: left;"><code>"Unknown"</code></td>
<td style="text-align: left;">Silver → <code>NaN</code>; Gold — RF classifier</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Total</strong></td>
<td style="text-align: left;"></td>
<td style="text-align: right;"><strong>1,746</strong></td>
<td style="text-align: right;"><strong>34.17</strong></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
<p><em>Note.</em> A missing-value summary run on the raw frame reports only the 201 <code>bmi</code> nulls; the 1,545 sentinel gaps are invisible until Silver converts them.</p>
<p><strong>Figure 2</strong></p>
<p><em>The Two Forms of Missingness in the Raw Frame</em></p>
<p><img src="assets/fig2_missingness_type_map.png" class="img-fluid" alt="Horizontal stacked bars for bmi, gender, and smoking_status. bmi shows 201 as true NaN (blue). gender shows 1 and smoking_status shows 1,544 as sentinel strings (amber). smoking_status dominates at 30.22 percent."></p>
<p><em>Note.</em> Blue = numeric null handled natively by pandas; amber = sentinel string that counts as a valid category until replaced. The distinction determines the layer at which each gap is resolved.</p>
</section>
<section id="numeric-distributions-and-the-target" class="level3">
<h3 class="anchored" data-anchor-id="numeric-distributions-and-the-target">Numeric distributions and the target</h3>
<p>The three continuous columns motivate specific Gold transformations (Figure 3). Age (<em>M</em> = 43.23, range 0.08–82.0) is broadly distributed across the lifespan — the basis for the clinical <code>age_bucket</code> bands and <code>age_squared</code>. Average glucose (<em>M</em> = 106.15, <em>Mdn</em> = 91.88) is strongly right-skewed with a secondary mode near 200 mg/dL — a diabetic subpopulation, the basis for <code>glucose_log</code> and the &gt; 140 mg/dL <code>glucose_high</code> flag. BMI (<em>M</em> = 28.89 over 4,909 observed rows) is right-skewed with a tail to 97.6 — the basis for the <code>bmi_obese</code> (≥ 30) and <code>bmi_underweight</code> (&lt; 18.5) flags.</p>
<p>The outcome is severely imbalanced (Figure 4): 249 stroke-positive rows (4.87%) against 4,861 negative (95.13%), a 19.5:1 ratio. This is a carry-forward constraint for every downstream notebook — accuracy is not a valid metric, and a naïve “no stroke” classifier would score 95.13%.</p>
<p><strong>Figure 3</strong></p>
<p><em>Raw Distributions of the Three Continuous Columns and the Features They Motivate</em></p>
<p><img src="assets/fig3_raw_numeric_distributions.png" class="img-fluid" alt="Three histograms. Age is broad and roughly flat. Average glucose is right-skewed with a small secondary hump near 200 mg/dL. BMI is right-skewed with a long upper tail. Each panel is captioned with the Gold features it motivates."></p>
<p><em>Note.</em> The subtitle on each panel names the engineered features the distribution’s shape justifies.</p>
<p><strong>Figure 4</strong></p>
<p><em>Stroke Outcome Class Imbalance in the Raw Frame</em></p>
<p><img src="assets/fig4_class_imbalance.png" class="img-fluid" alt="Two bars: 4,861 no-stroke (95.13%) and 249 stroke (4.87%), a roughly 19.5-to-1 imbalance."></p>
<p><em>Note.</em> Preserved unchanged through the pipeline (see Figure 7) — cleaning resolves data quality without distorting the target signal.</p>
</section>
</section>
<section id="bronze-layer-structural-cleaning" class="level2">
<h2 class="anchored" data-anchor-id="bronze-layer-structural-cleaning">Bronze layer — structural cleaning</h2>
<p>Bronze applies structural normalisation only; its contract is losslessness. Five dtype changes: <code>id</code> → <code>string</code> (identifier, not a quantity); <code>hypertension</code>, <code>heart_disease</code>, <code>stroke</code> → nullable <code>Int64</code> (explicit nullability, encoding preserved); <code>bmi</code> → nullable <code>Float64</code> (makes the 201 nulls explicit at the dtype level, which the Gold imputer’s <code>np.isnan()</code> step depends on). One rename: <code>Residence_type</code> → <code>residence_type</code>. One check: zero duplicate <code>id</code> values, asserted rather than silently dropped. Shape unchanged at 5,110 × 12; Parquet grows 0.081 → 0.086 MB, the overhead of nullable-dtype metadata. Six columns are deliberately untouched — their issues are semantic, and semantics belong to Silver.</p>
</section>
<section id="silver-layer-business-logic-cleaning" class="level2">
<h2 class="anchored" data-anchor-id="silver-layer-business-logic-cleaning">Silver layer — business-logic cleaning</h2>
<p>Silver applies five categories of transformation and adds one audit column:</p>
<ul>
<li><strong>Sentinel replacement.</strong> <code>gender = "Other"</code> → <code>NaN</code> (one row, retained — too rare to be a stable category; its other 11 fields are valid). <code>smoking_status = "Unknown"</code> → <code>NaN</code> (1,544 rows) — making the deterministic gap semantically consistent with <code>bmi</code>’s structural nulls so the Gold imputer treats all three columns uniformly.</li>
<li><strong>Binary recoding.</strong> <code>hypertension</code>, <code>heart_disease</code>, <code>stroke</code>: <code>0</code>/<code>1</code> → <code>"No"</code>/<code>"Yes"</code>, so no downstream pipeline can treat a flag as a continuous quantity and the reference level is unambiguous.</li>
<li><strong>Label standardisation.</strong> The inconsistent raw labels are mapped to a canonical hyphenated title case (Table 3).</li>
<li><strong>Categorical promotion.</strong> All eight string columns → <code>category</code> dtype, applied after all string edits. Memory drops from 2.10 MB (Bronze) to 0.51 MB.</li>
<li><strong>Audit-trail preservation.</strong> The pre-imputation <code>bmi</code> is copied to <code>bmi_raw</code>; after Gold fills <code>bmi</code>, <code>bmi_raw</code> keeps its 201 <code>&lt;NA&gt;</code> entries as a permanent record of which values were observed. Downstream sensitivity analyses partition on <code>bmi_raw.notna()</code>.</li>
</ul>
<p>Seven programmatic assertions confirm every transformation reached every affected row (zero residual sentinels, zero residual integer flags, zero residual raw labels, <code>bmi_raw</code> and <code>bmi</code> both at 201 nulls, row count 5,110). Shape 5,110 × 13.</p>
<p><strong>Table 3</strong></p>
<p><em>Raw-to-Canonical Label Standardisation</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Column</th>
<th style="text-align: left;">Raw labels</th>
<th style="text-align: left;">Canonical labels</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>work_type</code></td>
<td style="text-align: left;"><code>Private</code>, <code>Self-employed</code>, <code>Govt_job</code>, <code>children</code>, <code>Never_worked</code></td>
<td style="text-align: left;"><code>Private-Work</code>, <code>Self-Employed</code>, <code>Government-Job</code>, <code>Child-Care</code>, <code>Never-Worked</code></td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>smoking_status</code></td>
<td style="text-align: left;"><code>never smoked</code>, <code>formerly smoked</code>, <code>smokes</code>, <code>Unknown</code></td>
<td style="text-align: left;"><code>Never-Smoked</code>, <code>Formerly-Smoked</code>, <code>Currently-Smokes</code> (+ <code>Unknown</code> → <code>NaN</code>)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>hypertension</code> / <code>heart_disease</code> / <code>stroke</code></td>
<td style="text-align: left;"><code>0</code>, <code>1</code></td>
<td style="text-align: left;"><code>No</code>, <code>Yes</code></td>
</tr>
</tbody>
</table>
<p><em>Note.</em> The canonical conventions match the project’s parallel R pipeline for cross-language traceability.</p>
</section>
<section id="gold-layer-imputation-and-feature-engineering" class="level2">
<h2 class="anchored" data-anchor-id="gold-layer-imputation-and-feature-engineering">Gold layer — imputation and feature engineering</h2>
<section id="sequential-random-forest-imputation" class="level3">
<h3 class="anchored" data-anchor-id="sequential-random-forest-imputation">Sequential random-forest imputation</h3>
<p>The three columns with missing values — <code>bmi</code> (continuous), <code>gender</code> (binary), <code>smoking_status</code> (three-level) — are not missing independently; age, work type, and glucose all carry information about the likely values. A marginal imputer (<code>most_frequent</code> / <code>mean</code>) ignores that structure; a per-column model respects it. <code>sklearn</code>’s <code>IterativeImputer</code> cannot handle mixed-type targets with a single estimator, so the pipeline runs <strong>three sequential random-forest fits</strong> — one <code>RandomForestRegressor</code> for <code>bmi</code>, two <code>RandomForestClassifier</code>s for <code>gender</code> and <code>smoking_status</code> — functionally one round of MICE (van Buuren &amp; Groothuis-Oudshoorn, 2011) with a random-forest learner per column (Stekhoven &amp; Bühlmann, 2012). The order is deliberate: <code>bmi</code> is imputed first from the eight complete predictors, then the completed <code>bmi</code> becomes a predictor for <code>gender</code>, then completed <code>bmi</code> and <code>gender</code> both become predictors for <code>smoking_status</code> — each step sees a richer predictor set than a parallel approach would give it. Categorical targets are label-encoded before fitting and decoded against the Silver category levels afterward, so no new level can appear. The seed <code>random_state = 412</code> aligns with the R pipeline’s <code>set.seed(412)</code>.</p>
<p><strong>A methodological imprecision, named plainly.</strong> The predictor matrix for all three imputers included <code>stroke</code> as a candidate. The outcome is not available at genuine prediction time, and its inclusion is not defensible on first principles. Rather than leave that as a theoretical concern, a feature-importance audit of the three fitted models quantified it (Figure 5): <code>stroke</code> ranked <strong>last or next-to-last</strong> in every model — 8th of 8 for the BMI regressor (importance 0.0061), 9th of 9 for gender (0.0091), 9th of 10 for smoking status (0.0129) — never exceeding <strong>1.3%</strong> of splitting weight, with <code>avg_glucose_level</code> and <code>age</code> dominating all three. The leakage is real in principle but negligible in practice; the imputed values should be read with that caveat rather than as fully outcome-independent.</p>
<p>The imputation outcome (Table 4): all 1,746 gaps filled, zero nulls remaining. The single <code>gender</code> gap resolved to <code>Female</code>. The 1,544 <code>smoking_status</code> gaps distributed as <code>Never-Smoked</code> +1,212, <code>Formerly-Smoked</code> +237, <code>Currently-Smokes</code> +95. BMI’s mean shifted 28.89 → 28.96 and its SD tightened 7.85 → 7.78 — the expected signature of values imputed toward the conditional mean, with the range unchanged (Figure 6). The 201 imputed BMI values are themselves narrower (<em>SD</em> 5.46 vs.&nbsp;7.85) and slightly higher (<em>M</em> 30.58) than the observed rows — flagged for downstream BMI sensitivity analyses.</p>
<p><strong>Table 4</strong></p>
<p><em>Sequential RF Imputation Outcome</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Step</th>
<th style="text-align: left;">Column</th>
<th style="text-align: left;">Model</th>
<th style="text-align: right;"><em>n</em> filled</th>
<th style="text-align: right;">Predictors</th>
<th style="text-align: left;">Result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;"><code>bmi</code></td>
<td style="text-align: left;"><code>RandomForestRegressor</code></td>
<td style="text-align: right;">201</td>
<td style="text-align: right;">8 complete columns</td>
<td style="text-align: left;"><em>M</em> 28.89 → 28.96; <em>SD</em> 7.85 → 7.78; range unchanged</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;"><code>gender</code></td>
<td style="text-align: left;"><code>RandomForestClassifier</code></td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">8 + imputed <code>bmi</code></td>
<td style="text-align: left;">→ <code>Female</code> (Female 2,994 → 2,995)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;"><code>smoking_status</code></td>
<td style="text-align: left;"><code>RandomForestClassifier</code></td>
<td style="text-align: right;">1,544</td>
<td style="text-align: right;">8 + imputed <code>bmi</code> + imputed <code>gender</code></td>
<td style="text-align: left;">Never 1,892 → 3,104; Formerly 885 → 1,122; Current 789 → 884</td>
</tr>
</tbody>
</table>
<p><em>Note.</em> 100 trees per forest, <code>random_state = 412</code>. No new category levels introduced (closed-vocabulary decode).</p>
<p><strong>Figure 5</strong></p>
<p><em>Imputer Feature Importances — the Stroke-as-Predictor Leakage Audit</em></p>
<p><img src="assets/fig5_imputer_feature_importance.png" class="img-fluid" alt="Three horizontal bar charts of random-forest feature importances, one per imputer. In every panel the stroke bar (red) is the shortest, at rank 8/8, 9/9, and 9/10; avg_glucose_level and age are the longest bars in all three."></p>
<p><em>Note.</em> <code>stroke</code> (red) is last or next-to-last in every imputer, at ≤ 1.3% importance. The leakage is disclosed and bounded, not removed.</p>
<p><strong>Figure 6</strong></p>
<p><em>Observed Versus Imputed BMI</em></p>
<p><img src="assets/fig6_bmi_observed_vs_imputed.png" class="img-fluid" alt="Two overlaid density histograms of BMI. The 4,909 observed rows spread widely (SD 7.85); the 201 imputed rows are narrower (SD 5.46) and centred slightly higher. Dashed lines mark the two means, close together near 29-31."></p>
<p><em>Note.</em> Imputed values cluster toward the conditional mean of the predictor space — expected for model-based imputation — without introducing out-of-range values.</p>
</section>
<section id="feature-engineering" class="level3">
<h3 class="anchored" data-anchor-id="feature-engineering">Feature engineering</h3>
<p>Gold adds 11 analytical columns (Table 5) and drops three intermediate scaffolding columns (<code>hypertension_num</code>, <code>heart_disease_num</code>, <code>cardio_combo</code>) that are collinear with their categorical parents. Final shape: 5,110 × 24. Key distributions: <code>age_bucket</code> = young 1,515 / mid 1,018 / mature 1,201 / senior 1,376; <code>glucose_high</code> flags 821 rows (16.1%); <code>is_smoker</code> flags 2,006 (39.3%); <code>bmi_obese</code> flags 2,021 (39.6%).</p>
<p><strong>Table 5</strong></p>
<p><em>The 11 Engineered Gold Features</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Feature</th>
<th style="text-align: left;">Definition</th>
<th style="text-align: left;">Rationale</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>age_squared</code></td>
<td style="text-align: left;">age²</td>
<td style="text-align: left;">linear handle on accelerating age–risk relationship</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>age_bucket</code></td>
<td style="text-align: left;">age bands [0, 30, 45, 60, ∞)</td>
<td style="text-align: left;">clinically meaningful strata, not quantile cuts</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>is_smoker</code></td>
<td style="text-align: left;">1 if formerly or currently smokes</td>
<td style="text-align: left;">clinical grouping; more stable than 3-level status</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>bmi_obese</code></td>
<td style="text-align: left;">1 if BMI ≥ 30</td>
<td style="text-align: left;">WHO obesity threshold</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>bmi_underweight</code></td>
<td style="text-align: left;">1 if BMI &lt; 18.5</td>
<td style="text-align: left;">WHO underweight threshold</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>glucose_log</code></td>
<td style="text-align: left;">log1p(avg_glucose_level)</td>
<td style="text-align: left;">compresses the right tail for gradient models</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>glucose_high</code></td>
<td style="text-align: left;">1 if avg_glucose_level &gt; 140</td>
<td style="text-align: left;">pre-diabetic clinical threshold</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>age_glucose</code></td>
<td style="text-align: left;">age × glucose_log</td>
<td style="text-align: left;">age-related decline × metabolic stress</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>age_bmi</code></td>
<td style="text-align: left;">age × BMI</td>
<td style="text-align: left;">age × adiposity, non-linear on CV risk</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>hyper_glucose</code></td>
<td style="text-align: left;">hypertension × glucose_high</td>
<td style="text-align: left;">co-occurring vascular strain</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>smoker_obese</code></td>
<td style="text-align: left;">is_smoker × bmi_obese</td>
<td style="text-align: left;">dual lifestyle risk burden</td>
</tr>
</tbody>
</table>
<p><em>Note.</em> All interaction terms are candidate features; the modelling notebook decides which survive selection. <code>id</code> is retained (exclusion deferred downstream).</p>
</section>
</section>
<section id="before-and-after-impact" class="level2">
<h2 class="anchored" data-anchor-id="before-and-after-impact">Before-and-after impact</h2>
<p>The pipeline’s net effect is a complete analytical surface with the target signal intact (Figure 7). The 1,746 raw missing-and-sentinel gaps across <code>bmi</code>, <code>gender</code>, and <code>smoking_status</code> are driven to <strong>zero</strong> in Gold. The 4.87% stroke rate is <strong>identical</strong> in the raw frame and the Gold layer — cleaning and imputation resolved data quality without touching the outcome distribution.</p>
<p><strong>Figure 7</strong></p>
<p><em>Pipeline Impact: Gaps Resolved, Target Signal Preserved</em></p>
<p><img src="assets/fig7_before_after_impact.png" class="img-fluid" alt="Left panel: grouped bars showing bmi 201, gender 1, smoking_status 1,544 in the raw frame all going to 0 in the Gold layer. Right panel: stroke class proportions 95.13 / 4.87 percent identical between raw and Gold."></p>
<p><em>Note.</em> Left — data-quality gaps by column, raw versus Gold. Right — stroke class proportions, raw versus Gold.</p>
</section>
<section id="validation" class="level2">
<h2 class="anchored" data-anchor-id="validation">Validation</h2>
<p>Three checks confirm the Gold Parquet is correctly serialised and analytically ready. A <strong>serialisation round-trip</strong> reloads the file and asserts zero nulls across 11 primary analytical columns — this verifies that <code>category</code>, nullable <code>Float64</code>, and <code>string</code> dtypes all survive Parquet without a silent cast. A <strong>shape verification</strong> asserts the three layers against hardcoded expected dimensions: Bronze (5,110 × 12), Silver (5,110 × 13), Gold (5,110 × 24) — a deviation is a pipeline bug, not a configuration value. The <strong>row count</strong> holds at 5,110 across every layer, confirming no rows were dropped and the single <code>gender = "Other"</code> row was retained end to end. All checks pass.</p>
</section>
<section id="carry-forward-findings" class="level2">
<h2 class="anchored" data-anchor-id="carry-forward-findings">Carry-forward findings</h2>
<p>Four facts surfaced by the pipeline that every downstream notebook must account for:</p>
<ol type="1">
<li><strong>Class imbalance.</strong> 249 positives (4.87%), 19.5:1. Requires resampling, class weighting, or threshold calibration; accuracy is not a valid metric.</li>
<li><strong><code>bmi_raw</code> audit column.</strong> Its 201 <code>&lt;NA&gt;</code> entries mark exactly which rows received an imputed BMI. Observed-only analyses filter on <code>bmi_raw.notna()</code>; BMI odds ratios and coefficients warrant an observed-only sensitivity check because the imputed values are measurably narrower.</li>
<li><strong>Smoking imputed at scale.</strong> 1,544 values (30.22%) are modelled, not observed. Models that weight <code>smoking_status</code> or <code>is_smoker</code> heavily should be tested for imputation sensitivity; a re-run with a different seed would quantify stability.</li>
<li><strong>Age is the dominant univariate signal.</strong> Stroke concentrates in older adulthood (1,376 senior-band rows); any model excluding <code>age</code> / <code>age_squared</code> will likely underperform a simple age threshold.</li>
</ol>
</section>
<section id="tools-and-references" class="level2">
<h2 class="anchored" data-anchor-id="tools-and-references">Tools and references</h2>
<p>Built in Python with <code>pandas</code> and <code>pyarrow</code> for the medallion layers and <code>scikit-learn</code> for the random-forest imputers. Clinical thresholds follow the WHO body-mass-index classification. The sequential-fit imputation is a single-round instance of multivariate imputation by chained equations with tree learners.</p>
<p>Harris, C. R., Millman, K. J., van der Walt, S. J., Gommers, R., Virtanen, P., Cournapeau, D., Wieser, E., Taylor, J., Berg, S., Smith, N. J., Kern, R., Picus, M., Hoyer, S., van Kerkwijk, M. H., Brett, M., Haldane, A., del Río, J. F., Wiebe, M., Peterson, P., … Oliphant, T. E. (2020). Array programming with NumPy. <em>Nature, 585</em>, 357–362. https://doi.org/10.1038/s41586-020-2649-2</p>
<p>Pedregosa, F., Varoquaux, G., Gramfort, A., Michel, V., Thirion, B., Grisel, O., Blondel, M., Prettenhofer, P., Weiss, R., Dubourg, V., Vanderplas, J., Passos, A., Cournapeau, D., Brucher, M., Perrot, M., &amp; Duchesnay, É. (2011). Scikit-learn: Machine learning in Python. <em>Journal of Machine Learning Research, 12</em>, 2825–2830.</p>
<p>Stekhoven, D. J., &amp; Bühlmann, P. (2012). MissForest — non-parametric missing value imputation for mixed-type data. <em>Bioinformatics, 28</em>(1), 112–118. https://doi.org/10.1093/bioinformatics/btr597</p>
<p>The pandas development team. (2020). <em>pandas-dev/pandas: Pandas</em> (Version latest) [Computer software]. Zenodo. https://doi.org/10.5281/zenodo.3509134</p>
<p>van Buuren, S., &amp; Groothuis-Oudshoorn, K. (2011). mice: Multivariate imputation by chained equations in R. <em>Journal of Statistical Software, 45</em>(3), 1–67. https://doi.org/10.18637/jss.v045.i03</p>
<p>World Health Organization. (2010). <em>A healthy lifestyle — WHO recommendations</em> (Body mass index classification). World Health Organization.</p>
<p>fedesoriano. (2021). <em>Stroke prediction dataset</em> [Data set]. Kaggle. https://www.kaggle.com/datasets/fedesoriano/stroke-prediction-dataset</p>
<hr>
<p><em>Pipeline and figures by the author. The Gold Parquet described here is the sole data input for every downstream notebook in the project.</em></p>


<div id="contact" class="connect-section" style="text-align: center; padding: 50px 20px; background: #f9f9f9; border-radius: 15px; border: 1px solid #eaeaea; margin-top: 40px;">
<h3 style="color: #2c3e50; font-weight: 700; margin-bottom: 15px; border: none;" class="anchored">Let's Collaborate</h3>
<p style="color: #666; max-width: 650px; margin: 0 auto 30px auto; font-size: 1.05rem; line-height: 1.6;">Available for high-impact <strong>Business Intelligence, Power BI Engineering, and Advanced Data Analytics</strong> projects. Connect with me or hire me directly through the platforms below.</p>
<div style="display: flex; flex-wrap: wrap; justify-content: center; gap: 12px;">
<a href="https://www.linkedin.com/in/mkmuneer" class="btn btn-primary" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; text-decoration: none;"><i class="bi bi-linkedin"></i> LinkedIn</a>
<a href="https://github.com/mkhanmuneer" class="btn btn-dark" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; text-decoration: none;"><i class="bi bi-github"></i> GitHub</a>
<a href="https://www.kaggle.com/muhammadkhanmuneer" class="btn btn-info" target="_blank" rel="noopener" style="color: white; padding: 12px 25px; min-width: 150px; text-decoration: none;"><i class="bi bi-graph-up"></i> Kaggle</a>
<a href="https://www.upwork.com/freelancers/~018de8553286a1d00c" class="btn btn-outline-success" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; border-width: 2px; font-weight: 600; text-decoration: none;"><i class="bi bi-briefcase"></i> Upwork</a>
<a href="https://www.fiverr.com/neuronvision" class="btn btn-outline-success" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; border-width: 2px; font-weight: 600; text-decoration: none;"><i class="bi bi-lightning-charge"></i> Fiverr</a>
</div>
</div>

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/mkhanmuneer\.github\.io\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 Muhammad Khan Muneer</p>
</div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://www.upwork.com/freelancers/~018de8553286a1d00c">
<p>Hire on Upwork</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="https://www.fiverr.com/neuronvision">
<p>Hire on Fiverr</p>
</a>
  </li>  
</ul>
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mkhanmuneer">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/mkmuneer">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>