<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Muhammad Khan Muneer">
<meta name="keywords" content="clickstream analysis, web sessions, conversion funnel, add-to-cart rate, bounce rate, GA4 engagement, sessionisation, user panel, exploratory data analysis, browse versus purchase, Python, pandas">
<meta name="description" content="A behavioural diagnostic of 196,720 web sessions reconstructed from a product-page access log. The funnel is degenerate: every URL is a product path, so the only real step is browse → cart, at 46.4%. The audience is a panel: 3,340 IP addresses, ~59 sessions each over five months, 15 first-time sessions in the whole dataset — so the 46.4% rate reflects catalogue-familiar repeat visitors, not cold traffic. Behaviour is bimodal: sessions bounce in under a minute (51%) or run 15–60 minutes (27%), with almost nothing between; 82.7% view three pages or fewer. Bounce depends on the definition: 49.3% by the single-page rule, 35.5% by GA4’s engagement rule. Temporal volume is flat; engagement peaks in the evening (a correction to the source notebook’s off-peak claim).">

<title>A 46.4% Session-to-Cart Rate and a Bimodal Audience: A Conversion and Engagement Diagnostic Over 196,720 Sessions – Muhammad Khan Muneer</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-4d9afe2b8d18ee9fa5d0d57b5ed4214d.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-5af9b5ab1fa0c387551d40c1aacb317e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-ca0cfe78a00f84493d894d8af57a3a20.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-5af9b5ab1fa0c387551d40c1aacb317e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": true,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<link rel="stylesheet" href="../../styles/custom.css">
<meta property="og:title" content="Muhammad Khan Muneer — Data Science &amp; BI Portfolio">
<meta property="og:description" content="Engineering ML-driven analytics and automated decision systems.">
<meta property="og:image" content="https://mkhanmuneer.github.io/projects/clickstream-conversion-engagement-diagnostic-bimodal-audience/assets/fig1_user_panel.png">
<meta property="og:site_name" content="M. Khan Muneer Portfolio">
<meta property="og:image:height" content="811">
<meta property="og:image:width" content="1863">
<meta name="twitter:title" content="A 46.4% Session-to-Cart Rate and a Bimodal Audience: A Conversion and Engagement Diagnostic Over 196,720 Sessions – Muhammad Khan Muneer">
<meta name="twitter:description" content="A behavioural diagnostic of 196,720 web sessions reconstructed from a product-page access log. The funnel is degenerate: every URL is a product path, so the only real step is browse → cart, at 46.4%. The audience is a panel: 3,340 IP addresses, ~59 sessions each over five months, 15 first-time sessions in the whole dataset — so the 46.4% rate reflects catalogue-familiar repeat visitors, not cold traffic. Behaviour is bimodal: sessions bounce in under a minute (51%) or run 15–60 minutes (27%), with almost nothing between; 82.7% view three pages or fewer. Bounce depends on the definition: 49.3% by the single-page rule, 35.5% by GA4’s engagement rule. Temporal volume is flat; engagement peaks in the evening (a correction to the source notebook’s off-peak claim).">
<meta name="twitter:image" content="https://mkhanmuneer.github.io/projects/clickstream-conversion-engagement-diagnostic-bimodal-audience/assets/fig1_user_panel.png">
<meta name="twitter:creator" content="@iMKhanMuneer">
<meta name="twitter:site" content="@iMKhanMuneer">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image-height" content="811">
<meta name="twitter:image-width" content="1863">
</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../index.html#featured-projects"> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/mkmuneer"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mkhanmuneer"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://x.com/iMKhanMuneer"> <i class="bi bi-twitter-x" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.kaggle.com/muhammadkhanmuneer"> <i class="bi bi-graph-up" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../index.html#contact"> 
<span class="menu-text">Contact</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract">Abstract</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#method" id="toc-method" class="nav-link" data-scroll-target="#method">Method</a>
  <ul class="collapse">
  <li><a href="#data-source" id="toc-data-source" class="nav-link" data-scroll-target="#data-source">Data source</a></li>
  <li><a href="#variables-and-measures" id="toc-variables-and-measures" class="nav-link" data-scroll-target="#variables-and-measures">Variables and measures</a></li>
  <li><a href="#analytical-approach" id="toc-analytical-approach" class="nav-link" data-scroll-target="#analytical-approach">Analytical approach</a></li>
  <li><a href="#software" id="toc-software" class="nav-link" data-scroll-target="#software">Software</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#the-audience-is-a-panel-not-open-traffic" id="toc-the-audience-is-a-panel-not-open-traffic" class="nav-link" data-scroll-target="#the-audience-is-a-panel-not-open-traffic">The audience is a panel, not open traffic</a></li>
  <li><a href="#the-funnel-is-degenerate-the-one-real-step-is-46.4" id="toc-the-funnel-is-degenerate-the-one-real-step-is-46.4" class="nav-link" data-scroll-target="#the-funnel-is-degenerate-the-one-real-step-is-46.4">The funnel is degenerate; the one real step is 46.4%</a></li>
  <li><a href="#a-bimodal-audience" id="toc-a-bimodal-audience" class="nav-link" data-scroll-target="#a-bimodal-audience">A bimodal audience</a></li>
  <li><a href="#bounce-depends-on-the-definition" id="toc-bounce-depends-on-the-definition" class="nav-link" data-scroll-target="#bounce-depends-on-the-definition">Bounce depends on the definition</a></li>
  <li><a href="#temporal-behaviour-flat-volume-an-evening-engagement-peak-one-artefact" id="toc-temporal-behaviour-flat-volume-an-evening-engagement-peak-one-artefact" class="nav-link" data-scroll-target="#temporal-behaviour-flat-volume-an-evening-engagement-peak-one-artefact">Temporal behaviour: flat volume, an evening engagement peak, one artefact</a></li>
  <li><a href="#correlation-structure" id="toc-correlation-structure" class="nav-link" data-scroll-target="#correlation-structure">Correlation structure</a></li>
  <li><a href="#browse-versus-purchase" id="toc-browse-versus-purchase" class="nav-link" data-scroll-target="#browse-versus-purchase">Browse versus purchase</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a>
  <ul class="collapse">
  <li><a href="#principal-findings" id="toc-principal-findings" class="nav-link" data-scroll-target="#principal-findings">Principal findings</a></li>
  <li><a href="#the-mechanism-worth-naming" id="toc-the-mechanism-worth-naming" class="nav-link" data-scroll-target="#the-mechanism-worth-naming">The mechanism worth naming</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations">Limitations</a></li>
  <li><a href="#modelling-targets" id="toc-modelling-targets" class="nav-link" data-scroll-target="#modelling-targets">Modelling targets</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">A 46.4% Session-to-Cart Rate and a Bimodal Audience: A Conversion and Engagement Diagnostic Over 196,720 Sessions</h1>
<p class="subtitle lead">An exploratory clickstream analysis of a five-month web access log — why the funnel collapses to one step, why the audience is a panel rather than open traffic, and what that does to every rate the data reports.</p>
  <div class="quarto-categories">
    <div class="quarto-category">Exploratory Data Analysis</div>
    <div class="quarto-category">Descriptive Statistics</div>
    <div class="quarto-category">Web Analytics</div>
    <div class="quarto-category">Clickstream Analytics</div>
    <div class="quarto-category">Digital Analytics</div>
    <div class="quarto-category">Funnel Analysis</div>
    <div class="quarto-category">Conversion Analysis</div>
    <div class="quarto-category">Temporal Analysis</div>
    <div class="quarto-category">GA4</div>
    <div class="quarto-category">Python</div>
  </div>
  </div>

<div>
  <div class="description">
    <p>A behavioural diagnostic of 196,720 web sessions reconstructed from a product-page access log. <strong>The funnel is degenerate:</strong> every URL is a product path, so the only real step is browse → cart, at <strong>46.4%</strong>. <strong>The audience is a panel:</strong> 3,340 IP addresses, ~59 sessions each over five months, 15 first-time sessions in the whole dataset — so the 46.4% rate reflects catalogue-familiar repeat visitors, not cold traffic. <strong>Behaviour is bimodal:</strong> sessions bounce in under a minute (51%) or run 15–60 minutes (27%), with almost nothing between; 82.7% view three pages or fewer. <strong>Bounce depends on the definition:</strong> 49.3% by the single-page rule, 35.5% by GA4’s engagement rule. Temporal volume is flat; engagement peaks in the evening (a correction to the source notebook’s off-peak claim).</p>
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Muhammad Khan Muneer </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 2024</p>
    </div>
  </div>
  
    
  </div>
  

<div>
  <div class="keywords">
    <div class="block-title">Keywords</div>
    <p>clickstream analysis, web sessions, conversion funnel, add-to-cart rate, bounce rate, GA4 engagement, sessionisation, user panel, exploratory data analysis, browse versus purchase, Python, pandas</p>
  </div>
</div>

</header>


<section id="abstract" class="level2">
<h2 class="anchored" data-anchor-id="abstract">Abstract</h2>
<p>This study is a descriptive clickstream analysis of the <em>DataCo</em> web access log — 466,728 page views logged between 1 September 2017 and 31 January 2018, aggregated into <strong>196,720 visitor sessions</strong> carrying 37 engineered features. The analytical table is the validated Gold layer of a companion medallion pipeline; every measure is recomputed from it. Two structural facts govern the interpretation. <strong>The access log is restricted to product-page URLs</strong>, so every session already registers a product, category, and department view — the conversion funnel from arrival to product view collapses to 100% and the only meaningful step is the transition to an add-to-cart event, which occurs in <strong>46.4% of sessions</strong>. <strong>The audience is a bounded panel, not open web traffic:</strong> 3,340 IP addresses generate the sessions, an average of ~59 each over five months, and only <strong>15 of the 196,720 sessions</strong> originate from an IP never seen again — against a 30–60% new-visitor rate for a typical consumer site. The 46.4% cart rate is therefore a property of catalogue-familiar repeat visitors and should not be read as a general conversion benchmark. Session behaviour is <strong>bimodal</strong>: 51% of sessions bounce in under a minute while 27% run 15–60 minutes, with the 1–5 minute band nearly empty; 82.7% of sessions view three product pages or fewer. Bounce rate is <strong>49.3% by the single-page (UA) rule and 35.5% by GA4’s engagement rule</strong> — the two definitions differ by 14 points. Traffic volume is flat across the window (bar a single-day ingestion artefact on 14 September); mean engagement rises to an <strong>evening peak around 9pm</strong> — the reverse of the source notebook’s “off-peak visitors engage more” claim. No causal claim is made.</p>
<p><em>Keywords:</em> clickstream analysis, conversion funnel, add-to-cart rate, bounce rate, GA4 engagement, user panel, browse versus purchase</p>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>The companion operations, customer, and catalogue studies of this dataset worked from the order record. This study works from the other side of the transaction: the <strong>web access log</strong> — every product-page request made to the retailer’s site over a five-month window, reconstructed into visitor sessions.</p>
<p>The unit of analysis is the <strong>session</strong>: a run of page views from one IP address with no gap longer than 30 minutes. Each session is summarised into one row carrying its duration, page count, product breadth, cart activity, time of day, and the frequency with which its IP appears in the data.</p>
<p>Two properties of the data shape everything that follows, and both are stated up front because they bound what the numbers mean. First, the log captures <strong>product pages only</strong> — no homepage, search, or account traffic — so the classic “arrival → browse → cart” funnel has no early stages to measure. Second, the visitor base is a <strong>small, high-frequency panel</strong>: a few thousand IPs, each returning dozens of times. The headline 46.4% session-to-cart rate is real, but it is the rate for that panel, not a benchmark a cold-traffic retailer could expect to match.</p>
</section>
<section id="method" class="level2">
<h2 class="anchored" data-anchor-id="method">Method</h2>
<section id="data-source" class="level3">
<h3 class="anchored" data-anchor-id="data-source">Data source</h3>
<p>Two tables. <code>sessions_features_gold</code> (196,720 rows × 37 columns), one row per session, no missing values in any analysed column. <code>fact_access_logs_gold</code> (466,728 rows × 15 columns) at page-view grain, used for the daily-volume and product-concentration views. Cross-dataset comparison uses the <code>_overlap</code> variants of the session and logistics tables (195,341 sessions; 13,678 order-items) restricted to the shared window, joined on canonical product name. Table 1 summarises the session grain.</p>
<p><strong>Table 1</strong></p>
<p><em>Session Characteristics (N = 196,720 sessions from 3,340 IP addresses)</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Feature</th>
<th style="text-align: right;">Median</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">75th pct</th>
<th style="text-align: right;">Max</th>
<th style="text-align: right;">Skew</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Duration (minutes)</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">13.9</td>
<td style="text-align: right;">22.0</td>
<td style="text-align: right;">244.0</td>
<td style="text-align: right;">+2.48</td>
</tr>
<tr class="even">
<td style="text-align: left;">Page views</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2.37</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">+3.41</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Unique products viewed</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.11</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">+2.33</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cart events (key events)</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.67</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">+2.37</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Engagement score</td>
<td style="text-align: right;">1.20</td>
<td style="text-align: right;">1.65</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">18.4</td>
<td style="text-align: right;">+3.05</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sessions per IP (<code>ip_freq</code>, session-weighted)</td>
<td style="text-align: right;">104</td>
<td style="text-align: right;">99.0</td>
<td style="text-align: right;">127</td>
<td style="text-align: right;">234</td>
<td style="text-align: right;">−0.20</td>
</tr>
</tbody>
</table>
<p><em>Note.</em> Every behavioural feature is heavily right-skewed except <code>ip_freq</code>, which is compressed and near-symmetric — the panel signature. Regression targets need a <code>log1p</code> transform (see Discussion).</p>
</section>
<section id="variables-and-measures" class="level3">
<h3 class="anchored" data-anchor-id="variables-and-measures">Variables and measures</h3>
<p><strong><code>page_views</code></strong> and its structural equivalents (<code>product_views</code>, <code>category_pages_viewed</code>, <code>department_pages_viewed</code> are identical, a consequence of the product-only URL filter). <strong><code>duration_minutes</code></strong> (session end − start). <strong><code>engagement_score</code></strong> = <code>0.3·page_views + 0.3·unique_url_actions + 0.4·key_event_count</code>, a weighted composite with cart events weighted most heavily. <strong>Bounce definitions:</strong> <code>bounce_session_ua</code> = exactly one page view; <code>is_engaged_session_ga4</code> = duration &gt; 10 s OR page_views ≥ 2 OR a cart event; <code>bounce_session_ga4</code> = its negation. <strong><code>has_add_to_cart</code></strong> = at least one cart event. <strong><code>ip_freq</code></strong> = sessions attributed to the session’s IP; <strong><code>is_repeat_visitor</code></strong> = <code>ip_freq &gt; 1</code>. <strong><code>time_of_day_bucket</code></strong> and <code>session_hour</code>.</p>
</section>
<section id="analytical-approach" class="level3">
<h3 class="anchored" data-anchor-id="analytical-approach">Analytical approach</h3>
<p>Descriptive. Distributions are summarised for duration, page depth, and engagement; the funnel is reported as step-wise session shares; the three bounce definitions are compared directly. Temporal behaviour uses hour-of-day volume and mean engagement, and daily page-view volume. Feature relationships use pairwise Pearson correlation across ten session features. The browse-versus-purchase comparison regresses log units sold on log page views across the 36 products present in both datasets during the overlap window. No model is fitted; a target-viability scan is summarised in the Discussion.</p>
</section>
<section id="software" class="level3">
<h3 class="anchored" data-anchor-id="software">Software</h3>
<p>Python 3.10 with <code>pandas</code>, <code>numpy</code>, and <code>matplotlib</code>.</p>
</section>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<section id="the-audience-is-a-panel-not-open-traffic" class="level3">
<h3 class="anchored" data-anchor-id="the-audience-is-a-panel-not-open-traffic">The audience is a panel, not open traffic</h3>
<p>The single most consequential feature of this dataset is who is in it (Figure 1). The 196,720 sessions come from just <strong>3,340 IP addresses</strong> — an average of <strong>59 sessions per IP</strong> over five months, roughly one every two to three days. The distribution of sessions per IP is not the power law that open web traffic produces (a huge population of one-visit IPs, a handful of heavy IPs); it is compressed, with every IP returning between 1 and 234 times. And <strong><code>is_repeat_visitor</code> is true for 99.99% of sessions</strong> — only <strong>15 sessions in the entire dataset</strong> come from an IP that never reappears, against a 30–60% new-visitor rate for a typical consumer site. This is a structured visitor panel. Every rate reported below is a rate for catalogue-familiar frequent visitors, and the <code>is_repeat_visitor</code> flag is analytically dead (a 99.99% class) and excluded from any feature set.</p>
<p><strong>Figure 1</strong></p>
<p><em>Sessions per IP Address, and the Repeat-Visitor Split</em></p>
<p><img src="assets/fig1_user_panel.png" class="img-fluid" alt="Left: histogram of sessions attributed to each of 3,340 IP addresses over five months — a compressed distribution ranging 1 to 234 with a mean near 59, not a long-tailed power law. Right: two bars — returning visitors (IP seen before) 196,705 sessions (99.99%), first-time visitors 15 sessions (0.01%)."></p>
<p><em>Note.</em> Session-weighted <code>ip_freq</code> (each session carries its IP’s total) has a higher median (104) than the per-IP mean (59), because high-frequency IPs contribute more sessions.</p>
</section>
<section id="the-funnel-is-degenerate-the-one-real-step-is-46.4" class="level3">
<h3 class="anchored" data-anchor-id="the-funnel-is-degenerate-the-one-real-step-is-46.4">The funnel is degenerate; the one real step is 46.4%</h3>
<p>Because the access log was filtered to product-page URLs of the form <code>/department/…/category/…/product/…</code>, <strong>every session registers at least one department, category, and product view</strong> — the funnel steps from “arrival” to “any product view” are all exactly 100% (Figure 2, left). This is not perfect early-funnel conversion; it is the absence of early-funnel data. The one measurable step is the transition to a cart event: <strong>91,302 of 196,720 sessions (46.4%) contain at least one add-to-cart</strong> (Figure 2, right). Among GA4-engaged sessions the cart rate is 72%; among single-page (UA) bounce sessions it is still 28% — a one-page visit can and often does end in a cart. For a cold-traffic retailer 46.4% would be implausibly high; for this panel of repeat visitors who already know the catalogue, it is consistent with the rest of the picture.</p>
<p><strong>Figure 2</strong></p>
<p><em>The Session Funnel and the Session-to-Cart Rate by Session Type</em></p>
<p><img src="assets/fig2_session_to_cart_funnel.png" class="img-fluid" alt="Left: three bars — all sessions 100%, any product/category/department view 100%, add to cart 46.4%. Right: add-to-cart rate by session type — GA4-engaged sessions 72%, single-page (UA) bounce sessions 28%, all sessions 46%."></p>
<p><em>Note.</em> The 100% product-view step reflects the product-only URL filter, not conversion.</p>
</section>
<section id="a-bimodal-audience" class="level3">
<h3 class="anchored" data-anchor-id="a-bimodal-audience">A bimodal audience</h3>
<p>Session behaviour splits into two modes with little in between (Figures 3 and 4). <strong>Duration:</strong> the median session is <strong>1 minute</strong>, the mean is 13.9, and the maximum is 244. Bucketed, <strong>51% of sessions bounce (under 1 minute)</strong> and <strong>27% run Long (15–60 minutes)</strong>, but only <strong>4.7% fall in the Short (1–5 minute) band</strong> — visitors either leave almost immediately or settle in for a substantial stay (Figure 3). <strong>Page depth:</strong> the median session views <strong>2 pages</strong>, and <strong>82.7% view three or fewer</strong> (Figure 4); sessions reaching eight or more pages are under 4% of the total. The practical reading is that the site has a two-to-three-page window to engage most visitors, and deep browsing (page eight and beyond) is a path fewer than 7,600 sessions ever take.</p>
<p><strong>Figure 3</strong></p>
<p><em>Session Duration: Distribution and Buckets</em></p>
<p><img src="assets/fig3_bimodal_duration.png" class="img-fluid" alt="Left: histogram of session duration in minutes (clipped at 60) — a very tall bar at zero and a long right-skewed shoulder. Right: duration buckets as percentages — Bounce (under 1 minute) 51 percent, Short (1 to 5 minutes) 5 percent, Medium (5 to 15 minutes) 12 percent, Long (15 to 60 minutes) 27 percent, Very Long (over 60 minutes) 5 percent."></p>
<p><em>Note.</em> The near-empty Short band between the bounce spike and the Long bucket is the bimodal signature.</p>
<p><strong>Figure 4</strong></p>
<p><em>Page Views per Session</em></p>
<p><img src="assets/fig4_page_depth.png" class="img-fluid" alt="Left: histogram of page views per session — sharply peaked at 1 and 2, a long thin tail to 30. Right: page-depth buckets — 1 page 96,986 (49.3%), 2–3 pages 65,671 (33.4%), 4–7 pages 26,453 (13.4%), 8–15 pages 6,599 (3.4%), 16+ pages 1,011 (0.5%)."></p>
<p><em>Note.</em> The 1-page bucket (49.3%) is exactly the single-page (UA) bounce population.</p>
</section>
<section id="bounce-depends-on-the-definition" class="level3">
<h3 class="anchored" data-anchor-id="bounce-depends-on-the-definition">Bounce depends on the definition</h3>
<p>The bounce rate is not one number (Figure 5, Table 2). By the traditional <strong>single-page (UA) rule</strong> — a session with exactly one page view — <strong>49.3% of sessions bounce</strong> (96,986). By <strong>GA4’s engagement rule</strong> — a session that fails all of the 10-second, 2-page, and cart-event tests — <strong>35.5% bounce</strong> (69,832), and 64.5% are engaged (126,888). The 14-point gap is <strong>27,154 sessions</strong> that view a single page but stay longer than 10 seconds or add to cart. Which figure a downstream claim cites materially changes the story, so both are carried throughout. Note also that the GA4-bounce cart rate is necessarily 0% — triggering a cart is one of the engagement tests — so reporting it as evidence that “bounced visitors don’t convert” would be circular.</p>
<p><strong>Table 2</strong></p>
<p><em>Bounce, Engagement, and Cart Rates by Definition</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Measure</th>
<th style="text-align: left;">Rule</th>
<th style="text-align: right;">Sessions</th>
<th style="text-align: right;">% of all</th>
<th style="text-align: right;">Cart rate within group</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Single-page (UA) bounce</td>
<td style="text-align: left;">exactly 1 page view</td>
<td style="text-align: right;">96,986</td>
<td style="text-align: right;">49.3</td>
<td style="text-align: right;">28%</td>
</tr>
<tr class="even">
<td style="text-align: left;">GA4 bounce</td>
<td style="text-align: left;">fails all 3 engagement tests</td>
<td style="text-align: right;">69,832</td>
<td style="text-align: right;">35.5</td>
<td style="text-align: right;">0% (by definition)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GA4 engaged</td>
<td style="text-align: left;">passes ≥ 1 engagement test</td>
<td style="text-align: right;">126,888</td>
<td style="text-align: right;">64.5</td>
<td style="text-align: right;">72%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Any add-to-cart</td>
<td style="text-align: left;">≥ 1 cart event</td>
<td style="text-align: right;">91,302</td>
<td style="text-align: right;">46.4</td>
<td style="text-align: right;">—</td>
</tr>
</tbody>
</table>
<p><em>Note.</em> GA4 engaged and GA4 bounce are exact complements. 27,154 sessions are UA-bounce but GA4-engaged (one page, but stayed 10 s or carted).</p>
<p><strong>Figure 5</strong></p>
<p><em>Three Bounce and Engagement Definitions</em></p>
<p><img src="assets/fig5_bounce_definitions.png" class="img-fluid" alt="Horizontal bars: single-page (UA) bounce 49.3% (96,986); GA4 bounce 35.5% (69,832); GA4 engaged 64.5% (126,888). A note says 27,154 sessions view one page but stay over 10 seconds or add to cart."></p>
<p><em>Note.</em> GA4 engagement and GA4 bounce are exact complements; UA bounce is a separate, stricter cut.</p>
</section>
<section id="temporal-behaviour-flat-volume-an-evening-engagement-peak-one-artefact" class="level3">
<h3 class="anchored" data-anchor-id="temporal-behaviour-flat-volume-an-evening-engagement-peak-one-artefact">Temporal behaviour: flat volume, an evening engagement peak, one artefact</h3>
<p>Within the day, session volume is roughly constant from 6am to 10pm and low overnight. <strong>Mean engagement score, however, is not constant</strong>: it rises through the day to a <strong>peak around 9pm (1.89)</strong> and is <em>lowest</em> overnight and at 11pm (1.43) (Figure 6). This is the opposite of the source notebook’s claim that “early-morning off-peak visitors engage more deeply” — the data shows early-morning engagement slightly <em>below</em> the daytime average and the genuine peak in the evening. Any “target the off-peak high-intent audience” recommendation built on the original reading is not supported.</p>
<p>Zooming out to the day level, page-view volume is <strong>flat at roughly 2,700 per day</strong> across the five months, with <strong>no holiday ramp and no weekly cycle</strong> — further evidence of a panel rather than a seasonally responsive consumer audience — bar a single anomaly: <strong>14 September 2017 records 42,788 page views, 16× the baseline</strong> (Figure 7). This is a data-ingestion artefact (timestamps that could not be resolved bulk-assigned to one date) and is excluded from any trend reading.</p>
<p><strong>Figure 6</strong></p>
<p><em>Session Volume and Mean Engagement by Hour of Day</em></p>
<p><img src="assets/fig6_hour_of_day.png" class="img-fluid" alt="Bars of session volume by hour (near zero from midnight to 5am, roughly flat around 10,000 from 6am to 10pm) with an overlaid line of mean engagement score. The engagement line sits near 1.5 overnight, drifts up through the day, rises steeply after 6pm to a peak of 1.89 at 9pm, then drops to 1.43 at 11pm."></p>
<p><em>Note.</em> Left axis: session volume. Right axis: mean engagement score (1.3–2.0).</p>
<p><strong>Figure 7</strong></p>
<p><em>Daily Page-View Volume, September 2017 – January 2018</em></p>
<p><img src="assets/fig7_ingestion_spike.png" class="img-fluid" alt="Line of page-views per day — a single enormous spike to 42,788 on 14 September 2017, then a dead-flat line at about 2,700 per day for the rest of the window with no visible trend or seasonality."></p>
<p><em>Note.</em> The 14 September spike is 16× the ~2,721/day median and is a data-ingestion artefact.</p>
</section>
<section id="correlation-structure" class="level3">
<h3 class="anchored" data-anchor-id="correlation-structure">Correlation structure</h3>
<p>Across ten session features (Figure 8), the strong correlations are structural rather than informative. <strong><code>engagement_score</code> correlates with <code>page_views</code> at 0.98 and with <code>key_event_count</code> at 0.83 — because those are its formula inputs</strong>; it is a restatement, not an independent signal. <code>duration_minutes</code> correlates with <code>page_views</code> at 0.71 (longer sessions see more pages). The one behaviourally interesting result is a null: <strong><code>ip_freq</code> correlates with every behavioural feature at |r| ≤ 0.08</strong> — how often a visitor’s IP appears does <em>not</em> predict how they behave in any given session. Visit frequency and engagement intensity are independent in this panel.</p>
<p><strong>Figure 8</strong></p>
<p><em>Session-Feature Correlation Matrix</em></p>
<p><img src="assets/fig8_correlation_matrix.png" class="img-fluid" alt="Correlation heatmap of ten session features. A dark red block links page views, unique URL actions, unique products, cart events, duration, and engagement score (r 0.7 to 0.98). The IP-frequency row and the repeat-visitor row are near white (all |r| below 0.1). Session hour is near zero against everything."></p>
<p><em>Note.</em> The engagement-score row is dark by construction; treat it as a summary, not a predictor.</p>
</section>
<section id="browse-versus-purchase" class="level3">
<h3 class="anchored" data-anchor-id="browse-versus-purchase">Browse versus purchase</h3>
<p>For the 36 products present in both the access log and the order record during the overlap window, log units sold regresses on log page views with <strong>r = 0.61</strong> — a moderate, positive alignment, not a tight one (Figure 9). The most-browsed products are generally among the better sellers, but the scatter is wide: one product draws ~13,000 views and sells four units in the window; another draws ~6,000 views and sells ~1,000. Those gaps — high browse with weak conversion, or the reverse — are the catalogue-optimisation targets the data points to, though with only 36 matched products and a five-month window the individual estimates are noisy.</p>
<p><strong>Figure 9</strong></p>
<p><em>Product Page-Views Versus Units Sold (overlap window, 36 products)</em></p>
<p><img src="assets/fig9_browse_vs_purchase.png" class="img-fluid" alt="Log-log scatter of units sold against product page-views for 36 products. Points rise from bottom-left to top-right around a dashed fit line but with wide vertical scatter; a high-browse high-sales point (a neoprene life vest) sits above the line and a moderate-browse very-low-sales point (an air mattress) sits well below it. Log-log r = 0.61."></p>
<p><em>Note.</em> Overlap window only (1 September 2017 – 31 January 2018); canonical-product-name join.</p>
</section>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<section id="principal-findings" class="level3">
<h3 class="anchored" data-anchor-id="principal-findings">Principal findings</h3>
<p>Four results define this dataset. First, <strong>it is a panel</strong> — 3,340 IPs, 15 first-time sessions — so every rate here describes catalogue-familiar repeat visitors and none of them is a cold-traffic benchmark. Second, <strong>the funnel has one measurable step</strong>, browse → cart at <strong>46.4%</strong>, because the log is product-pages only. Third, <strong>behaviour is bimodal</strong> — bounce in under a minute (51%) or stay 15–60 minutes (27%), and 82.7% see three pages or fewer — so the site’s leverage is concentrated in the first two or three product pages. Fourth, <strong>bounce is 49.3% or 35.5% depending on the definition</strong>, and the two should never be conflated.</p>
</section>
<section id="the-mechanism-worth-naming" class="level3">
<h3 class="anchored" data-anchor-id="the-mechanism-worth-naming">The mechanism worth naming</h3>
<p>The 46.4% cart rate and the 99.99% repeat-visitor rate are the same fact seen twice. An audience that returns 59 times in five months is not deciding whether to shop here; it is arriving with intent, going to a known product, and acting. That is why nearly half of one-page sessions still end in a cart, and why engagement rises in the evening (unhurried browsing) rather than in the transactional daytime peak. It also means the most actionable lever is not “convert more visitors” — this audience already converts — but the <strong>first-product-page experience</strong>, since 82.7% of sessions never get past page three and the median session is a single minute.</p>
</section>
<section id="limitations" class="level3">
<h3 class="anchored" data-anchor-id="limitations">Limitations</h3>
<p>The analysis is descriptive; no relationship is shown to be causal. The visitor base is a bounded panel of 3,340 IPs — findings do not generalise to open consumer traffic, and any model trained here learns this panel’s behaviour. The access log has no homepage, search, or account traffic, so early-funnel behaviour is unobservable. <code>engagement_score</code> is a deterministic function of three other features and should be treated as a summary, not an independent variable. The GA4-bounce cart rate is 0% by definition, not by observation. The 14 September spike is excluded from trend reading but retained in the aggregate session counts. The browse-versus-purchase result rests on 36 matched products over five months and its per-product estimates are noisy. <code>duration_minutes</code> cannot distinguish active reading from an idle browser tab.</p>
</section>
<section id="modelling-targets" class="level3">
<h3 class="anchored" data-anchor-id="modelling-targets">Modelling targets</h3>
<p>A viability scan of 20 candidate session-grain targets ranks <strong><code>bounce_session_ua</code></strong> highest (score 100) — a near-exact 50.7/49.3 class balance makes it the cleanest binary target. <strong><code>has_add_to_cart</code></strong> scores 97 (53.6/46.4 balance) and is the most commercially meaningful. <code>duration_bucket</code>, <code>page_depth_bucket</code>, and <code>session_dow</code> score 98 as multi-class targets. <code>is_engaged_session_ga4</code> / <code>bounce_session_ga4</code> score 93, penalised only by their 64.5/35.5 split. Regression targets — <code>engagement_score</code>, <code>page_views</code>, <code>duration_minutes</code> — score 76, needing a <code>log1p</code> transform (which brings duration skew from +2.5 to +0.4) and removal of the redundant identical columns. <code>is_repeat_visitor</code> is excluded (99.99% imbalance).</p>
</section>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion">Conclusion</h3>
<p>This is a clean, complete session dataset describing a specific high-frequency visitor panel. Its headline metric — a 46.4% session-to-cart rate — is genuine but bounded: it is what a familiar, returning audience does, not what the site converts from scratch. The lever the data points to is the first product page, because most visits are a single minute and three pages. The companion segmentation and modelling studies build on the same Gold layer.</p>
</section>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<p>Constante, F., Silva, F., &amp; Pereira, A. (2019). <em>DataCo smart supply chain for big data analysis</em> (Version 5) [Data set]. Mendeley Data. https://doi.org/10.17632/8gx2fvg2k6.5</p>
<p>Google. (2023). <em>[GA4] Engaged sessions and engagement rate.</em> Google Analytics Help.</p>
<p>Harris, C. R., Millman, K. J., van der Walt, S. J., Gommers, R., Virtanen, P., Cournapeau, D., Wieser, E., Taylor, J., Berg, S., Smith, N. J., Kern, R., Picus, M., Hoyer, S., van Kerkwijk, M. H., Brett, M., Haldane, A., del Río, J. F., Wiebe, M., Peterson, P., … Oliphant, T. E. (2020). Array programming with NumPy. <em>Nature, 585</em>, 357–362. https://doi.org/10.1038/s41586-020-2649-2</p>
<p>The pandas development team. (2020). <em>pandas-dev/pandas: Pandas</em> (Version latest) [Computer software]. Zenodo. https://doi.org/10.5281/zenodo.3509134</p>
<hr>
<p><em>Analysis and figures by the author. A descriptive clickstream study of one dataset; the visitor base is a bounded panel and no rate here is a general benchmark.</em></p>


<div id="contact" class="connect-section" style="text-align: center; padding: 50px 20px; background: #f9f9f9; border-radius: 15px; border: 1px solid #eaeaea; margin-top: 40px;">
<h3 style="color: #2c3e50; font-weight: 700; margin-bottom: 15px; border: none;" class="anchored">Let's Collaborate</h3>
<p style="color: #666; max-width: 650px; margin: 0 auto 30px auto; font-size: 1.05rem; line-height: 1.6;">Available for high-impact <strong>Business Intelligence, Power BI Engineering, and Advanced Data Analytics</strong> projects. Connect with me or hire me directly through the platforms below.</p>
<div style="display: flex; flex-wrap: wrap; justify-content: center; gap: 12px;">
<a href="https://www.linkedin.com/in/mkmuneer" class="btn btn-primary" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; text-decoration: none;"><i class="bi bi-linkedin"></i> LinkedIn</a>
<a href="https://github.com/mkhanmuneer" class="btn btn-dark" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; text-decoration: none;"><i class="bi bi-github"></i> GitHub</a>
<a href="https://www.kaggle.com/muhammadkhanmuneer" class="btn btn-info" target="_blank" rel="noopener" style="color: white; padding: 12px 25px; min-width: 150px; text-decoration: none;"><i class="bi bi-graph-up"></i> Kaggle</a>
<a href="https://www.upwork.com/freelancers/~018de8553286a1d00c" class="btn btn-outline-success" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; border-width: 2px; font-weight: 600; text-decoration: none;"><i class="bi bi-briefcase"></i> Upwork</a>
<a href="https://www.fiverr.com/neuronvision" class="btn btn-outline-success" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; border-width: 2px; font-weight: 600; text-decoration: none;"><i class="bi bi-lightning-charge"></i> Fiverr</a>
</div>
</div>

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/mkhanmuneer\.github\.io\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 Muhammad Khan Muneer</p>
</div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://www.upwork.com/freelancers/~018de8553286a1d00c">
<p>Hire on Upwork</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="https://www.fiverr.com/neuronvision">
<p>Hire on Fiverr</p>
</a>
  </li>  
</ul>
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mkhanmuneer">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/mkmuneer">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>