<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Muhammad Khan Muneer">
<meta name="keywords" content="delay prediction, XGBoost, operational risk score, data leakage audit, multicollinearity, variance inflation factor, probability calibration, threshold analysis, precision recall trade-off, risk segmentation, capacity-aware triage, logistics analytics, Python, scikit-learn">
<meta name="description" content="A supervised modelling pipeline over a three-year, 180,519-order logistics dataset. Two engines: an XGBoost classifier for will this order be late? and an XGBoost regressor for how long will it take?, trained on the same 22-feature, leakage-audited matrix. Honest performance: the classifier reaches ROC-AUC 0.872 on a 36,104-order held-out set (accuracy 0.79, precision 0.85, recall 0.75 at the default threshold); the regressor reaches MAE 0.71 days, R² 0.68 on calendar days to ship. One number: the two outputs blend with historical destination, mode, and category late-rates into a 0–100 operational risk score. The triage contribution: fixed score thresholds place 25–37% of the portfolio in the Critical band; percentile and capacity-aware strategies hold it at a chosen 15% — the alert queue is sized to the control tower, not to the score’s shape. Reproduced entirely from persisted model artefacts.">

<title>A Dual-Engine Delay-Risk Model for 180,519 Shipments, and a Triage Layer Sized to Team Capacity – Muhammad Khan Muneer</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-4d9afe2b8d18ee9fa5d0d57b5ed4214d.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-5af9b5ab1fa0c387551d40c1aacb317e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-ca0cfe78a00f84493d894d8af57a3a20.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-5af9b5ab1fa0c387551d40c1aacb317e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": true,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<link rel="stylesheet" href="../../styles/custom.css">
<meta property="og:title" content="Muhammad Khan Muneer — Data Science &amp; BI Portfolio">
<meta property="og:description" content="Engineering ML-driven analytics and automated decision systems.">
<meta property="og:image" content="https://mkhanmuneer.github.io/projects/operational-risk-scoring-dual-engine-delay-prediction-and-capacity-sized-triage/assets/fig4_feature_importance.png">
<meta property="og:site_name" content="M. Khan Muneer Portfolio">
<meta property="og:image:alt" content="Two horizontal bar charts. Classification: shipping mode 0.72, then order hour, destination city, store city, store state and further geography all near 0.014-0.022. Regression: shipping mode 0.59, then destination city, season, destination state, week of year and further terms all near 0.02-0.04.">
<meta property="og:image:height" content="982">
<meta property="og:image:width" content="2072">
<meta name="twitter:title" content="A Dual-Engine Delay-Risk Model for 180,519 Shipments, and a Triage Layer Sized to Team Capacity – Muhammad Khan Muneer">
<meta name="twitter:description" content="A supervised modelling pipeline over a three-year, 180,519-order logistics dataset. Two engines: an XGBoost classifier for will this order be late? and an XGBoost regressor for how long will it take?, trained on the same 22-feature, leakage-audited matrix. Honest performance: the classifier reaches ROC-AUC 0.872 on a 36,104-order held-out set (accuracy 0.79, precision 0.85, recall 0.75 at the default threshold); the regressor reaches MAE 0.71 days, R² 0.68 on calendar days to ship. One number: the two outputs blend with historical destination, mode, and category late-rates into a 0–100 operational risk score. The triage contribution: fixed score thresholds place 25–37% of the portfolio in the Critical band; percentile and capacity-aware strategies hold it at a chosen 15% — the alert queue is sized to the control tower, not to the score’s shape. Reproduced entirely from persisted model artefacts.">
<meta name="twitter:image" content="https://mkhanmuneer.github.io/projects/operational-risk-scoring-dual-engine-delay-prediction-and-capacity-sized-triage/assets/fig4_feature_importance.png">
<meta name="twitter:creator" content="@iMKhanMuneer">
<meta name="twitter:site" content="@iMKhanMuneer">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image:alt" content="Two horizontal bar charts. Classification: shipping mode 0.72, then order hour, destination city, store city, store state and further geography all near 0.014-0.022. Regression: shipping mode 0.59, then destination city, season, destination state, week of year and further terms all near 0.02-0.04.">
<meta name="twitter:image-height" content="982">
<meta name="twitter:image-width" content="2072">
</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../index.html#featured-projects"> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/mkmuneer"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mkhanmuneer"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://x.com/iMKhanMuneer"> <i class="bi bi-twitter-x" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.kaggle.com/muhammadkhanmuneer"> <i class="bi bi-graph-up" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../index.html#contact"> 
<span class="menu-text">Contact</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract">Abstract</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#method" id="toc-method" class="nav-link" data-scroll-target="#method">Method</a>
  <ul class="collapse">
  <li><a href="#data-and-feature-engineering" id="toc-data-and-feature-engineering" class="nav-link" data-scroll-target="#data-and-feature-engineering">Data and feature engineering</a></li>
  <li><a href="#leakage-audit-and-dimensional-pruning" id="toc-leakage-audit-and-dimensional-pruning" class="nav-link" data-scroll-target="#leakage-audit-and-dimensional-pruning">Leakage audit and dimensional pruning</a></li>
  <li><a href="#encoding-splits-and-the-two-engines" id="toc-encoding-splits-and-the-two-engines" class="nav-link" data-scroll-target="#encoding-splits-and-the-two-engines">Encoding, splits, and the two engines</a></li>
  <li><a href="#the-composite-risk-score" id="toc-the-composite-risk-score" class="nav-link" data-scroll-target="#the-composite-risk-score">The composite risk score</a></li>
  <li><a href="#segmentation-strategies" id="toc-segmentation-strategies" class="nav-link" data-scroll-target="#segmentation-strategies">Segmentation strategies</a></li>
  <li><a href="#software" id="toc-software" class="nav-link" data-scroll-target="#software">Software</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#classification-roc-auc-0.872-on-the-held-out-set" id="toc-classification-roc-auc-0.872-on-the-held-out-set" class="nav-link" data-scroll-target="#classification-roc-auc-0.872-on-the-held-out-set">Classification: ROC-AUC 0.872 on the held-out set</a></li>
  <li><a href="#a-threshold-menu-not-a-single-operating-point" id="toc-a-threshold-menu-not-a-single-operating-point" class="nav-link" data-scroll-target="#a-threshold-menu-not-a-single-operating-point">A threshold menu, not a single operating point</a></li>
  <li><a href="#one-driver-dominates-both-engines" id="toc-one-driver-dominates-both-engines" class="nav-link" data-scroll-target="#one-driver-dominates-both-engines">One driver dominates both engines</a></li>
  <li><a href="#regression-within-a-day-but-conservative-on-the-tails" id="toc-regression-within-a-day-but-conservative-on-the-tails" class="nav-link" data-scroll-target="#regression-within-a-day-but-conservative-on-the-tails">Regression: within a day, but conservative on the tails</a></li>
  <li><a href="#the-composite-score-bimodal-but-balanced" id="toc-the-composite-score-bimodal-but-balanced" class="nav-link" data-scroll-target="#the-composite-score-bimodal-but-balanced">The composite score: bimodal but balanced</a></li>
  <li><a href="#the-score-tracks-shipping-mode" id="toc-the-score-tracks-shipping-mode" class="nav-link" data-scroll-target="#the-score-tracks-shipping-mode">The score tracks shipping mode</a></li>
  <li><a href="#triage-sizing-the-critical-queue-to-the-team" id="toc-triage-sizing-the-critical-queue-to-the-team" class="nav-link" data-scroll-target="#triage-sizing-the-critical-queue-to-the-team">Triage: sizing the Critical queue to the team</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a>
  <ul class="collapse">
  <li><a href="#principal-findings" id="toc-principal-findings" class="nav-link" data-scroll-target="#principal-findings">Principal findings</a></li>
  <li><a href="#the-honesty-trade-off-and-what-it-cost" id="toc-the-honesty-trade-off-and-what-it-cost" class="nav-link" data-scroll-target="#the-honesty-trade-off-and-what-it-cost">The honesty trade-off, and what it cost</a></li>
  <li><a href="#the-score-is-a-probability-band" id="toc-the-score-is-a-probability-band" class="nav-link" data-scroll-target="#the-score-is-a-probability-band">The score is a probability band</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations">Limitations</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">A Dual-Engine Delay-Risk Model for 180,519 Shipments, and a Triage Layer Sized to Team Capacity</h1>
<p class="subtitle lead">An XGBoost classifier and regressor scored against a leakage-controlled feature set, blended into a 0–100 operational risk index — with an honest ROC-AUC of 0.87, and a segmentation that caps the Critical alert queue at a fixed share of the portfolio instead of an arbitrary score cut-off.</p>
  <div class="quarto-categories">
    <div class="quarto-category">Machine Learning</div>
    <div class="quarto-category">Classification</div>
    <div class="quarto-category">Regression</div>
    <div class="quarto-category">Gradient Boosting</div>
    <div class="quarto-category">Model Evaluation</div>
    <div class="quarto-category">Model Calibration</div>
    <div class="quarto-category">Data Leakage</div>
    <div class="quarto-category">Multicollinearity</div>
    <div class="quarto-category">Feature Engineering</div>
    <div class="quarto-category">Risk Scoring</div>
    <div class="quarto-category">Supply Chain</div>
    <div class="quarto-category">Python</div>
  </div>
  </div>

<div>
  <div class="description">
    <p>A supervised modelling pipeline over a three-year, 180,519-order logistics dataset. <strong>Two engines:</strong> an XGBoost classifier for <em>will this order be late?</em> and an XGBoost regressor for <em>how long will it take?</em>, trained on the same 22-feature, leakage-audited matrix. <strong>Honest performance:</strong> the classifier reaches <strong>ROC-AUC 0.872</strong> on a 36,104-order held-out set (accuracy 0.79, precision 0.85, recall 0.75 at the default threshold); the regressor reaches <strong>MAE 0.71 days, R² 0.68</strong> on calendar days to ship. <strong>One number:</strong> the two outputs blend with historical destination, mode, and category late-rates into a 0–100 operational risk score. <strong>The triage contribution:</strong> fixed score thresholds place 25–37% of the portfolio in the Critical band; percentile and capacity-aware strategies hold it at a chosen 15% — the alert queue is sized to the control tower, not to the score’s shape. Reproduced entirely from persisted model artefacts.</p>
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Muhammad Khan Muneer </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 2025</p>
    </div>
  </div>
  
    
  </div>
  

<div>
  <div class="keywords">
    <div class="block-title">Keywords</div>
    <p>delay prediction, XGBoost, operational risk score, data leakage audit, multicollinearity, variance inflation factor, probability calibration, threshold analysis, precision recall trade-off, risk segmentation, capacity-aware triage, logistics analytics, Python, scikit-learn</p>
  </div>
</div>

</header>


<section id="abstract" class="level2">
<h2 class="anchored" data-anchor-id="abstract">Abstract</h2>
<p>This study builds a supervised model that assigns every order in a three-year, 180,519-record e-commerce logistics dataset a bounded operational risk score, so a control tower can intervene before a shipment is late rather than after. The architecture is two engines on a shared feature set: an XGBoost <strong>classifier</strong> for the probability of a late delivery and an XGBoost <strong>regressor</strong> for the number of calendar days a shipment will take. The feature matrix was reduced from 59 joined columns to 22 through a leakage audit (ten post-shipment fields removed), an identifier sweep, and a variance-inflation scan that dropped five collinear columns — including the scheduled-shipping-window field, a near-linear shadow of the actual duration. On a stratified 36,104-order held-out set the classifier reaches <strong>ROC-AUC 0.872</strong> (accuracy 0.791, precision 0.848, recall 0.753 at the 0.50 threshold) and the regressor reaches <strong>MAE 0.71 days, RMSE 0.94 days, R² 0.681</strong> — real decision-support performance, and well below the inflated figures a leaked feature set would produce. Four independent attribution methods across both engines converge on the same dominant driver: <strong>shipping mode</strong> carries 0.72 of the classifier’s gain importance and 0.59 of the regressor’s, an order of magnitude above any other feature. The two model outputs are blended with historical destination, shipping-mode, and category late-rates (weights 0.60 / 0.20 / 0.10 / 0.10) and min-max scaled to a 0–100 index. The study’s operational contribution is the triage layer: fixed score thresholds place <strong>25–37% of the portfolio in the Critical band</strong>, which no control tower can action; percentile and capacity-aware strategies hold the Critical share at a <strong>chosen 15%</strong>, sizing the alert queue to the team rather than to the score distribution’s shape. Every result is reproduced from persisted model artefacts.</p>
<p><em>Keywords:</em> delay prediction, XGBoost, operational risk score, data-leakage audit, probability calibration, threshold analysis, capacity-aware triage</p>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>A logistics control tower needs to answer two questions about every order the moment it is placed: <strong>will it be late</strong>, and <strong>how long will it take</strong>. A binary flag without a duration cannot prioritise a five-day delay over a one-day delay; a duration without a probability cannot tell an operator whether a prediction is worth acting on. This study builds both answers as separate supervised models over the same feature set, then fuses them into a single 0–100 index a control tower can rank orders by.</p>
<p>Two design commitments shape the work. The first is <strong>leakage discipline</strong>: in a logistics dataset it is trivially easy to “predict” lateness from fields that are only populated after a shipment moves — actual transit days, delivery-performance labels, the dataset’s own post-hoc risk flag. A model trained on those fields scores near-perfectly and is worthless in production. The pipeline removes every post-shipment field and every row identifier before training, and the resulting performance figures are lower and honest. The second is <strong>operational realism in the triage layer</strong>: converting a continuous score into Low / Elevated / Critical bands with fixed cut-offs produces a Critical band whose size is an accident of the score distribution. A control tower has a fixed number of analysts; the segmentation should target a fixed <em>share</em> of orders, and this study compares five ways of doing that.</p>
</section>
<section id="method" class="level2">
<h2 class="anchored" data-anchor-id="method">Method</h2>
<section id="data-and-feature-engineering" class="level3">
<h3 class="anchored" data-anchor-id="data-and-feature-engineering">Data and feature engineering</h3>
<p>One fact table at order-item grain, <code>fact_logistics_gold</code> (180,519 rows), joined to a date dimension on a surrogate key to add fiscal-period, weekday, business-day, and season fields. The upstream Gold layer had already engineered the two modelling targets from fulfilment timestamps — <code>is_late_actual</code> (binary; <strong>54.7%</strong> of order-items are late) and <code>calendar_days_to_ship</code> (integer, 0–6 days) — along with a high-value-order flag (net sales ≥ 2× median), a profit-margin ratio, and order-hour fields. The joined frame carried 59 columns.</p>
</section>
<section id="leakage-audit-and-dimensional-pruning" class="level3">
<h3 class="anchored" data-anchor-id="leakage-audit-and-dimensional-pruning">Leakage audit and dimensional pruning</h3>
<p>The feature matrix was cut from 59 columns to <strong>22</strong> in four passes (Table 1). Ten <strong>post-shipment leakage</strong> fields were removed (<code>shipping_delay_days</code>, <code>shipping_date_key</code>, <code>shipping_hour</code>, <code>shipping_time</code>, <code>delivery_performance_type</code>, <code>late_delivery_risk</code>, <code>system_prediction_gap</code>, <code>order_profit_per_order</code>, <code>order_item_profit_ratio</code>, and the regression target for the classifier). Six <strong>redundant</strong> fields (duplicate date keys, the raw product name superseded by a canonical form, a price-tier alias). Eleven <strong>low-signal</strong> fields confirmed near-zero on a mutual-information scan against the target (<code>order_time</code>, several post-fulfilment monetary fields, <code>is_peak_logistics</code>, <code>is_month_end</code>/<code>is_month_start</code>, and category dimensions already absorbed by stronger features). Four <strong>row identifiers</strong> (<code>order_id</code>, <code>order_item_id</code>, <code>customer_id</code>, <code>department_id</code>) — these scored <em>highest</em> on mutual information precisely because a tree can memorise them, which is the failure mode the scan exists to catch. Finally a <strong>variance-inflation</strong> scan flagged five columns above VIF 10: <code>month</code> and <code>quarter</code> (collinear with <code>week_of_year</code>), <code>product_price</code> (with <code>net_sales_amount</code>), <code>store_country</code> (with <code>store_latitude</code>), and <code>shipping_days_scheduled</code> — a near-linear shadow of actual transit that, when retained in an earlier iteration, ranked among the top three drivers and masked the true importance of shipping mode.</p>
<p><strong>Table 1</strong></p>
<p><em>Feature-Matrix Reduction (59 joined columns → 22 modelling features)</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Removal pass</th>
<th style="text-align: right;">Count</th>
<th style="text-align: left;">Rationale</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Post-shipment leakage</td>
<td style="text-align: right;">10</td>
<td style="text-align: left;">Fields populated only after a shipment moves; would encode the answer</td>
</tr>
<tr class="even">
<td style="text-align: left;">Redundant</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">Duplicate keys, superseded names, tier aliases</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Low mutual information</td>
<td style="text-align: right;">11</td>
<td style="text-align: left;">Near-zero signal against the target on an MI scan</td>
</tr>
<tr class="even">
<td style="text-align: left;">Row identifiers</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">Unique per row; enable memorisation (highest MI, for that reason)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Multicollinearity (VIF &gt; 10)</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">Near-linear shadow of a feature already in the matrix</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Retained</strong></td>
<td style="text-align: right;"><strong>22</strong></td>
<td style="text-align: left;">Shipping mode, geography (store + destination), order hour, calendar, order quantity, high-value flag</td>
</tr>
</tbody>
</table>
<p><em>Note.</em> Passes overlap slightly on a few columns; the net matrix is 22 features. The five VIF drops include <code>shipping_days_scheduled</code>, whose removal is revisited in the Discussion.</p>
</section>
<section id="encoding-splits-and-the-two-engines" class="level3">
<h3 class="anchored" data-anchor-id="encoding-splits-and-the-two-engines">Encoding, splits, and the two engines</h3>
<p>Five high-cardinality fields (<code>destination_city</code>, <code>destination_country</code>, <code>destination_state</code>, <code>store_city</code>, <code>product_name_canonical</code>) were <strong>target-encoded</strong> to a single numeric column each; the remaining categoricals were <strong>ordinal-encoded</strong>. The classification data was split 80/20 <strong>stratified</strong> on the target — 144,415 training rows, 36,104 test — preserving the 54.7% late rate in both. The regression used the same feature set against <code>calendar_days_to_ship</code>.</p>
<p>Both engines are <strong>XGBoost</strong>. The classifier’s hyperparameters were selected by a <strong>50-iteration randomised search over a 3-fold cross-validation</strong>, optimising ROC-AUC across eight parameters (capacity, learning rate, subsampling, and explicit regularisation); the search ran 4.8 minutes and the fitted search object was persisted so every downstream prediction reloads rather than re-fits. The cross-validated search score was 0.968; the <strong>held-out test-set ROC-AUC is 0.872</strong> (Results), and the test-set figure is the one reported throughout — the gap is the usual optimism of a cross-validated tuning score relative to a true hold-out.</p>
</section>
<section id="the-composite-risk-score" class="level3">
<h3 class="anchored" data-anchor-id="the-composite-risk-score">The composite risk score</h3>
<p>For every order in the full 180,519-record portfolio the classifier’s <code>p_delay</code> and the regressor’s <code>expected_delay_days</code> were generated by reloading the persisted models. Three historical baselines were computed as empirical late-rates by destination country, by shipping mode, and by product category. The <strong>operational risk score</strong> blends them:</p>
<blockquote class="blockquote">
<p>raw = 0.60 · p_delay + 0.20 · destination late-rate + 0.10 · shipping-mode late-rate + 0.10 · category late-rate</p>
</blockquote>
<p>min-max scaled to 0–100. The regressor’s duration estimate is exported alongside the score as an independent magnitude signal, <strong>not folded into the blend</strong> — so a consumer reads probability, expected duration, and the unified index side by side.</p>
</section>
<section id="segmentation-strategies" class="level3">
<h3 class="anchored" data-anchor-id="segmentation-strategies">Segmentation strategies</h3>
<p>Five ways of cutting the continuous score into Low / Elevated / Critical bands were evaluated: two <strong>fixed-threshold</strong> schemes ([0, 40, 75] and [0, 60, 85]), a <strong>quantile</strong> scheme (the score’s own 60th and 85th percentiles), a <strong>rolling-percentile</strong> scheme (60th/85th percentiles on a trailing 3,000-order window, for drift resistance), and a <strong>capacity-aware</strong> scheme that sets the Critical and Elevated shares first (top 15%, next 20%) and solves for the cut-offs.</p>
</section>
<section id="software" class="level3">
<h3 class="anchored" data-anchor-id="software">Software</h3>
<p>Python 3.10 with <code>xgboost</code>, <code>scikit-learn</code> (<code>RandomizedSearchCV</code>, metrics, <code>calibration_curve</code>), <code>category_encoders</code> (<code>TargetEncoder</code>), <code>statsmodels</code> (VIF), <code>shap</code>, <code>pandas</code>, <code>numpy</code>, and <code>matplotlib</code>. <code>random_state = 42</code> throughout.</p>
</section>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<section id="classification-roc-auc-0.872-on-the-held-out-set" class="level3">
<h3 class="anchored" data-anchor-id="classification-roc-auc-0.872-on-the-held-out-set">Classification: ROC-AUC 0.872 on the held-out set</h3>
<p>On the 36,104-order test set the tuned classifier reaches <strong>ROC-AUC 0.872</strong> and average precision 0.880 (Figure 1). At the default 0.50 threshold it scores <strong>accuracy 0.791, precision 0.848, recall 0.753, F1 0.798</strong> (Table 2); the confusion matrix is 14,864 true positives, 4,885 false negatives, 2,660 false positives, 13,695 true negatives (Figure 2). The probabilities are <strong>imperfectly calibrated</strong>: the model runs under-confident through the low-to-mid range (orders it scores at 0.08 are late 22% of the time; orders it scores at 0.35 are late 52% of the time) and there is a pocket of over-confidence at the very top — a decile the model scores at ≈1.0 is late only 76% of the time, an artefact traced to Same-Day shipments in the Discussion. This is a genuine decision-support model, not the near-perfect classifier a leaked feature set produces.</p>
<p><strong>Figure 1</strong></p>
<p><em>Classifier Discrimination on the Held-Out Test Set</em></p>
<p><img src="assets/fig1_roc_pr.png" class="img-fluid" alt="Two panels. Left: ROC curve for the XGBoost classifier, AUC 0.872, bowed above the chance diagonal. Right: precision-recall curve, average precision 0.880, well above the 0.55 prevalence line."></p>
<p><em>Note.</em> n = 36,104. AUC = area under the ROC curve; AP = average precision.</p>
<p><strong>Figure 2</strong></p>
<p><em>Confusion Matrix and Reliability Curve (Threshold 0.50)</em></p>
<p><img src="assets/fig2_confusion_calibration.png" class="img-fluid" alt="Left: 2x2 confusion matrix — actual on-time predicted on-time 13,695; actual on-time predicted late 2,660; actual late predicted on-time 4,885; actual late predicted late 14,864. Right: reliability curve sitting above the diagonal through the low and mid range (under-confident), meeting it near 0.8, then dropping to 0.76 observed at the highest predicted-probability decile."></p>
<p><em>Note.</em> Reliability curve uses ten quantile bins.</p>
</section>
<section id="a-threshold-menu-not-a-single-operating-point" class="level3">
<h3 class="anchored" data-anchor-id="a-threshold-menu-not-a-single-operating-point">A threshold menu, not a single operating point</h3>
<p>Sweeping the decision threshold from 0.30 to 0.90 exposes the precision/recall trade-off as a tunable control (Figure 3, Table 2). <strong>Recall is highest at the lowest threshold</strong> — 0.838 at t = 0.30, flagging 57% of orders as late — the setting for SLA-critical flows where a missed delay costs more than an over-notification. <strong>Precision is highest at t = 0.90</strong> — 0.895, flagging only 34% of orders — the setting for expensive interventions like premium-shipping upgrades. <strong>F1 is also highest at t = 0.30 (0.821)</strong> and declines monotonically across the range, so there is no interior F1 peak to default to; the choice is genuinely a business one about the relative cost of the two error types.</p>
<p><strong>Figure 3</strong></p>
<p><em>Precision, Recall, F1, and Flag Volume Across Seven Thresholds</em></p>
<p><img src="assets/fig3_threshold_sweep.png" class="img-fluid" alt="Line chart against decision threshold 0.3 to 0.9. Precision rises from 0.80 to 0.90; recall falls from 0.84 to 0.55; F1 falls from 0.82 to 0.68. Grey bars show the share of test orders flagged late falling from 57% at t=0.3 to 34% at t=0.9."></p>
<p><em>Note.</em> All values on the 36,104-order test set.</p>
<p><strong>Table 2</strong></p>
<p><em>Classification Performance at the Default Threshold, and the Threshold Sweep</em></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Threshold</th>
<th style="text-align: right;">Precision</th>
<th style="text-align: right;">Recall</th>
<th style="text-align: right;">F1</th>
<th style="text-align: right;">Orders flagged late</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">0.30</td>
<td style="text-align: right;">0.803</td>
<td style="text-align: right;">0.838</td>
<td style="text-align: right;">0.821</td>
<td style="text-align: right;">57.1%</td>
</tr>
<tr class="even">
<td style="text-align: left;">0.40</td>
<td style="text-align: right;">0.828</td>
<td style="text-align: right;">0.794</td>
<td style="text-align: right;">0.810</td>
<td style="text-align: right;">52.4%</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>0.50</strong> (default)</td>
<td style="text-align: right;"><strong>0.848</strong></td>
<td style="text-align: right;"><strong>0.753</strong></td>
<td style="text-align: right;"><strong>0.798</strong></td>
<td style="text-align: right;">48.5%</td>
</tr>
<tr class="even">
<td style="text-align: left;">0.60</td>
<td style="text-align: right;">0.863</td>
<td style="text-align: right;">0.710</td>
<td style="text-align: right;">0.779</td>
<td style="text-align: right;">45.0%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">0.70</td>
<td style="text-align: right;">0.875</td>
<td style="text-align: right;">0.666</td>
<td style="text-align: right;">0.756</td>
<td style="text-align: right;">41.6%</td>
</tr>
<tr class="even">
<td style="text-align: left;">0.80</td>
<td style="text-align: right;">0.886</td>
<td style="text-align: right;">0.617</td>
<td style="text-align: right;">0.728</td>
<td style="text-align: right;">38.1%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">0.90</td>
<td style="text-align: right;">0.895</td>
<td style="text-align: right;">0.552</td>
<td style="text-align: right;">0.683</td>
<td style="text-align: right;">33.7%</td>
</tr>
</tbody>
</table>
<p><em>Note.</em> Accuracy at t = 0.50 is 0.791; ROC-AUC (threshold-independent) is 0.872; Brier score 0.155.</p>
</section>
<section id="one-driver-dominates-both-engines" class="level3">
<h3 class="anchored" data-anchor-id="one-driver-dominates-both-engines">One driver dominates both engines</h3>
<p>Gain-based feature importance puts <strong>shipping mode far ahead of everything else</strong> in both models — 0.72 of the classifier’s total gain, 0.59 of the regressor’s (Figure 4). Every other feature contributes between 0.01 and 0.04: order hour and a cluster of store- and destination-geography columns for the classifier; destination geography, season, and week-of-year for the regressor. The notebook’s SHAP analysis (not reproduced here) reports the same ranking from a second attribution method on both engines, so four independent views — classification gain, classification SHAP, regression gain, regression SHAP — agree on the same top features. That convergence is the evidence that the models learned real logistics structure: which carrier moves the order, where it is going, where it ships from, and when in the day it was placed.</p>
<p><strong>Figure 4</strong></p>
<p><em>Gain Importance — Classifier and Regressor</em></p>
<p><img src="assets/fig4_feature_importance.png" class="img-fluid" alt="Two horizontal bar charts. Classification: shipping mode 0.72, then order hour, destination city, store city, store state and further geography all near 0.014-0.022. Regression: shipping mode 0.59, then destination city, season, destination state, week of year and further terms all near 0.02-0.04."></p>
<p><em>Note.</em> Gain importance, normalised to sum to 1 within each engine.</p>
</section>
<section id="regression-within-a-day-but-conservative-on-the-tails" class="level3">
<h3 class="anchored" data-anchor-id="regression-within-a-day-but-conservative-on-the-tails">Regression: within a day, but conservative on the tails</h3>
<p>The duration regressor reaches <strong>MAE 0.71 days, RMSE 0.94 days, R² 0.681</strong> on the held-out set (Figure 5). The near-equal MAE and RMSE indicate a well-behaved error distribution with no catastrophic misses; <strong>71% of test orders are predicted within one day</strong> of the actual duration and the residuals are centred on zero. The model does <strong>compress the tails</strong> — orders that actually take 6 days are predicted at ≈4.6 on average, and orders that take 0 days are predicted at ≈0 but with a spread into negative values — which is expected for a bounded integer target with irreducible noise (weather, customs, last-mile congestion) that the pre-shipment features cannot see. Two-thirds of the variance explained from information available at order placement is a production-grade result for this problem.</p>
<p><strong>Figure 5</strong></p>
<p><em>Regression Fit on Calendar Days to Ship</em></p>
<p><img src="assets/fig5_regression_fit.png" class="img-fluid" alt="Left: box plots of predicted days by actual days (0, 2, 3, 4, 5, 6 — no orders take exactly 1 day). Medians track the diagonal in the middle but fall below it at actual=6 (median predicted ~4.6) and the actual=0 box straddles zero. Right: residual histogram, symmetric and centred on zero, most mass between minus 1 and plus 1 day."></p>
<p><em>Note.</em> n = 36,104. No order in the data ships in exactly 1 calendar day, hence the gap.</p>
</section>
<section id="the-composite-score-bimodal-but-balanced" class="level3">
<h3 class="anchored" data-anchor-id="the-composite-score-bimodal-but-balanced">The composite score: bimodal but balanced</h3>
<p>Blending the two engines with the historical baselines and scaling to 0–100 produces a score with <strong>mean 52.3 and median 48.4</strong> across the full portfolio (Figure 6). The distribution has <strong>two modes</strong> — near 18 and near 88 — inherited from the classifier’s probability output, which itself is concentrated at the extremes (28% of orders below P = 0.1, 34% above P = 0.9). But the two modes are close to balanced, so mean and median nearly coincide, and <strong>18% of orders fall in the 40–75 middle band</strong> — thinner than the modes, but not the empty gap a raw probability cut produces. The score-versus-duration panel confirms the design: the score is stratified by probability, not by predicted duration — a long expected shipping time on its own does not lift an order’s score.</p>
<p><strong>Figure 6</strong></p>
<p><em>Operational Risk Score — Distribution and Relationship to Predicted Duration</em></p>
<p><img src="assets/fig6_risk_score_distribution.png" class="img-fluid" alt="Left: histogram of the 0-100 operational risk score for 180,519 orders, two humps around 18 and 88 with a populated trough between 40 and 75; dashed lines mark mean 52.3 and median 48.4. Right: hexbin of score against expected shipping duration — horizontal bands of density at score ~18, ~78 and ~88 that do not slope with duration."></p>
<p><em>Note.</em> Score = min-max scaled blend of <code>p_delay</code> (0.60) and historical destination / mode / category late-rates (0.20 / 0.10 / 0.10).</p>
</section>
<section id="the-score-tracks-shipping-mode" class="level3">
<h3 class="anchored" data-anchor-id="the-score-tracks-shipping-mode">The score tracks shipping mode</h3>
<p>Aggregating the score by shipping mode makes its logic legible (Figure 7). <strong>First Class</strong> averages a score of <strong>90</strong> and is late on <strong>100%</strong> of its 27,814 orders — consistent with the companion OTIF diagnostic, which found First Class is promised a one-day window it never meets. <strong>Second Class</strong> averages 79 (actual late rate 80%). <strong>Standard Class</strong> averages 35 (actual 40%). <strong>Same Day</strong> averages <strong>44 despite being late on 0% of its orders</strong> — the score over-rates it, for the reason given next.</p>
<p><strong>Figure 7</strong></p>
<p><em>Mean Risk Score vs Actual Late Rate, by Shipping Mode</em></p>
<p><img src="assets/fig7_score_by_shipping_mode.png" class="img-fluid" alt="Paired bars for four shipping modes. Standard Class: score 35, actual late rate 40%. Same Day: score 44, actual late rate 0% (no orange bar). Second Class: score 79, actual 80%. First Class: score 90, actual 100%."></p>
<p><em>Note.</em> Actual late rate from <code>is_late_actual</code> in the Gold layer.</p>
</section>
<section id="triage-sizing-the-critical-queue-to-the-team" class="level3">
<h3 class="anchored" data-anchor-id="triage-sizing-the-critical-queue-to-the-team">Triage: sizing the Critical queue to the team</h3>
<p>Cutting the score into three bands with <strong>fixed thresholds</strong> produces a Critical share that is an artefact of the distribution (Figure 8, Table 3). The industry-standard [0, 40, 75] cut sends <strong>37%</strong> of the portfolio to Critical; the refined [0, 60, 85] cut — the one persisted on the scored table — sends <strong>25%</strong>. Both are far more than a fulfilment-supervisor team sized for this portfolio can action; escalating a quarter of all orders makes every escalation worthless within days. The <strong>percentile strategies</strong> solve this structurally: the quantile cut holds Critical at exactly <strong>15%</strong> by construction, and the capacity-aware cut lets the team set that share directly (10% for a smaller team, 20% for a larger one). The rolling-percentile variant does the same on a trailing window, so the Critical share stays at 15% of <em>current</em> conditions through a holiday surge or a carrier disruption rather than spiking. On this dataset the rolling and global quantile cuts land within 0.1 point of each other, which is itself a finding — the score distribution is stationary across the 2015–2018 window, with no regime shift.</p>
<p><strong>Figure 8</strong></p>
<p><em>Critical / Elevated / Low Shares Under Four Segmentation Strategies</em></p>
<p><img src="assets/fig8_segmentation_strategies.png" class="img-fluid" alt="Horizontal stacked bars. Industry-standard [0,40,75]: Low 45%, Elevated 18%, Critical 37%. Refined fixed [0,60,85]: Low 56%, Elevated 19%, Critical 25%. Quantile (p60/p85): Low 60%, Elevated 25%, Critical 15%. Capacity-aware (top 15% / next 20%): Low 65%, Elevated 20%, Critical 15%."></p>
<p><em>Note.</em> Shares of the 180,519-order portfolio. The rolling-percentile strategy (not shown) matches the quantile strategy to within 0.1 point.</p>
<p><strong>Table 3</strong></p>
<p><em>Risk-Bucket Profile Under the Persisted [0, 60, 85] Segmentation</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Band</th>
<th style="text-align: right;">Orders</th>
<th style="text-align: right;">Share</th>
<th style="text-align: right;">Mean P(late)</th>
<th style="text-align: right;">Mean expected duration</th>
<th style="text-align: right;">High-value share</th>
<th style="text-align: right;">Mean shipping-mode late-rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Low</td>
<td style="text-align: right;">100,795</td>
<td style="text-align: right;">55.8%</td>
<td style="text-align: right;">17.3%</td>
<td style="text-align: right;">3.66 d</td>
<td style="text-align: right;">12.6%</td>
<td style="text-align: right;">0.39</td>
</tr>
<tr class="even">
<td style="text-align: left;">Elevated</td>
<td style="text-align: right;">33,755</td>
<td style="text-align: right;">18.7%</td>
<td style="text-align: right;">86.1%</td>
<td style="text-align: right;">3.72 d</td>
<td style="text-align: right;">12.2%</td>
<td style="text-align: right;">0.50</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Critical</td>
<td style="text-align: right;">45,969</td>
<td style="text-align: right;">25.5%</td>
<td style="text-align: right;">99.5%</td>
<td style="text-align: right;">2.88 d</td>
<td style="text-align: right;">12.6%</td>
<td style="text-align: right;">0.92</td>
</tr>
</tbody>
</table>
<p><em>Note.</em> The Critical band’s mean expected duration (2.88 d) is <em>lower</em> than the Elevated band’s (3.72 d): an order reaches Critical on near-certain probability, not on a long predicted duration — the index measures risk, not magnitude. High-value orders are evenly spread across the three bands.</p>
</section>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<section id="principal-findings" class="level3">
<h3 class="anchored" data-anchor-id="principal-findings">Principal findings</h3>
<p>The pipeline delivers a working dual-engine risk model: a delay classifier at <strong>ROC-AUC 0.872</strong> and a duration regressor at <strong>R² 0.681</strong>, both from information available at order placement, blended into a single 0–100 index. Its most transferable contribution is not the model but the <strong>triage layer</strong> — the demonstration that fixed score thresholds cannot control alert volume (they hand a control tower 25–37% of the portfolio as Critical), and that percentile or capacity-aware cuts fix this by targeting a share instead of a score value. The substantive operational finding is that one lever dominates: <strong>shipping mode</strong> accounts for the majority of both engines’ predictive power, and the score by mode (First Class 90 / Second 79 / Standard 35 / Same Day 44) says the single most effective intervention is mode selection at order entry.</p>
</section>
<section id="the-honesty-trade-off-and-what-it-cost" class="level3">
<h3 class="anchored" data-anchor-id="the-honesty-trade-off-and-what-it-cost">The honesty trade-off, and what it cost</h3>
<p>The headline number is 0.87, not the 0.97–0.99 an unaudited pipeline reports on this data. The gap is the leakage audit and the identifier removal doing their job: a model that “knows” the actual transit days, or that can memorise <code>order_id</code>, ranks late deliveries almost perfectly and predicts nothing useful about a new order. Dropping <code>shipping_days_scheduled</code> for multicollinearity had a specific, visible cost, though. That field encodes the promised window, which is deterministic for two modes — Same Day is scheduled at zero days, First Class at one — so removing it left the classifier unable to identify those cases cleanly. The consequence shows up directly: the classifier assigns Same-Day orders a mean P(late) of 0.48 and the composite score rates them at 44, even though <strong>not one Same-Day order in the data is late</strong>. This is the over-confident pocket in the reliability curve. A production build should either keep a leakage-safe encoding of the promised window or apply a deterministic override for the two fixed-schedule modes.</p>
</section>
<section id="the-score-is-a-probability-band" class="level3">
<h3 class="anchored" data-anchor-id="the-score-is-a-probability-band">The score is a probability band</h3>
<p>The Critical band carries a <em>lower</em> mean expected duration than the Elevated band (2.88 vs 3.72 days). This is not a defect — probability carries 60% of the blend, so an order reaches Critical by being near-certain to be late, not by being predicted to take a long time. Whether that is the right weighting is a business question: a control tower optimising for SLA breaches wants probability to dominate; one optimising for customer-experience severity would raise the duration weight. The regression estimate is exported unblended precisely so that choice stays open downstream.</p>
</section>
<section id="limitations" class="level3">
<h3 class="anchored" data-anchor-id="limitations">Limitations</h3>
<p><strong>Calibration.</strong> The probabilities are usable for ranking but not as literal likelihoods without a calibration layer (isotonic or Platt); they run under-confident below 0.8 and over-confident at the very top. <strong>Reproducibility of the score.</strong> The persisted scored table’s <code>risk_bucket</code> column is the fixed [0, 60, 85] cut, not the rolling-percentile scheme the project metadata names as canonical, and the metadata’s stated bucket distributions predate the final score version — the numbers here are recomputed from the persisted score itself. <strong>Tail compression.</strong> The regressor pulls 0-day and 6-day shipments toward the centre, so it under-warns on the longest delays. <strong>Naming.</strong> The exported <code>expected_delay_days</code> field is predicted <em>calendar days to ship</em> (total duration), not days of delay. <strong>Scope.</strong> Every figure is the 2015–2018 DataCo window; the stationarity that makes the rolling and global cuts agree is a property of this dataset, not a guarantee for a live network.</p>
</section>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion">Conclusion</h3>
<p>A leakage-controlled XGBoost classifier and regressor, blended with historical late-rate baselines into a 0–100 operational risk score, give a logistics control tower an honest per-order risk read (ROC-AUC 0.87, duration MAE 0.71 days) rather than an inflated one. The score’s value is realised only through a triage layer that sizes the Critical alert queue to the team’s capacity — a fixed 15% share under percentile or capacity-aware segmentation — instead of to an arbitrary threshold that would flag a quarter of the portfolio. The persisted model bundle and the 180,519-row scored table support that deployment directly.</p>
</section>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<p>Constante, F., Silva, F., &amp; Pereira, A. (2019). <em>DataCo smart supply chain for big data analysis</em> (Version 5) [Data set]. Mendeley Data. https://doi.org/10.17632/8gx2fvg2k6.5</p>
<p>Chen, T., &amp; Guestrin, C. (2016). XGBoost: A scalable tree boosting system. <em>Proceedings of the 22nd ACM SIGKDD International Conference on Knowledge Discovery and Data Mining</em>, 785–794. https://doi.org/10.1145/2939672.2939785</p>
<p>Lundberg, S. M., &amp; Lee, S.-I. (2017). A unified approach to interpreting model predictions. <em>Advances in Neural Information Processing Systems, 30</em>, 4765–4774.</p>
<p>Niculescu-Mizil, A., &amp; Caruana, R. (2005). Predicting good probabilities with supervised learning. <em>Proceedings of the 22nd International Conference on Machine Learning</em>, 625–632. https://doi.org/10.1145/1102351.1102430</p>
<p>Pedregosa, F., Varoquaux, G., Gramfort, A., Michel, V., Thirion, B., Grisel, O., Blondel, M., Prettenhofer, P., Weiss, R., Dubourg, V., Vanderplas, J., Passos, A., Cournapeau, D., Brucher, M., Perrot, M., &amp; Duchesnay, É. (2011). Scikit-learn: Machine learning in Python. <em>Journal of Machine Learning Research, 12</em>, 2825–2830.</p>
<p>Saito, T., &amp; Rehmsmeier, M. (2015). The precision-recall plot is more informative than the ROC plot when evaluating binary classifiers on imbalanced datasets. <em>PLOS ONE, 10</em>(3), e0118432. https://doi.org/10.1371/journal.pone.0118432</p>
<hr>
<p><em>Analysis and figures by the author. A supervised model on one 2015–2018 logistics dataset; the reported ROC-AUC of 0.87 is the leakage-controlled figure, and the probabilities need a calibration layer before literal interpretation.</em></p>


<div id="contact" class="connect-section" style="text-align: center; padding: 50px 20px; background: #f9f9f9; border-radius: 15px; border: 1px solid #eaeaea; margin-top: 40px;">
<h3 style="color: #2c3e50; font-weight: 700; margin-bottom: 15px; border: none;" class="anchored">Let's Collaborate</h3>
<p style="color: #666; max-width: 650px; margin: 0 auto 30px auto; font-size: 1.05rem; line-height: 1.6;">Available for high-impact <strong>Business Intelligence, Power BI Engineering, and Advanced Data Analytics</strong> projects. Connect with me or hire me directly through the platforms below.</p>
<div style="display: flex; flex-wrap: wrap; justify-content: center; gap: 12px;">
<a href="https://www.linkedin.com/in/mkmuneer" class="btn btn-primary" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; text-decoration: none;"><i class="bi bi-linkedin"></i> LinkedIn</a>
<a href="https://github.com/mkhanmuneer" class="btn btn-dark" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; text-decoration: none;"><i class="bi bi-github"></i> GitHub</a>
<a href="https://www.kaggle.com/muhammadkhanmuneer" class="btn btn-info" target="_blank" rel="noopener" style="color: white; padding: 12px 25px; min-width: 150px; text-decoration: none;"><i class="bi bi-graph-up"></i> Kaggle</a>
<a href="https://www.upwork.com/freelancers/~018de8553286a1d00c" class="btn btn-outline-success" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; border-width: 2px; font-weight: 600; text-decoration: none;"><i class="bi bi-briefcase"></i> Upwork</a>
<a href="https://www.fiverr.com/neuronvision" class="btn btn-outline-success" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; border-width: 2px; font-weight: 600; text-decoration: none;"><i class="bi bi-lightning-charge"></i> Fiverr</a>
</div>
</div>

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/mkhanmuneer\.github\.io\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 Muhammad Khan Muneer</p>
</div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://www.upwork.com/freelancers/~018de8553286a1d00c">
<p>Hire on Upwork</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="https://www.fiverr.com/neuronvision">
<p>Hire on Fiverr</p>
</a>
  </li>  
</ul>
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mkhanmuneer">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/mkmuneer">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>