<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Muhammad Khan Muneer">
<meta name="keywords" content="medallion architecture, ETL pipeline, bronze silver gold, data quality audit, sentinel encoding, redundant columns, sessionisation, GA4 engagement, feature engineering, Parquet, idempotent pipeline, data validation, supply chain analytics, Python, pandas">
<meta name="description" content="A three-layer medallion ETL pipeline that feeds every downstream DataCo analysis. Dual-domain ingestion: 180,519 order-item transactions (three years) joined conceptually to 466,728 web page-views (five months). Adaptive anomaly reconciliation: 4,657 Same-Day shipments carry a recorded transit time of 1 day that date arithmetic proves is 0 — the field is overridden from the timestamps. Redundancy audit: 7 identical column pairs and 3 zero-variance columns (two of them sentinel-masked with XXXXXXXXX) removed at Silver. Sessionisation: a 30-minute inactivity rule turns the page-view stream into 196,720 sessions. Output: 11 Gold Parquet tables at six analytical grains, validated for round-trip integrity, shape, and determinism.">

<title>An Idempotent Medallion Pipeline for a Dual-Domain Supply-Chain Dataset, With Adaptive Anomaly Reconciliation – Muhammad Khan Muneer</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-4d9afe2b8d18ee9fa5d0d57b5ed4214d.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-5af9b5ab1fa0c387551d40c1aacb317e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-ca0cfe78a00f84493d894d8af57a3a20.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-5af9b5ab1fa0c387551d40c1aacb317e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": true,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<link rel="stylesheet" href="../../styles/custom.css">
<meta property="og:title" content="Muhammad Khan Muneer — Data Science &amp; BI Portfolio">
<meta property="og:description" content="Engineering ML-driven analytics and automated decision systems.">
<meta property="og:image" content="https://mkhanmuneer.github.io/projects/dataco-medallion-pipeline-adaptive-anomaly-reconciliation/assets/fig1_medallion_architecture.png">
<meta property="og:site_name" content="M. Khan Muneer Portfolio">
<meta property="og:image:alt" content="Four boxes left to right: RAW (2 source CSVs, 182.5 MB), BRONZE (structural cleaning), SILVER (business logic, sentinels and the Same-Day fix), GOLD (feature engineering, 11 tables, 34 MB), with a branch down to six analytical grains: order-item 180,519, customer 20,652, product 118, page-view 466,728, session 196,720, date 1,127.">
<meta property="og:image:height" content="840">
<meta property="og:image:width" content="1745">
<meta name="twitter:title" content="An Idempotent Medallion Pipeline for a Dual-Domain Supply-Chain Dataset, With Adaptive Anomaly Reconciliation – Muhammad Khan Muneer">
<meta name="twitter:description" content="A three-layer medallion ETL pipeline that feeds every downstream DataCo analysis. Dual-domain ingestion: 180,519 order-item transactions (three years) joined conceptually to 466,728 web page-views (five months). Adaptive anomaly reconciliation: 4,657 Same-Day shipments carry a recorded transit time of 1 day that date arithmetic proves is 0 — the field is overridden from the timestamps. Redundancy audit: 7 identical column pairs and 3 zero-variance columns (two of them sentinel-masked with XXXXXXXXX) removed at Silver. Sessionisation: a 30-minute inactivity rule turns the page-view stream into 196,720 sessions. Output: 11 Gold Parquet tables at six analytical grains, validated for round-trip integrity, shape, and determinism.">
<meta name="twitter:image" content="https://mkhanmuneer.github.io/projects/dataco-medallion-pipeline-adaptive-anomaly-reconciliation/assets/fig1_medallion_architecture.png">
<meta name="twitter:creator" content="@iMKhanMuneer">
<meta name="twitter:site" content="@iMKhanMuneer">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image:alt" content="Four boxes left to right: RAW (2 source CSVs, 182.5 MB), BRONZE (structural cleaning), SILVER (business logic, sentinels and the Same-Day fix), GOLD (feature engineering, 11 tables, 34 MB), with a branch down to six analytical grains: order-item 180,519, customer 20,652, product 118, page-view 466,728, session 196,720, date 1,127.">
<meta name="twitter:image-height" content="840">
<meta name="twitter:image-width" content="1745">
</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../index.html#featured-projects"> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/mkmuneer"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mkhanmuneer"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://x.com/iMKhanMuneer"> <i class="bi bi-twitter-x" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.kaggle.com/muhammadkhanmuneer"> <i class="bi bi-graph-up" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../index.html#contact"> 
<span class="menu-text">Contact</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#pipeline-architecture" id="toc-pipeline-architecture" class="nav-link" data-scroll-target="#pipeline-architecture">Pipeline architecture</a></li>
  <li><a href="#raw-ingestion-and-audit" id="toc-raw-ingestion-and-audit" class="nav-link" data-scroll-target="#raw-ingestion-and-audit">Raw ingestion and audit</a>
  <ul class="collapse">
  <li><a href="#the-two-source-domains" id="toc-the-two-source-domains" class="nav-link" data-scroll-target="#the-two-source-domains">The two source domains</a></li>
  <li><a href="#structural-findings" id="toc-structural-findings" class="nav-link" data-scroll-target="#structural-findings">Structural findings</a></li>
  <li><a href="#the-same-day-shipping-anomaly" id="toc-the-same-day-shipping-anomaly" class="nav-link" data-scroll-target="#the-same-day-shipping-anomaly">The Same-Day shipping anomaly</a></li>
  </ul></li>
  <li><a href="#bronze-layer-structural-cleaning" id="toc-bronze-layer-structural-cleaning" class="nav-link" data-scroll-target="#bronze-layer-structural-cleaning">Bronze layer — structural cleaning</a></li>
  <li><a href="#silver-layer-business-logic-cleaning" id="toc-silver-layer-business-logic-cleaning" class="nav-link" data-scroll-target="#silver-layer-business-logic-cleaning">Silver layer — business-logic cleaning</a></li>
  <li><a href="#gold-layer-domain-feature-engineering" id="toc-gold-layer-domain-feature-engineering" class="nav-link" data-scroll-target="#gold-layer-domain-feature-engineering">Gold layer — domain feature engineering</a></li>
  <li><a href="#validation" id="toc-validation" class="nav-link" data-scroll-target="#validation">Validation</a></li>
  <li><a href="#carry-forward-findings" id="toc-carry-forward-findings" class="nav-link" data-scroll-target="#carry-forward-findings">Carry-forward findings</a></li>
  <li><a href="#tools-and-references" id="toc-tools-and-references" class="nav-link" data-scroll-target="#tools-and-references">Tools and references</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">An Idempotent Medallion Pipeline for a Dual-Domain Supply-Chain Dataset, With Adaptive Anomaly Reconciliation</h1>
<p class="subtitle lead">Turning a 180,519-row logistics CSV and a 466,728-event web access log into eleven validated Gold feature tables — a Bronze → Silver → Gold contract, a data-driven Same-Day shipping fix, and a 153-day cross-domain window.</p>
  <div class="quarto-categories">
    <div class="quarto-category">Data Engineering</div>
    <div class="quarto-category">ETL Pipeline</div>
    <div class="quarto-category">Medallion Architecture</div>
    <div class="quarto-category">Dimensional Modelling</div>
    <div class="quarto-category">Star Schema</div>
    <div class="quarto-category">Data Quality</div>
    <div class="quarto-category">Feature Engineering</div>
    <div class="quarto-category">Data Validation</div>
    <div class="quarto-category">Supply Chain</div>
    <div class="quarto-category">Web Analytics</div>
    <div class="quarto-category">Python</div>
  </div>
  </div>

<div>
  <div class="description">
    <p>A three-layer medallion ETL pipeline that feeds every downstream DataCo analysis. <strong>Dual-domain ingestion:</strong> 180,519 order-item transactions (three years) joined conceptually to 466,728 web page-views (five months). <strong>Adaptive anomaly reconciliation:</strong> 4,657 Same-Day shipments carry a recorded transit time of 1 day that date arithmetic proves is 0 — the field is overridden from the timestamps. <strong>Redundancy audit:</strong> 7 identical column pairs and 3 zero-variance columns (two of them sentinel-masked with <code>XXXXXXXXX</code>) removed at Silver. <strong>Sessionisation:</strong> a 30-minute inactivity rule turns the page-view stream into 196,720 sessions. <strong>Output:</strong> 11 Gold Parquet tables at six analytical grains, validated for round-trip integrity, shape, and determinism.</p>
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Muhammad Khan Muneer </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 2024</p>
    </div>
  </div>
  
    
  </div>
  

<div>
  <div class="keywords">
    <div class="block-title">Keywords</div>
    <p>medallion architecture, ETL pipeline, bronze silver gold, data quality audit, sentinel encoding, redundant columns, sessionisation, GA4 engagement, feature engineering, Parquet, idempotent pipeline, data validation, supply chain analytics, Python, pandas</p>
  </div>
</div>

</header>


<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<p>This is the extract–transform–load (ETL) stage of an eight-notebook analysis of the <em>DataCo Smart Supply Chain</em> dataset. It has one job: turn two raw source files into a set of validated, feature-engineered analytical tables that the operations, customer, product, clickstream, segmentation, and risk-scoring notebooks can each load without re-running any upstream logic. The pipeline does that through a <strong>three-layer medallion architecture</strong> (Bronze → Silver → Gold), where each layer has a strict contract, a distinct fault-isolation boundary, and a persisted Parquet snapshot any consumer can reload independently.</p>
<p>Two properties of the raw data shape the whole design:</p>
<ul>
<li><strong>The two domains do not share a time axis.</strong> The logistics file covers 37 months (January 2015 – January 2018); the web access log covers 5 months (September 2017 – January 2018). Any analysis that links browsing to purchasing is only defensible inside the 153-day intersection — a constraint the pipeline enforces by materialising <code>_overlap</code> subsets rather than leaving it to each analyst to remember.</li>
<li><strong>Data-quality defects are heterogeneous and mostly invisible to a null count.</strong> Seven pairs of columns are byte-for-byte identical; three columns hold a single value across all 180,519 rows; two more are filled entirely with the mask string <code>XXXXXXXXX</code>; and 4,657 Same-Day shipments carry a transit-time field that contradicts their own timestamps. None of these show up as missing values. The layered design surfaces each one explicitly and resolves it at the layer that has the context to do so.</li>
</ul>
<p>The result is <strong>11 Gold Parquet tables</strong> at six analytical grains, built deterministically and checked for serialisation integrity, shape, and reproducibility.</p>
</section>
<section id="pipeline-architecture" class="level2">
<h2 class="anchored" data-anchor-id="pipeline-architecture">Pipeline architecture</h2>
<p>Each layer knows strictly more about the data than the one before it. Bronze knows what the data <em>looks like</em>; Silver knows what it <em>means</em>; Gold produces the <em>analytical surface</em>. The contract for each layer — and, just as important, what each layer must <strong>not</strong> do — is fixed (Figure 1, Table 1).</p>
<p><strong>Figure 1</strong></p>
<p><em>The Bronze → Silver → Gold Medallion Pipeline</em></p>
<p><img src="assets/fig1_medallion_architecture.png" class="img-fluid" alt="Four boxes left to right: RAW (2 source CSVs, 182.5 MB), BRONZE (structural cleaning), SILVER (business logic, sentinels and the Same-Day fix), GOLD (feature engineering, 11 tables, 34 MB), with a branch down to six analytical grains: order-item 180,519, customer 20,652, product 118, page-view 466,728, session 196,720, date 1,127."></p>
<p><em>Note.</em> Each arrow adds knowledge, never rows. A downstream notebook reloads any single layer independently — Gold for analysis, Silver to debug a business rule, Bronze to debug structure.</p>
<p><strong>Table 1</strong></p>
<p><em>Layer Contracts in the Medallion Pipeline</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Layer</th>
<th style="text-align: left;">Knows</th>
<th style="text-align: left;">Does</th>
<th style="text-align: left;">Must not do</th>
<th style="text-align: left;">Persisted as</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Raw</td>
<td style="text-align: left;">nothing</td>
<td style="text-align: left;">byte-for-byte Parquet snapshot of each source file</td>
<td style="text-align: left;">any transformation</td>
<td style="text-align: left;"><code>*/parquet/*.parquet</code> (lineage anchor)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bronze</td>
<td style="text-align: left;">physical structure</td>
<td style="text-align: left;">snake_case rename, canonical column map, date parsing, identifier → <code>string</code>, whitespace trim, dedup</td>
<td style="text-align: left;">replace sentinels, drop columns, derive features</td>
<td style="text-align: left;"><code>fact_logistics_bronze.parquet</code>, <code>fact_access_logs_bronze.parquet</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Silver</td>
<td style="text-align: left;">domain meaning</td>
<td style="text-align: left;">drop redundant / zero-variance / masked columns, numeric &amp; categorical dtype enforcement, product-name canonicalisation, the Same-Day fix, sessionisation, overlap subsets</td>
<td style="text-align: left;">impute, engineer analytical features, drop rows</td>
<td style="text-align: left;"><code>fact_*_silver.parquet</code> (+ <code>_overlap</code>)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gold</td>
<td style="text-align: left;">analytical intent</td>
<td style="text-align: left;">financial ratios, shipping-performance flags, RFM / CLV, session engagement metrics, funnel flags, date spine</td>
<td style="text-align: left;">drop rows, touch Bronze or Raw</td>
<td style="text-align: left;">11 <code>*_gold.parquet</code> tables</td>
</tr>
</tbody>
</table>
<p><em>Note.</em> Row count is invariant within each domain across Bronze, Silver, and Gold — 180,519 order-items and 466,728 page-views throughout. Only column counts and grain change.</p>
<p>Across the four layers the logistics schema <strong>contracts</strong> from 53 to 44 columns as redundancy is removed and PII is pruned, while the access-log schema <strong>grows</strong> from 8 to 15 as session and event features are derived (Figure 4, later). The Gold layer then reshapes those two fact tables into six grains (Table 2).</p>
<p><strong>Table 2</strong></p>
<p><em>The Eleven Gold Tables</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Table</th>
<th style="text-align: left;">Grain</th>
<th style="text-align: right;">Rows</th>
<th style="text-align: right;">Cols</th>
<th style="text-align: left;">Built from</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>fact_logistics_gold</code></td>
<td style="text-align: left;">order-item</td>
<td style="text-align: right;">180,519</td>
<td style="text-align: right;">44</td>
<td style="text-align: left;"><code>fact_logistics_silver</code></td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>fact_logistics_gold_overlap</code></td>
<td style="text-align: left;">order-item (windowed)</td>
<td style="text-align: right;">13,678</td>
<td style="text-align: right;">44</td>
<td style="text-align: left;">Silver overlap subset</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>fact_access_logs_gold</code></td>
<td style="text-align: left;">page-view</td>
<td style="text-align: right;">466,728</td>
<td style="text-align: right;">15</td>
<td style="text-align: left;"><code>fact_access_logs_silver</code></td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>fact_access_logs_gold_overlap</code></td>
<td style="text-align: left;">page-view (windowed)</td>
<td style="text-align: right;">464,007</td>
<td style="text-align: right;">15</td>
<td style="text-align: left;">Silver overlap subset</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>sessions_features_gold</code></td>
<td style="text-align: left;">session</td>
<td style="text-align: right;">196,720</td>
<td style="text-align: right;">37</td>
<td style="text-align: left;"><code>fact_access_logs_gold</code></td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>sessions_features_gold_overlap</code></td>
<td style="text-align: left;">session (windowed)</td>
<td style="text-align: right;">195,341</td>
<td style="text-align: right;">37</td>
<td style="text-align: left;">overlap page-views</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>customer_features_gold</code></td>
<td style="text-align: left;">customer</td>
<td style="text-align: right;">20,652</td>
<td style="text-align: right;">39</td>
<td style="text-align: left;"><code>fact_logistics_gold</code></td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>customer_features_gold_overlap</code></td>
<td style="text-align: left;">customer (windowed)</td>
<td style="text-align: right;">9,946</td>
<td style="text-align: right;">39</td>
<td style="text-align: left;">overlap order-items</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>product_features_gold</code></td>
<td style="text-align: left;">product</td>
<td style="text-align: right;">118</td>
<td style="text-align: right;">38</td>
<td style="text-align: left;"><code>fact_logistics_gold</code></td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>product_features_gold_overlap</code></td>
<td style="text-align: left;">product (windowed)</td>
<td style="text-align: right;">71</td>
<td style="text-align: right;">38</td>
<td style="text-align: left;">overlap order-items</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>dim_date_gold</code></td>
<td style="text-align: left;">calendar date</td>
<td style="text-align: right;">1,127</td>
<td style="text-align: right;">17</td>
<td style="text-align: left;">generated spine, 2015-01-01 → 2018-01-31</td>
</tr>
</tbody>
</table>
<p><em>Note.</em> Tables are built in dependency order: <code>fact_logistics_gold</code> precedes the customer and product tables; <code>fact_access_logs_gold</code> precedes the sessions table. Each <code>_overlap</code> table is the same transformation applied to the 153-day subset.</p>
</section>
<section id="raw-ingestion-and-audit" class="level2">
<h2 class="anchored" data-anchor-id="raw-ingestion-and-audit">Raw ingestion and audit</h2>
<p>Both source files are written to Parquet <strong>before any transformation</strong> as immutable lineage anchors, then audited against the untouched frames. No cleaning happens here — only diagnosis, and every diagnostic exists because it forces a specific downstream decision.</p>
<section id="the-two-source-domains" class="level3">
<h3 class="anchored" data-anchor-id="the-two-source-domains">The two source domains</h3>
<p><code>fact_logistics_raw</code> arrives at <strong>180,519 rows × 53 columns</strong> — three years of order-item transactions, loaded with Latin-1 encoding because the file carries extended-ASCII characters (accented place names) that corrupt silently under UTF-8. <code>fact_access_logs_raw</code> arrives at <strong>469,977 rows × 8 columns</strong> — tokenised web access-log events at page-view grain. A 52-row column-definition reference accompanies the logistics file and passes through untouched.</p>
<p>The two observation windows barely overlap (Figure 2). The logistics series runs at roughly 1,780 orders per month for three years, with a modest rise in the final quarter; the access log is concentrated in a single five-month block, 99.4% of it inside the 153-day window <code>2017-09-01 → 2018-01-31</code>. Only <strong>13,678 order-items — 7.6% of the logistics history</strong> — fall in that window. Every cross-domain claim in the downstream notebooks is scoped to the <code>_overlap</code> tables for this reason.</p>
<p><strong>Figure 2</strong></p>
<p><em>Two Domains, Two Observation Windows, One 153-Day Overlap</em></p>
<p><img src="assets/fig2_observation_windows.png" class="img-fluid" alt="Top panel: monthly unique orders for the logistics domain, near 1,780 per month from January 2015 to January 2018 with a small rise to about 2,100 in the final four months, which are shaded as the overlap window. Bottom panel: monthly page-views for the web access log, September 2017 to January 2018 only, starting at 137,238 in September and settling near 83,000, almost entirely inside the shaded window."></p>
<p><em>Note.</em> Top — logistics, 37 months. Bottom — web access logs, 5 months, on its own axis. The shaded band is the temporal intersection; cross-domain analysis is limited to it.</p>
</section>
<section id="structural-findings" class="level3">
<h3 class="anchored" data-anchor-id="structural-findings">Structural findings</h3>
<p>The logistics audit surfaces several classes of defect that a missing-value summary never shows (Table 3). Seven pairs of columns are perfectly identical — <code>Sales per customer</code> / <code>Order Item Total</code>, <code>Customer Id</code> / <code>Order Customer Id</code>, <code>Benefit per order</code> / <code>Order Profit Per Order</code>, and four more — pure redundancy that would inflate any correlation matrix and risk double-counting in aggregation. Three columns are zero-variance: <code>Customer Email</code> and <code>Customer Password</code> both hold only <code>XXXXXXXXX</code> (deliberate suppression, not a null), and <code>Product Status</code> is <code>0</code> for every row. <code>Order Zipcode</code> is 86% empty; <code>Product Description</code> is 100% empty. And a geographic check confirms the <code>Customer City/State/Street/Zipcode/Lat/Long</code> fields describe <strong>retail store locations, not customer addresses</strong> — carrying the <code>customer_</code> prefix forward would attribute every store-level aggregation to the wrong entity.</p>
<p>The access-log audit is shorter: zero nulls, but <strong>3,249 exact-duplicate rows</strong> (repeat log-collector entries) and <strong>100% of URLs percent-encoded</strong> (<code>%20</code>, <code>%2F</code>, …), which would make every later substring test for <code>/product/</code> or <code>/add_to_cart</code> fail silently.</p>
<p><strong>Table 3</strong></p>
<p><em>Raw-Layer Defects and Where Each Is Resolved</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Domain</th>
<th style="text-align: left;">Defect</th>
<th style="text-align: left;">Extent</th>
<th style="text-align: left;">Resolved at</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Logistics</td>
<td style="text-align: left;">identical column pairs</td>
<td style="text-align: left;">7 pairs</td>
<td style="text-align: left;">Silver — drop one of each</td>
</tr>
<tr class="even">
<td style="text-align: left;">Logistics</td>
<td style="text-align: left;">zero-variance columns</td>
<td style="text-align: left;">3: <code>Product Status</code> = <code>0</code> throughout; <code>Customer Email</code> / <code>Customer Password</code> = <code>XXXXXXXXX</code> throughout (suppressed PII masquerading as a category, not a null)</td>
<td style="text-align: left;">Silver — drop</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Logistics</td>
<td style="text-align: left;">structurally empty</td>
<td style="text-align: left;"><code>Product Description</code> 100% null (dropped), <code>Order Zipcode</code> 86% null (retained as sparse)</td>
<td style="text-align: left;">Silver</td>
</tr>
<tr class="even">
<td style="text-align: left;">Logistics</td>
<td style="text-align: left;">mislabelled entity</td>
<td style="text-align: left;">store-location fields prefixed <code>customer_</code></td>
<td style="text-align: left;">Bronze — rename to <code>store_*</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Logistics</td>
<td style="text-align: left;">trapped dates</td>
<td style="text-align: left;">2 date columns stored as <code>object</code></td>
<td style="text-align: left;">Bronze — <code>to_datetime</code></td>
</tr>
<tr class="even">
<td style="text-align: left;">Logistics</td>
<td style="text-align: left;">identifier dtype</td>
<td style="text-align: left;">11 ID columns stored as float/int</td>
<td style="text-align: left;">Bronze — cast to <code>string</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Access logs</td>
<td style="text-align: left;">duplicate rows</td>
<td style="text-align: left;">3,249</td>
<td style="text-align: left;">Bronze — <code>drop_duplicates</code> → 466,728</td>
</tr>
<tr class="even">
<td style="text-align: left;">Access logs</td>
<td style="text-align: left;">percent-encoded URLs</td>
<td style="text-align: left;">100% of rows</td>
<td style="text-align: left;">Bronze — <code>unquote</code></td>
</tr>
</tbody>
</table>
<p><em>Note.</em> Bronze fixes anything structural; Silver fixes anything that needs to know what a column <em>means</em>.</p>
</section>
<section id="the-same-day-shipping-anomaly" class="level3">
<h3 class="anchored" data-anchor-id="the-same-day-shipping-anomaly">The Same-Day shipping anomaly</h3>
<p>One defect needs its own diagnosis. The dataset carries <code>Days for shipping (real)</code> as the recorded transit time. Among the <strong>9,737 Same-Day orders</strong> (5.4% of all order-items), <strong>4,657 carry a recorded value of 1 day</strong> — yet date arithmetic on the same rows, <code>(shipping_date − order_date).days</code>, returns <strong>0 for every Same-Day order without exception</strong>. The recorded field is partially wrong; the timestamps are internally consistent and are treated as authoritative (Figure 3).</p>
<p>Silver resolves this with an <strong>adaptive fix</strong>: for every row where <code>shipping_mode == "Same Day"</code>, the transit-time field is overridden with the value computed from the timestamps. A post-fix check confirms <strong>zero remaining mismatches</strong> between the recorded and computed transit times across all 180,519 rows, and all 9,737 Same-Day orders land at <code>calendar_days_to_ship = 0</code> in Gold. The fix is data-driven rather than a hard-coded <code>Same Day → 0</code> rule, so it stays correct if a future data drop records a genuine non-zero Same-Day transit.</p>
<p><strong>Figure 3</strong></p>
<p><em>The Adaptive Same-Day Reconciliation</em></p>
<p><img src="assets/fig3_same_day_fix.png" class="img-fluid" alt="Left: among 9,737 Same-Day order-items, the recorded transit-time field shows 5,080 at 0 days and 4,657 at 1 day, with the 1-day bar labelled mislabelled. Right: after the fix, date arithmetic places all 9,737 at 0 days."></p>
<p><em>Note.</em> Left — the recorded field, raw. Right — the value from the timestamps, applied in Silver and carried to Gold. The 4,657 disagreements are ~2.6% of all order-items but would bias any Same-Day delivery-performance metric upward.</p>
</section>
</section>
<section id="bronze-layer-structural-cleaning" class="level2">
<h2 class="anchored" data-anchor-id="bronze-layer-structural-cleaning">Bronze layer — structural cleaning</h2>
<p>Bronze applies structural normalisation only; its contract is losslessness. For <strong>logistics</strong>: all 53 column names are normalised to snake_case and then remapped through a canonical dictionary (the five store-location fields become <code>store_*</code>); both date columns are parsed to <code>datetime64[ns]</code>; eleven identifier columns are cast to <code>string</code> to protect leading zeros and join keys; string columns are whitespace-trimmed; a dedup pass runs (a structural safety check — the logistics file has no duplicates). Shape unchanged at 180,519 × 53.</p>
<p>For <strong>access logs</strong>: the same snake_case pass; every URL decoded with <code>urllib.parse.unquote</code>; the date column parsed to <code>datetime64[ns]</code>; two helper columns added (<code>is_valid_ip</code>, <code>date_only</code>); and the 3,249 duplicate rows removed. Shape 469,977 × 8 → <strong>466,728 × 10</strong>.</p>
<p>Bronze deliberately leaves the redundant, zero-variance, and masked columns in place — their problems are semantic, and semantics belong to Silver. Keeping them here gives any downstream debugger an unmodified reference.</p>
</section>
<section id="silver-layer-business-logic-cleaning" class="level2">
<h2 class="anchored" data-anchor-id="silver-layer-business-logic-cleaning">Silver layer — business-logic cleaning</h2>
<p>Silver is the last layer at which data-quality issues are corrected. For <strong>logistics</strong> it drops the 6 redundant columns and the 4 zero-variance / structurally-empty columns (<code>customer_email</code>, <code>customer_password</code>, <code>product_stock_flag</code>, <code>product_description</code>), enforces numeric dtype on 10 measure columns and <code>category</code> dtype on 11 categorical columns, derives <code>product_name_canonical</code> (a lowercased, punctuation-stripped join key shared with the access-log domain), computes <code>calendar_days_to_ship</code> from the timestamps, and applies the Same-Day fix. Net column change: 53 → <strong>45</strong>.</p>
<p>For <strong>access logs</strong> it applies the semantic renames (<code>date</code> → <code>session_date_time</code>, <code>url</code> → <code>page_url</code>, …), drops the Bronze <code>is_valid_ip</code> helper, adds <code>product_name_canonical</code>, and performs <strong>sessionisation</strong>: events are grouped by tokenised IP, sorted by timestamp, and a new session is started whenever the gap since the previous event from that IP exceeds <strong>30 minutes</strong> — the Universal Analytics inactivity convention, which makes the derived session metrics comparable to standard web-analytics benchmarks. The 466,728 page-views resolve into <strong>196,720 sessions</strong> across <strong>3,340 distinct IPs</strong> — a mean of about 2.4 page-views per session. Net column change: 10 → <strong>11</strong>.</p>
<p>Silver also materialises the <strong>overlap subsets</strong> by filtering both domains to <code>2017-09-01 → 2018-01-31</code>: 13,678 logistics order-items (7.6%) and 464,007 page-views (99.4%). Every downstream <code>_overlap</code> table inherits this scope without re-applying the filter.</p>
<p>The cumulative effect across all four layers is a logistics schema that shrinks by nine columns and an access-log schema that more than doubles (Figure 4).</p>
<p><strong>Figure 4</strong></p>
<p><em>Schema Evolution Across the Four Layers</em></p>
<p><img src="assets/fig4_schema_evolution.png" class="img-fluid" alt="Grouped bar chart. Logistics columns: 53 at Raw, 53 at Bronze, 45 at Silver, 44 at Gold. Access-log columns: 8 at Raw, 10 at Bronze, 11 at Silver, 15 at Gold."></p>
<p><em>Note.</em> Logistics loses redundant and PII columns at Silver and one net column at Gold (feature additions minus a pruning step). The access-log schema grows monotonically as session keys and event flags are derived.</p>
</section>
<section id="gold-layer-domain-feature-engineering" class="level2">
<h2 class="anchored" data-anchor-id="gold-layer-domain-feature-engineering">Gold layer — domain feature engineering</h2>
<p>Gold resolves no data-quality issues; it only derives analytical features from the clean Silver inputs.</p>
<p><strong><code>fact_logistics_gold</code></strong> (180,519 × 44) adds a profitability block (<code>profit_margin_ratio</code>, <code>is_high_value_order</code>), an audited shipping-performance block (<code>shipping_delay_days</code>, <code>is_late_actual</code>, a five-level <code>delivery_performance_type</code>, and <code>system_prediction_gap</code> — the source system’s risk flag minus the observed outcome), integer date keys for the star join, and a <code>product_price_segment</code> quintile. Two findings fall straight out of these features and become carry-forward constraints (Figure 5): the <strong>recomputed late-delivery rate is 54.7%</strong>, and <strong>18.7% of order-items (33,784) are loss-making</strong> — though at product grain the loss nets out to only 3 of 118 products, so the customer- and product-level notebooks must be careful about which grain a margin claim is made at.</p>
<p><strong>Figure 5</strong></p>
<p><em>Two Gold Features That Constrain the Downstream Notebooks</em></p>
<p><img src="assets/fig5_delivery_and_margin.png" class="img-fluid" alt="Left: delivery_performance_type counts — Early 43,366, On-time 38,410, Minor Delay 84,708, Moderate Delay 14,035, Critical Delay 0; 54.7% of order-items are late. Right: 146,735 order-items (81.3%) at positive margin, 33,784 (18.7%) at negative margin."></p>
<p><em>Note.</em> Both flags are engineered once in <code>fact_logistics_gold</code> and inherited by <code>customer_features_gold</code> and <code>product_features_gold</code>.</p>
<p><strong><code>sessions_features_gold</code></strong> (196,720 × 37) aggregates the page-view stream to session grain and stores <strong>two bounce definitions</strong> side by side — the UA rule (exactly one page-view: 49.3% of sessions) and the GA4 engagement rule (not engaged, i.e.&nbsp;under 10 s and under 2 page-views and no key event: 35.5%). It also carries a composite <code>engagement_score</code>, funnel presence flags, a time-of-day bucket, and page-depth bins (Figure 6). The two bounce rates differ by 14 points, so any downstream engagement claim must state which definition it uses.</p>
<p><strong>Figure 6</strong></p>
<p><em>The Sessionisation Output</em></p>
<p><img src="assets/fig6_sessionisation_output.png" class="img-fluid" alt="Left: sessions by page-view count — 1 page 96,986; 2-3 pages 65,671; 4-7 pages 26,453; 8-15 pages 6,599; 16+ pages 1,011. Right: UA bounce 49.3%, GA4 bounce 35.5%, reached add-to-cart 46.4%."></p>
<p><em>Note.</em> Nearly half of all sessions are single-page. The add-to-cart rate (46.4%) is the denominator the clickstream notebook uses for its conversion funnel. Every access-log URL resolves to a product path, so a session-level product-view funnel is not informative for this dataset — page depth and the two bounce definitions carry the engagement signal instead.</p>
<p><strong><code>customer_features_gold</code></strong> (20,652 × 39) collapses the order-item table to customer grain with RFM quintiles, a <code>clv_proxy</code> (annualised revenue), and a four-level <code>loyalty_tier</code> (At Risk 223, Standard 13,057, Loyal 5,883, Champion 1,489). <strong><code>product_features_gold</code></strong> (118 × 38) does the same at product grain, with <code>revenue_margin_pct</code> spanning −4.2% to 23.0%. <strong><code>dim_date_gold</code></strong> (1,127 × 17) is a generated conformed date spine with an <code>in_overlap_window</code> flag on the 153 dates inside the cross-domain window.</p>
</section>
<section id="validation" class="level2">
<h2 class="anchored" data-anchor-id="validation">Validation</h2>
<p>Three checks confirm the persisted Gold layer is correct and analytically ready.</p>
<p><strong>Table 4</strong></p>
<p><em>Pipeline Validation Results</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Component</th>
<th style="text-align: left;">Assertion</th>
<th style="text-align: left;">Result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Serialisation round-trip</td>
<td style="text-align: left;">reload each table; primary analytical column has 0% nulls after the write–read cycle (6 tables checked)</td>
<td style="text-align: left;">pass — <code>category</code>, nullable float, and <code>string</code> dtypes all survive Parquet</td>
</tr>
<tr class="even">
<td style="text-align: left;">Shape verification</td>
<td style="text-align: left;">all 11 Gold tables match hard-coded expected dimensions</td>
<td style="text-align: left;">pass — 11 / 11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Determinism</td>
<td style="text-align: left;">rebuild <code>fact_logistics_gold</code> from Silver a second time</td>
<td style="text-align: left;">pass — byte-identical output</td>
</tr>
</tbody>
</table>
<p><em>Note.</em> A shape deviation would signal a pipeline bug — a missing filter or a join fan-out — not a configuration value, which is why the expected dimensions are asserted rather than logged.</p>
<p>The pipeline compresses <strong>182.5 MB of source CSV into 34.1 MB of Gold Parquet (5.3×)</strong> and, for the logistics table, cuts the in-memory footprint from 334 MB to 160 MB (2.1×) through categorical dtypes and the removal of redundant and PII columns (Figure 7).</p>
<p><strong>Figure 7</strong></p>
<p><em>Pipeline Impact: Compression and the Six Grains</em></p>
<p><img src="assets/fig7_pipeline_impact.png" class="img-fluid" alt="Left: on-disk size, 182.5 MB of raw CSV versus 34.1 MB of Gold Parquet, 5.3 times smaller. Right: rows per analytical grain on a log scale — page-views 466,728, sessions 196,720, order-items 180,519, customers 20,652, products 118, dates 1,127."></p>
<p><em>Note.</em> Left — on-disk CSV versus on-disk Parquet. Right — the six grains the Gold layer produces from the two fact tables.</p>
</section>
<section id="carry-forward-findings" class="level2">
<h2 class="anchored" data-anchor-id="carry-forward-findings">Carry-forward findings</h2>
<p>Four facts every downstream notebook inherits from this pipeline:</p>
<ol type="1">
<li><strong>Late-delivery rate ≈ 54.7%.</strong> <code>is_late_actual</code> in <code>fact_logistics_gold</code> is consistent across shipping modes and order sizes — a baseline, not a subpopulation artefact. It propagates into the customer and product tables as <code>late_rate</code>.</li>
<li><strong>Negative-margin order-items ≈ 18.7% (33,784 rows).</strong> The loss-making population is visible at the fact-table grain; at product grain it nets to just 3 of 118 products. Margin claims must name their grain.</li>
<li><strong>The 153-day overlap window governs all cross-domain work.</strong> Web-to-purchase attribution is limited to the <code>_overlap</code> tables — 13,678 order-items and 464,007 page-views. Applying it across the full three-year logistics history would attribute browsing behaviour to purchases made before the web data begins.</li>
<li><strong>Sessionisation uses a 30-minute inactivity rule</strong> and produces 196,720 sessions from 466,728 page-views (≈ 2.4 per session). The UA bounce rate (49.3%) and the GA4 bounce rate (35.5%) differ by 14 points; downstream engagement analysis must specify which it cites. The repeat-visitor flag is near-universal (only 3,340 IPs) and should be treated as non-informative.</li>
</ol>
</section>
<section id="tools-and-references" class="level2">
<h2 class="anchored" data-anchor-id="tools-and-references">Tools and references</h2>
<p>Built in Python with <code>pandas</code> and <code>pyarrow</code> for the medallion layers. Sessionisation follows the Universal Analytics 30-minute inactivity convention; the dual bounce definition follows Google Analytics 4’s engaged-session rule. The dataset is the <em>DataCo Smart Supply Chain for Big Data Analysis</em> set.</p>
<p>Constante, F., Silva, F., &amp; Pereira, A. (2019). <em>DataCo smart supply chain for big data analysis</em> (Version 5) [Data set]. Mendeley Data. https://doi.org/10.17632/8gx2fvg2k6.5</p>
<p>Harris, C. R., Millman, K. J., van der Walt, S. J., Gommers, R., Virtanen, P., Cournapeau, D., Wieser, E., Taylor, J., Berg, S., Smith, N. J., Kern, R., Picus, M., Hoyer, S., van Kerkwijk, M. H., Brett, M., Haldane, A., del Río, J. F., Wiebe, M., Peterson, P., … Oliphant, T. E. (2020). Array programming with NumPy. <em>Nature, 585</em>, 357–362. https://doi.org/10.1038/s41586-020-2649-2</p>
<p>The pandas development team. (2020). <em>pandas-dev/pandas: Pandas</em> (Version latest) [Computer software]. Zenodo. https://doi.org/10.5281/zenodo.3509134</p>
<hr>
<p><em>Pipeline and figures by the author. The eleven Gold Parquet tables described here are the sole data input for every downstream notebook in this series; this is a data-engineering report and makes no inferential claim.</em></p>


<div id="contact" class="connect-section" style="text-align: center; padding: 50px 20px; background: #f9f9f9; border-radius: 15px; border: 1px solid #eaeaea; margin-top: 40px;">
<h3 style="color: #2c3e50; font-weight: 700; margin-bottom: 15px; border: none;" class="anchored">Let's Collaborate</h3>
<p style="color: #666; max-width: 650px; margin: 0 auto 30px auto; font-size: 1.05rem; line-height: 1.6;">Available for high-impact <strong>Business Intelligence, Power BI Engineering, and Advanced Data Analytics</strong> projects. Connect with me or hire me directly through the platforms below.</p>
<div style="display: flex; flex-wrap: wrap; justify-content: center; gap: 12px;">
<a href="https://www.linkedin.com/in/mkmuneer" class="btn btn-primary" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; text-decoration: none;"><i class="bi bi-linkedin"></i> LinkedIn</a>
<a href="https://github.com/mkhanmuneer" class="btn btn-dark" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; text-decoration: none;"><i class="bi bi-github"></i> GitHub</a>
<a href="https://www.kaggle.com/muhammadkhanmuneer" class="btn btn-info" target="_blank" rel="noopener" style="color: white; padding: 12px 25px; min-width: 150px; text-decoration: none;"><i class="bi bi-graph-up"></i> Kaggle</a>
<a href="https://www.upwork.com/freelancers/~018de8553286a1d00c" class="btn btn-outline-success" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; border-width: 2px; font-weight: 600; text-decoration: none;"><i class="bi bi-briefcase"></i> Upwork</a>
<a href="https://www.fiverr.com/neuronvision" class="btn btn-outline-success" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; border-width: 2px; font-weight: 600; text-decoration: none;"><i class="bi bi-lightning-charge"></i> Fiverr</a>
</div>
</div>

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/mkhanmuneer\.github\.io\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 Muhammad Khan Muneer</p>
</div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://www.upwork.com/freelancers/~018de8553286a1d00c">
<p>Hire on Upwork</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="https://www.fiverr.com/neuronvision">
<p>Hire on Fiverr</p>
</a>
  </li>  
</ul>
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mkhanmuneer">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/mkmuneer">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>