<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Muhammad Khan Muneer">
<meta name="keywords" content="OTIF, on-time in-full, late delivery, supply chain diagnostic, shipping mode, lead time, delivery performance, exploratory data analysis, profit margin erosion, correlation analysis, predictive integrity, ROC-AUC, Brier score, Python, pandas">
<meta name="description" content="A diagnostic read of on-time-in-full (OTIF) performance across 180,519 order-items. The headline: 54.7% of order-items arrive late; OTIF is 45.3%. The mechanism: the outcome is set almost entirely by shipping mode, because mode fixes the promised lead time while the network’s achievable transit is a flat 2–6 days regardless — First Class is promised 1 day, takes exactly 2, and is late 100% of the time across all 27,814 shipments and every region. Not a driver: customer segment (44.7–45.5%, a sub-1-point spread) and destination region. A prediction–action gap: the source system’s late-delivery flag matches the outcome on 95.2% of order-items (ROC-AUC 0.95), yet the majority still ship late.">

<title>Where a Global Supply Chain Loses Time: A Multi-Axis OTIF Diagnostic of 180,519 Order-Items – Muhammad Khan Muneer</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-4d9afe2b8d18ee9fa5d0d57b5ed4214d.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-5af9b5ab1fa0c387551d40c1aacb317e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-ca0cfe78a00f84493d894d8af57a3a20.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-5af9b5ab1fa0c387551d40c1aacb317e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": true,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<link rel="stylesheet" href="../../styles/custom.css">
<meta property="og:title" content="Muhammad Khan Muneer — Data Science &amp; BI Portfolio">
<meta property="og:description" content="Engineering ML-driven analytics and automated decision systems.">
<meta property="og:image" content="https://mkhanmuneer.github.io/projects/global-supply-chain-otif-diagnostic-where-orders-lose-time/assets/fig6_region_mode_otif_heatmap.png">
<meta property="og:site_name" content="M. Khan Muneer Portfolio">
<meta property="og:image:height" content="1387">
<meta property="og:image:width" content="1475">
<meta name="twitter:title" content="Where a Global Supply Chain Loses Time: A Multi-Axis OTIF Diagnostic of 180,519 Order-Items – Muhammad Khan Muneer">
<meta name="twitter:description" content="A diagnostic read of on-time-in-full (OTIF) performance across 180,519 order-items. The headline: 54.7% of order-items arrive late; OTIF is 45.3%. The mechanism: the outcome is set almost entirely by shipping mode, because mode fixes the promised lead time while the network’s achievable transit is a flat 2–6 days regardless — First Class is promised 1 day, takes exactly 2, and is late 100% of the time across all 27,814 shipments and every region. Not a driver: customer segment (44.7–45.5%, a sub-1-point spread) and destination region. A prediction–action gap: the source system’s late-delivery flag matches the outcome on 95.2% of order-items (ROC-AUC 0.95), yet the majority still ship late.">
<meta name="twitter:image" content="https://mkhanmuneer.github.io/projects/global-supply-chain-otif-diagnostic-where-orders-lose-time/assets/fig6_region_mode_otif_heatmap.png">
<meta name="twitter:creator" content="@iMKhanMuneer">
<meta name="twitter:site" content="@iMKhanMuneer">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image-height" content="1387">
<meta name="twitter:image-width" content="1475">
</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../index.html#featured-projects"> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/mkmuneer"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mkhanmuneer"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://x.com/iMKhanMuneer"> <i class="bi bi-twitter-x" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.kaggle.com/muhammadkhanmuneer"> <i class="bi bi-graph-up" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../index.html#contact"> 
<span class="menu-text">Contact</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract">Abstract</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#method" id="toc-method" class="nav-link" data-scroll-target="#method">Method</a>
  <ul class="collapse">
  <li><a href="#data-source" id="toc-data-source" class="nav-link" data-scroll-target="#data-source">Data source</a></li>
  <li><a href="#variables-and-measures" id="toc-variables-and-measures" class="nav-link" data-scroll-target="#variables-and-measures">Variables and measures</a></li>
  <li><a href="#analytical-approach" id="toc-analytical-approach" class="nav-link" data-scroll-target="#analytical-approach">Analytical approach</a></li>
  <li><a href="#software" id="toc-software" class="nav-link" data-scroll-target="#software">Software</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#commercial-baseline" id="toc-commercial-baseline" class="nav-link" data-scroll-target="#commercial-baseline">Commercial baseline</a></li>
  <li><a href="#the-core-finding-54.7-late" id="toc-the-core-finding-54.7-late" class="nav-link" data-scroll-target="#the-core-finding-54.7-late">The core finding: 54.7% late</a></li>
  <li><a href="#the-mechanism-mode-fixes-the-promise-not-the-capability" id="toc-the-mechanism-mode-fixes-the-promise-not-the-capability" class="nav-link" data-scroll-target="#the-mechanism-mode-fixes-the-promise-not-the-capability">The mechanism: mode fixes the promise, not the capability</a></li>
  <li><a href="#geography-is-not-a-driver-either" id="toc-geography-is-not-a-driver-either" class="nav-link" data-scroll-target="#geography-is-not-a-driver-either">Geography is not a driver either</a></li>
  <li><a href="#temporal-behaviour-flat-then-truncated" id="toc-temporal-behaviour-flat-then-truncated" class="nav-link" data-scroll-target="#temporal-behaviour-flat-then-truncated">Temporal behaviour: flat, then truncated</a></li>
  <li><a href="#correlation-structure" id="toc-correlation-structure" class="nav-link" data-scroll-target="#correlation-structure">Correlation structure</a></li>
  <li><a href="#predictive-integrity-of-the-systems-own-flag" id="toc-predictive-integrity-of-the-systems-own-flag" class="nav-link" data-scroll-target="#predictive-integrity-of-the-systems-own-flag">Predictive integrity of the system’s own flag</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a>
  <ul class="collapse">
  <li><a href="#principal-findings" id="toc-principal-findings" class="nav-link" data-scroll-target="#principal-findings">Principal findings</a></li>
  <li><a href="#the-mechanism-worth-naming" id="toc-the-mechanism-worth-naming" class="nav-link" data-scroll-target="#the-mechanism-worth-naming">The mechanism worth naming</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations">Limitations</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Where a Global Supply Chain Loses Time: A Multi-Axis OTIF Diagnostic of 180,519 Order-Items</h1>
<p class="subtitle lead">An exploratory operations analysis of a three-year, 164-country logistics dataset — decomposing a 54.7% late-delivery rate across shipping mode, customer segment, destination region, and time, and testing the system’s own late-delivery flag.</p>
  <div class="quarto-categories">
    <div class="quarto-category">Exploratory Data Analysis</div>
    <div class="quarto-category">Descriptive Statistics</div>
    <div class="quarto-category">Operations Analytics</div>
    <div class="quarto-category">Supply Chain</div>
    <div class="quarto-category">Logistics</div>
    <div class="quarto-category">OTIF Analysis</div>
    <div class="quarto-category">Temporal Analysis</div>
    <div class="quarto-category">Correlation Analysis</div>
    <div class="quarto-category">Python</div>
  </div>
  </div>

<div>
  <div class="description">
    <p>A diagnostic read of on-time-in-full (OTIF) performance across 180,519 order-items. <strong>The headline:</strong> 54.7% of order-items arrive late; OTIF is 45.3%. <strong>The mechanism:</strong> the outcome is set almost entirely by shipping mode, because mode fixes the <em>promised</em> lead time while the network’s <em>achievable</em> transit is a flat 2–6 days regardless — First Class is promised 1 day, takes exactly 2, and is late 100% of the time across all 27,814 shipments and every region. <strong>Not a driver:</strong> customer segment (44.7–45.5%, a sub-1-point spread) and destination region. <strong>A prediction–action gap:</strong> the source system’s late-delivery flag matches the outcome on 95.2% of order-items (ROC-AUC 0.95), yet the majority still ship late.</p>
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Muhammad Khan Muneer </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 2024</p>
    </div>
  </div>
  
    
  </div>
  

<div>
  <div class="keywords">
    <div class="block-title">Keywords</div>
    <p>OTIF, on-time in-full, late delivery, supply chain diagnostic, shipping mode, lead time, delivery performance, exploratory data analysis, profit margin erosion, correlation analysis, predictive integrity, ROC-AUC, Brier score, Python, pandas</p>
  </div>
</div>

</header>


<section id="abstract" class="level2">
<h2 class="anchored" data-anchor-id="abstract">Abstract</h2>
<p>This study is a descriptive operations diagnostic of the <em>DataCo</em> logistics dataset — 180,519 order-items shipped over three years (January 2015 – January 2018) to 164 countries. The objective is to quantify on-time-in-full (OTIF) performance and locate where delivery time is lost. The analytical table is the validated Gold layer produced by a companion data-engineering pipeline; all measures are recomputed from it directly. <strong>54.7% of order-items arrive late</strong> (OTIF 45.3%), and this rate is flat across all 37 months with no trend and no material seasonality. The late-delivery outcome is governed almost entirely by <strong>shipping mode</strong>: mode determines the <em>promised</em> lead time (Same Day 0 days, First Class 1, Second Class 2, Standard Class 4), while the network’s <em>achievable</em> transit is a near-flat 2–6 days for every scheduled tier. First Class is promised 1 day, takes exactly 2, and is therefore late on <strong>100.0% of its 27,814 shipments</strong> in every destination region. Customer segment (44.7–45.5% on-time) and destination region are not drivers. Commercially, 18.7% of order-items are loss-making, with a tail to −$4,275 per line, concentrated at low discount and low ticket value — consistent with fixed fulfilment cost exceeding the sale price on economy items. The source system’s own late-delivery flag reproduces the realised outcome with ROC-AUC 0.95 and a 4.8% error rate, yet the majority of flagged orders still ship late — a prediction–action gap, not a prediction gap. No inferential or causal claim is made; the dataset is a single operational history and OTIF here reduces to on-time only, as no fill-rate field is present.</p>
<p><em>Keywords:</em> OTIF, late delivery, shipping mode, lead time, supply-chain diagnostic, exploratory data analysis, predictive integrity</p>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>On-time-in-full (OTIF) is the standard headline metric of logistics performance: the share of orders delivered by the promised date and in the promised quantity. It is a blunt instrument by design — one number that a fulfilment operation either clears or does not. This analysis takes a dataset of 180,519 order-items from a global e-commerce supply chain and asks three questions of it: how bad is OTIF, where is the time being lost, and does the operation already know.</p>
<p>The dataset is transactional at <strong>order-item grain</strong> — one row per product within one customer order, so a three-product order appears as three rows. That grain is deliberate: every discount, delay, and margin is recorded at the level of the individual item, which is where operational decisions actually bite. The table used here is the Gold output of a companion medallion ETL pipeline that resolved the raw encoding issues, corrected mislabelled store-location fields, and — importantly for this analysis — reconstructed the Same-Day transit-time field from the actual order and shipping timestamps after finding it mis-recorded for 4,657 shipments. All delivery-timing logic below rests on that corrected field.</p>
<p>The central result is uncomfortable and simple: <strong>more than half of all order-items arrive late.</strong> The rest of the analysis is about what that number is made of.</p>
</section>
<section id="method" class="level2">
<h2 class="anchored" data-anchor-id="method">Method</h2>
<section id="data-source" class="level3">
<h3 class="anchored" data-anchor-id="data-source">Data source</h3>
<p>A single analytical table, <code>fact_logistics_gold</code> (180,519 rows × 44 columns), covering order-items with <code>order_date</code> between 1 January 2015 and 31 January 2018. It carries no missing values in any analysed column — the upstream pipeline applied deterministic type casting and dropped or repaired every field with a known defect. Geographic and catalogue scope is summarised in Table 1.</p>
<p><strong>Table 1</strong></p>
<p><em>Dataset Scope and Composition (N = 180,519 order-items)</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Dimension</th>
<th style="text-align: left;">Composition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Time</td>
<td style="text-align: left;">2015-01-01 to 2018-01-31 (1,126 days); volume stable to Sep 2017, then a data-truncation artefact (see Results)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Destinations</td>
<td style="text-align: left;">164 countries · 23 regions · 5 markets (LATAM 51,594; Europe 50,252; Pacific Asia 41,260; USCA 25,799; Africa 11,614)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Stores</td>
<td style="text-align: left;">563 cities across two countries (continental USA 111,146; Puerto Rico 69,373 — a single hub city, Caguas, accounts for 66,770)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Catalogue</td>
<td style="text-align: left;">118 products · 50 categories · 11 departments (Fan Shop 66,861; Apparel 48,998; Golf 33,220)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Customer segments</td>
<td style="text-align: left;">Consumer 93,504 (51.8%) · Corporate 54,789 (30.4%) · Home Office 32,226 (17.9%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Shipping modes</td>
<td style="text-align: left;">Standard Class 107,752 · Second Class 35,216 · First Class 27,814 · Same Day 9,737</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Payment types</td>
<td style="text-align: left;">Debit 69,295 · Transfer 49,883 · Payment 41,725 · Cash 19,616</td>
</tr>
</tbody>
</table>
<p><em>Note.</em> The five highest-volume products account for 58% of all order-items; the catalogue is highly concentrated, a point the companion product-analytics study develops.</p>
</section>
<section id="variables-and-measures" class="level3">
<h3 class="anchored" data-anchor-id="variables-and-measures">Variables and measures</h3>
<p>The primary operational outcome is <strong><code>is_late_actual</code></strong> — a binary flag set when actual transit (<code>calendar_days_to_ship</code>, reconstructed from timestamps) exceeds the scheduled window (<code>shipping_days_scheduled</code>). <strong>OTIF</strong> is reported as <code>1 − mean(is_late_actual)</code>; with no delivered-quantity field in the source, “in full” cannot be evaluated and OTIF here is on-time only. Supporting measures: <strong><code>delivery_performance_type</code></strong> (a five-level cut of <code>shipping_delay_days</code>: Early &lt; −1, On-time [−1, 0], Minor Delay (0, 2], Moderate Delay (2, 5], Critical Delay &gt; 5); <strong><code>shipping_delay_days</code></strong> (signed actual − scheduled); <strong><code>profit_margin_ratio</code></strong> and <strong><code>order_profit_per_order</code></strong> for the commercial view; and <strong><code>late_delivery_risk</code></strong>, a binary flag generated by the source operational system before shipment, with <strong><code>system_prediction_gap</code></strong> = <code>late_delivery_risk − is_late_actual</code>.</p>
</section>
<section id="analytical-approach" class="level3">
<h3 class="anchored" data-anchor-id="analytical-approach">Analytical approach</h3>
<p>The analysis is descriptive. OTIF is decomposed by cross-tabulation against shipping mode, customer segment, and the region × mode grid, with counts reported alongside every rate. The promised-versus-achievable lead-time mechanism is examined by cross-tabulating <code>shipping_days_scheduled</code> and <code>calendar_days_to_ship</code> within each mode. Temporal behaviour uses monthly resampling of the on-time rate and of order-item versus unique-order counts. Pairwise Pearson correlations are computed across ten financial and operational variables. Isolation Forest (contamination = auto) is applied to the discount–profit plane as an unsupervised check on where losses concentrate. The predictive integrity of <code>late_delivery_risk</code> is assessed against <code>is_late_actual</code> with ROC-AUC, the Brier score, and a confusion decomposition. No model is fitted for prediction; no hypothesis test is performed.</p>
</section>
<section id="software" class="level3">
<h3 class="anchored" data-anchor-id="software">Software</h3>
<p>Python 3.10 with <code>pandas</code>, <code>numpy</code>, <code>scikit-learn</code> (Isolation Forest, ROC-AUC, Brier score), and <code>matplotlib</code> for figures.</p>
</section>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<section id="commercial-baseline" class="level3">
<h3 class="anchored" data-anchor-id="commercial-baseline">Commercial baseline</h3>
<p>The operation runs on thin and fragile margins. Net sales per order-item have a median of $164 (mean $183, max $1,940). Profit per order-item has a median of just <strong>$31.52</strong>, an interquartile range of $7.00–$64.80, and a tail reaching <strong>−$4,275</strong> on a single line; <strong>18.7% of all order-items are loss-making</strong> (Figure 1, left). The profit-margin ratio is multimodal (Figure 1, right): a primary mass between 0.30 and 0.50, a fragile secondary cluster between 0 and 0.20, and distinct recurring <strong>loss bands near −0.25 and −0.75</strong> — their regularity points to fixed operational triggers rather than random variation.</p>
<p><strong>Figure 1</strong></p>
<p><em>Profit and Margin Distributions at Order-Item Grain</em></p>
<p><img src="assets/fig1_profit_margin_distributions.png" class="img-fluid" alt="Left: histogram of profit per order-item, a sharp positive peak near zero with a long negative tail; median USD 32, 18.7% loss-making, tail to minus USD 4,275. Right: histogram of profit-margin ratio, primary mass 0.30 to 0.50 with discrete negative clusters near minus 0.25 and minus 0.75."></p>
<p><em>Note.</em> Profit axis clipped at −1,500 for legibility; the true minimum is −4,275.</p>
<p>Plotting discount against margin locates the erosion (Figure 2). The deepest losses sit at the <strong>low end of the discount range</strong> — a large volume of near-zero-discount, low-ticket order-items nonetheless producing margins of −0.75 and below. Losses thin out and rise toward break-even as discount climbs past ~$200, because high-discount lines are high-ticket products whose margins absorb both the concession and the shipping cost. An Isolation Forest on the same plane flags about 15% of order-items as anomalous; these span the full discount range (median discount $40) but are <strong>four times more likely to be loss-making than the rest</strong> (52% vs.&nbsp;13%) — the anomaly signal is the profit collapse, not the discount level. The pattern is consistent with a <strong>fixed fulfilment cost that exceeds the sale value of economy items</strong> — the business subsidising the logistics of its own low-price catalogue — rather than with discounting per se.</p>
<p><strong>Figure 2</strong></p>
<p><em>Discount Versus Profit-Margin Ratio (hex-binned, log colour scale)</em></p>
<p><img src="assets/fig2_discount_margin_erosion.png" class="img-fluid" alt="Hex-bin density of order-item discount on the x-axis against profit-margin ratio on the y-axis. The densest cells are at near-zero discount and span the full margin range including deep negatives; a dotted line marks a recurring band at minus 0.75. Points thin out and rise toward break-even as discount exceeds 200 dollars."></p>
<p><em>Note.</em> Colour is order-item count on a log scale. The dashed line is break-even; the dotted line marks the −0.75 band.</p>
</section>
<section id="the-core-finding-54.7-late" class="level3">
<h3 class="anchored" data-anchor-id="the-core-finding-54.7-late">The core finding: 54.7% late</h3>
<p>Recomputed from the corrected transit field, <strong>54.7% of order-items arrive late and OTIF is 45.3%</strong> (Figure 3). The single largest outcome class is <strong>Minor Delay</strong> — a 1–2 day overrun — at 84,708 order-items (46.9%). Early deliveries account for 24.0% and On-time for 21.3%; Moderate Delay is 7.8%, and the Critical Delay class (&gt; 5 days late) is <strong>empty</strong>, which reflects the scheduled/actual arithmetic being bounded rather than extreme delays being eliminated. A near-quarter of shipments arriving <em>early</em> alongside a majority arriving <em>late</em> describes a network that is unpredictable rather than uniformly slow.</p>
<p><strong>Figure 3</strong></p>
<p><em>Delivery-Performance Decomposition</em></p>
<p><img src="assets/fig3_delivery_performance_profile.png" class="img-fluid" alt="Bar chart of delivery_performance_type: Early 43,366 (24.0%), On-time 38,410 (21.3%), Minor Delay 84,708 (46.9%), Moderate Delay 14,035 (7.8%), Critical Delay 0. Title notes 54.7% late, OTIF 45.3%."></p>
<p><em>Note.</em> “Late” = Minor Delay + Moderate Delay = 98,743 order-items = 54.7%.</p>
</section>
<section id="the-mechanism-mode-fixes-the-promise-not-the-capability" class="level3">
<h3 class="anchored" data-anchor-id="the-mechanism-mode-fixes-the-promise-not-the-capability">The mechanism: mode fixes the promise, not the capability</h3>
<p>The late rate is almost entirely a function of <strong>shipping mode</strong>, and the reason is structural (Figure 4). Mode maps one-to-one onto the <em>promised</em> lead time: Same Day is scheduled at 0 days, First Class at 1, Second Class at 2, Standard Class at 4 (the value 3 never occurs). But the <em>achievable</em> transit distribution is essentially the same for the three scheduled tiers — a roughly uniform spread over <strong>2 to 6 days</strong>. Same Day, promised 0 and delivered in 0, is on-time 100% of the time. First Class, promised 1 and delivered in <strong>exactly 2</strong>, is late 100% of the time. Second Class (promised 2) catches only the ~20% of shipments that happen to land at 2 days; Standard Class (promised 4) catches ~60%.</p>
<p><strong>Figure 4</strong></p>
<p><em>Promised Lead Time Versus Achievable Transit, by Shipping Mode</em></p>
<p><img src="assets/fig4_promised_vs_actual_leadtime.png" class="img-fluid" alt="Four small histograms of actual transit days, one per shipping mode, each with a red vertical line at the promised lead time. Same Day: all mass at 0, line at 0, 100% on-time. First Class: all mass at exactly 2, line at 1, 0% on-time. Second Class: uniform mass across 2 to 6, line at 2, 20% on-time. Standard Class: uniform mass across 2 to 6, line at 4, 60% on-time."></p>
<p><em>Note.</em> The physical network delivers in 2–6 days irrespective of the service tier purchased. OTIF differs across tiers only because the promise does.</p>
<p>The OTIF-by-mode ranking follows directly: <strong>First Class 0.0%</strong> (n = 27,814), Second Class 20.3% (n = 35,216), Standard Class 60.2% (n = 107,752), Same Day 100.0% (n = 9,737) (Figure 5, left). By contrast, <strong>customer segment is not a driver</strong>: Corporate 45.5%, Consumer 45.4%, Home Office 44.7% — a spread under one percentage point across 180,519 order-items (Figure 5, right). Whoever placed the order faces the same odds.</p>
<p><strong>Figure 5</strong></p>
<p><em>On-Time Rate by Shipping Mode and by Customer Segment</em></p>
<p><img src="assets/fig5_otif_by_mode_and_segment.png" class="img-fluid" alt="Left: horizontal bars of on-time rate by shipping mode — First Class 0.0%, Second Class 20.3%, Standard Class 60.2%, Same Day 100.0%. Right: horizontal bars by customer segment — Corporate 45.5%, Consumer 45.4%, Home Office 44.7%, a spread under one point."></p>
<p><em>Note.</em> Sample sizes are printed against each bar. The mode axis spans 0–100%; the segment axis spans a 44–46% window.</p>
</section>
<section id="geography-is-not-a-driver-either" class="level3">
<h3 class="anchored" data-anchor-id="geography-is-not-a-driver-either">Geography is not a driver either</h3>
<p>Breaking OTIF out on the full 23-region × 4-mode grid confirms the mechanism (Figure 6). Within each mode column the on-time rate varies by only a few points across every region on four continents: First Class is 0% everywhere, Same Day 100% everywhere, Second Class 16–27%, Standard Class 55–70%. There is no regional bottleneck, no customs-delay signature, no carrier-specific lane failure — <strong>the outcome follows the column, not the row.</strong> Any remediation aimed at a region rather than at the lead-time commitments would be aimed at the wrong axis.</p>
<p><strong>Figure 6</strong></p>
<p><em>On-Time Rate (%) by Destination Region × Shipping Mode</em></p>
<p><img src="assets/fig6_region_mode_otif_heatmap.png" class="img-fluid" alt="Heatmap with 23 destination regions as rows and four shipping modes as columns. The Same Day column is a solid green band at 100 everywhere; First Class is a solid red band at 0 everywhere; Second Class is orange around 16 to 27; Standard Class is yellow-green around 55 to 70. Rows barely vary."></p>
<p><em>Note.</em> Rows sorted by Standard Class on-time rate. Colour runs red (0%) to green (100%).</p>
</section>
<section id="temporal-behaviour-flat-then-truncated" class="level3">
<h3 class="anchored" data-anchor-id="temporal-behaviour-flat-then-truncated">Temporal behaviour: flat, then truncated</h3>
<p>The monthly on-time rate is <strong>flat at ~45% across all 37 months</strong>, ranging only from 42.9% to 46.8% with no trend and no repeating seasonal pattern (Figure 7, top). The 54.7% late rate is a permanent structural feature of this network, not an episode.</p>
<p>The apparent revenue collapse in late 2017 is a <strong>data-truncation artefact, not a business event</strong> (Figure 7, bottom). From October 2017 the order-item count drops from ~5,200/month to ~2,100/month, but the <strong>unique-order count holds steady</strong> (and even rises slightly) — multi-line orders in the final four months are recorded as a single line each. Revenue, summed over order-items, falls mechanically. The last four months should be read as truncated, and any trend, seasonal-decomposition, or “operational instability” reading of that period is not supported by the order-level data.</p>
<p><strong>Figure 7</strong></p>
<p><em>Monthly On-Time Rate and the Late-2017 Volume Truncation</em></p>
<p><img src="assets/fig7_temporal_flat_rate_truncation.png" class="img-fluid" alt="Top panel: monthly on-time rate, a nearly flat line hovering at about 45% for all 37 months. Bottom panel: two monthly series — order-items (rows) steady near 5,200 then dropping sharply to about 2,100 from October 2017, and unique orders steady near 1,750 throughout with a slight rise at the end. The final four months are shaded."></p>
<p><em>Note.</em> Dashed line = the 45.3% overall on-time rate. Shaded band = the truncated final quarter.</p>
</section>
<section id="correlation-structure" class="level3">
<h3 class="anchored" data-anchor-id="correlation-structure">Correlation structure</h3>
<p>Across ten financial and operational variables, two clusters matter. The <strong>delivery variables are mutually collinear</strong>: <code>is_late_actual</code> with <code>late_delivery_risk</code> at <em>r</em> = 0.90, <code>is_late_actual</code> with <code>shipping_delay_days</code> at 0.81, <code>shipping_delay_days</code> with <code>calendar_days_to_ship</code> at 0.63 — any model using more than one would be measuring the same phenomenon repeatedly. On the commercial side, <code>product_price</code> drives <code>net_sales_amount</code> (<em>r</em> = 0.78) and <code>order_item_discount</code> tracks it (0.50), while higher-priced products sell in smaller quantities (<code>product_price</code> × <code>order_item_quantity</code> = −0.48). The starkest cell is <code>net_sales_amount</code> × <code>profit_margin_ratio</code> = <strong>0.00</strong>: revenue scale and margin are structurally decoupled — volume, on its own, does nothing for profitability. The delivery block and the financial block are mutually uncorrelated (all |<em>r</em>| ≤ 0.01), meaning lateness is not predictable from the order’s size, price, or discount.</p>
</section>
<section id="predictive-integrity-of-the-systems-own-flag" class="level3">
<h3 class="anchored" data-anchor-id="predictive-integrity-of-the-systems-own-flag">Predictive integrity of the system’s own flag</h3>
<p>The dataset carries <code>late_delivery_risk</code>, a binary flag the source system assigns before shipment. Checked against the realised outcome, it is highly accurate: <strong>ROC-AUC 0.951</strong>, Brier score 0.048, and a <strong>4.81% error rate</strong> — it agrees with the outcome on 171,845 of 180,519 order-items (95.2%), with a small, near-symmetric residual of 4,220 misses (2.3%) against 4,454 false alarms (2.5%); precision 0.955, recall 0.957 (Figure 8).</p>
<p><strong>Figure 8</strong></p>
<p><em>The System’s Late-Delivery Flag Versus the Realised Outcome</em></p>
<p><img src="assets/fig8_predictive_integrity.png" class="img-fluid" alt="Left: ROC curve for late_delivery_risk against is_late_actual, hugging the top-left corner, AUC 0.951, Brier 0.048, error 4.81%. Right: bar chart — correctly flagged 171,845 (95.2%), missed 4,220 (2.3%), false alarm 4,454 (2.5%)."></p>
<p><em>Note.</em> <code>late_delivery_risk</code> is a 0/1 flag, so the ROC has a single interior operating point.</p>
<p>This cuts two ways. As a data property, it means the flag is a trustworthy feature and a defensible modelling target. As an operational finding, it is pointed: the system correctly identifies which orders will be late for 95 in every 100 — and 54.7% of them still ship late. The information needed to intervene exists before the package moves. The gap is between prediction and action.</p>
</section>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<section id="principal-findings" class="level3">
<h3 class="anchored" data-anchor-id="principal-findings">Principal findings</h3>
<p>Three results stand out. First, <strong>OTIF is 45.3% and structurally constant</strong> — flat across 37 months and identical across customer segments and destination regions. Second, <strong>the outcome is set by the lead-time promise, not by execution variance</strong>: the network delivers in a flat 2–6 days regardless of service tier, so on-time performance is entirely a function of how aggressive the promised window is. First Class, promised the tightest window bar Same Day, fails completely and uniformly. Third, the operation <strong>already predicts its own failures</strong> with 95% accuracy and does not act on the prediction.</p>
</section>
<section id="the-mechanism-worth-naming" class="level3">
<h3 class="anchored" data-anchor-id="the-mechanism-worth-naming">The mechanism worth naming</h3>
<p>The First Class result — 0.0% on-time across 27,814 shipments and all 23 regions — is not a carrier problem or a regional problem. First Class order-items are scheduled at 1 day and take exactly 2, every time. The scheduling logic is committing to a lead time the fulfilment network has never once met. The fix implied by the data is not operational (“ship faster”) but a <strong>planning correction</strong>: align the promised windows for the premium tiers with the network’s demonstrated 2–6 day capability, or re-engineer the physical process to hit them. Until then, every First Class sale is a late delivery booked in advance, and every Second Class sale is an 80% chance of one. The commercial fragility compounds it: with a median profit of $31.52 and a fixed fulfilment cost that already pushes 18.7% of lines into loss, a delay is not a service inconvenience — it is the event that tips a thin-margin order into a negative one.</p>
</section>
<section id="limitations" class="level3">
<h3 class="anchored" data-anchor-id="limitations">Limitations</h3>
<p>The analysis is descriptive and rests on a single operational history; it supports no causal or inferential claim. OTIF is measured as on-time only — the source has no delivered-quantity field, so the “in-full” half of the metric cannot be evaluated and true OTIF may be lower. The catastrophic negative-profit values (to −$4,275) are taken as recorded and not independently verifiable. The final four months are truncated at the order-item grain and were excluded from any trend reading. The <code>delivery_performance_type</code> bins are bounded, which is why the Critical Delay class is empty; the underlying <code>shipping_delay_days</code> still ranges to +4. Finally, <code>late_delivery_risk</code> is a field of unknown provenance — its near-perfect accuracy may reflect that it is computed from the same scheduling inputs rather than an independent forecast.</p>
</section>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion">Conclusion</h3>
<p>Half of this supply chain’s deliveries are late, and the dataset says why with unusual clarity: the promises are miscalibrated against a fixed physical capability, uniformly, everywhere, for three years — and the system that could flag it does, and nothing downstream responds. The operational lever is lead-time planning, not carrier management or segment prioritisation. The companion customer, product, and clickstream studies build on the same Gold layer to examine who is served, what is sold, and how demand is generated.</p>
</section>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<p>Constante, F., Silva, F., &amp; Pereira, A. (2019). <em>DataCo smart supply chain for big data analysis</em> (Version 5) [Data set]. Mendeley Data. https://doi.org/10.17632/8gx2fvg2k6.5</p>
<p>Harris, C. R., Millman, K. J., van der Walt, S. J., Gommers, R., Virtanen, P., Cournapeau, D., Wieser, E., Taylor, J., Berg, S., Smith, N. J., Kern, R., Picus, M., Hoyer, S., van Kerkwijk, M. H., Brett, M., Haldane, A., del Río, J. F., Wiebe, M., Peterson, P., … Oliphant, T. E. (2020). Array programming with NumPy. <em>Nature, 585</em>, 357–362. https://doi.org/10.1038/s41586-020-2649-2</p>
<p>Liu, F. T., Ting, K. M., &amp; Zhou, Z.-H. (2008). Isolation forest. In <em>2008 Eighth IEEE International Conference on Data Mining</em> (pp.&nbsp;413–422). IEEE. https://doi.org/10.1109/ICDM.2008.17</p>
<p>Pedregosa, F., Varoquaux, G., Gramfort, A., Michel, V., Thirion, B., Grisel, O., Blondel, M., Prettenhofer, P., Weiss, R., Dubourg, V., Vanderplas, J., Passos, A., Cournapeau, D., Brucher, M., Perrot, M., &amp; Duchesnay, É. (2011). Scikit-learn: Machine learning in Python. <em>Journal of Machine Learning Research, 12</em>, 2825–2830.</p>
<p>The pandas development team. (2020). <em>pandas-dev/pandas: Pandas</em> (Version latest) [Computer software]. Zenodo. https://doi.org/10.5281/zenodo.3509134</p>
<hr>
<p><em>Analysis and figures by the author. A descriptive operations study of one dataset; no estimate here supports a causal claim, and OTIF is measured as on-time only.</em></p>


<div id="contact" class="connect-section" style="text-align: center; padding: 50px 20px; background: #f9f9f9; border-radius: 15px; border: 1px solid #eaeaea; margin-top: 40px;">
<h3 style="color: #2c3e50; font-weight: 700; margin-bottom: 15px; border: none;" class="anchored">Let's Collaborate</h3>
<p style="color: #666; max-width: 650px; margin: 0 auto 30px auto; font-size: 1.05rem; line-height: 1.6;">Available for high-impact <strong>Business Intelligence, Power BI Engineering, and Advanced Data Analytics</strong> projects. Connect with me or hire me directly through the platforms below.</p>
<div style="display: flex; flex-wrap: wrap; justify-content: center; gap: 12px;">
<a href="https://www.linkedin.com/in/mkmuneer" class="btn btn-primary" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; text-decoration: none;"><i class="bi bi-linkedin"></i> LinkedIn</a>
<a href="https://github.com/mkhanmuneer" class="btn btn-dark" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; text-decoration: none;"><i class="bi bi-github"></i> GitHub</a>
<a href="https://www.kaggle.com/muhammadkhanmuneer" class="btn btn-info" target="_blank" rel="noopener" style="color: white; padding: 12px 25px; min-width: 150px; text-decoration: none;"><i class="bi bi-graph-up"></i> Kaggle</a>
<a href="https://www.upwork.com/freelancers/~018de8553286a1d00c" class="btn btn-outline-success" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; border-width: 2px; font-weight: 600; text-decoration: none;"><i class="bi bi-briefcase"></i> Upwork</a>
<a href="https://www.fiverr.com/neuronvision" class="btn btn-outline-success" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; border-width: 2px; font-weight: 600; text-decoration: none;"><i class="bi bi-lightning-charge"></i> Fiverr</a>
</div>
</div>

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/mkhanmuneer\.github\.io\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 Muhammad Khan Muneer</p>
</div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://www.upwork.com/freelancers/~018de8553286a1d00c">
<p>Hire on Upwork</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="https://www.fiverr.com/neuronvision">
<p>Hire on Fiverr</p>
</a>
  </li>  
</ul>
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mkhanmuneer">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/mkmuneer">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>