<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Muhammad Khan Muneer">
<meta name="keywords" content="medallion architecture, ETL pipeline, bronze silver gold, sentinel encoding, data quality audit, last-click attribution, offer funnel, intention-to-treat, feature engineering, Parquet, idempotent pipeline, data validation, Starbucks capstone, offer response, Python, pandas">
<meta name="description" content="A three-layer medallion ETL pipeline that feeds a five-notebook study of offer response on the Starbucks/Udacity capstone data. Sentinel resolution: age = 118 masks 2,175 customers (12.79%) whose demographics were never collected — invisible to a null count until Silver converts it. Dict-schema harmonisation: the event log stores Python dicts as strings whose offer-id key differs by event type ('offer id' vs 'offer_id'); a one-line or fallback prevents a silent half-funnel loss on every join. Attribution: one rule — viewed before the transaction, transaction inside the validity window, last-click tie-break — stated once and applied across the funnel, transaction, and offer-performance tables. The carry-forward finding: 55.1% of completable offers are completed but only 38.8% are viewed then completed, and the two most-engaged customer archetypes (43% / 43% of the base) diverge 4.8× in median spend on comparable exposure. Output: five Gold Parquet tables, validated for round-trip integrity, shape, and determinism.">

<title>A Medallion Pipeline for Simulated Offer-Response Data: Sentinel Resolution, Dict-Schema Harmonisation, and an Idempotent Attribution Layer – Muhammad Khan Muneer</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-4d9afe2b8d18ee9fa5d0d57b5ed4214d.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-5af9b5ab1fa0c387551d40c1aacb317e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-ca0cfe78a00f84493d894d8af57a3a20.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-5af9b5ab1fa0c387551d40c1aacb317e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": true,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<link rel="stylesheet" href="../../styles/custom.css">
<meta property="og:title" content="Muhammad Khan Muneer — Data Science &amp; BI Portfolio">
<meta property="og:description" content="Engineering ML-driven analytics and automated decision systems.">
<meta property="og:image" content="https://mkhanmuneer.github.io/projects/starbucks-offer-events-medallion-pipeline-sentinel-resolution-dict-harmonisation/assets/fig1_medallion_architecture.png">
<meta property="og:site_name" content="M. Khan Muneer Portfolio">
<meta property="og:image:alt" content="Four boxes left to right. RAW: portfolio.csv, profile.csv, transcript.csv (10 / 17,000 / 306,534 rows), immutable Parquet snapshot. BRONZE: three bronze tables, structure only — renames, dtypes, date parse. SILVER: three silver tables, business logic — sentinel to NaN, key harmonise, channel flags, demographic bands. GOLD: five analytical tables built under one attribution rule. Arrows labelled persist, clean, engineer.">
<meta property="og:image:height" content="810">
<meta property="og:image:width" content="1900">
<meta name="twitter:title" content="A Medallion Pipeline for Simulated Offer-Response Data: Sentinel Resolution, Dict-Schema Harmonisation, and an Idempotent Attribution Layer – Muhammad Khan Muneer">
<meta name="twitter:description" content="A three-layer medallion ETL pipeline that feeds a five-notebook study of offer response on the Starbucks/Udacity capstone data. Sentinel resolution: age = 118 masks 2,175 customers (12.79%) whose demographics were never collected — invisible to a null count until Silver converts it. Dict-schema harmonisation: the event log stores Python dicts as strings whose offer-id key differs by event type ('offer id' vs 'offer_id'); a one-line or fallback prevents a silent half-funnel loss on every join. Attribution: one rule — viewed before the transaction, transaction inside the validity window, last-click tie-break — stated once and applied across the funnel, transaction, and offer-performance tables. The carry-forward finding: 55.1% of completable offers are completed but only 38.8% are viewed then completed, and the two most-engaged customer archetypes (43% / 43% of the base) diverge 4.8× in median spend on comparable exposure. Output: five Gold Parquet tables, validated for round-trip integrity, shape, and determinism.">
<meta name="twitter:image" content="https://mkhanmuneer.github.io/projects/starbucks-offer-events-medallion-pipeline-sentinel-resolution-dict-harmonisation/assets/fig1_medallion_architecture.png">
<meta name="twitter:creator" content="@iMKhanMuneer">
<meta name="twitter:site" content="@iMKhanMuneer">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image:alt" content="Four boxes left to right. RAW: portfolio.csv, profile.csv, transcript.csv (10 / 17,000 / 306,534 rows), immutable Parquet snapshot. BRONZE: three bronze tables, structure only — renames, dtypes, date parse. SILVER: three silver tables, business logic — sentinel to NaN, key harmonise, channel flags, demographic bands. GOLD: five analytical tables built under one attribution rule. Arrows labelled persist, clean, engineer.">
<meta name="twitter:image-height" content="810">
<meta name="twitter:image-width" content="1900">
</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../index.html#featured-projects"> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/mkmuneer"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mkhanmuneer"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://x.com/iMKhanMuneer"> <i class="bi bi-twitter-x" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.kaggle.com/muhammadkhanmuneer"> <i class="bi bi-graph-up" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../index.html#contact"> 
<span class="menu-text">Contact</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#pipeline-architecture" id="toc-pipeline-architecture" class="nav-link" data-scroll-target="#pipeline-architecture">Pipeline architecture</a></li>
  <li><a href="#raw-ingestion-and-audit" id="toc-raw-ingestion-and-audit" class="nav-link" data-scroll-target="#raw-ingestion-and-audit">Raw ingestion and audit</a>
  <ul class="collapse">
  <li><a href="#the-sentinel-age" id="toc-the-sentinel-age" class="nav-link" data-scroll-target="#the-sentinel-age">The sentinel age</a></li>
  <li><a href="#the-event-logs-three-dict-schemas" id="toc-the-event-logs-three-dict-schemas" class="nav-link" data-scroll-target="#the-event-logs-three-dict-schemas">The event log’s three dict schemas</a></li>
  </ul></li>
  <li><a href="#bronze-layer-structural-cleaning" id="toc-bronze-layer-structural-cleaning" class="nav-link" data-scroll-target="#bronze-layer-structural-cleaning">Bronze layer — structural cleaning</a></li>
  <li><a href="#silver-layer-business-logic-cleaning" id="toc-silver-layer-business-logic-cleaning" class="nav-link" data-scroll-target="#silver-layer-business-logic-cleaning">Silver layer — business-logic cleaning</a></li>
  <li><a href="#gold-layer-domain-feature-engineering" id="toc-gold-layer-domain-feature-engineering" class="nav-link" data-scroll-target="#gold-layer-domain-feature-engineering">Gold layer — domain feature engineering</a>
  <ul class="collapse">
  <li><a href="#the-attribution-rule" id="toc-the-attribution-rule" class="nav-link" data-scroll-target="#the-attribution-rule">The attribution rule</a></li>
  <li><a href="#offer-dimension" id="toc-offer-dimension" class="nav-link" data-scroll-target="#offer-dimension">Offer dimension</a></li>
  <li><a href="#offer-events-funnel-reconstruction" id="toc-offer-events-funnel-reconstruction" class="nav-link" data-scroll-target="#offer-events-funnel-reconstruction">Offer-events funnel reconstruction</a></li>
  <li><a href="#transaction-attribution" id="toc-transaction-attribution" class="nav-link" data-scroll-target="#transaction-attribution">Transaction attribution</a></li>
  <li><a href="#customer-features-and-engagement-archetypes" id="toc-customer-features-and-engagement-archetypes" class="nav-link" data-scroll-target="#customer-features-and-engagement-archetypes">Customer features and engagement archetypes</a></li>
  <li><a href="#offer-performance" id="toc-offer-performance" class="nav-link" data-scroll-target="#offer-performance">Offer performance</a></li>
  </ul></li>
  <li><a href="#validation" id="toc-validation" class="nav-link" data-scroll-target="#validation">Validation</a></li>
  <li><a href="#carry-forward-findings" id="toc-carry-forward-findings" class="nav-link" data-scroll-target="#carry-forward-findings">Carry-forward findings</a></li>
  <li><a href="#tools-and-references" id="toc-tools-and-references" class="nav-link" data-scroll-target="#tools-and-references">Tools and references</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">A Medallion Pipeline for Simulated Offer-Response Data: Sentinel Resolution, Dict-Schema Harmonisation, and an Idempotent Attribution Layer</h1>
<p class="subtitle lead">Turning a 10-row offer catalogue, a 17,000-row customer roster, and a 306,534-event log into five validated Gold tables — with a Bronze → Silver → Gold contract, one attribution rule stated once, and a funnel that separates viewing an offer from completing it anyway.</p>
  <div class="quarto-categories">
    <div class="quarto-category">Data Engineering</div>
    <div class="quarto-category">ETL Pipeline</div>
    <div class="quarto-category">Medallion Architecture</div>
    <div class="quarto-category">Dimensional Modelling</div>
    <div class="quarto-category">Data Quality</div>
    <div class="quarto-category">Feature Engineering</div>
    <div class="quarto-category">Attribution Modelling</div>
    <div class="quarto-category">Funnel Analysis</div>
    <div class="quarto-category">Marketing Analytics</div>
    <div class="quarto-category">Python</div>
  </div>
  </div>

<div>
  <div class="description">
    <p>A three-layer medallion ETL pipeline that feeds a five-notebook study of offer response on the Starbucks/Udacity capstone data. <strong>Sentinel resolution:</strong> <code>age = 118</code> masks 2,175 customers (12.79%) whose demographics were never collected — invisible to a null count until Silver converts it. <strong>Dict-schema harmonisation:</strong> the event log stores Python dicts as strings whose offer-id key differs by event type (<code>'offer id'</code> vs <code>'offer_id'</code>); a one-line <code>or</code> fallback prevents a silent half-funnel loss on every join. <strong>Attribution:</strong> one rule — viewed before the transaction, transaction inside the validity window, last-click tie-break — stated once and applied across the funnel, transaction, and offer-performance tables. <strong>The carry-forward finding:</strong> 55.1% of completable offers are completed but only 38.8% are viewed <em>then</em> completed, and the two most-engaged customer archetypes (43% / 43% of the base) diverge 4.8× in median spend on comparable exposure. <strong>Output:</strong> five Gold Parquet tables, validated for round-trip integrity, shape, and determinism.</p>
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Muhammad Khan Muneer </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 2025</p>
    </div>
  </div>
  
    
  </div>
  

<div>
  <div class="keywords">
    <div class="block-title">Keywords</div>
    <p>medallion architecture, ETL pipeline, bronze silver gold, sentinel encoding, data quality audit, last-click attribution, offer funnel, intention-to-treat, feature engineering, Parquet, idempotent pipeline, data validation, Starbucks capstone, offer response, Python, pandas</p>
  </div>
</div>

</header>


<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<p>This is the extract–transform–load stage of a five-notebook study of how customers respond to promotional offers, built on the Starbucks/Udacity “capstone” simulated-offers dataset. It has one job: turn three raw CSV files — a <strong>10-row</strong> offer catalogue, a <strong>17,000-row</strong> customer roster, and a <strong>306,534-row</strong> event log spanning a <strong>714-hour</strong> observation window — into a set of analytical tables that the segmentation, experiment-design, quasi-experimental, and uplift notebooks can each load without re-running any upstream logic. The pipeline produces those tables through a <strong>three-layer medallion architecture</strong> (Bronze → Silver → Gold), where each layer has a strict contract, a distinct fault-isolation boundary, and a persisted Parquet snapshot any consumer can reload independently.</p>
<p>Three structural problems in the raw data shape the whole pipeline, and each is resolved at exactly one layer:</p>
<ul>
<li><strong>A sentinel age.</strong> <code>profile.csv</code> encodes “demographics not collected at signup” as <code>age = 118</code> — a structurally impossible value that co-occurs <em>exactly</em> with missing <code>gender</code> and missing <code>income</code> on <strong>2,175 rows (12.79%)</strong>. A missing-value summary run on the raw frame reports zero nulls in <code>age</code>; the gap is invisible until Silver converts the sentinel to <code>NaN</code>.</li>
<li><strong>A dict stored as a string, with an inconsistent key.</strong> The event log’s <code>value</code> column holds Python dict literals serialised as text. Received and viewed events key the offer identifier as <code>'offer id'</code> (with a space); completed events key it as <code>'offer_id'</code> (with an underscore); transactions carry no offer key at all. A naive lookup on one spelling silently drops half the funnel on every join.</li>
<li><strong>A serialised channel list.</strong> The offer catalogue’s <code>channels</code> column is a stringified list (<code>['web', 'email', 'mobile']</code>) that encodes up to four binary distribution flags as one text field — unusable by any model until parsed.</li>
</ul>
<p>Two findings the pipeline <em>surfaces but does not resolve</em> are handed forward to the analytical notebooks. First, of the completable (non-informational) offer instances, <strong>55.1%</strong> are recorded as completed, but only <strong>38.8%</strong> are viewed <em>and then</em> completed in the correct order — a meaningful share of “completions” come from customers who crossed the spending threshold without ever seeing the offer. Second, the customer base splits almost exactly in half between two archetypes that view most of their offers but diverge sharply on whether that viewing converts. Both point at the same question notebooks 03–05 take up directly: does offer exposure <em>cause</em> spending, or merely correlate with customers who would have spent anyway?</p>
</section>
<section id="pipeline-architecture" class="level2">
<h2 class="anchored" data-anchor-id="pipeline-architecture">Pipeline architecture</h2>
<p>Each layer knows strictly more about the data than the one before it. Bronze knows what the data <em>looks like</em>; Silver knows what it <em>means</em>; Gold produces the <em>analytical surface</em>. The contract for each layer — and, just as important, what each layer must <strong>not</strong> do — is fixed (Figure 1, Table 1).</p>
<p><strong>Figure 1</strong></p>
<p><em>The Bronze → Silver → Gold Medallion Pipeline</em></p>
<p><img src="assets/fig1_medallion_architecture.png" class="img-fluid" alt="Four boxes left to right. RAW: portfolio.csv, profile.csv, transcript.csv (10 / 17,000 / 306,534 rows), immutable Parquet snapshot. BRONZE: three bronze tables, structure only — renames, dtypes, date parse. SILVER: three silver tables, business logic — sentinel to NaN, key harmonise, channel flags, demographic bands. GOLD: five analytical tables built under one attribution rule. Arrows labelled persist, clean, engineer."></p>
<p><em>Note.</em> Every tier persists to Parquet, re-runs idempotently, and is validated for round-trip integrity and shape. Arrows add knowledge, never rows: the customer roster is 17,000 records at Raw, Bronze, Silver, and in the customer-feature Gold table.</p>
<p><strong>Table 1</strong></p>
<p><em>Layer Contracts in the Medallion Pipeline</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Layer</th>
<th style="text-align: left;">Knows</th>
<th style="text-align: left;">Does</th>
<th style="text-align: left;">Must not do</th>
<th style="text-align: left;">Persisted as</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Raw</td>
<td style="text-align: left;">nothing</td>
<td style="text-align: left;">byte-for-byte Parquet snapshot of the three source CSVs</td>
<td style="text-align: left;">any transformation</td>
<td style="text-align: left;"><code>data/raw/parquet/*.parquet</code></td>
</tr>
<tr class="even">
<td style="text-align: left;">Bronze</td>
<td style="text-align: left;">physical structure</td>
<td style="text-align: left;">column rename to <code>snake_case</code>, join-key rename (<code>id</code> → <code>offer_id</code> / <code>customer_id</code>), dtype enforcement, <code>YYYYMMDD</code> → <code>datetime</code>, primary-key dedup check</td>
<td style="text-align: left;">replace sentinels, parse dicts, derive columns</td>
<td style="text-align: left;"><code>*_bronze.parquet</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Silver</td>
<td style="text-align: left;">domain meaning</td>
<td style="text-align: left;">sentinel <code>118</code> → <code>NaN</code> + <code>has_demographics</code> flag, parse the <code>value</code> dict and harmonise its offer-id key, expand <code>channels</code> into four flags, cut age/income/cohort bands, order the event categorical</td>
<td style="text-align: left;">impute, attribute transactions, drop rows</td>
<td style="text-align: left;"><code>*_silver.parquet</code></td>
</tr>
<tr class="even">
<td style="text-align: left;">Gold</td>
<td style="text-align: left;">analytical intent</td>
<td style="text-align: left;">funnel reconstruction, last-click attribution, customer- and offer-level aggregates, engagement archetypes</td>
<td style="text-align: left;">drop rows, touch Bronze or Raw</td>
<td style="text-align: left;">five <code>*_gold.parquet</code> tables</td>
</tr>
</tbody>
</table>
<p><em>Note.</em> Row counts are invariant within each source: portfolio 10, profile 17,000, transcript 306,534 across Raw, Bronze, and Silver. Gold re-grains deliberately — to the offer instance, the transaction, and the customer.</p>
<p>The five Gold tables and their grains are fixed for the lifetime of the project (Table 2). Every downstream notebook loads from <code>data/gold/</code> and touches nothing upstream in normal operation.</p>
<p><strong>Table 2</strong></p>
<p><em>The Five Gold Tables</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Table</th>
<th style="text-align: left;">Grain</th>
<th style="text-align: left;">Rows × cols</th>
<th style="text-align: left;">Primary purpose</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>dim_offer_gold</code></td>
<td style="text-align: left;">one row per offer</td>
<td style="text-align: left;">10 × 15</td>
<td style="text-align: left;">offer catalogue with channel flags and chart labels</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>offer_events_gold</code></td>
<td style="text-align: left;">one row per <code>(customer, offer, received_time)</code></td>
<td style="text-align: left;">76,277 × 19</td>
<td style="text-align: left;">funnel flags — received / viewed / completed — plus latencies</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>transactions_gold</code></td>
<td style="text-align: left;">one row per transaction</td>
<td style="text-align: left;">138,953 × 10</td>
<td style="text-align: left;">last-click offer attribution</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>customer_features_gold</code></td>
<td style="text-align: left;">one row per customer</td>
<td style="text-align: left;">17,000 × 30</td>
<td style="text-align: left;">RFM aggregates, offer-response summary, engagement archetype</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>offer_performance_gold</code></td>
<td style="text-align: left;">one row per offer</td>
<td style="text-align: left;">10 × 23</td>
<td style="text-align: left;">per-offer funnel rates and mean spend per exposure</td>
</tr>
</tbody>
</table>
<p><em>Note.</em> Combined footprint ≈ 6.6 MB on disk. Every downstream notebook loads these five files and nothing upstream.</p>
</section>
<section id="raw-ingestion-and-audit" class="level2">
<h2 class="anchored" data-anchor-id="raw-ingestion-and-audit">Raw ingestion and audit</h2>
<p>Each source loads into memory and is written to Parquet <strong>before any transformation</strong>, as an immutable lineage anchor. A structural audit then runs against the untouched frames; no cleaning happens here, only diagnosis (Table 3).</p>
<p><strong>Table 3</strong></p>
<p><em>The Three Source Tables and the Structural Issue Each Carries</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Source</th>
<th style="text-align: left;">Grain</th>
<th style="text-align: left;">Shape</th>
<th style="text-align: left;">Structural issue found</th>
<th style="text-align: left;">Resolved at</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>portfolio.csv</code></td>
<td style="text-align: left;">one row per offer</td>
<td style="text-align: left;">10 × 7</td>
<td style="text-align: left;"><code>channels</code> is a stringified Python list; <code>id</code> is an ambiguous join key</td>
<td style="text-align: left;">Bronze (rename) → Silver (parse to flags)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>profile.csv</code></td>
<td style="text-align: left;">one row per customer</td>
<td style="text-align: left;">17,000 × 6</td>
<td style="text-align: left;"><code>age = 118</code> sentinel on 2,175 rows; <code>became_member_on</code> is a <code>YYYYMMDD</code> integer</td>
<td style="text-align: left;">Bronze (date parse) → Silver (sentinel → <code>NaN</code>)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>transcript.csv</code></td>
<td style="text-align: left;">one row per event</td>
<td style="text-align: left;">306,534 × 5</td>
<td style="text-align: left;"><code>value</code> holds dict literals as strings; offer-id key differs by event type</td>
<td style="text-align: left;">Silver (<code>ast.literal_eval</code> + key harmonise)</td>
</tr>
</tbody>
</table>
<p><em>Note.</em> A generic missing-value summary on the raw frames reports only structurally-visible nulls — it sees none of the three issues above. Each is found by a targeted diagnostic and fixed at the layer that owns its semantics.</p>
<section id="the-sentinel-age" class="level3">
<h3 class="anchored" data-anchor-id="the-sentinel-age">The sentinel age</h3>
<p>Among the 17,000 customers, <code>gender</code> and <code>income</code> are each missing on exactly <strong>2,175 rows (12.79%)</strong> — an identical count that is not a coincidence. Every one of those rows carries <code>age = 118</code>, and no row outside that set is missing either field. A human aged 118 is structurally impossible, and the IQR fence (Q3 + 1.5·IQR = 115) flags all 2,175 as outliers, but a z-score test does not: the sentinel inflates the mean to 62.53 and the SD to 26.74 enough to hide 118 within three SDs of its own distorted centre. The co-occurrence check — not a univariate outlier test — is the right instrument here.</p>
<p>Silver replaces the exact value <code>118</code> with <code>NaN</code> and derives one <code>has_demographics</code> boolean so no downstream notebook re-implements the three-column mask. After the replacement, the age column collapses from a bimodal artefact to a single coherent population: mean <strong>54.4</strong>, median <strong>55</strong>, range <strong>18–101</strong>, near-zero skew (Figure 2).</p>
<p><strong>Figure 2</strong></p>
<p><em>The <code>age = 118</code> Sentinel Masked 2,175 Customers’ Missing Demographics</em></p>
<p><img src="assets/fig2_age_sentinel_resolution.png" class="img-fluid" alt="Two histograms. Left, the raw roster: a plausible age distribution centred near a median of 58 with a tall isolated red bar at 118 holding 2,175 sentinel rows, annotated 'demographics never collected'. Right, after Silver: the sentinel bar is gone, 14,825 customers remain, median 55, mean 54.4, range 18 to 101."></p>
<p><em>Note.</em> The 2,175 sentinel customers are retained in every table — only their demographic fields become <code>NaN</code>. Left panel <em>n</em> = 17,000; right panel <em>n</em> = 14,825 with recorded demographics.</p>
<p>Among the 14,825 customers with demographics, the roster skews older and middle-income: <strong>28.8%</strong> are aged 65 or over, <strong>72%</strong> are 45 or over, the two central income bands (USD 40–80k) hold <strong>62%</strong>, and gender runs <strong>57.2%</strong> male, <strong>41.3%</strong> female, <strong>1.4%</strong> other (Figure 3). Membership acquisition accelerates sharply from 2015, peaking in 2017–2018 — the final stretch of the observation window (Figure 4).</p>
<p><strong>Figure 3</strong></p>
<p><em>Demographic Composition of the 14,825 Customers with Recorded Demographics</em></p>
<p><img src="assets/fig3_demographic_composition.png" class="img-fluid" alt="Three bar charts. Age band rises monotonically from 5.9 percent under 25 to 28.8 percent at 65 plus. Household income band peaks in the 40-to-60k and 60-to-80k bands at about 30 percent each, tapering to 7.4 percent above 100k. Gender is 57.2 percent male, 41.3 percent female, 1.4 percent other."></p>
<p><em>Note.</em> Bands are cut at conventional life-stage and income points (age 25/35/45/55/65; income USD 40k/60k/80k/100k), not by quantile — so the bar heights carry a real distributional signal.</p>
<p><strong>Figure 4</strong></p>
<p><em>Quarterly Customer Acquisition, 2013–2018</em></p>
<p><img src="assets/fig4_acquisition_trend.png" class="img-fluid" alt="An area-and-line chart of new members per membership quarter. The series is flat near 150 per quarter through 2014, climbs to about 900 across 2015–2016, then spikes above 2,500 in 2017 before falling. A dashed 3-quarter moving average tracks the rise."></p>
<p><em>Note.</em> Membership tenure spans 2013-07-29 to 2018-07-26. The final quarter is partial (the roster is a snapshot mid-2018), which accounts for its sharp drop.</p>
</section>
<section id="the-event-logs-three-dict-schemas" class="level3">
<h3 class="anchored" data-anchor-id="the-event-logs-three-dict-schemas">The event log’s three dict schemas</h3>
<p>The transcript’s 306,534 events are <strong>45.3%</strong> transactions (138,953), <strong>24.9%</strong> offers received (76,277), <strong>18.8%</strong> offers viewed (57,725), and <strong>11.0%</strong> offers completed (33,579). Each event type stores its <code>value</code> payload as a Python dict serialised to text, with a schema that varies by type:</p>
<ul>
<li><code>offer received</code> / <code>offer viewed</code> → <code>{'offer id': '9b98b8...'}</code> — key is <code>'offer id'</code>, with a space</li>
<li><code>offer completed</code> → <code>{'offer_id': '2906b8...', 'reward': 2}</code> — key is <code>'offer_id'</code>, with an underscore, plus the reward paid</li>
<li><code>transaction</code> → <code>{'amount': 8.20}</code> — no offer key at all</li>
</ul>
<p>Silver parses each string with <code>ast.literal_eval</code> (the single-quoted literals are valid Python but invalid JSON) and extracts the identifier with a two-spelling fallback — <code>d.get('offer_id') or d.get('offer id')</code> — in one pass. Without that fallback, a lookup on <code>'offer_id'</code> alone returns <code>None</code> for every received and viewed event, and every funnel join that matches events by offer silently loses its received/viewed side. The parsed frame is then stably sorted on <code>(customer_id, time, event)</code> with the event as an ordered categorical (received &lt; viewed &lt; completed &lt; transaction), so that the “first” event in any later <code>groupby</code> is deterministic.</p>
</section>
</section>
<section id="bronze-layer-structural-cleaning" class="level2">
<h2 class="anchored" data-anchor-id="bronze-layer-structural-cleaning">Bronze layer — structural cleaning</h2>
<p>Bronze applies structural normalisation only; its contract is losslessness, so a hash comparison against the raw Parquet isolates exactly the columns Bronze was documented to touch. Per table: column names are lower-cased and spaced-to-underscored; the pandas index artefact <code>Unnamed: 0</code> becomes <code>row_id</code>; the join key <code>id</code> becomes <code>offer_id</code> (portfolio) or <code>customer_id</code> (profile), and <code>person</code> becomes <code>customer_id</code> (transcript), so all three tables share one key spelling. <code>reward</code>, <code>difficulty</code>, <code>duration</code> become nullable <code>Int64</code>; <code>time</code> becomes <code>Int64</code> hours; <code>became_member_on</code> is parsed from its <code>YYYYMMDD</code> integer to <code>datetime64</code>, confirming a span of <strong>2013-07-29 to 2018-07-26</strong>. The <code>age = 118</code> sentinel, the <code>channels</code> string, and the <code>value</code> dict-string all pass through <strong>unchanged</strong> — their issues are semantic, and semantics belong to Silver. Shapes are invariant: 10 × 7, 17,000 × 6, 306,534 × 5.</p>
</section>
<section id="silver-layer-business-logic-cleaning" class="level2">
<h2 class="anchored" data-anchor-id="silver-layer-business-logic-cleaning">Silver layer — business-logic cleaning</h2>
<p>Silver knows what the data <em>means</em>. It applies four transformations Bronze was forbidden to:</p>
<ul>
<li><strong>Channel-flag derivation.</strong> <code>ast.literal_eval</code> restores the <code>channels</code> list; four binary indicators (<code>has_email</code>, <code>has_mobile</code>, <code>has_social</code>, <code>has_web</code>) and a <code>channel_count</code> (2–4) replace it. <code>has_email</code> turns out constant at 1 across all ten offers — every offer goes out by email — so it carries no discriminating power; <code>has_web</code> is the only flag that varies meaningfully (two offers omit it). An <code>is_informational</code> flag is set once here because informational offers have a structural downstream consequence: with no completion criterion, their <code>was_completed</code> must be <code>NaN</code>, not <code>0</code>.</li>
<li><strong>Sentinel resolution.</strong> <code>age == 118</code> → <code>NaN</code>; <code>has_demographics = age.notna() &amp; gender.notna() &amp; income.notna()</code> splits the base cleanly into <strong>14,825 / 2,175</strong> with no partial-demographic rows.</li>
<li><strong>Band cutting.</strong> Age bands <code>[&lt;25, 25–34, 35–44, 45–54, 55–64, 65+]</code>, income bands <code>[&lt;40k, 40–60k, 60–80k, 80–100k, 100k+]</code>, and membership cohort columns (<code>member_year</code>, <code>member_yearquarter</code>) are derived for downstream segmentation (Figures 3–4).</li>
<li><strong>Dict parsing and key harmonisation</strong> (above). The result adds <code>offer_id</code>, <code>amount</code>, <code>reward_received</code>, <code>time_days</code>; the original <code>value</code> is renamed <code>value_raw</code> and kept as an audit trail rather than dropped.</li>
</ul>
<p>The Silver transcript’s null pattern is now structural rather than dirty: <code>amount</code> is <code>NaN</code> on the 54.7% of rows that are offer events, <code>offer_id</code> is <code>NaN</code> on the 45.3% that are transactions, <code>reward_received</code> is <code>NaN</code> on the 89% that are not completions. Each null rate encodes which event type a row belongs to.</p>
</section>
<section id="gold-layer-domain-feature-engineering" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="gold-layer-domain-feature-engineering">Gold layer — domain feature engineering</h2>
<section id="the-attribution-rule" class="level3">
<h3 class="anchored" data-anchor-id="the-attribution-rule">The attribution rule</h3>
<p>A transaction is attributed to an offer instance when <strong>both</strong> conditions hold: (1) the customer <strong>viewed</strong> the offer before the transaction (<code>view_time ≤ txn_time</code>), and (2) the transaction fell <strong>inside the validity window</strong> (<code>received_time ≤ txn_time ≤ received_time + duration × 24 h</code>). If several viewed instances qualify at once, the one with the <strong>most recent view</strong> wins (last-click); if none qualify, the transaction is <strong>organic</strong>. This is the conventional rule for the Starbucks/Udacity capstone. It is stated here, once, and applied identically in the funnel table, the transaction table, and the offer-performance table — so every downstream reference to “attributed spend” or “offer completion” rests on the same substrate.</p>
</section>
<section id="offer-dimension" class="level3">
<h3 class="anchored" data-anchor-id="offer-dimension">Offer dimension</h3>
<p><code>dim_offer_gold</code> passes the ten-offer catalogue through with <code>duration_hours</code> (attribution math runs in hours) and a human-readable <code>offer_label</code> used as a chart axis label everywhere downstream. The catalogue is small and static (Table 4, with its funnel performance).</p>
</section>
<section id="offer-events-funnel-reconstruction" class="level3">
<h3 class="anchored" data-anchor-id="offer-events-funnel-reconstruction">Offer-events funnel reconstruction</h3>
<p><code>offer_events_gold</code> is the structurally hardest build: one row per <strong>offer instance</strong> — a unique <code>(customer, offer, received_time)</code> triple — accumulating funnel state. Three problems drive the design. <strong>Multiple receipts:</strong> <strong>11,718</strong> <code>(customer, offer)</code> pairs receive the same offer more than once in the window, so a <code>cumcount()</code> <code>instance_idx</code> prevents a view at hour 50 from being attributed to both a receipt at hour 0 and one at hour 300. <strong>Window-scoped lookups:</strong> views and completions are matched to an instance only if they fall in <code>[received_time, window_end_time]</code>, then collapsed to the earliest per instance. <strong>Semantic nulls:</strong> informational offers get <code>was_completed = NaN</code>, which <code>.sum()</code> treats as 0 and <code>.mean()</code> excludes from the denominator — both correct for funnel rates.</p>
<p>The funnel produces <strong>76,277</strong> instances. <strong>56,895 (74.6%)</strong> are viewed within the window — the raw transcript has 57,725 view events, and the <strong>830-event</strong> difference is views that landed outside every validity window and are correctly excluded. Of the completable instances, <strong>33,631 (55.1%)</strong> are completed, but only <strong>23,677 (38.8%)</strong> are viewed <em>and then</em> completed in order (Figure 5). That 16-point gap is the intention-to-treat versus treatment-on-treated distinction, embedded in the schema: a large minority of “completions” are customers who hit the spending threshold without the offer ever entering their awareness.</p>
<p><strong>Figure 5</strong></p>
<p><em>Offer Funnel: 74.6% of Offers Are Viewed, but Only 38.8% Are Viewed Then Completed</em></p>
<p><img src="assets/fig5_offer_funnel.png" class="img-fluid" alt="A horizontal funnel of four bars. Received 76,277 (100 percent). Viewed 56,895 (74.6 percent of received). Completed, completable offers only, 33,631 (55.1 percent of completable). Viewed then completed 23,677 (38.8 percent of completable)."></p>
<p><em>Note.</em> “Completable” excludes the two informational offers (15,235 instances), which have no completion criterion. The drop from 55.1% completed to 38.8% viewed-then-completed is the share of completions that cannot be attributed to the offer having been seen.</p>
</section>
<section id="transaction-attribution" class="level3">
<h3 class="anchored" data-anchor-id="transaction-attribution">Transaction attribution</h3>
<p><code>transactions_gold</code> assigns each of the <strong>138,953</strong> transactions to an offer instance or marks it organic. A surrogate <code>txn_id</code> is assigned first (transactions have no natural key); the candidate pool is restricted to <em>viewed</em> instances (56,895) before the merge; the two-condition window filter reduces the merged cross-product to <strong>122,677</strong> valid <code>(transaction, instance)</code> pairs for <strong>104,657</strong> transactions — so many transactions face several eligible instances at once, resolved by the last-click sort-then-<code>first()</code>.</p>
<p>The result: <strong>104,657 (75.3%)</strong> of transactions are attributed and <strong>34,296 (24.7%)</strong> are organic; in spend terms, attributed transactions carry <strong>USD 1,347,865 (75.9%)</strong> of the <strong>USD 1,775,452</strong> total. The near-match between the 75.3% count share and 75.9% spend share means attributed transactions are only marginally larger on average (USD 12.88 vs USD 12.47) — a mechanical difference with no causal reading. Transaction amounts themselves are severely heavy-tailed: median <strong>USD 8.89</strong>, mean <strong>USD 12.78</strong>, 99th percentile <strong>USD 40.02</strong>, maximum <strong>USD 1,062.28</strong> (Figure 6).</p>
<p><strong>Figure 6</strong></p>
<p><em>Transaction Amounts Are Heavy-Tailed: 99% Under USD 40, a Thin Tail Past USD 1,000</em></p>
<p><img src="assets/fig6_transaction_amount_distribution.png" class="img-fluid" alt="Two panels. Left, a histogram of transactions under USD 60: a tall spike near zero, a shoulder plateau around 4,000 transactions from USD 10 to USD 20, then a long right decline; median USD 8.89, mean USD 12.78. Right, the full range on log–log axes showing a smooth body rising to about USD 20 and a thin tail extending past USD 1,000."></p>
<p><em>Note.</em> Skew 19.2, kurtosis 451. The tail is genuine but rare — the mean sits above the 60th percentile, which is why median spend is the reference statistic in the analytical notebooks.</p>
</section>
<section id="customer-features-and-engagement-archetypes" class="level3">
<h3 class="anchored" data-anchor-id="customer-features-and-engagement-archetypes">Customer features and engagement archetypes</h3>
<p><code>customer_features_gold</code> is one row per customer (17,000 × 30): recency–frequency–monetary aggregates (recency anchored to the fixed window close, not <code>now()</code>, so the feature is reproducible), an offer-response summary, and a single <code>engagement_archetype</code> assigned by strict priority on view rate and conditional completion rate:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Archetype</th>
<th style="text-align: left;">Rule</th>
<th style="text-align: right;"><em>n</em></th>
<th style="text-align: right;">Share</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>engaged_responder</code></td>
<td style="text-align: left;">view rate ≥ 0.5 and completion-given-viewed ≥ 0.5</td>
<td style="text-align: right;">7,321</td>
<td style="text-align: right;">43.1%</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>engaged_non_responder</code></td>
<td style="text-align: left;">view rate ≥ 0.5 and completion-given-viewed &lt; 0.5</td>
<td style="text-align: right;">7,252</td>
<td style="text-align: right;">42.7%</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>low_viewer</code></td>
<td style="text-align: left;">view rate &lt; 0.5</td>
<td style="text-align: right;">1,999</td>
<td style="text-align: right;">11.8%</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>offer_unresponsive</code></td>
<td style="text-align: left;">received offers, made zero transactions</td>
<td style="text-align: right;">422</td>
<td style="text-align: right;">2.5%</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>no_offers</code></td>
<td style="text-align: left;">received zero offers</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0.04%</td>
</tr>
</tbody>
</table>
<p>The two dominant archetypes together are <strong>85.7%</strong> of the base and are <em>equally engaged</em> — both view most of their offers — yet their median spend over the window differs by roughly <strong>4.8×</strong>: <strong>USD 138</strong> for responders (IQR 80–201) against <strong>USD 29</strong> for non-responders (IQR 14–74), with non-overlapping IQRs (Figure 7). Whether that premium is a causal effect of completing offers, or simply reflects that responders are higher-spending customers who would have crossed the threshold anyway, is the question the downstream causal notebooks exist to answer.</p>
<p><strong>Figure 7</strong></p>
<p><em>Two Equally Engaged Archetypes, a 4.8× Gap in Median Spend</em></p>
<p><img src="assets/fig7_spend_by_engagement_archetype.png" class="img-fluid" alt="A boxplot of total spend over the window by engagement archetype, outliers hidden. Engaged responder has a median near USD 138 and an interquartile box from about 80 to 200. Engaged non-responder sits far lower, median about USD 29, box 14 to 74. Low viewer median about USD 34. Offer unresponsive is flat at zero. No offers, n = 6, median about USD 45."></p>
<p><em>Note.</em> The two boxes’ interquartile ranges do not overlap, so the gap is a robust distributional difference, not an outlier artefact. Whiskers are 1.5·IQR; extreme values (up to ~USD 1,600) are omitted for readability.</p>
</section>
<section id="offer-performance" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="offer-performance">Offer performance</h3>
<p><code>offer_performance_gold</code> aggregates the same funnel and attribution data to the offer level, exposing both an intention-to-treat rate (<code>completion_rate</code> = completed ÷ received) and its treatment-on-treated analogue (<code>view_to_completion_rate</code> = viewed-then-completed ÷ viewed), plus mean attributed spend per <em>exposure</em> (denominator = instances distributed, so zero-spend instances count — excluding them would introduce survivorship bias). Assignment is near-uniform (7,571–7,677 instances per offer), so the wide performance spread is a genuine response signal, not an exposure imbalance (Table 4). View rate ranges from <strong>35.6%</strong> (the narrow, hard-to-clear discount: reward 5, spend 20, web+email only) to <strong>96.8%</strong> (the easy discount: reward 2, spend 10, all four channels), with tight 95% Wilson intervals at <em>n</em> ≈ 7,600 (Figure 8).</p>
<p><strong>Table 4</strong></p>
<p><em>The Ten-Offer Catalogue and Its Funnel Performance</em></p>
<div class="column-page-inset">
<table class="caption-top table">
<colgroup>
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Offer</th>
<th style="text-align: left;">Type</th>
<th style="text-align: right;">Reward</th>
<th style="text-align: right;">Spend req.</th>
<th style="text-align: right;">Duration</th>
<th style="text-align: left;">Channels</th>
<th style="text-align: right;">Received</th>
<th style="text-align: right;">View rate</th>
<th style="text-align: right;">Completion rate (ITT)</th>
<th style="text-align: right;">View→completion</th>
<th style="text-align: right;">Mean spend / exposure</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">BOGO r5 / d5 / 7d</td>
<td style="text-align: left;">bogo</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">7 d</td>
<td style="text-align: left;">web, email, mobile</td>
<td style="text-align: right;">7,677</td>
<td style="text-align: right;">54.4%</td>
<td style="text-align: right;">56.7%</td>
<td style="text-align: right;">51.1%</td>
<td style="text-align: right;">USD 13.31</td>
</tr>
<tr class="even">
<td style="text-align: left;">BOGO r5 / d5 / 5d</td>
<td style="text-align: left;">bogo</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">5 d</td>
<td style="text-align: left;">web, email, mobile, social</td>
<td style="text-align: right;">7,571</td>
<td style="text-align: right;">95.5%</td>
<td style="text-align: right;">56.7%</td>
<td style="text-align: right;">49.1%</td>
<td style="text-align: right;">USD 20.21</td>
</tr>
<tr class="odd">
<td style="text-align: left;">BOGO r10 / d10 / 7d</td>
<td style="text-align: left;">bogo</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">7 d</td>
<td style="text-align: left;">email, mobile, social</td>
<td style="text-align: right;">7,658</td>
<td style="text-align: right;">87.7%</td>
<td style="text-align: right;">48.2%</td>
<td style="text-align: right;">39.1%</td>
<td style="text-align: right;">USD 22.20</td>
</tr>
<tr class="even">
<td style="text-align: left;">BOGO r10 / d10 / 5d</td>
<td style="text-align: left;">bogo</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">5 d</td>
<td style="text-align: left;">web, email, mobile, social</td>
<td style="text-align: right;">7,593</td>
<td style="text-align: right;">95.5%</td>
<td style="text-align: right;">43.9%</td>
<td style="text-align: right;">38.2%</td>
<td style="text-align: right;">USD 20.17</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Discount r2 / d10 / 10d</td>
<td style="text-align: left;">discount</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">10 d</td>
<td style="text-align: left;">web, email, mobile, social</td>
<td style="text-align: right;">7,597</td>
<td style="text-align: right;">96.8%</td>
<td style="text-align: right;">70.2%</td>
<td style="text-align: right;">63.6%</td>
<td style="text-align: right;">USD 34.28</td>
</tr>
<tr class="even">
<td style="text-align: left;">Discount r2 / d10 / 7d</td>
<td style="text-align: left;">discount</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">7 d</td>
<td style="text-align: left;">web, email, mobile</td>
<td style="text-align: right;">7,632</td>
<td style="text-align: right;">54.0%</td>
<td style="text-align: right;">52.7%</td>
<td style="text-align: right;">52.2%</td>
<td style="text-align: right;">USD 13.64</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Discount r3 / d7 / 7d</td>
<td style="text-align: left;">discount</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">7 d</td>
<td style="text-align: left;">web, email, mobile, social</td>
<td style="text-align: right;">7,646</td>
<td style="text-align: right;">96.2%</td>
<td style="text-align: right;">67.6%</td>
<td style="text-align: right;">60.0%</td>
<td style="text-align: right;">USD 25.67</td>
</tr>
<tr class="even">
<td style="text-align: left;">Discount r5 / d20 / 10d</td>
<td style="text-align: left;">discount</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">10 d</td>
<td style="text-align: left;">web, email</td>
<td style="text-align: right;">7,668</td>
<td style="text-align: right;">35.6%</td>
<td style="text-align: right;">44.9%</td>
<td style="text-align: right;">49.8%</td>
<td style="text-align: right;">USD 10.24</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Informational / 4d</td>
<td style="text-align: left;">informational</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4 d</td>
<td style="text-align: left;">web, email, mobile</td>
<td style="text-align: right;">7,617</td>
<td style="text-align: right;">50.0%</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">USD 7.47</td>
</tr>
<tr class="even">
<td style="text-align: left;">Informational / 3d</td>
<td style="text-align: left;">informational</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3 d</td>
<td style="text-align: left;">email, mobile, social</td>
<td style="text-align: right;">7,618</td>
<td style="text-align: right;">80.8%</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">USD 9.62</td>
</tr>
</tbody>
</table>
</div>
<p><em>Note.</em> “Spend req.” is the <code>difficulty</code> — the amount that must be spent to complete. ITT = intention-to-treat (completed ÷ received); view→completion is the treatment-on-treated analogue (viewed-then-completed ÷ viewed). Informational offers have no completion criterion. Mean spend per exposure divides attributed spend by <em>all</em> instances distributed, including those that generated none.</p>
<p><strong>Figure 8</strong></p>
<p><em>Per-Offer View Rate with 95% Wilson Intervals: a 35.6% to 96.8% Spread</em></p>
<p><img src="assets/fig8_offer_view_rate_wilson.png" class="img-fluid" alt="A dot-and-interval plot of view rate for the ten offers, sorted low to high. The narrow high-difficulty discount (reward 5, spend 20, web and email only) sits at 35.6 percent at the bottom; the easy all-channel discount (reward 2, spend 10) tops the chart at 96.8 percent. Intervals are narrow, roughly one to two points wide. Dots are coloured by offer type."></p>
<p><em>Note.</em> Wilson score intervals (Wilson, 1927) at <em>n</em> ≈ 7,600 per offer. The two informational offers (no reward incentive) sit mid-distribution at 50% and 81%, so engagement is driven substantially by channel breadth and offer format, not the financial incentive alone.</p>
</section>
</section>
<section id="validation" class="level2">
<h2 class="anchored" data-anchor-id="validation">Validation</h2>
<p>Two independent passes confirm the Gold layer is correctly serialised and analytically ready (Table 5). A <strong>round-trip</strong> re-reads each Parquet file and asserts a zero null rate on a key column — simultaneously a losslessness check across the dtype spectrum (nullable integer, nullable float, string, ordered categorical, boolean). A <strong>shape verification</strong> asserts each table against hardcoded expected dimensions; a deviation is a pipeline bug, not a config value. All checks pass. The two attribution-sensitive tables — <code>offer_events_gold</code> at 76,277 rows and <code>transactions_gold</code> at 138,953 — match exactly, confirming the window filter and last-click groupby are deterministic and the pipeline is idempotent.</p>
<p><strong>Table 5</strong></p>
<p><em>Gold-Layer Validation Results</em></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Table</th>
<th style="text-align: left;">Round-trip key column</th>
<th style="text-align: right;">Null rate</th>
<th style="text-align: left;">Shape check</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>dim_offer_gold</code></td>
<td style="text-align: left;"><code>offer_id</code></td>
<td style="text-align: right;">0.00%</td>
<td style="text-align: left;">pass</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>offer_events_gold</code></td>
<td style="text-align: left;"><code>was_viewed</code></td>
<td style="text-align: right;">0.00%</td>
<td style="text-align: left;">pass (76,277 × 19)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>transactions_gold</code></td>
<td style="text-align: left;"><code>amount</code></td>
<td style="text-align: right;">0.00%</td>
<td style="text-align: left;">pass (138,953 × 10)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>customer_features_gold</code></td>
<td style="text-align: left;"><code>customer_id</code></td>
<td style="text-align: right;">0.00%</td>
<td style="text-align: left;">pass</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>offer_performance_gold</code></td>
<td style="text-align: left;"><code>view_rate</code></td>
<td style="text-align: right;">0.00%</td>
<td style="text-align: left;">pass</td>
</tr>
</tbody>
</table>
<p><em>Note.</em> Each table is re-read from disk, not checked in memory, so a pass is also a Parquet write-read losslessness assertion.</p>
</section>
<section id="carry-forward-findings" class="level2">
<h2 class="anchored" data-anchor-id="carry-forward-findings">Carry-forward findings</h2>
<p>Four facts every downstream notebook must account for:</p>
<ol type="1">
<li><strong>The ITT / TOT gap.</strong> 55.1% of completable instances are completed; only 38.8% are viewed <em>then</em> completed. Raw completion rate overstates the share of customers genuinely influenced by seeing an offer — an intention-to-treat versus treatment-on-treated distinction that the experiment-design and quasi-experimental notebooks build on directly.</li>
<li><strong>The two engaged archetypes.</strong> 43% responders, 43% non-responders, comparable offer exposure, ~4.8× median-spend gap. This is the natural comparison for any causal analysis of offer effectiveness — and the place where a descriptive read is not enough.</li>
<li><strong><code>has_demographics</code> is a hard partition.</strong> 2,175 customers (12.8%) have no age, gender, or income. Any covariate-adjusted or matched analysis must decide explicitly whether to drop them or model the missingness; a silent inner join loses them.</li>
<li><strong>Attribution is a modelling choice, not ground truth.</strong> The last-click rule with a view-before-purchase gate is one defensible convention; first-click and fractional credit are others. “Attributed” means a viewed offer’s window covered the transaction — nothing causal. The 24.7% organic baseline is the reference the causal notebooks estimate incremental effects against.</li>
</ol>
</section>
<section id="tools-and-references" class="level2">
<h2 class="anchored" data-anchor-id="tools-and-references">Tools and references</h2>
<p>Built in Python with <code>pandas</code> and <code>pyarrow</code> for the medallion layers; <code>ast.literal_eval</code> for the dict-string parse; <code>numpy</code> and <code>scipy</code> for the aggregates and the Wilson score intervals in Figure 8. The dataset is the simulated offer-response data from the Starbucks / Udacity Data Scientist Nanodegree capstone, distributed on Kaggle.</p>
<p>Harris, C. R., Millman, K. J., van der Walt, S. J., Gommers, R., Virtanen, P., Cournapeau, D., Wieser, E., Taylor, J., Berg, S., Smith, N. J., Kern, R., Picus, M., Hoyer, S., van Kerkwijk, M. H., Brett, M., Haldane, A., del Río, J. F., Wiebe, M., Peterson, P., … Oliphant, T. E. (2020). Array programming with NumPy. <em>Nature, 585</em>, 357–362. https://doi.org/10.1038/s41586-020-2649-2</p>
<p>The pandas development team. (2020). <em>pandas-dev/pandas: Pandas</em> (Version latest) [Computer software]. Zenodo. https://doi.org/10.5281/zenodo.3509134</p>
<p>Virtanen, P., Gommers, R., Oliphant, T. E., Haberland, M., Reddy, T., Cournapeau, D., Burovski, E., Peterson, P., Weckesser, W., Bright, J., van der Walt, S. J., Brett, M., Wilson, J., Millman, K. J., Mayorov, N., Nelson, A. R. J., Jones, E., Kern, R., Larson, E., … Vázquez-Baeza, Y. (2020). SciPy 1.0: Fundamental algorithms for scientific computing in Python. <em>Nature Methods, 17</em>, 261–272. https://doi.org/10.1038/s41592-019-0686-2</p>
<p>Wilson, E. B. (1927). Probable inference, the law of succession, and statistical inference. <em>Journal of the American Statistical Association, 22</em>(158), 209–212. https://doi.org/10.1080/01621459.1927.10502953</p>
<p>Starbucks, &amp; Udacity. (2018). <em>Starbucks Capstone Challenge simulated offers dataset</em> [Data set]. Retrieved from Kaggle (I. Muliar, mirror). https://www.kaggle.com/datasets/ihormuliar/starbucks-customer-data</p>
<hr>
<p><em>Pipeline and figures by the author. Every figure and headline number here was regenerated from the raw CSVs by a standalone deterministic rebuild; all values match the notebook’s executed outputs. The five Gold Parquet tables described here are the sole data input for every downstream notebook in this study.</em></p>


<div id="contact" class="connect-section" style="text-align: center; padding: 50px 20px; background: #f9f9f9; border-radius: 15px; border: 1px solid #eaeaea; margin-top: 40px;">
<h3 style="color: #2c3e50; font-weight: 700; margin-bottom: 15px; border: none;" class="anchored">Let's Collaborate</h3>
<p style="color: #666; max-width: 650px; margin: 0 auto 30px auto; font-size: 1.05rem; line-height: 1.6;">Available for high-impact <strong>Business Intelligence, Power BI Engineering, and Advanced Data Analytics</strong> projects. Connect with me or hire me directly through the platforms below.</p>
<div style="display: flex; flex-wrap: wrap; justify-content: center; gap: 12px;">
<a href="https://www.linkedin.com/in/mkmuneer" class="btn btn-primary" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; text-decoration: none;"><i class="bi bi-linkedin"></i> LinkedIn</a>
<a href="https://github.com/mkhanmuneer" class="btn btn-dark" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; text-decoration: none;"><i class="bi bi-github"></i> GitHub</a>
<a href="https://www.kaggle.com/muhammadkhanmuneer" class="btn btn-info" target="_blank" rel="noopener" style="color: white; padding: 12px 25px; min-width: 150px; text-decoration: none;"><i class="bi bi-graph-up"></i> Kaggle</a>
<a href="https://www.upwork.com/freelancers/~018de8553286a1d00c" class="btn btn-outline-success" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; border-width: 2px; font-weight: 600; text-decoration: none;"><i class="bi bi-briefcase"></i> Upwork</a>
<a href="https://www.fiverr.com/neuronvision" class="btn btn-outline-success" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; border-width: 2px; font-weight: 600; text-decoration: none;"><i class="bi bi-lightning-charge"></i> Fiverr</a>
</div>
</div>

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/mkhanmuneer\.github\.io\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 Muhammad Khan Muneer</p>
</div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://www.upwork.com/freelancers/~018de8553286a1d00c">
<p>Hire on Upwork</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="https://www.fiverr.com/neuronvision">
<p>Hire on Fiverr</p>
</a>
  </li>  
</ul>
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mkhanmuneer">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/mkmuneer">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>