<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Muhammad Khan Muneer">
<meta name="keywords" content="quasi-experimental, intention-to-treat, instrumental variables, two-stage least squares, local average treatment effect, E-value, unmeasured confounding, plausibly exogenous, Conley Hansen Rossi, standardised mean difference, Benjamini-Hochberg, exclusion restriction, Starbucks capstone, Python, statsmodels">
<meta name="description" content="Observational causal inference on a non-randomised 76,277-instance offer rollout, with the identification limits stated at every step. The constraint: every customer received offers, so there is no treatment-vs-untreated contrast; the ITT analysis compares each offer to the pooled rest, and viewing is instrumented by offer identity. Balance: offer receipt is near-random across the catalogue (39 of 40 covariate cells |SMD| < 0.1), but offer viewing is strongly selective (pre-period spend SMD +0.23) — which is why the IV earns its place. ITT: all 28 per-offer contrasts are significant after Benjamini–Hochberg, so the reading is effect-size-first. One discount (reward 2, difficulty 10, 10-day) is top on view rate (96.8%), completion (70.2%), and spend (+USD 18.44 vs pool); one discount (reward 5, difficulty 20) fails on all three. IV/2SLS: the pooled LATE of viewing on spend is USD 29.15 (95% CI [27.68, 30.63], first-stage F = 999). Sensitivity: the top discount’s E-value is 2.28 (strong); the other nine offers sit at 1.31–1.84 (moderate); the LATE’s Conley–Hansen–Rossi breakdown point is a direct effect of USD 11.66 (40% of the stock estimate).">

<title>Causal Inference on a Rollout That Was Never Randomised: Per-Offer ITT Contrasts, an IV/2SLS LATE for Viewing, and E-Value / Plausibly-Exogenous Sensitivity Bounds – Muhammad Khan Muneer</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-4d9afe2b8d18ee9fa5d0d57b5ed4214d.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-5af9b5ab1fa0c387551d40c1aacb317e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-ca0cfe78a00f84493d894d8af57a3a20.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-5af9b5ab1fa0c387551d40c1aacb317e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": true,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<link rel="stylesheet" href="../../styles/custom.css">
<meta property="og:title" content="Muhammad Khan Muneer — Data Science &amp; BI Portfolio">
<meta property="og:description" content="Engineering ML-driven analytics and automated decision systems.">
<meta property="og:image" content="https://mkhanmuneer.github.io/projects/starbucks-quasi-experimental-causal-inference-itt-iv-late-evalue-sensitivity/assets/fig1_retrospective_power.png">
<meta property="og:site_name" content="M. Khan Muneer Portfolio">
<meta property="og:image:alt" content="Two panels showing minimum detectable effect against sample size per arm on a log axis. Left panel: MDE on a rate falls from about 17 percentage points at n = 100 to 1.98 pp at the realised n of 7,627 per arm. Right panel: MDE on mean spend falls from about USD 17.6 to USD 2.01 at the same n. Each panel marks the realised sample size with a dashed line and a red point.">
<meta property="og:image:height" content="895">
<meta property="og:image:width" content="1842">
<meta name="twitter:title" content="Causal Inference on a Rollout That Was Never Randomised: Per-Offer ITT Contrasts, an IV/2SLS LATE for Viewing, and E-Value / Plausibly-Exogenous Sensitivity Bounds – Muhammad Khan Muneer">
<meta name="twitter:description" content="Observational causal inference on a non-randomised 76,277-instance offer rollout, with the identification limits stated at every step. The constraint: every customer received offers, so there is no treatment-vs-untreated contrast; the ITT analysis compares each offer to the pooled rest, and viewing is instrumented by offer identity. Balance: offer receipt is near-random across the catalogue (39 of 40 covariate cells |SMD| < 0.1), but offer viewing is strongly selective (pre-period spend SMD +0.23) — which is why the IV earns its place. ITT: all 28 per-offer contrasts are significant after Benjamini–Hochberg, so the reading is effect-size-first. One discount (reward 2, difficulty 10, 10-day) is top on view rate (96.8%), completion (70.2%), and spend (+USD 18.44 vs pool); one discount (reward 5, difficulty 20) fails on all three. IV/2SLS: the pooled LATE of viewing on spend is USD 29.15 (95% CI [27.68, 30.63], first-stage F = 999). Sensitivity: the top discount’s E-value is 2.28 (strong); the other nine offers sit at 1.31–1.84 (moderate); the LATE’s Conley–Hansen–Rossi breakdown point is a direct effect of USD 11.66 (40% of the stock estimate).">
<meta name="twitter:image" content="https://mkhanmuneer.github.io/projects/starbucks-quasi-experimental-causal-inference-itt-iv-late-evalue-sensitivity/assets/fig1_retrospective_power.png">
<meta name="twitter:creator" content="@iMKhanMuneer">
<meta name="twitter:site" content="@iMKhanMuneer">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image:alt" content="Two panels showing minimum detectable effect against sample size per arm on a log axis. Left panel: MDE on a rate falls from about 17 percentage points at n = 100 to 1.98 pp at the realised n of 7,627 per arm. Right panel: MDE on mean spend falls from about USD 17.6 to USD 2.01 at the same n. Each panel marks the realised sample size with a dashed line and a red point.">
<meta name="twitter:image-height" content="895">
<meta name="twitter:image-width" content="1842">
</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../index.html#featured-projects"> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/mkmuneer"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mkhanmuneer"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://x.com/iMKhanMuneer"> <i class="bi bi-twitter-x" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.kaggle.com/muhammadkhanmuneer"> <i class="bi bi-graph-up" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../index.html#contact"> 
<span class="menu-text">Contact</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract">Abstract</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#method" id="toc-method" class="nav-link" data-scroll-target="#method">Method</a>
  <ul class="collapse">
  <li><a href="#data-source-and-unit-of-analysis" id="toc-data-source-and-unit-of-analysis" class="nav-link" data-scroll-target="#data-source-and-unit-of-analysis">Data source and unit of analysis</a></li>
  <li><a href="#estimands-and-pre-registration" id="toc-estimands-and-pre-registration" class="nav-link" data-scroll-target="#estimands-and-pre-registration">Estimands and pre-registration</a></li>
  <li><a href="#identification-strategy" id="toc-identification-strategy" class="nav-link" data-scroll-target="#identification-strategy">Identification strategy</a></li>
  <li><a href="#sensitivity-analyses" id="toc-sensitivity-analyses" class="nav-link" data-scroll-target="#sensitivity-analyses">Sensitivity analyses</a></li>
  <li><a href="#software" id="toc-software" class="nav-link" data-scroll-target="#software">Software</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#exposure-and-retrospective-power" id="toc-exposure-and-retrospective-power" class="nav-link" data-scroll-target="#exposure-and-retrospective-power">Exposure and retrospective power</a></li>
  <li><a href="#covariate-balance" id="toc-covariate-balance" class="nav-link" data-scroll-target="#covariate-balance">Covariate balance</a></li>
  <li><a href="#intention-to-treat-effects" id="toc-intention-to-treat-effects" class="nav-link" data-scroll-target="#intention-to-treat-effects">Intention-to-treat effects</a></li>
  <li><a href="#treatment-on-treated-and-the-iv-late" id="toc-treatment-on-treated-and-the-iv-late" class="nav-link" data-scroll-target="#treatment-on-treated-and-the-iv-late">Treatment-on-treated and the IV LATE</a></li>
  <li><a href="#sensitivity-to-the-identification-assumptions" id="toc-sensitivity-to-the-identification-assumptions" class="nav-link" data-scroll-target="#sensitivity-to-the-identification-assumptions">Sensitivity to the identification assumptions</a></li>
  <li><a href="#no-novelty-decay" id="toc-no-novelty-decay" class="nav-link" data-scroll-target="#no-novelty-decay">No novelty decay</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a>
  <ul class="collapse">
  <li><a href="#principal-findings" id="toc-principal-findings" class="nav-link" data-scroll-target="#principal-findings">Principal findings</a></li>
  <li><a href="#the-itt-versus-late-decomposition" id="toc-the-itt-versus-late-decomposition" class="nav-link" data-scroll-target="#the-itt-versus-late-decomposition">The ITT-versus-LATE decomposition</a></li>
  <li><a href="#what-the-sensitivity-bounds-actually-license" id="toc-what-the-sensitivity-bounds-actually-license" class="nav-link" data-scroll-target="#what-the-sensitivity-bounds-actually-license">What the sensitivity bounds actually license</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations">Limitations</a></li>
  <li><a href="#conclusion-and-targeting-recommendation" id="toc-conclusion-and-targeting-recommendation" class="nav-link" data-scroll-target="#conclusion-and-targeting-recommendation">Conclusion and targeting recommendation</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Causal Inference on a Rollout That Was Never Randomised: Per-Offer ITT Contrasts, an IV/2SLS LATE for Viewing, and E-Value / Plausibly-Exogenous Sensitivity Bounds</h1>
<p class="subtitle lead">The Starbucks promotions rollout has no no-offer arm — so the estimands are within-treated differential effects and a compliance-weighted local effect. One discount lifts spend USD 18.44 per exposure (E-value 2.28, the only offer robust to any hidden confounder weaker than 2.28×); the pooled IV LATE for viewing is USD 29.15 but breaks down at 40% exclusion-restriction slippage.</p>
  <div class="quarto-categories">
    <div class="quarto-category">Causal Inference</div>
    <div class="quarto-category">Quasi-Experiment</div>
    <div class="quarto-category">Observational Study</div>
    <div class="quarto-category">Instrumental Variables</div>
    <div class="quarto-category">Intention-to-Treat Analysis</div>
    <div class="quarto-category">Sensitivity Analysis</div>
    <div class="quarto-category">Statistical Inference</div>
    <div class="quarto-category">Marketing Analytics</div>
    <div class="quarto-category">Python</div>
  </div>
  </div>

<div>
  <div class="description">
    <p>Observational causal inference on a non-randomised 76,277-instance offer rollout, with the identification limits stated at every step. <strong>The constraint:</strong> every customer received offers, so there is no treatment-vs-untreated contrast; the ITT analysis compares each offer to the pooled rest, and viewing is instrumented by offer identity. <strong>Balance:</strong> offer <em>receipt</em> is near-random across the catalogue (39 of 40 covariate cells |SMD| &lt; 0.1), but offer <em>viewing</em> is strongly selective (pre-period spend SMD +0.23) — which is why the IV earns its place. <strong>ITT:</strong> all 28 per-offer contrasts are significant after Benjamini–Hochberg, so the reading is effect-size-first. One discount (reward 2, difficulty 10, 10-day) is top on view rate (96.8%), completion (70.2%), and spend (+USD 18.44 vs pool); one discount (reward 5, difficulty 20) fails on all three. <strong>IV/2SLS:</strong> the pooled LATE of viewing on spend is USD 29.15 (95% CI [27.68, 30.63], first-stage F = 999). <strong>Sensitivity:</strong> the top discount’s E-value is 2.28 (strong); the other nine offers sit at 1.31–1.84 (moderate); the LATE’s Conley–Hansen–Rossi breakdown point is a direct effect of USD 11.66 (40% of the stock estimate).</p>
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Muhammad Khan Muneer </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 2025</p>
    </div>
  </div>
  
    
  </div>
  

<div>
  <div class="keywords">
    <div class="block-title">Keywords</div>
    <p>quasi-experimental, intention-to-treat, instrumental variables, two-stage least squares, local average treatment effect, E-value, unmeasured confounding, plausibly exogenous, Conley Hansen Rossi, standardised mean difference, Benjamini-Hochberg, exclusion restriction, Starbucks capstone, Python, statsmodels</p>
  </div>
</div>

</header>


<section id="abstract" class="level2">
<h2 class="anchored" data-anchor-id="abstract">Abstract</h2>
<p>The Starbucks/Udacity capstone promotions rollout was not a randomised experiment: essentially every customer received offers during the 30-day window, so there is no treatment-versus-untreated contrast to exploit. This study estimates two identifiable quantities instead, with the identification limits stated at each step. The <strong>intention-to-treat (ITT)</strong> analysis compares each of the 10 offers against the pooled remainder on view rate, completion rate, and mean attributed spend per exposure (unit of analysis: the offer instance, <em>n</em> = 76,277). The <strong>local average treatment effect (LATE) of viewing</strong> is recovered by instrumenting <code>was_viewed</code> with offer-identity dummies in a two-stage least-squares model. Covariate balance shows that offer <em>receipt</em> is close to random across the catalogue (39 of 40 covariate-by-offer standardised mean differences fall below 0.1), but offer <em>viewing</em> is strongly selective — pre-period spend has a standardised mean difference of +0.23 between viewers and non-viewers — which is precisely why the IV is required. All 28 per-offer ITT contrasts are statistically significant after a Benjamini–Hochberg correction, so interpretation is effect-size-first. One discount (reward USD 2, difficulty USD 10, 10-day) is top on every metric: 96.8% view rate, 70.2% completion, and +USD 18.44 mean spend per exposure versus the pool (95% CI [+16.95, +19.93]); its E-value of 2.28 places it alone in the “strong” robustness band, meaning no unmeasured confounder weaker than a 2.28× risk-ratio association could explain it away. One discount (reward USD 5, difficulty USD 20) fails on all three metrics. The pooled IV LATE of viewing on spend is USD 29.15 (95% CI [27.68, 30.63]; first-stage <em>F</em> = 999), but a Conley–Hansen–Rossi plausibly-exogenous analysis shows the positive-LATE conclusion breaks down once a direct effect of offer identity on spend reaches USD 11.66 — 40% of the stock estimate. The deliverable is a reusable observational-inference stack — pre-registered estimands, balance diagnostics, ITT/IV estimation, and quantified breakdown thresholds — that applies to any rollout where randomisation was not engineered in.</p>
<p><em>Keywords:</em> quasi-experimental, intention-to-treat, instrumental variables, local average treatment effect, E-value, plausibly exogenous, Conley–Hansen–Rossi, standardised mean difference, exclusion restriction</p>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>A previous study in this project designed a clean randomised A/B test on a simulated substrate — the reference standard. This is the compromised case. The observed rollout assigned offers to customers with near-uniform <em>volume</em> per offer, but the offers themselves differ systematically in reward, spend threshold, duration, and channel mix, and no randomisation protects against confounding between which customer received which offer and how much that customer would have spent anyway. There is no no-offer arm: only 6 of 17,000 customers received zero offers.</p>
<p>The response is to do everything with the rigour of observational causal inference and to name the estimands precisely. The <strong>ITT</strong> contrasts recover the effect of <em>receiving</em> a particular offer relative to receiving one of the others — the policy-level “if I send this instead of that, what happens?” — not the effect of an offer versus nothing. The <strong>IV LATE</strong> recovers the effect of <em>viewing</em> an offer, for the compliers whose viewing decision responds to offer characteristics, under an exclusion restriction that offer identity affects spend only through the funnel. Both are informative for a targeting decision; neither is a clean causal effect against a no-treatment counterfactual, and every causal-language claim here refers to those two estimands.</p>
<p>The identification assumptions behind each estimator are not directly testable, so two sensitivity analyses quantify how far each can be violated before its conclusion overturns: an E-value on the ITT contrasts (threat: unmeasured confounding) and a Conley–Hansen–Rossi plausibly-exogenous analysis on the LATE (threat: exclusion-restriction violation).</p>
</section>
<section id="method" class="level2">
<h2 class="anchored" data-anchor-id="method">Method</h2>
<section id="data-source-and-unit-of-analysis" class="level3">
<h3 class="anchored" data-anchor-id="data-source-and-unit-of-analysis">Data source and unit of analysis</h3>
<p>Three Gold-layer tables from the project’s medallion ETL pipeline (built from the Starbucks / Udacity Data Scientist Nanodegree capstone simulated-offers data, distributed on Kaggle): <code>offer_events_gold</code> (one row per offer instance, <em>n</em> = 76,277), <code>transactions_gold</code> (<em>n</em> = 138,953), and <code>customer_features_gold</code> (<em>n</em> = 17,000). The analysis unit is the <strong>offer instance</strong> — a <code>customer × offer × received-time</code> triple — because the same customer appears across multiple offers within the window. The primary outcome, <code>instance_spend</code>, is the sum of attributed transaction amounts within the instance’s attribution window (0 when the offer was never viewed, by the attribution rule). Mean <code>instance_spend</code> is USD 17.67 (median USD 2.31, max USD 1,136.78); 66,501 instances (87.2%) carry complete demographics.</p>
</section>
<section id="estimands-and-pre-registration" class="level3">
<h3 class="anchored" data-anchor-id="estimands-and-pre-registration">Estimands and pre-registration</h3>
<p>The estimands, outcomes, guardrail, and decision rule are fixed before any test runs (Table 1). One quantity is explicitly refused in advance: a single pooled catalogue-wide effect. The 10 offers differ too much in reward, threshold, duration, and channel for a pooled effect to carry a coherent business meaning, so effects are estimated per offer against the pooled rest.</p>
<p><strong>Table 1</strong></p>
<p><em>Pre-Registered Estimands and Decision Rule</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Element</th>
<th style="text-align: left;">Specification</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Unit of analysis</td>
<td style="text-align: left;">Offer instance (<code>customer × offer × received-time</code>), <em>n</em> = 76,277</td>
</tr>
<tr class="even">
<td style="text-align: left;">Primary outcome</td>
<td style="text-align: left;">Mean attributed spend per exposure (USD), within the attribution window</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Secondary outcomes</td>
<td style="text-align: left;">View rate; completion rate among non-informational offers; transaction frequency</td>
</tr>
<tr class="even">
<td style="text-align: left;">Guardrail</td>
<td style="text-align: left;">Total spend per customer over the window (attributed + organic)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ITT estimand</td>
<td style="text-align: left;">Effect of <em>receiving</em> offer A vs the pooled other offers</td>
</tr>
<tr class="even">
<td style="text-align: left;">TOT / LATE estimand</td>
<td style="text-align: left;">Effect of <em>viewing</em> an offer, for compliers (IV)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tests</td>
<td style="text-align: left;">Two-proportion <em>z</em> (rates), Welch <em>t</em> (spend); Benjamini–Hochberg FDR at 5% across 28 contrasts</td>
</tr>
<tr class="even">
<td style="text-align: left;">Decision rule</td>
<td style="text-align: left;">Positive effect declared only if BH-adjusted <em>p</em> &lt; 0.05 <strong>and</strong> the guardrail does not move adversely <strong>and</strong> the arm size supports a meaningful MDE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Refused</td>
<td style="text-align: left;">A single pooled catalogue-wide effect</td>
</tr>
</tbody>
</table>
<p><em>Note.</em> Because spend is Pareto-distributed (Gini 0.525), every contrast is reported with a dollar effect size and a 95% interval, and significance language is reserved for the rare interval that crosses zero.</p>
</section>
<section id="identification-strategy" class="level3">
<h3 class="anchored" data-anchor-id="identification-strategy">Identification strategy</h3>
<p><strong>Covariate balance.</strong> Standardised mean differences (Austin, 2011) for age, income, pre-period transaction count, and pre-period spend, computed per offer (each offer vs the pooled rest) and pooled (viewers vs non-viewers). Imbalances above |SMD| = 0.1 are carried as controls.</p>
<p><strong>ITT.</strong> Per offer: two-proportion <em>z</em>-tests on view rate and completion rate against the pooled baseline, a Welch <em>t</em>-test on mean <code>instance_spend</code>, and a Benjamini–Hochberg (1995) correction across all 28 tests.</p>
<p><strong>IV / 2SLS.</strong> <code>instance_spend</code> regressed on standardised age, standardised income, and <code>was_viewed</code>, with <code>was_viewed</code> instrumented by offer-identity dummy variables (Angrist, Imbens &amp; Rubin, 1996). Offer identity is the one variable the balance table shows is near-random across customers at receipt; the per-offer view-rate spread of 61 percentage points supplies the first-stage variation. The naive as-treated (“viewed vs viewed”) comparison is reported alongside as a biased benchmark.</p>
</section>
<section id="sensitivity-analyses" class="level3">
<h3 class="anchored" data-anchor-id="sensitivity-analyses">Sensitivity analyses</h3>
<p><strong>E-value (VanderWeele &amp; Ding, 2017)</strong> on each ITT spend contrast: the dollar differential is converted to a standardised mean difference against the pooled within-arm spend SD (USD 44.39), mapped to an approximate risk ratio, and expressed as the minimum confounder–exposure and confounder–outcome association strength that would explain the effect away (E ≥ 2.0 = strong robustness; 1.25–2.0 = moderate).</p>
<p><strong>Conley–Hansen–Rossi (2012)</strong> plausibly-exogenous bounds on the LATE: the exclusion restriction is progressively relaxed by allowing a direct effect γ of offer identity on spend, and the adjusted LATE and its union-of-CIs interval are traced as γ grows from 0 to the stock LATE. The breakdown point is the smallest γ at which the interval first includes zero.</p>
</section>
<section id="software" class="level3">
<h3 class="anchored" data-anchor-id="software">Software</h3>
<p>Python 3.10 with <code>statsmodels</code> (<code>IV2SLS</code>, <code>proportions_ztest</code>, <code>multipletests</code>), <code>scipy</code>, <code>numpy</code>, <code>scikit-learn</code> (<code>LogisticRegression</code> for the IPW balance check), and <code>matplotlib</code>. Deterministic throughout — no random seeds — and reproduces bit-for-bit from the Gold tables.</p>
</section>
</section>
<section id="results" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<section id="exposure-and-retrospective-power" class="level3">
<h3 class="anchored" data-anchor-id="exposure-and-retrospective-power">Exposure and retrospective power</h3>
<p>The rollout is volume-balanced: 76,277 instances split across 10 offers between 7,571 and 7,677 each (max-to-min ratio 1.01×), every offer within ±0.7% of the uniform baseline. A χ² test against uniform expectation would fail to reject, but that only confirms the operator was careful about volume — it says nothing about assignment integrity, which is why the offer <em>mix</em> (not volume) is the confounding threat. At ~7,600 instances per arm against a pooled reference of ~68,000, the retrospective minimum detectable effect is <strong>±1.98 percentage points</strong> on a rate and <strong>±USD 2.01</strong> on mean spend (Figure 1). Every per-offer differential of business interest exceeds both thresholds several times over — which is why the analysis is effect-size-first and treats the Benjamini–Hochberg correction as family-wide error control rather than a signal filter.</p>
<p><strong>Figure 1</strong></p>
<p><em>Retrospective Minimum Detectable Effect vs Sample Size per Arm</em></p>
<p><img src="assets/fig1_retrospective_power.png" class="img-fluid" alt="Two panels showing minimum detectable effect against sample size per arm on a log axis. Left panel: MDE on a rate falls from about 17 percentage points at n = 100 to 1.98 pp at the realised n of 7,627 per arm. Right panel: MDE on mean spend falls from about USD 17.6 to USD 2.01 at the same n. Each panel marks the realised sample size with a dashed line and a red point."></p>
<p><em>Note.</em> Two-proportion test around a baseline view rate of 0.746 (left); Welch <em>t</em> around a spend SD of USD 44.39 (right). Both at α = 0.05, 80% power.</p>
</section>
<section id="covariate-balance" class="level3">
<h3 class="anchored" data-anchor-id="covariate-balance">Covariate balance</h3>
<p>Offer <em>receipt</em> is close to random across the catalogue. Of the 40 covariate-by-offer standardised mean differences, only one exceeds 0.1: the top discount (reward 2, difficulty 10, 10-day) shows an SMD of +0.151 on pre-period transaction count — customers who received it had been marginally more active. Age and income are effectively balanced everywhere (all |SMD| ≤ 0.012). This is what a volume-balanced rollout with near-random assignment conditional on platform exposure looks like.</p>
<p>Offer <em>viewing</em>, conditional on receipt, is a different story (Figure 2). Pooled across the catalogue, viewers differ from non-viewers by <strong>+0.23 SMD on pre-period spend</strong> and <strong>+0.18 on pre-period transaction count</strong> — both well past the 0.1 threshold — and lean positive on income (+0.07) and age (+0.05). Engaged, spend-heavy customers view offers at a markedly higher rate, so a naive “viewed vs not-viewed” comparison is contaminated by exactly the traits that predict spend independent of any offer. Inverse-propensity weighting on the four covariates pulls every imbalance back inside 0.1 (pre-period spend +0.23 → +0.07, transactions +0.18 → +0.01), confirming the selection is on observed characteristics — and motivating the IV, which sidesteps it by using offer identity as the instrument.</p>
<p><strong>Figure 2</strong></p>
<p><em>Pooled Covariate Balance — Viewers vs Non-Viewers, Before and After IPW Adjustment</em></p>
<p><img src="assets/fig2_balance_love.png" class="img-fluid" alt="A dumbbell plot of absolute standardised mean differences for four covariates. Before adjustment (red), pre-period spend sits at 0.23 and pre-period transactions at 0.18, both past a dashed 0.1 threshold; income and age are near 0.05. After inverse-propensity weighting (green), all four covariates fall below 0.1."></p>
<p><em>Note.</em> Viewing is selective on observed pre-period behaviour; IPW restores balance, which is why offer identity (near-random at receipt) is used as the IV instrument.</p>
</section>
<section id="intention-to-treat-effects" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="intention-to-treat-effects">Intention-to-treat effects</h3>
<p>All 28 per-offer contrasts — 10 on view rate, 8 on completion rate, 10 on mean spend — are significant after Benjamini–Hochberg at 5% (Table 2). At these sample sizes that is a fact about power, not about the offers, so the reading is by effect size.</p>
<p><strong>On mean spend</strong> (Figure 3). The top discount (reward 2, difficulty 10, 10-day) drives <strong>+USD 18.44 per exposure</strong> versus the pooled baseline of ~USD 16 (95% CI [+16.95, +19.93]) — nearly USD 10 clear of the next offer. The three high-reward BOGOs sit between +USD 2.78 and +USD 5.04 — statistically separated from zero but substantively small. Below the line: two mid-tier offers near −USD 5, the big-reward discount at −USD 8.26, and the two informational offers at −USD 8.94 and −USD 11.33. The informational offers post the largest negative contrasts because the pooled reference is dominated by reward-bearing offers — an offer with no reward mechanically sits below it, which means attributed spend per exposure is the wrong yardstick for informational inventory, not evidence that it destroys value.</p>
<p><strong>On the funnel rates</strong> (Figure 4). The two low-reward, long-duration discounts reach 96–97% of recipients (+24 pp vs baseline); the high-reward, high-threshold discount reaches only 35.6% (−43 pp) — it is effectively hidden from two-thirds of the people who receive it. On completion, the two short-threshold discounts lead at 70.2% and 67.6% (+14 to +17 pp); the 10-day BOGOs and the big-reward discount all under-perform by 8–13 pp.&nbsp;The completion hierarchy is not the reward hierarchy — short-threshold, moderate-reward discounts convert best.</p>
<p><strong>Table 2</strong></p>
<p><em>Per-Offer ITT Effects vs the Pooled Other Offers (offer instance, n = 76,277)</em></p>
<div class="column-page-inset">
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Offer</th>
<th style="text-align: right;">View rate (Δ pp)</th>
<th style="text-align: right;">Completion rate (Δ pp)</th>
<th style="text-align: right;">Mean spend Δ (USD)</th>
<th style="text-align: left;">95% CI</th>
<th style="text-align: right;">E-value</th>
<th style="text-align: left;">Band</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Discount r2 / d10 / 10d</td>
<td style="text-align: right;">96.8% (+24.7)</td>
<td style="text-align: right;">70.2% (+17.2)</td>
<td style="text-align: right;"><strong>+18.44</strong></td>
<td style="text-align: left;">[+16.95, +19.93]</td>
<td style="text-align: right;">2.28</td>
<td style="text-align: left;">strong</td>
</tr>
<tr class="even">
<td style="text-align: left;">Discount r3 / d7 / 7d</td>
<td style="text-align: right;">96.2% (+24.0)</td>
<td style="text-align: right;">67.6% (+14.2)</td>
<td style="text-align: right;">+8.89</td>
<td style="text-align: left;">[+7.78, +10.00]</td>
<td style="text-align: right;">1.69</td>
<td style="text-align: left;">moderate</td>
</tr>
<tr class="odd">
<td style="text-align: left;">BOGO r10 / d10 / 7d</td>
<td style="text-align: right;">87.7% (+14.6)</td>
<td style="text-align: right;">48.2% (−7.9)</td>
<td style="text-align: right;">+5.04</td>
<td style="text-align: left;">[+3.92, +6.16]</td>
<td style="text-align: right;">1.46</td>
<td style="text-align: left;">moderate</td>
</tr>
<tr class="even">
<td style="text-align: left;">BOGO r5 / d5 / 5d</td>
<td style="text-align: right;">95.5% (+23.2)</td>
<td style="text-align: right;">56.7% (+1.9)</td>
<td style="text-align: right;">+2.82</td>
<td style="text-align: left;">[+1.72, +3.91]</td>
<td style="text-align: right;">1.31</td>
<td style="text-align: left;">moderate</td>
</tr>
<tr class="odd">
<td style="text-align: left;">BOGO r10 / d10 / 5d</td>
<td style="text-align: right;">95.5% (+23.2)</td>
<td style="text-align: right;">43.9% (−12.8)</td>
<td style="text-align: right;">+2.78</td>
<td style="text-align: left;">[+1.65, +3.91]</td>
<td style="text-align: right;">1.31</td>
<td style="text-align: left;">moderate</td>
</tr>
<tr class="even">
<td style="text-align: left;">Discount r2 / d10 / 7d</td>
<td style="text-align: right;">54.0% (−22.9)</td>
<td style="text-align: right;">52.7% (−2.7)</td>
<td style="text-align: right;">−4.48</td>
<td style="text-align: left;">[−5.47, −3.49]</td>
<td style="text-align: right;">1.42</td>
<td style="text-align: left;">moderate</td>
</tr>
<tr class="odd">
<td style="text-align: left;">BOGO r5 / d5 / 7d</td>
<td style="text-align: right;">54.4% (−22.4)</td>
<td style="text-align: right;">56.7% (+1.9)</td>
<td style="text-align: right;">−4.85</td>
<td style="text-align: left;">[−5.79, −3.91]</td>
<td style="text-align: right;">1.44</td>
<td style="text-align: left;">moderate</td>
</tr>
<tr class="even">
<td style="text-align: left;">Discount r5 / d20 / 10d</td>
<td style="text-align: right;">35.6% (−43.3)</td>
<td style="text-align: right;">44.9% (−11.7)</td>
<td style="text-align: right;">−8.26</td>
<td style="text-align: left;">[−9.17, −7.35]</td>
<td style="text-align: right;">1.65</td>
<td style="text-align: left;">moderate</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Informational / 3d</td>
<td style="text-align: right;">80.8% (+6.9)</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">−8.94</td>
<td style="text-align: left;">[−9.60, −8.28]</td>
<td style="text-align: right;">1.69</td>
<td style="text-align: left;">moderate</td>
</tr>
<tr class="even">
<td style="text-align: left;">Informational / 4d</td>
<td style="text-align: right;">50.0% (−27.3)</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">−11.33</td>
<td style="text-align: left;">[−11.99, −10.68]</td>
<td style="text-align: right;">1.84</td>
<td style="text-align: left;">moderate</td>
</tr>
</tbody>
</table>
</div>
<p><em>Note.</em> Δ pp = percentage-point difference from the pooled reference. All 28 contrasts significant after Benjamini–Hochberg at 5%. E-value = minimum confounder association (risk-ratio scale) on both arms of the sandwich needed to explain the spend effect away.</p>
<p><strong>Figure 3</strong></p>
<p><em>Per-Offer ITT Effect on Mean Spend, Graded by E-Value Robustness</em></p>
<p><img src="assets/fig3_itt_forest.png" class="img-fluid" alt="A forest plot of the ten offers ordered by ITT effect on mean spend per exposure, from about minus USD 11 for the 4-day informational offer to plus USD 18.4 for the reward-2 10-day discount. Confidence intervals are narrow. Nine offers are coloured gold (moderate E-value band); the top discount is green, annotated E-value 2.28, the only offer in the strong band."></p>
<p><em>Note.</em> Colour = E-value band (green ≥ 2.0 strong; gold 1.25–2.0 moderate). The magnitude of the effect and the magnitude of the robustness scale together.</p>
<p><strong>Figure 4</strong></p>
<p><em>Per-Offer ITT Effects on View Rate and Completion Rate</em></p>
<p><img src="assets/fig4_itt_rates.png" class="img-fluid" alt="Two forest panels. Left, ITT effect on view rate: from minus 43 percentage points for the reward-5 difficulty-20 discount to plus 25 for the reward-2 10-day discount. Right, ITT effect on completion rate: from minus 13 points for the reward-10 5-day BOGO to plus 17 for the reward-2 10-day discount. Points coloured green where the interval is above zero, red where below."></p>
<p><em>Note.</em> Every interval clears the ±1.98 pp retrospective resolution; the completion-rate panel covers non-informational offers only.</p>
</section>
<section id="treatment-on-treated-and-the-iv-late" class="level3">
<h3 class="anchored" data-anchor-id="treatment-on-treated-and-the-iv-late">Treatment-on-treated and the IV LATE</h3>
<p>The naive as-treated comparison (“viewed vs viewed”) rearranges the ranking in ways the causal story does not support (Figure 5). The worst ITT offer — the reward-5 difficulty-20 discount at −USD 8.26 against the ITT pool — appears at <strong>+USD 5.32</strong> in the naive-TOT frame, a USD 14 swing. The mechanism is transparent: that offer is viewed by only 35.6% of recipients, and those viewers are a self-selected, higher-engagement subset. A naive within-viewer contrast captures that selection as effect. An offer that reaches few recipients and keeps the engaged self-selectors among them is causally <em>harder to reach</em>, not causally <em>better</em>.</p>
<p>The IV/2SLS estimate is the causally interpretable counterpart (Figure 6). Instrumenting <code>was_viewed</code> with offer-identity dummies, on the 66,501 instances with complete demographics, the pooled LATE of viewing on <code>instance_spend</code> is <strong>USD 29.15</strong> (SE USD 0.75; 95% CI [27.68, 30.63]). The first-stage <em>F</em> of 999 is far above the weak-instrument threshold, unsurprising given the 61-point per-offer view-rate spread the dummies exploit. The interpretation is specific: this is the causal effect of <em>viewing</em>, for the compliers whose attention responds to offer characteristics — not a population-average effect, and explicitly not the effect of receiving an offer versus receiving nothing. The LATE is larger than any per-offer ITT contrast because the two estimands answer different questions: ITT contrasts an offer against other reward-bearing offers, LATE contrasts viewing against the attribution-zero no-view state.</p>
<p><strong>Figure 5</strong></p>
<p><em>How Conditioning on Viewing Rearranges the Per-Offer Ranking</em></p>
<p><img src="assets/fig5_naive_tot_vs_itt.png" class="img-fluid" alt="A connected-dot plot of the ten offers. For each offer a blue dot marks the ITT effect on mean spend and a gold dot marks the naive treatment-on-treated effect, joined by an arrow. Most offers move toward zero or reverse sign; the reward-5 difficulty-20 discount jumps from about minus USD 8 (ITT) to plus USD 5 (naive TOT)."></p>
<p><em>Note.</em> Naive TOT restricts to viewers, whose composition differs by offer; the shifts are selection, not causal improvement.</p>
<p><strong>Figure 6</strong></p>
<p><em>Instrumental-Variable (2SLS) Identification</em></p>
<p><img src="assets/fig6_iv_schematic.png" class="img-fluid" alt="A three-box diagram: RECEIVED (instrument Z) points to VIEWED (treatment T) labelled first stage F = 999; VIEWED points to SPEND (outcome Y) labelled second stage LATE USD 29.15. A dashed red arc from RECEIVED to SPEND is crossed out, labelled exclusion restriction — no direct Received-to-Spend path — breaks down if a direct effect reaches USD 11.66. Age and income enter both stages as covariates."></p>
<p><em>Note.</em> The instrument set is the offer-identity dummy variables; age and income are exogenous covariates in both stages.</p>
</section>
<section id="sensitivity-to-the-identification-assumptions" class="level3">
<h3 class="anchored" data-anchor-id="sensitivity-to-the-identification-assumptions">Sensitivity to the identification assumptions</h3>
<p><strong>Unmeasured confounding (E-value).</strong> Of the 10 ITT spend contrasts, only the top discount reaches the strong band, at <strong>E = 2.28</strong>: an unmeasured confounder would need a 2.28× risk-ratio association with both offer receipt and spend to nullify its +USD 18.44 effect — far beyond the strongest measured imbalance (|SMD| = 0.151). The other nine offers sit in the moderate band (E = 1.31–1.84); the two smallest BOGO contrasts (E = 1.31) are fragile, since a confounder only 1.3× stronger than anything measured would suffice. The magnitude of the effect and the magnitude of the robustness move together — the offers whose business decision matters most are the ones best protected against hidden confounding.</p>
<p><strong>Exclusion-restriction violation (Conley–Hansen–Rossi).</strong> As a direct effect of offer identity on spend is allowed to grow, the adjusted LATE falls and its interval widens (Table 3, Figure 7). The LATE survives the first ~30% of slippage cleanly; at <strong>γ/LATE = 0.40</strong> the interval first includes zero — a direct effect of <strong>USD 11.66 per exposure</strong> (40% of the stock LATE) would render the positive-LATE conclusion unsupported. Whether 40% is a comfortable margin depends on whether brand-halo, anchor-pricing, or notification-preview effects of offer metadata can plausibly move spend by that magnitude outside the funnel. None is zero a priori. The reading is <em>moderate</em> robustness — a best estimate with a named caveat, not a settled number.</p>
<p><strong>Table 3</strong></p>
<p><em>Conley–Hansen–Rossi Bounds on the IV LATE Under Exclusion-Restriction Violation</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Direct effect γ (fraction of LATE)</th>
<th style="text-align: right;">γ (USD)</th>
<th style="text-align: right;">Adjusted LATE (USD)</th>
<th style="text-align: left;">95% CI (USD)</th>
<th style="text-align: left;">Interval includes 0</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">29.15</td>
<td style="text-align: left;">[27.68, 30.63]</td>
<td style="text-align: left;">no</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.2</td>
<td style="text-align: right;">5.83</td>
<td style="text-align: right;">19.62</td>
<td style="text-align: left;">[9.98, 29.27]</td>
<td style="text-align: left;">no</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.3</td>
<td style="text-align: right;">8.75</td>
<td style="text-align: right;">14.86</td>
<td style="text-align: left;">[0.49, 29.23]</td>
<td style="text-align: left;">no</td>
</tr>
<tr class="even">
<td style="text-align: right;"><strong>0.4</strong></td>
<td style="text-align: right;"><strong>11.66</strong></td>
<td style="text-align: right;"><strong>10.09</strong></td>
<td style="text-align: left;"><strong>[−9.02, 29.21]</strong></td>
<td style="text-align: left;"><strong>yes</strong></td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.6</td>
<td style="text-align: right;">17.49</td>
<td style="text-align: right;">0.57</td>
<td style="text-align: left;">[−28.06, 29.19]</td>
<td style="text-align: left;">yes</td>
</tr>
<tr class="even">
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">29.15</td>
<td style="text-align: right;">−18.49</td>
<td style="text-align: left;">[−66.16, 29.17]</td>
<td style="text-align: left;">yes</td>
</tr>
</tbody>
</table>
<p><em>Note.</em> Abridged from an 11-point grid. Breakdown point in bold.</p>
<p><strong>Figure 7</strong></p>
<p><em>Plausibly-Exogenous IV: Adjusted LATE and Interval as the Exclusion Restriction Is Relaxed</em></p>
<p><img src="assets/fig7_cjr_bounds.png" class="img-fluid" alt="A line-and-band chart. The adjusted LATE falls from USD 29 at gamma = 0 to about minus USD 18 at gamma equal to the full LATE. A shaded 95% CI band widens as gamma grows. A dotted vertical line at gamma over LATE = 0.40 marks where the lower band first crosses zero, annotated breakdown, direct effect USD 11.66."></p>
<p><em>Note.</em> Union-of-CIs inference. The positive-LATE conclusion is robust to roughly a third of exclusion-restriction slippage, no more.</p>
</section>
<section id="no-novelty-decay" class="level3">
<h3 class="anchored" data-anchor-id="no-novelty-decay">No novelty decay</h3>
<p>Mean attributed spend per viewed instance is flat across the 30-day window — between USD 22 and USD 26 by day of receipt, mean USD 23.66 (Figure 8). Within this observation window there is no evidence of the effect fading; a longer horizon might attenuate the discount lifts and elevate the brand-maintenance value of informational offers, but that is beyond what 30 days can show.</p>
<p><strong>Figure 8</strong></p>
<p><em>Mean Attributed Spend per Viewed Instance by Day of Offer Receipt</em></p>
<p><img src="assets/fig8_timedecay.png" class="img-fluid" alt="A point-and-error-bar chart of mean attributed spend per viewed instance against day of offer receipt within the 30-day window. The seven points sit between USD 22 and USD 26 with a dashed reference line at the mean of USD 23.66; there is no downward trend."></p>
<p><em>Note.</em> Points shown only for receipt days with at least 20 viewed and 20 non-viewed instances.</p>
</section>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<section id="principal-findings" class="level3">
<h3 class="anchored" data-anchor-id="principal-findings">Principal findings</h3>
<p>Under the identification assumptions the sensitivity analyses quantify: (1) one discount — the cheapest reward paired with the longest attribution window — dominates the catalogue on view rate, completion, and spend simultaneously, and it is the only offer whose spend effect is robust (E = 2.28) to any plausible hidden confounder. (2) One discount — the highest reward paired with the highest spend threshold — fails on reach, completion, and spend simultaneously, an interpretable double failure of high threshold and low visibility. (3) The informational offers post the largest negative spend contrasts by construction of the pooled reference; they should be measured on total spend or a reach proxy, not attributed spend per exposure. (4) The pooled LATE of viewing (USD 29.15) dwarfs the per-offer ITT contrasts, consistent with funnel-reach being the binding constraint rather than persuasion — conditional on the exclusion restriction holding approximately.</p>
</section>
<section id="the-itt-versus-late-decomposition" class="level3">
<h3 class="anchored" data-anchor-id="the-itt-versus-late-decomposition">The ITT-versus-LATE decomposition</h3>
<p>The scale gap between the per-offer ITT differentials (single to mid-teens of dollars) and the pooled LATE (USD 29) is not a contradiction. ITT asks “what happens when you send this offer instead of another one” — a contrast against a reference of other reward-bearing offers. LATE asks “what happens when a complier actually sees an offer, regardless of which” — a contrast against the no-view state, which in this attribution scheme is zero. The IV framework separates the effect of the offer <em>mix</em> from the effect of <em>funnel-reaching</em> the customer, and the second is the larger lever if the exclusion restriction is approximately right.</p>
</section>
<section id="what-the-sensitivity-bounds-actually-license" class="level3">
<h3 class="anchored" data-anchor-id="what-the-sensitivity-bounds-actually-license">What the sensitivity bounds actually license</h3>
<p>A stakeholder should lean more heavily on the ITT findings than on the LATE. The E-value analysis gives a clean argument for the top discount and a directional-but-not-unassailable one for the rest. The LATE’s 40% breakdown point is moderate: enough to report USD 29.15 as a best estimate with the exclusion-restriction caveat attached, not enough to treat it as settled or to build a channel-investment case that does not survive its own sensitivity check.</p>
</section>
<section id="limitations" class="level3">
<h3 class="anchored" data-anchor-id="limitations">Limitations</h3>
<p>The ITT contrasts are within-treated differential effects, not treatment-versus-untreated effects — a clean counterfactual needs a randomised no-offer holdout. The IV exclusion restriction (offer identity affects spend only through viewing) is plausible but unverifiable; the breakdown point is USD 11.66. The heterogeneity analysis attempted in the source work collapses into an attribution tautology — <code>instance_spend</code> is zero for non-viewed instances by construction, so a “viewed vs not-viewed” lift by subgroup equals mean spend among viewers by definition — and is not reported here; per-customer effect estimation is the subject of the next study. The 2,175 customers without demographics are excluded from the balance and IV work by listwise deletion. And 30 days is a short-run window: these are lifts per exposure, not lifetime-value estimates.</p>
</section>
<section id="conclusion-and-targeting-recommendation" class="level3">
<h3 class="anchored" data-anchor-id="conclusion-and-targeting-recommendation">Conclusion and targeting recommendation</h3>
<p>Scale the cheapest-reward-longest-duration discount — the one offer where the evidence is unambiguous on every axis and robust to any confounder weaker than 2.28×. Retire the big-reward-big-threshold discount and free the catalogue slot for a randomised test. Reframe the informational offers as brand-maintenance inventory measured on total spend, not attributed spend. Keep BOGOs but do not scale them on the pooled differential alone. Treat the LATE-implied case for investing in notification delivery as conditional on the exclusion restriction, and fund the infrastructure — a pre-period window, a randomised holdout arm, randomised notification variation — that would let the next rollout be analysed as a clean experiment rather than reconstructed as a quasi-experiment.</p>
</section>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<p>Angrist, J. D., Imbens, G. W., &amp; Rubin, D. B. (1996). Identification of causal effects using instrumental variables. <em>Journal of the American Statistical Association, 91</em>(434), 444–455. https://doi.org/10.1080/01621459.1996.10476902</p>
<p>Austin, P. C. (2011). An introduction to propensity score methods for reducing the effects of confounding in observational studies. <em>Multivariate Behavioral Research, 46</em>(3), 399–424. https://doi.org/10.1080/00273171.2011.568786</p>
<p>Benjamini, Y., &amp; Hochberg, Y. (1995). Controlling the false discovery rate: A practical and powerful approach to multiple testing. <em>Journal of the Royal Statistical Society: Series B, 57</em>(1), 289–300. https://doi.org/10.1111/j.2517-6161.1995.tb02031.x</p>
<p>Conley, T. G., Hansen, C. B., &amp; Rossi, P. E. (2012). Plausibly exogenous. <em>The Review of Economics and Statistics, 94</em>(1), 260–272. https://doi.org/10.1162/REST_a_00139</p>
<p>Rosenbaum, P. R., &amp; Rubin, D. B. (1983). The central role of the propensity score in observational studies for causal effects. <em>Biometrika, 70</em>(1), 41–55. https://doi.org/10.1093/biomet/70.1.41</p>
<p>Seabold, S., &amp; Perktold, J. (2010). statsmodels: Econometric and statistical modeling with Python. <em>Proceedings of the 9th Python in Science Conference</em>, 92–96. https://doi.org/10.25080/Majora-92bf1922-011</p>
<p>VanderWeele, T. J., &amp; Ding, P. (2017). Sensitivity analysis in observational research: Introducing the E-value. <em>Annals of Internal Medicine, 167</em>(4), 268–274. https://doi.org/10.7326/M16-2607</p>
<p>Welch, B. L. (1947). The generalization of “Student’s” problem when several different population variances are involved. <em>Biometrika, 34</em>(1–2), 28–35. https://doi.org/10.1093/biomet/34.1-2.28</p>
<p>Starbucks, &amp; Udacity. (2018). <em>Starbucks Capstone Challenge simulated offers dataset</em> [Data set]. Retrieved from Kaggle (I. Muliar, mirror). https://www.kaggle.com/datasets/ihormuliar/starbucks-customer-data</p>
<hr>
<p><em>Quasi-experimental study on a non-randomised rollout. The ITT contrasts recover within-treated differential effects, not treatment-versus-untreated effects; the IV LATE rests on an exclusion restriction that cannot be verified from this data and whose breakdown point is USD 11.66 per exposure. Every figure and number was regenerated from the Gold tables by a deterministic pipeline.</em></p>


<div id="contact" class="connect-section" style="text-align: center; padding: 50px 20px; background: #f9f9f9; border-radius: 15px; border: 1px solid #eaeaea; margin-top: 40px;">
<h3 style="color: #2c3e50; font-weight: 700; margin-bottom: 15px; border: none;" class="anchored">Let's Collaborate</h3>
<p style="color: #666; max-width: 650px; margin: 0 auto 30px auto; font-size: 1.05rem; line-height: 1.6;">Available for high-impact <strong>Business Intelligence, Power BI Engineering, and Advanced Data Analytics</strong> projects. Connect with me or hire me directly through the platforms below.</p>
<div style="display: flex; flex-wrap: wrap; justify-content: center; gap: 12px;">
<a href="https://www.linkedin.com/in/mkmuneer" class="btn btn-primary" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; text-decoration: none;"><i class="bi bi-linkedin"></i> LinkedIn</a>
<a href="https://github.com/mkhanmuneer" class="btn btn-dark" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; text-decoration: none;"><i class="bi bi-github"></i> GitHub</a>
<a href="https://www.kaggle.com/muhammadkhanmuneer" class="btn btn-info" target="_blank" rel="noopener" style="color: white; padding: 12px 25px; min-width: 150px; text-decoration: none;"><i class="bi bi-graph-up"></i> Kaggle</a>
<a href="https://www.upwork.com/freelancers/~018de8553286a1d00c" class="btn btn-outline-success" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; border-width: 2px; font-weight: 600; text-decoration: none;"><i class="bi bi-briefcase"></i> Upwork</a>
<a href="https://www.fiverr.com/neuronvision" class="btn btn-outline-success" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; border-width: 2px; font-weight: 600; text-decoration: none;"><i class="bi bi-lightning-charge"></i> Fiverr</a>
</div>
</div>

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/mkhanmuneer\.github\.io\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 Muhammad Khan Muneer</p>
</div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://www.upwork.com/freelancers/~018de8553286a1d00c">
<p>Hire on Upwork</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="https://www.fiverr.com/neuronvision">
<p>Hire on Fiverr</p>
</a>
  </li>  
</ul>
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mkhanmuneer">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/mkmuneer">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>