<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Muhammad Khan Muneer">
<meta name="keywords" content="algorithmic fairness, equity audit, subgroup analysis, equalized odds, demographic parity, false-negative rate, stroke screening, class imbalance, age disparity, cryptogenic stroke, model governance, Youden threshold, Python">
<meta name="description" content="A subgroup audit of three tuned stroke-screening models on a 1,022-patient test set (50 events). The headline conceals a failure: overall recall of ~0.82 is a senior-band metric — the 60+ band holds 76% of test strokes and is detected at ~0.97, while every model misses every stroke in the mid and young bands. Inverted risk-factor disparity: patients with hypertension, heart disease, or high glucose are detected better; the markerless stroke is the hardest case. A vacuous-fairness trap: the linear model at a 0.10 threshold scores a perfect Equalized-Odds gap of 0.00 — only because it flags every patient positive.">

<title>A Clinical ML Equity Audit: Age-Band Disparities, Risk-Factor Detection Asymmetry, and Fairness Metrics – Muhammad Khan Muneer</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-4d9afe2b8d18ee9fa5d0d57b5ed4214d.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-5af9b5ab1fa0c387551d40c1aacb317e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-ca0cfe78a00f84493d894d8af57a3a20.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-5af9b5ab1fa0c387551d40c1aacb317e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": true,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<link rel="stylesheet" href="../../styles/custom.css">
<meta property="og:title" content="Muhammad Khan Muneer — Data Science &amp; BI Portfolio">
<meta property="og:description" content="Engineering ML-driven analytics and automated decision systems.">
<meta property="og:image" content="https://mkhanmuneer.github.io/projects/clinical-ml-equity-audit-age-band-disparities-risk-factor-detection-asymmetry-fairness-metrics/assets/fig1_recall_by_age_band.png">
<meta property="og:site_name" content="M. Khan Muneer Portfolio">
<meta property="og:image:alt" content="Grouped bars of recall for three models across four age bands. Young and mid bands: all bars at zero. Mature: GLMNET zero, XGBoost and LightGBM at 0.67. Senior: 0.92 to 0.97 for all three.">
<meta property="og:image:height" content="887">
<meta property="og:image:width" content="1872">
<meta name="twitter:title" content="A Clinical ML Equity Audit: Age-Band Disparities, Risk-Factor Detection Asymmetry, and Fairness Metrics – Muhammad Khan Muneer">
<meta name="twitter:description" content="A subgroup audit of three tuned stroke-screening models on a 1,022-patient test set (50 events). The headline conceals a failure: overall recall of ~0.82 is a senior-band metric — the 60+ band holds 76% of test strokes and is detected at ~0.97, while every model misses every stroke in the mid and young bands. Inverted risk-factor disparity: patients with hypertension, heart disease, or high glucose are detected better; the markerless stroke is the hardest case. A vacuous-fairness trap: the linear model at a 0.10 threshold scores a perfect Equalized-Odds gap of 0.00 — only because it flags every patient positive.">
<meta name="twitter:image" content="https://mkhanmuneer.github.io/projects/clinical-ml-equity-audit-age-band-disparities-risk-factor-detection-asymmetry-fairness-metrics/assets/fig1_recall_by_age_band.png">
<meta name="twitter:creator" content="@iMKhanMuneer">
<meta name="twitter:site" content="@iMKhanMuneer">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image:alt" content="Grouped bars of recall for three models across four age bands. Young and mid bands: all bars at zero. Mature: GLMNET zero, XGBoost and LightGBM at 0.67. Senior: 0.92 to 0.97 for all three.">
<meta name="twitter:image-height" content="887">
<meta name="twitter:image-width" content="1872">
</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../index.html#featured-projects"> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/mkmuneer"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mkhanmuneer"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://x.com/iMKhanMuneer"> <i class="bi bi-twitter-x" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.kaggle.com/muhammadkhanmuneer"> <i class="bi bi-graph-up" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../index.html#contact"> 
<span class="menu-text">Contact</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract">Abstract</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#method" id="toc-method" class="nav-link" data-scroll-target="#method">Method</a>
  <ul class="collapse">
  <li><a href="#models-and-test-set" id="toc-models-and-test-set" class="nav-link" data-scroll-target="#models-and-test-set">Models and test set</a></li>
  <li><a href="#subgroup-axes" id="toc-subgroup-axes" class="nav-link" data-scroll-target="#subgroup-axes">Subgroup axes</a></li>
  <li><a href="#thresholds-and-metrics" id="toc-thresholds-and-metrics" class="nav-link" data-scroll-target="#thresholds-and-metrics">Thresholds and metrics</a></li>
  <li><a href="#software-and-reproducibility" id="toc-software-and-reproducibility" class="nav-link" data-scroll-target="#software-and-reproducibility">Software and reproducibility</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#age-band-overall-recall-is-a-senior-band-metric" id="toc-age-band-overall-recall-is-a-senior-band-metric" class="nav-link" data-scroll-target="#age-band-overall-recall-is-a-senior-band-metric">Age band: overall recall is a senior-band metric</a></li>
  <li><a href="#clinical-risk-factors-the-disparity-inverts" id="toc-clinical-risk-factors-the-disparity-inverts" class="nav-link" data-scroll-target="#clinical-risk-factors-the-disparity-inverts">Clinical risk factors: the disparity inverts</a></li>
  <li><a href="#gender-a-modest-architecture-dependent-gap" id="toc-gender-a-modest-architecture-dependent-gap" class="nav-link" data-scroll-target="#gender-a-modest-architecture-dependent-gap">Gender: a modest, architecture-dependent gap</a></li>
  <li><a href="#formal-fairness-gaps" id="toc-formal-fairness-gaps" class="nav-link" data-scroll-target="#formal-fairness-gaps">Formal fairness gaps</a></li>
  <li><a href="#the-vacuous-fairness-result" id="toc-the-vacuous-fairness-result" class="nav-link" data-scroll-target="#the-vacuous-fairness-result">The vacuous-fairness result</a></li>
  <li><a href="#consolidated-worst-case-surface" id="toc-consolidated-worst-case-surface" class="nav-link" data-scroll-target="#consolidated-worst-case-surface">Consolidated worst-case surface</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a>
  <ul class="collapse">
  <li><a href="#what-the-headline-number-hides" id="toc-what-the-headline-number-hides" class="nav-link" data-scroll-target="#what-the-headline-number-hides">What the headline number hides</a></li>
  <li><a href="#two-disparities-opposite-directions" id="toc-two-disparities-opposite-directions" class="nav-link" data-scroll-target="#two-disparities-opposite-directions">Two disparities, opposite directions</a></li>
  <li><a href="#the-screening-mode-trap" id="toc-the-screening-mode-trap" class="nav-link" data-scroll-target="#the-screening-mode-trap">The screening-mode trap</a></li>
  <li><a href="#deployment-implications" id="toc-deployment-implications" class="nav-link" data-scroll-target="#deployment-implications">Deployment implications</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations">Limitations</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">A Clinical ML Equity Audit: Age-Band Disparities, Risk-Factor Detection Asymmetry, and Fairness Metrics</h1>
<p class="subtitle lead">Decomposing a stroke-screening model’s headline recall across five clinical and demographic subgroups — and showing that a single overall number conceals a structural age-band failure.</p>
  <div class="quarto-categories">
    <div class="quarto-category">Machine Learning</div>
    <div class="quarto-category">Classification</div>
    <div class="quarto-category">Algorithmic Fairness</div>
    <div class="quarto-category">Model Evaluation</div>
    <div class="quarto-category">Model Auditing</div>
    <div class="quarto-category">Subgroup Analysis</div>
    <div class="quarto-category">Gradient Boosting</div>
    <div class="quarto-category">Clinical Research</div>
    <div class="quarto-category">Healthcare Analytics</div>
    <div class="quarto-category">Python</div>
  </div>
  </div>

<div>
  <div class="description">
    <p>A subgroup audit of three tuned stroke-screening models on a 1,022-patient test set (50 events). <strong>The headline conceals a failure:</strong> overall recall of ~0.82 is a senior-band metric — the 60+ band holds 76% of test strokes and is detected at ~0.97, while every model misses <em>every</em> stroke in the mid and young bands. <strong>Inverted risk-factor disparity:</strong> patients with hypertension, heart disease, or high glucose are detected better; the markerless stroke is the hardest case. <strong>A vacuous-fairness trap:</strong> the linear model at a 0.10 threshold scores a perfect Equalized-Odds gap of 0.00 — only because it flags every patient positive.</p>
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Muhammad Khan Muneer </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 2026</p>
    </div>
  </div>
  
    
  </div>
  

<div>
  <div class="keywords">
    <div class="block-title">Keywords</div>
    <p>algorithmic fairness, equity audit, subgroup analysis, equalized odds, demographic parity, false-negative rate, stroke screening, class imbalance, age disparity, cryptogenic stroke, model governance, Youden threshold, Python</p>
  </div>
</div>

</header>


<section id="abstract" class="level2">
<h2 class="anchored" data-anchor-id="abstract">Abstract</h2>
<p>The preceding modelling study reported overall recall of 0.70–0.82 for three tuned stroke-screening classifiers on a 1,022-patient held-out test set (50 stroke events, 4.9% prevalence). This audit asks whether that detection is distributed across the population or concentrated in one subgroup. It decomposes each model’s false-negative rate across five axes — age band, hypertension, heart disease, elevated glucose, gender — at two operating points (each model’s Youden threshold and a 0.10 screening threshold), and formalises the result with the Equalized-Odds and Demographic-Parity gaps. The finding is unambiguous: <strong>overall recall is a senior-age-band metric.</strong> The 60+ band holds 38 of 50 test events (76%) and is detected at 0.92–0.97; in the mid (30–44) and young (0–29) bands, every model misses every stroke (false-negative rate 1.00), and in the mature (45–59) band the tree models detect 4 of 6 while the linear model detects none. The age-band Equalized-Odds gap reaches 1.78 of a possible 2.0. Against the clinical risk factors the disparity inverts — risk-factor-positive patients are detected more reliably, because they carry the feature signals the models weight — leaving the markerless stroke as the structurally hardest case. A separate result: at the 0.10 screening threshold the linear model records a perfect Equalized-Odds gap of 0.00 across every axis, but only because its minimum predicted probability (0.143) exceeds the threshold, so it classifies every patient positive — fairness satisfied vacuously. The audit is descriptive; no fairness constraints were imposed during training.</p>
<p><em>Keywords:</em> algorithmic fairness, equity audit, equalized odds, false-negative rate, stroke screening, age disparity</p>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>A model that reports 82% recall on a rare outcome invites a follow-up question: 82% of <em>whom</em>? Aggregate metrics on an imbalanced problem can be carried almost entirely by one dominant subgroup while other groups bear the miss-rate burden. This audit — the final analytical stage of a six-notebook stroke-risk pipeline — decomposes the three tuned classifiers from the modelling study across five clinically and demographically meaningful subgroups, at two operating points, to characterise the equity landscape <em>before</em> any deployment decision.</p>
<p>The audit is deliberately descriptive. The models were tuned on overall ROC-AUC with no fairness objective; this study measures the consequences of that, it does not remediate them. Remediation — per-subgroup thresholds, re-weighting, constrained optimisation — is a separate exercise that this audit is meant to inform.</p>
</section>
<section id="method" class="level2">
<h2 class="anchored" data-anchor-id="method">Method</h2>
<section id="models-and-test-set" class="level3">
<h3 class="anchored" data-anchor-id="models-and-test-set">Models and test set</h3>
<p>Three tuned pipelines from the modelling study — GLMNET (Elastic Net), XGBoost, LightGBM — were loaded with the exact 1,022-patient held-out test set (50 stroke-positive, 4.9%). Predicted probabilities were generated and their distributions checked before any slicing: GLMNET’s probabilities span [0.143, 0.775] (<em>M</em> = 0.398); XGBoost’s [0.001, 0.662] (<em>M</em> = 0.079) and LightGBM’s [0.000, 0.769] (<em>M</em> = 0.057) are compressed toward zero, as gradient-boosted ensembles under class weighting tend to be.</p>
</section>
<section id="subgroup-axes" class="level3">
<h3 class="anchored" data-anchor-id="subgroup-axes">Subgroup axes</h3>
<p>Five axes were audited (Table 1): a four-level <strong>age band</strong> (young 0–29, mid 30–44, mature 45–59, senior 60+); the three <strong>clinical risk factors</strong> retained as independent predictors in the inferential study (<strong>hypertension</strong>, <strong>heart disease</strong>, <strong>elevated glucose</strong>); and <strong>gender</strong>, included as an equity completeness check because male and female event rates in the test set are near-identical (4.96% vs.&nbsp;4.84%).</p>
<p><strong>Table 1</strong></p>
<p><em>Test-Set Composition of the Five Subgroup Axes (N = 1,022; 50 Stroke Events)</em></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Axis</th>
<th style="text-align: left;">Level</th>
<th style="text-align: right;"><em>n</em></th>
<th style="text-align: right;">Events</th>
<th style="text-align: right;">Event rate</th>
<th style="text-align: right;">Share of all 50 events</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Age band</td>
<td style="text-align: left;">Young (0–29)</td>
<td style="text-align: right;">320</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.31%</td>
<td style="text-align: right;">2%</td>
</tr>
<tr class="even">
<td style="text-align: left;">”</td>
<td style="text-align: left;">Mid (30–44)</td>
<td style="text-align: right;">207</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">2.42%</td>
<td style="text-align: right;">10%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">”</td>
<td style="text-align: left;">Mature (45–59)</td>
<td style="text-align: right;">223</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">2.69%</td>
<td style="text-align: right;">12%</td>
</tr>
<tr class="even">
<td style="text-align: left;">”</td>
<td style="text-align: left;">Senior (60+)</td>
<td style="text-align: right;">272</td>
<td style="text-align: right;">38</td>
<td style="text-align: right;">13.97%</td>
<td style="text-align: right;"><strong>76%</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hypertension</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">921</td>
<td style="text-align: right;">38</td>
<td style="text-align: right;">4.13%</td>
<td style="text-align: right;">76%</td>
</tr>
<tr class="even">
<td style="text-align: left;">”</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">101</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">11.88%</td>
<td style="text-align: right;">24%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Heart disease</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">967</td>
<td style="text-align: right;">39</td>
<td style="text-align: right;">4.03%</td>
<td style="text-align: right;">78%</td>
</tr>
<tr class="even">
<td style="text-align: left;">”</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">55</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">20.00%</td>
<td style="text-align: right;">22%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Elevated glucose</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">863</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">3.71%</td>
<td style="text-align: right;">64%</td>
</tr>
<tr class="even">
<td style="text-align: left;">”</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">159</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">11.32%</td>
<td style="text-align: right;">36%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gender</td>
<td style="text-align: left;">Female</td>
<td style="text-align: right;">599</td>
<td style="text-align: right;">29</td>
<td style="text-align: right;">4.84%</td>
<td style="text-align: right;">58%</td>
</tr>
<tr class="even">
<td style="text-align: left;">”</td>
<td style="text-align: left;">Male</td>
<td style="text-align: right;">423</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">4.96%</td>
<td style="text-align: right;">42%</td>
</tr>
</tbody>
</table>
<p><em>Note.</em> Subgroup recall figures are only interpretable against these denominators: recall 0.90 on a slice with 2 events measures something different from recall 0.90 on a slice with 38.</p>
</section>
<section id="thresholds-and-metrics" class="level3">
<h3 class="anchored" data-anchor-id="thresholds-and-metrics">Thresholds and metrics</h3>
<p>Each model was evaluated at <strong>its Youden’s <em>J</em> threshold</strong> (0.615 GLMNET, 0.094 XGBoost, 0.036 LightGBM) and at a fixed <strong>0.10 screening threshold</strong> (maximum-sensitivity operating point). For every subgroup level, the audit computed recall, false-negative rate (FNR / miss rate), specificity, false-positive rate, and predicted-positive rate; slices with zero or all positives were skipped. Two standard fairness metrics summarise each axis: the <strong>Equalized-Odds gap</strong> (Hardt et al., 2016) — the maximum pairwise true-positive-rate gap plus the maximum pairwise false-positive-rate gap across levels, bounded at 2.0 — and the <strong>Demographic-Parity gap</strong> (Dwork et al., 2012) — the maximum pairwise difference in predicted-positive rate.</p>
</section>
<section id="software-and-reproducibility" class="level3">
<h3 class="anchored" data-anchor-id="software-and-reproducibility">Software and reproducibility</h3>
<p>Python with <code>scikit-learn</code>, <code>xgboost</code>, <code>lightgbm</code>. The tuned pipelines and the exact test set are persisted artefacts; every figure and number here was recomputed from them and matched the original run.</p>
</section>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<section id="age-band-overall-recall-is-a-senior-band-metric" class="level3">
<h3 class="anchored" data-anchor-id="age-band-overall-recall-is-a-senior-band-metric">Age band: overall recall is a senior-band metric</h3>
<p>The decomposition by age (Figure 1, Figure 2, Table 2) is the audit’s central finding. At the Youden threshold, the <strong>senior band</strong> (272 patients, 38 events) is the only band with strong detection — XGBoost and LightGBM at recall 0.974 (37 of 38), GLMNET at 0.921 (35 of 38). The <strong>mature band</strong> (223 patients, 6 events) splits the architectures: the tree models detect 4 of 6 (recall 0.667), GLMNET detects <strong>0 of 6</strong> — its 0.615 threshold is too high for any mature-band patient to clear. The <strong>mid band</strong> (207 patients, 5 events) and <strong>young band</strong> (320 patients, 1 event) are complete failures: <strong>every model misses every stroke</strong> (FNR 1.00). A classifier reported at 0.82 overall recall is, in operational terms, achieving near-perfect senior-band detection and near-zero detection everywhere else — GLMNET’s 35 true positives at Youden come <em>entirely</em> from the 272 senior-band patients, with zero contribution from the other 750.</p>
<p><strong>Table 2</strong></p>
<p><em>Recall and False-Negative Rate by Age Band and Model (Youden Threshold)</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Age band (events)</th>
<th style="text-align: center;">GLMNET recall / FNR</th>
<th style="text-align: center;">XGBoost recall / FNR</th>
<th style="text-align: center;">LightGBM recall / FNR</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Young (1)</td>
<td style="text-align: center;">0.00 / 1.00</td>
<td style="text-align: center;">0.00 / 1.00</td>
<td style="text-align: center;">0.00 / 1.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mid (5)</td>
<td style="text-align: center;">0.00 / 1.00</td>
<td style="text-align: center;">0.00 / 1.00</td>
<td style="text-align: center;">0.00 / 1.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mature (6)</td>
<td style="text-align: center;">0.00 / 1.00</td>
<td style="text-align: center;">0.67 / 0.33</td>
<td style="text-align: center;">0.67 / 0.33</td>
</tr>
<tr class="even">
<td style="text-align: left;">Senior (38)</td>
<td style="text-align: center;">0.92 / 0.08</td>
<td style="text-align: center;">0.97 / 0.03</td>
<td style="text-align: center;">0.97 / 0.03</td>
</tr>
</tbody>
</table>
<p><em>Note.</em> The senior band supplies 76% of test events; the models’ behaviour there sets the headline number.</p>
<p><strong>Figure 1</strong></p>
<p><em>Recall by Age Band at the Youden Threshold</em></p>
<p><img src="assets/fig1_recall_by_age_band.png" class="img-fluid" alt="Grouped bars of recall for three models across four age bands. Young and mid bands: all bars at zero. Mature: GLMNET zero, XGBoost and LightGBM at 0.67. Senior: 0.92 to 0.97 for all three."></p>
<p><em>Note.</em> Bars are labelled with the patient and event count per band. Detection is confined to the senior band, with a partial tree-model foothold in the mature band.</p>
<p><strong>Figure 2</strong></p>
<p><em>False-Negative Rate by Model and Age Band, at Both Thresholds</em></p>
<p><img src="assets/fig2_fnr_heatmap_age.png" class="img-fluid" alt="Two heatmaps of miss rate. Youden panel: young and mid columns are solid red (1.00) for all models; mature is amber for the tree models and red for GLMNET; senior is green. Screening panel: GLMNET is all green (0.00) — the vacuous result — while the tree models still show red in young/mid."></p>
<p><em>Note.</em> Left — Youden thresholds. Right — the 0.10 screening threshold, where GLMNET’s all-green row is the vacuous-fairness artefact discussed below, not genuine detection.</p>
</section>
<section id="clinical-risk-factors-the-disparity-inverts" class="level3">
<h3 class="anchored" data-anchor-id="clinical-risk-factors-the-disparity-inverts">Clinical risk factors: the disparity inverts</h3>
<p>Against the clinical axes (Figure 3, Table 3) the pattern reverses: <strong>risk-factor-positive patients are detected more reliably than risk-factor-negative patients</strong>, consistently across hypertension, heart disease, and elevated glucose. At the Youden threshold, XGBoost and LightGBM achieve recall 1.00 for hypertensive stroke patients (12 of 12) and for heart-disease stroke patients (11 of 11), against 0.76–0.77 for the risk-factor-negative groups. GLMNET shows the same direction with wider gaps — its normal-glucose FNR reaches 0.41. The mechanism is coherent: risk-factor-positive patients carry the very features the models learned to weight, so their predicted probabilities clear the threshold more often. The <strong>markerless stroke</strong> — a patient who has an event without hypertension, cardiac disease, or glucose elevation — is the structurally hardest case for any fixed-threshold classifier, and it is exactly the cryptogenic presentation clinicians find hardest too.</p>
<p><strong>Table 3</strong></p>
<p><em>Recall for Risk-Factor-Positive vs.&nbsp;Risk-Factor-Negative Stroke Patients (Youden Threshold)</em></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Risk factor</th>
<th style="text-align: left;">Group (events)</th>
<th style="text-align: right;">GLMNET</th>
<th style="text-align: right;">XGBoost</th>
<th style="text-align: right;">LightGBM</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Hypertension</td>
<td style="text-align: left;">positive (12)</td>
<td style="text-align: right;">0.83</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">”</td>
<td style="text-align: left;">negative (38)</td>
<td style="text-align: right;">0.66</td>
<td style="text-align: right;">0.76</td>
<td style="text-align: right;">0.76</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Heart disease</td>
<td style="text-align: left;">positive (11)</td>
<td style="text-align: right;">0.82</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">”</td>
<td style="text-align: left;">negative (39)</td>
<td style="text-align: right;">0.67</td>
<td style="text-align: right;">0.77</td>
<td style="text-align: right;">0.77</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Elevated glucose</td>
<td style="text-align: left;">positive (18)</td>
<td style="text-align: right;">0.89</td>
<td style="text-align: right;">0.94</td>
<td style="text-align: right;">0.94</td>
</tr>
<tr class="even">
<td style="text-align: left;">”</td>
<td style="text-align: left;">negative (32)</td>
<td style="text-align: right;">0.59</td>
<td style="text-align: right;">0.75</td>
<td style="text-align: right;">0.75</td>
</tr>
</tbody>
</table>
<p><em>Note.</em> Every model detects risk-factor-positive strokes better; GLMNET’s gaps are the widest (FNR gap up to 0.30 on glucose).</p>
<p><strong>Figure 3</strong></p>
<p><em>Inverted Disparity: Miss Rate for Risk-Factor-Positive vs.&nbsp;-Negative Stroke Patients</em></p>
<p><img src="assets/fig3_risk_factor_asymmetry.png" class="img-fluid" alt="Three panels (hypertension, heart disease, elevated glucose). In each, the risk-factor-negative bars are higher (worse miss rate, ~0.24–0.41) than the risk-factor-positive bars (~0.00–0.11) for all three models."></p>
<p><em>Note.</em> Lower is better. The risk-factor-positive bars sit well below the negative bars in every panel — the opposite of the age-band pattern.</p>
</section>
<section id="gender-a-modest-architecture-dependent-gap" class="level3">
<h3 class="anchored" data-anchor-id="gender-a-modest-architecture-dependent-gap">Gender: a modest, architecture-dependent gap</h3>
<p>Gender (Table 4) behaves as expected for a near-balanced axis, with one wrinkle. At the Youden threshold the tree models carry a narrow gap in the <em>male-favoured</em> direction (male recall 0.857 vs.&nbsp;female 0.793; FNR gap 0.064 each). <strong>GLMNET carries a wider gap in the opposite direction</strong> — female recall 0.793 vs.&nbsp;male 0.571, an FNR gap of 0.222, the widest gender disparity of any model — most plausibly reflecting the age–gender correlation in this cohort interacting with GLMNET’s high threshold. GLMNET’s Demographic-Parity gap on gender is only 0.010: it flags near-identical proportions of men and women; the disparity is in detection accuracy, not flagging rate.</p>
<p><strong>Table 4</strong></p>
<p><em>Gender: Recall and FNR Gap (Youden Threshold)</em></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;">Female recall</th>
<th style="text-align: right;">Male recall</th>
<th style="text-align: right;">FNR gap</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">GLMNET (Elastic Net)</td>
<td style="text-align: right;">0.79</td>
<td style="text-align: right;">0.57</td>
<td style="text-align: right;">0.222</td>
</tr>
<tr class="even">
<td style="text-align: left;">XGBoost</td>
<td style="text-align: right;">0.79</td>
<td style="text-align: right;">0.86</td>
<td style="text-align: right;">0.064</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LightGBM</td>
<td style="text-align: right;">0.79</td>
<td style="text-align: right;">0.86</td>
<td style="text-align: right;">0.064</td>
</tr>
</tbody>
</table>
<p><em>Note.</em> The tree models are the more gender-equitable architectures here; GLMNET’s gap is detection-side, not flagging-side.</p>
</section>
<section id="formal-fairness-gaps" class="level3">
<h3 class="anchored" data-anchor-id="formal-fairness-gaps">Formal fairness gaps</h3>
<p>The Equalized-Odds gaps (Figure 4, Table 5) compress the picture. <strong>Age band is the dominant disparity source</strong> — Equalized-Odds gap 1.78 (LightGBM), 1.76 (XGBoost), 1.45 (GLMNET), close to the theoretical maximum of 2.0; GLMNET’s is lower only because its senior-band recall is lower, narrowing the true-positive-rate component. The clinical risk factors sit in a moderate 0.38–0.72 band. <strong>Gender is the most equitable axis for the tree models</strong> (0.08–0.09) and roughly three times worse for GLMNET (0.22). Fairness here is not a single-number property of a model — it spans nearly the full range of the metric depending on which axis is examined.</p>
<p><strong>Table 5</strong></p>
<p><em>Equalized-Odds Gap by Model and Axis (Youden Threshold; 0 = Equitable, 2.0 = Maximum)</em></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Axis</th>
<th style="text-align: right;">GLMNET</th>
<th style="text-align: right;">XGBoost</th>
<th style="text-align: right;">LightGBM</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Age band</strong></td>
<td style="text-align: right;"><strong>1.45</strong></td>
<td style="text-align: right;"><strong>1.76</strong></td>
<td style="text-align: right;"><strong>1.78</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;">Hypertension</td>
<td style="text-align: right;">0.38</td>
<td style="text-align: right;">0.66</td>
<td style="text-align: right;">0.72</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Heart disease</td>
<td style="text-align: right;">0.52</td>
<td style="text-align: right;">0.70</td>
<td style="text-align: right;">0.64</td>
</tr>
<tr class="even">
<td style="text-align: left;">Elevated glucose</td>
<td style="text-align: right;">0.53</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">0.57</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gender</td>
<td style="text-align: right;">0.22</td>
<td style="text-align: right;">0.09</td>
<td style="text-align: right;">0.08</td>
</tr>
</tbody>
</table>
<p><em>Note.</em> Demographic-Parity gaps follow the same ordering (age band: LightGBM 0.83, XGBoost 0.81, GLMNET 0.58).</p>
<p><strong>Figure 4</strong></p>
<p><em>Equalized-Odds Gap Surface: Model × Subgroup Axis</em></p>
<p><img src="assets/fig4_equity_surface.png" class="img-fluid" alt="A 3-by-5 heatmap of Equalized-Odds gaps. The age-band column is red (1.45 to 1.78). The gender column is green (0.08 to 0.22). The three clinical columns are amber (0.38 to 0.72)."></p>
<p><em>Note.</em> Youden threshold. The distance between the greenest cell (gender, tree models) and the reddest (age band) spans almost the full colour range.</p>
</section>
<section id="the-vacuous-fairness-result" class="level3">
<h3 class="anchored" data-anchor-id="the-vacuous-fairness-result">The vacuous-fairness result</h3>
<p>At the 0.10 screening threshold, <strong>GLMNET records an Equalized-Odds gap and a Demographic-Parity gap of 0.00 on every axis</strong> (Figure 5). This must be read correctly. GLMNET’s minimum predicted probability is 0.143, above the 0.10 cut-off, so <em>every</em> patient is classified positive — true-positive rate 1.00 everywhere, false-positive rate 1.00 everywhere, specificity 0.00 everywhere, all gaps zero by construction. A trivially positive classifier satisfies Equalized Odds by definition, not by merit. Any governance review that saw GLMNET’s perfect screening-threshold fairness scores without this mechanism disclosed would be misled. The tree models, which retain genuine probability-based discrimination at 0.10, still show large age-band gaps there (XGBoost 1.74, LightGBM 1.32).</p>
<p><strong>Figure 5</strong></p>
<p><em>Vacuous Fairness: GLMNET at the 0.10 Screening Threshold</em></p>
<p><img src="assets/fig5_vacuous_fairness.png" class="img-fluid" alt="Bars per age band for GLMNET at threshold 0.10: predicted-positive rate 1.00 and recall 1.00 in every band, specificity 0.00 in every band."></p>
<p><em>Note.</em> Recall is 1.00 in every band because the model flags every patient; the Equalized-Odds gap of 0.00 is an artefact of that, not evidence of equity.</p>
</section>
<section id="consolidated-worst-case-surface" class="level3">
<h3 class="anchored" data-anchor-id="consolidated-worst-case-surface">Consolidated worst-case surface</h3>
<p>The worst-case FNR across levels of each axis (Figure 6) is the governance-ready summary. On the age-band axis, <strong>all three models hit worst-case FNR 1.00</strong> at the Youden threshold — the mid and young bands. On the clinical axes, the tree models hold worst-case FNR to 0.21–0.25; GLMNET is worse on every one (0.33–0.43) and worst on gender (0.43). No model is adequate in the under-45 population at any non-degenerate threshold.</p>
<p><strong>Figure 6</strong></p>
<p><em>Worst-Case False-Negative Rate Across Subgroup Levels (Youden Threshold)</em></p>
<p><img src="assets/fig6_worst_case_fnr.png" class="img-fluid" alt="A 3-by-5 heatmap of worst-case miss rate. The age-band column is solid red at 1.00 for all three models. The clinical and gender columns are green-to-amber: tree models 0.21 to 0.25, GLMNET 0.33 to 0.43."></p>
<p><em>Note.</em> The age-band column is the deployment blocker; the clinical columns favour the tree models.</p>
</section>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<section id="what-the-headline-number-hides" class="level3">
<h3 class="anchored" data-anchor-id="what-the-headline-number-hides">What the headline number hides</h3>
<p>An overall recall of 0.82 on this cohort is an average weighted by where the events are — and 76% of them are in the senior band. The audit shows the models learned to detect senior-band strokes and essentially nothing else at their Youden thresholds. This is not a subtle bias; it is a categorical failure in two of four age bands. Reporting the aggregate without the decomposition would misrepresent the models as broadly capable screeners when they are narrow ones.</p>
</section>
<section id="two-disparities-opposite-directions" class="level3">
<h3 class="anchored" data-anchor-id="two-disparities-opposite-directions">Two disparities, opposite directions</h3>
<p>The age-band and risk-factor patterns point opposite ways, and both are explicable from the same fact: the models detect patients who carry the signals they were trained to weight. Older patients and risk-factor-positive patients carry those signals; younger and markerless patients do not. The clinically uncomfortable consequence is that the patients the model helps least are the ones a clinician would also find hardest — the young or cryptogenic stroke — so the tool adds least value exactly where human judgement is most stretched.</p>
</section>
<section id="the-screening-mode-trap" class="level3">
<h3 class="anchored" data-anchor-id="the-screening-mode-trap">The screening-mode trap</h3>
<p>GLMNET’s perfect fairness scores at the 0.10 threshold are a worked example of why fairness metrics need a classifier-behaviour check beside them. A model that flags everyone is perfectly equitable and perfectly useless. This is a documented counter-example for any future audit that reports strong fairness numbers without interrogating the predicted-positive rate.</p>
</section>
<section id="deployment-implications" class="level3">
<h3 class="anchored" data-anchor-id="deployment-implications">Deployment implications</h3>
<p>Three follow. First, <strong>age-stratified thresholds or a separate protocol for patients under 45</strong> would be needed to address the age-band gap without retraining — the models cannot be deployed as-is for a general-population screen. Second, <strong>GLMNET must not be run at the 0.10 screening threshold</strong> on this pipeline vintage; its usable operating range is around its Youden point. Third, on the clinical axes, <strong>XGBoost and LightGBM are the more subgroup-equitable choices</strong> — worst-case FNR 0.21–0.25 versus GLMNET’s 0.33–0.43, and gender gaps a third the size.</p>
</section>
<section id="limitations" class="level3">
<h3 class="anchored" data-anchor-id="limitations">Limitations</h3>
<p>The audit inherits the modelling study’s limits: a single 80/20 split, one cohort, and only 50 test events — so the small-slice figures (mid band: 5 events; mature: 6; heart disease: 11) carry wide sampling uncertainty and a single misclassification moves a subgroup recall substantially. The fairness metrics are computed at fixed thresholds, not integrated over the operating curve. The audit is descriptive: it quantifies disparity but applies no mitigation, and the choice among mitigation strategies is itself a value-laden decision that belongs with the clinical and governance stakeholders.</p>
</section>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion">Conclusion</h3>
<p>The three tuned stroke-screening models detect strokes almost exclusively in patients aged 60 and over; in the mid and young age bands they miss every case. Against the clinical risk factors the disparity inverts, leaving the markerless stroke as the hardest case. Equalized-Odds gaps confirm age as the dominant disparity axis (up to 1.78 of 2.0) and gender as the most equitable for the tree models. The linear model’s apparently perfect fairness at a low screening threshold is an artefact of flagging every patient. None of the models is ready for general-population deployment without age-stratified operating points.</p>
</section>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<p>Barocas, S., Hardt, M., &amp; Narayanan, A. (2019). <em>Fairness and machine learning: Limitations and opportunities</em>. fairmlbook.org.</p>
<p>Chen, I. Y., Pierson, E., Rose, S., Joshi, S., Ferryman, K., &amp; Ghassemi, M. (2021). Ethical machine learning in healthcare. <em>Annual Review of Biomedical Data Science, 4</em>, 123–144. https://doi.org/10.1146/annurev-biodatasci-092820-114757</p>
<p>Dwork, C., Hardt, M., Pitassi, T., Reingold, O., &amp; Zemel, R. (2012). Fairness through awareness. <em>Proceedings of the 3rd Innovations in Theoretical Computer Science Conference</em>, 214–226. https://doi.org/10.1145/2090236.2090255</p>
<p>Hardt, M., Price, E., &amp; Srebro, N. (2016). Equality of opportunity in supervised learning. <em>Advances in Neural Information Processing Systems, 29</em>, 3315–3323.</p>
<p>Obermeyer, Z., Powers, B., Vogeli, C., &amp; Mullainathan, S. (2019). Dissecting racial bias in an algorithm used to manage the health of populations. <em>Science, 366</em>(6464), 447–453. https://doi.org/10.1126/science.aax2342</p>
<p>Pedregosa, F., Varoquaux, G., Gramfort, A., Michel, V., Thirion, B., Grisel, O., Blondel, M., Prettenhofer, P., Weiss, R., Dubourg, V., Vanderplas, J., Passos, A., Cournapeau, D., Brucher, M., Perrot, M., &amp; Duchesnay, É. (2011). Scikit-learn: Machine learning in Python. <em>Journal of Machine Learning Research, 12</em>, 2825–2830.</p>
<p>Rajkomar, A., Hardt, M., Howell, M. D., Corrado, G., &amp; Chin, M. H. (2018). Ensuring fairness in machine learning to advance health equity. <em>Annals of Internal Medicine, 169</em>(12), 866–872. https://doi.org/10.7326/M18-1990</p>
<p>Youden, W. J. (1950). Index for rating diagnostic tests. <em>Cancer, 3</em>(1), 32–35. https://doi.org/10.1002/1097-0142(1950)3:1&lt;32::AID-CNCR2820030106&gt;3.0.CO;2-3</p>
<p>fedesoriano. (2021). <em>Stroke prediction dataset</em> [Data set]. Kaggle. https://www.kaggle.com/datasets/fedesoriano/stroke-prediction-dataset</p>
<hr>
<p><em>Audit and figures by the author. Descriptive only — the models were not trained with fairness constraints, and no mitigation was applied. All subgroup metrics are single-split and single-cohort.</em></p>


<div id="contact" class="connect-section" style="text-align: center; padding: 50px 20px; background: #f9f9f9; border-radius: 15px; border: 1px solid #eaeaea; margin-top: 40px;">
<h3 style="color: #2c3e50; font-weight: 700; margin-bottom: 15px; border: none;" class="anchored">Let's Collaborate</h3>
<p style="color: #666; max-width: 650px; margin: 0 auto 30px auto; font-size: 1.05rem; line-height: 1.6;">Available for high-impact <strong>Business Intelligence, Power BI Engineering, and Advanced Data Analytics</strong> projects. Connect with me or hire me directly through the platforms below.</p>
<div style="display: flex; flex-wrap: wrap; justify-content: center; gap: 12px;">
<a href="https://www.linkedin.com/in/mkmuneer" class="btn btn-primary" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; text-decoration: none;"><i class="bi bi-linkedin"></i> LinkedIn</a>
<a href="https://github.com/mkhanmuneer" class="btn btn-dark" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; text-decoration: none;"><i class="bi bi-github"></i> GitHub</a>
<a href="https://www.kaggle.com/muhammadkhanmuneer" class="btn btn-info" target="_blank" rel="noopener" style="color: white; padding: 12px 25px; min-width: 150px; text-decoration: none;"><i class="bi bi-graph-up"></i> Kaggle</a>
<a href="https://www.upwork.com/freelancers/~018de8553286a1d00c" class="btn btn-outline-success" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; border-width: 2px; font-weight: 600; text-decoration: none;"><i class="bi bi-briefcase"></i> Upwork</a>
<a href="https://www.fiverr.com/neuronvision" class="btn btn-outline-success" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; border-width: 2px; font-weight: 600; text-decoration: none;"><i class="bi bi-lightning-charge"></i> Fiverr</a>
</div>
</div>

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/mkhanmuneer\.github\.io\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 Muhammad Khan Muneer</p>
</div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://www.upwork.com/freelancers/~018de8553286a1d00c">
<p>Hire on Upwork</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="https://www.fiverr.com/neuronvision">
<p>Hire on Fiverr</p>
</a>
  </li>  
</ul>
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mkhanmuneer">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/mkmuneer">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>