<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Muhammad Khan Muneer">
<meta name="keywords" content="length of stay, count regression, Poisson regression, Poisson deviance, retransformation bias, smearing estimator, model selection, LightGBM, elastic net, regression to the mean, predictive ceiling, calibration, Youden’s J, SHAP, Python">
<meta name="description" content="An admission-time length-of-stay regression on 99,340 diabetic inpatient encounters, evaluated on a patient-disjoint 19,812-encounter holdout. The leakage discipline: only the 23 features known at or before admission — 30 stay-accumulated clinical and medication columns are excluded with a stated reason each. The predictive ceiling: the champion (LightGBM, Poisson objective) reaches test R² 0.09, RMSE 2.85 days, MAE 2.21 days, barely ahead of the mean-only baseline’s MAE of 2.35. Predictions collapse toward the centre — actual stays span 1–14 days, predicted stays barely leave 3–7. The metric trap: an ElasticNet fitted on log-transformed length of stay has the best test MAE (2.19) but the worst Poisson deviance of all seven models (1.888, above the baseline’s 1.884) — its expm1 back-transform is a retransformation-biased point estimate that MAE cannot see. The operational read: a Youden-calibrated extended-stay flag (predicted stay ≥ 4.5 days) catches 60% of stays longer than a week at 63% specificity — an advisory signal for discharge planning, not a trigger (AUC 0.65).">

<title>Admission-Time Length-of-Stay Forecasting: When MAE Selects the Wrong Model, and Poisson Deviance Selects the Right One – Muhammad Khan Muneer</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-4d9afe2b8d18ee9fa5d0d57b5ed4214d.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-5af9b5ab1fa0c387551d40c1aacb317e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-ca0cfe78a00f84493d894d8af57a3a20.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-5af9b5ab1fa0c387551d40c1aacb317e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": true,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<link rel="stylesheet" href="../../styles/custom.css">
<meta property="og:title" content="Muhammad Khan Muneer — Data Science &amp; BI Portfolio">
<meta property="og:description" content="Engineering ML-driven analytics and automated decision systems.">
<meta property="og:image" content="https://mkhanmuneer.github.io/projects/admission-time-length-of-stay-forecasting-when-mae-selects-the-wrong-model-poisson-deviance-champion-selection/assets/fig2_mae_vs_deviance_ladder.png">
<meta property="og:site_name" content="M. Khan Muneer Portfolio">
<meta property="og:image:height" content="884">
<meta property="og:image:width" content="1687">
<meta name="twitter:title" content="Admission-Time Length-of-Stay Forecasting: When MAE Selects the Wrong Model, and Poisson Deviance Selects the Right One – Muhammad Khan Muneer">
<meta name="twitter:description" content="An admission-time length-of-stay regression on 99,340 diabetic inpatient encounters, evaluated on a patient-disjoint 19,812-encounter holdout. The leakage discipline: only the 23 features known at or before admission — 30 stay-accumulated clinical and medication columns are excluded with a stated reason each. The predictive ceiling: the champion (LightGBM, Poisson objective) reaches test R² 0.09, RMSE 2.85 days, MAE 2.21 days, barely ahead of the mean-only baseline’s MAE of 2.35. Predictions collapse toward the centre — actual stays span 1–14 days, predicted stays barely leave 3–7. The metric trap: an ElasticNet fitted on log-transformed length of stay has the best test MAE (2.19) but the worst Poisson deviance of all seven models (1.888, above the baseline’s 1.884) — its expm1 back-transform is a retransformation-biased point estimate that MAE cannot see. The operational read: a Youden-calibrated extended-stay flag (predicted stay ≥ 4.5 days) catches 60% of stays longer than a week at 63% specificity — an advisory signal for discharge planning, not a trigger (AUC 0.65).">
<meta name="twitter:image" content="https://mkhanmuneer.github.io/projects/admission-time-length-of-stay-forecasting-when-mae-selects-the-wrong-model-poisson-deviance-champion-selection/assets/fig2_mae_vs_deviance_ladder.png">
<meta name="twitter:creator" content="@iMKhanMuneer">
<meta name="twitter:site" content="@iMKhanMuneer">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image-height" content="884">
<meta name="twitter:image-width" content="1687">
</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../index.html#featured-projects"> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/mkmuneer"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mkhanmuneer"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://x.com/iMKhanMuneer"> <i class="bi bi-twitter-x" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.kaggle.com/muhammadkhanmuneer"> <i class="bi bi-graph-up" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../index.html#contact"> 
<span class="menu-text">Contact</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract">Abstract</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#method" id="toc-method" class="nav-link" data-scroll-target="#method">Method</a>
  <ul class="collapse">
  <li><a href="#data-target-and-leakage-audit" id="toc-data-target-and-leakage-audit" class="nav-link" data-scroll-target="#data-target-and-leakage-audit">Data, target, and leakage audit</a></li>
  <li><a href="#split-and-preprocessing" id="toc-split-and-preprocessing" class="nav-link" data-scroll-target="#split-and-preprocessing">Split and preprocessing</a></li>
  <li><a href="#model-ladder-and-champion-selection" id="toc-model-ladder-and-champion-selection" class="nav-link" data-scroll-target="#model-ladder-and-champion-selection">Model ladder and champion selection</a></li>
  <li><a href="#validation-lenses" id="toc-validation-lenses" class="nav-link" data-scroll-target="#validation-lenses">Validation lenses</a></li>
  <li><a href="#reproduction-and-software" id="toc-reproduction-and-software" class="nav-link" data-scroll-target="#reproduction-and-software">Reproduction and software</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#the-ladder-and-the-maedeviance-disagreement" id="toc-the-ladder-and-the-maedeviance-disagreement" class="nav-link" data-scroll-target="#the-ladder-and-the-maedeviance-disagreement">The ladder, and the MAE–deviance disagreement</a></li>
  <li><a href="#a-calibrated-champion-at-a-low-predictive-ceiling" id="toc-a-calibrated-champion-at-a-low-predictive-ceiling" class="nav-link" data-scroll-target="#a-calibrated-champion-at-a-low-predictive-ceiling">A calibrated champion at a low predictive ceiling</a></li>
  <li><a href="#an-advisory-extended-stay-flag" id="toc-an-advisory-extended-stay-flag" class="nav-link" data-scroll-target="#an-advisory-extended-stay-flag">An advisory extended-stay flag</a></li>
  <li><a href="#fairness-and-drivers" id="toc-fairness-and-drivers" class="nav-link" data-scroll-target="#fairness-and-drivers">Fairness and drivers</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Admission-Time Length-of-Stay Forecasting: When MAE Selects the Wrong Model, and Poisson Deviance Selects the Right One</h1>
<p class="subtitle lead">Predicting how many days an admission will last from information known at the door. A seven-model ladder, a predictive ceiling of R² 0.09, and a metric-selection trap — the model with the best MAE has the worst deviance of all seven, worse than always predicting the mean.</p>
  <div class="quarto-categories">
    <div class="quarto-category">Machine Learning</div>
    <div class="quarto-category">Regression</div>
    <div class="quarto-category">Poisson Regression</div>
    <div class="quarto-category">Count Regression</div>
    <div class="quarto-category">Model Evaluation</div>
    <div class="quarto-category">Model Explainability</div>
    <div class="quarto-category">Cross-Validation</div>
    <div class="quarto-category">Gradient Boosting</div>
    <div class="quarto-category">Healthcare Analytics</div>
    <div class="quarto-category">Hospital Readmission</div>
    <div class="quarto-category">Python</div>
  </div>
  </div>

<div>
  <div class="description">
    <p>An admission-time length-of-stay regression on 99,340 diabetic inpatient encounters, evaluated on a patient-disjoint 19,812-encounter holdout. <strong>The leakage discipline:</strong> only the 23 features known at or before admission — 30 stay-accumulated clinical and medication columns are excluded with a stated reason each. <strong>The predictive ceiling:</strong> the champion (LightGBM, Poisson objective) reaches test R² 0.09, RMSE 2.85 days, MAE 2.21 days, barely ahead of the mean-only baseline’s MAE of 2.35. Predictions collapse toward the centre — actual stays span 1–14 days, predicted stays barely leave 3–7. <strong>The metric trap:</strong> an ElasticNet fitted on log-transformed length of stay has the best test MAE (2.19) but the worst Poisson deviance of all seven models (1.888, above the baseline’s 1.884) — its expm1 back-transform is a retransformation-biased point estimate that MAE cannot see. <strong>The operational read:</strong> a Youden-calibrated extended-stay flag (predicted stay ≥ 4.5 days) catches 60% of stays longer than a week at 63% specificity — an advisory signal for discharge planning, not a trigger (AUC 0.65).</p>
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Muhammad Khan Muneer </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 2025</p>
    </div>
  </div>
  
    
  </div>
  

<div>
  <div class="keywords">
    <div class="block-title">Keywords</div>
    <p>length of stay, count regression, Poisson regression, Poisson deviance, retransformation bias, smearing estimator, model selection, LightGBM, elastic net, regression to the mean, predictive ceiling, calibration, Youden’s J, SHAP, Python</p>
  </div>
</div>

</header>


<section id="abstract" class="level2">
<h2 class="anchored" data-anchor-id="abstract">Abstract</h2>
<p>This study builds an admission-time forecast of inpatient length of stay for a diabetic cohort, using only information available at the moment of admission. The target, days in hospital, is an integer count structurally bounded at 1–14 by the source dataset’s inclusion criterion, right-skewed (skew 1.14, mean 4.38). A leakage audit restricts the feature set to the 23 columns known at or before admission and excludes 30 stay-accumulated clinical and medication features, each with a stated reason. Seven models were fitted on a patient-disjoint 80/20 split — a mean-only baseline, Poisson and Gamma generalised linear models, an elastic-net regression on log-transformed length of stay, a random forest, and LightGBM and XGBoost with Poisson objectives — and tuned on shared patient-disjoint inner folds. The champion was selected on Poisson deviance rather than mean absolute error, because deviance penalises mean-miscalibration and tail behaviour together, which MAE does not. That choice mattered: <strong>the elastic-net model has the best test MAE (2.19 days) but the worst Poisson deviance of all seven models — 1.888, above the mean-only baseline’s 1.884</strong> — because its expm1 back-transform produces a retransformation-biased point estimate that MAE cannot detect. The deviance champion (LightGBM, Poisson) reaches test R² 0.09, RMSE 2.85 days, and MAE 2.21 days, with a near-zero residual mean (+0.009) and decile calibration within roughly 0.1 days across the predicted range. Its predictions collapse toward the centre — actual stays span 1–14 days, predicted stays barely leave 3–7 — so the model is well-calibrated on average but weakly discriminating. A Youden-calibrated extended-stay flag (predicted stay ≥ 4.5 days for a true stay longer than a week, 15% prevalence) reaches 60% sensitivity at 63% specificity (AUC 0.65). A fairness audit across race and gender found no meaningful disparity among the two subgroups with enough test rows to support a claim.</p>
<p><em>Keywords:</em> length of stay, count regression, Poisson deviance, retransformation bias, model selection, regression to the mean, predictive ceiling, calibration</p>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Length of stay drives inpatient resource consumption — beds, staffing, discharge planning, downstream capacity. A forecast available <em>at admission</em>, before the clinical trajectory unfolds, is an operational planning signal that a post-hoc estimate cannot be. It does not need to be precise to the day; it needs to be well-calibrated and honest about where it is confident, so a discharge-planning team can use it without being misled.</p>
<p>The task has two constraints that shape the whole analysis. First, <strong>leakage</strong>. Most of the strong length-of-stay predictors in an administrative dataset — the count of lab procedures, the medication regimen, the discharge disposition, the secondary diagnoses — do not exist yet at the moment of prediction; they accumulate during the stay. Using them would inflate every metric and produce a model that cannot be deployed at admission. Second, the <strong>target’s shape</strong>. Days in hospital is a right-skewed integer count bounded at 14; a normal-error assumption is questionable, and the natural objectives are Poisson-family, not ordinary least squares.</p>
<p>The analysis is built around one methodological decision: <strong>select the champion on Poisson deviance, not test MAE</strong>. MAE treats a model that systematically mis-predicts the mean the same as one that is well-calibrated on average but noisier point-to-point. Deviance penalises both at once. In this ladder the two criteria disagree, and the disagreement is the central finding — the MAE-best model carries a retransformation bias that deviance exposes and MAE conceals.</p>
</section>
<section id="method" class="level2">
<h2 class="anchored" data-anchor-id="method">Method</h2>
<section id="data-target-and-leakage-audit" class="level3">
<h3 class="anchored" data-anchor-id="data-target-and-leakage-audit">Data, target, and leakage audit</h3>
<p>The source is the <em>Diabetes 130-US Hospitals for Years 1999–2008</em> dataset (Strack et al., 2014; Clore et al., 2014). The modelling cohort is 99,340 encounters. The regression target, <code>time_in_hospital</code>, is an integer count of days, bounded at 1–14 by the source dataset’s inclusion criterion — a structural boundary, not right-censoring within the data — so findings are scoped to stays of 14 days or fewer. It is right-skewed (skew 1.14, mean 4.38, median 4; Figure 1). A <code>log1p</code> transform reduces the skew to 0.11, which motivates fitting one model on the transformed target and using Poisson-family objectives for the rest.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/fig1_target_distribution.png" class="img-fluid figure-img"></p>
<figcaption>The target distribution: an integer count of days, bounded at 14 by the source cohort’s inclusion criterion, right-skewed with mean 4.4 and median 4.</figcaption>
</figure>
</div>
<p>The leakage audit retains <strong>23 features known at or before admission</strong> — age, prior-utilisation counts, gender, race, admission type and source, payer code, admitting specialty, and the primary-diagnosis group and its dummies — and <strong>excludes 30</strong>, each with a stated reason. The largest excluded block is stay-accumulated clinical and medication behaviour (lab-procedure count, medication count, the medication-change family). Discharge disposition is excluded on the same logic even though it is the single strongest predictor in the companion readmission model: it is determined at discharge, not admission. The readmission outcome is excluded as downstream.</p>
</section>
<section id="split-and-preprocessing" class="level3">
<h3 class="anchored" data-anchor-id="split-and-preprocessing">Split and preprocessing</h3>
<p>The holdout is the first fold of a <code>StratifiedGroupKFold</code> (5 splits, <code>random_state = 42</code>) on the patient identifier, stratified on a quantile binning of the target: <strong>79,528 training encounters, 19,812 test encounters</strong>, with zero patient overlap and near-identical mean length of stay across the split (4.38 versus 4.39 days). Numeric features were median-imputed and standardised; low-cardinality categoricals ordinal-encoded; the two high-cardinality columns (payer code, admitting specialty) target-encoded (in-sample).</p>
</section>
<section id="model-ladder-and-champion-selection" class="level3">
<h3 class="anchored" data-anchor-id="model-ladder-and-champion-selection">Model ladder and champion selection</h3>
<p>Seven models: a mean-only baseline; Poisson and Gamma generalised linear models with a log link (Nelder &amp; Wedderburn, 1972; McCullagh &amp; Nelder, 1989); an elastic-net regression fitted on <code>log1p(target)</code> and back-transformed with <code>expm1</code> (Zou &amp; Hastie, 2005); a random forest (Breiman, 2001); and LightGBM and XGBoost with Poisson objectives (Ke et al., 2017; Chen &amp; Guestrin, 2016). The six non-baseline models share one preprocessing pipeline and are tuned with <code>RandomizedSearchCV</code> on the same five pre-materialised patient-disjoint inner folds, so their cross-validated MAE figures are directly comparable.</p>
<p>The champion is selected on <strong>test Poisson deviance</strong>. MAE and cross-validated MAE are reported alongside for transparency, and the analysis states explicitly whether the deviance pick differs from the MAE-only pick. The <code>log1p</code>/<code>expm1</code> model is the case the deviance criterion is designed to catch: back-transforming a model fitted in log space produces a biased point estimate on the original scale (Jensen’s inequality; the classic correction is the smearing estimator of Duan, 1983), which scores well on MAE while systematically misrepresenting the conditional mean.</p>
</section>
<section id="validation-lenses" class="level3">
<h3 class="anchored" data-anchor-id="validation-lenses">Validation lenses</h3>
<p>The confirmed champion was checked four ways: residual diagnostics and a predicted-versus-actual density; calibration by predicted-length-of-stay decile (mean actual versus mean predicted within each bin); an operational framing (share of predictions within one and two days, error by primary diagnosis group, and a Youden’s <em>J</em>–calibrated extended-stay flag for a stay longer than a week; Youden, 1950); a fairness audit of per-subgroup error across race and gender (Bird et al., 2020); and a SHAP explainability pass on the champion (Lundberg &amp; Lee, 2017).</p>
</section>
<section id="reproduction-and-software" class="level3">
<h3 class="anchored" data-anchor-id="reproduction-and-software">Reproduction and software</h3>
<p>Every number was recomputed from the persisted <code>model_comparison.csv</code>, <code>calibration_table.csv</code>, the per-group tables, the stored <code>test_predictions.parquet</code>, and the champion’s SHAP result object. No model was re-trained. Python 3.10 with <code>scikit-learn</code> 1.2, <code>lightgbm</code>, <code>xgboost</code>, <code>statsmodels</code>, and <code>fairlearn</code>.</p>
</section>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<section id="the-ladder-and-the-maedeviance-disagreement" class="level3">
<h3 class="anchored" data-anchor-id="the-ladder-and-the-maedeviance-disagreement">The ladder, and the MAE–deviance disagreement</h3>
<p>The seven models span a narrow band (<strong>Table 1</strong>, Figure 2). On MAE the leader is the <strong>elastic-net on <code>log1p</code> (2.186 days)</strong>, with XGBoost second (2.189) and the LightGBM–Poisson champion third (2.210); the mean-only baseline is 2.351. On Poisson deviance the order changes: <strong>LightGBM (Poisson) is best at 1.706</strong>, and the elastic-net is <strong>last at 1.888 — worse than the mean-only baseline’s 1.884</strong>. Every other model’s deviance rank roughly tracks its MAE rank; the elastic-net is the sole outlier, and in the predicted direction. Its <code>expm1</code> back-transform yields a point estimate that minimises absolute error while systematically misrepresenting the conditional mean, exactly what deviance penalises and MAE does not. Selecting on deviance therefore promotes the model that already had the best RMSE (2.851) and the best R² (0.091) in the ladder, at a test-MAE cost of 0.024 days.</p>
<p><strong>Table 1</strong></p>
<p><em>Seven-Model Ladder on the Held-Out Test Set (n = 19,812)</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th>MAE (days)</th>
<th>RMSE</th>
<th>R²</th>
<th>Poisson deviance</th>
<th>Within 1 day</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Elastic-net (<code>log1p</code>)</td>
<td><strong>2.186</strong></td>
<td>2.982</td>
<td>0.006</td>
<td><strong>1.888</strong> (worst)</td>
<td>31.1%</td>
</tr>
<tr class="even">
<td>XGBoost (Poisson)</td>
<td>2.189</td>
<td>2.897</td>
<td>0.062</td>
<td>1.761</td>
<td>28.5%</td>
</tr>
<tr class="odd">
<td>LightGBM (Poisson) — champion</td>
<td>2.210</td>
<td><strong>2.851</strong></td>
<td><strong>0.091</strong></td>
<td><strong>1.706</strong> (best)</td>
<td>27.4%</td>
</tr>
<tr class="even">
<td>Random forest</td>
<td>2.220</td>
<td>2.868</td>
<td>0.081</td>
<td>1.729</td>
<td>27.4%</td>
</tr>
<tr class="odd">
<td>GLM (Poisson)</td>
<td>2.258</td>
<td>2.901</td>
<td>0.059</td>
<td>1.767</td>
<td>26.3%</td>
</tr>
<tr class="even">
<td>Gamma GLM (log link)</td>
<td>2.258</td>
<td>2.903</td>
<td>0.058</td>
<td>1.768</td>
<td>26.3%</td>
</tr>
<tr class="odd">
<td>Baseline (mean)</td>
<td>2.351</td>
<td>2.991</td>
<td>0.000</td>
<td>1.884</td>
<td>23.8%</td>
</tr>
</tbody>
</table>
<p><em>Note.</em> The MAE leader (elastic-net) has the worst Poisson deviance of all seven — the deviance criterion’s target failure mode. The champion is selected on deviance.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/fig2_mae_vs_deviance_ladder.png" class="img-fluid figure-img"></p>
<figcaption>The seven-model ladder sorted by Poisson deviance (amber, right axis) with test MAE alongside (blue, left axis). LightGBM (Poisson) has the lowest deviance but only the third-lowest MAE; the elastic-net has the lowest MAE and the highest deviance — above the mean-only baseline.</figcaption>
</figure>
</div>
</section>
<section id="a-calibrated-champion-at-a-low-predictive-ceiling" class="level3">
<h3 class="anchored" data-anchor-id="a-calibrated-champion-at-a-low-predictive-ceiling">A calibrated champion at a low predictive ceiling</h3>
<p>The deviance champion is well-calibrated on average. Its residual mean is <strong>+0.009 days</strong> (no systematic bias), its residual standard deviation equals its RMSE (2.851) as expected for a well-behaved residual, and by predicted-length-of-stay decile the mean actual tracks the mean predicted to within about 0.1 days across the whole range — the largest gap is a 0.11-day over-prediction in the top decile (Figure 4).</p>
<p>But calibrated is not accurate. The champion reaches <strong>R² 0.09</strong> — barely ahead of predicting the mean for everyone — and its predictions collapse toward the centre (Figure 3): actual stays span the full 1–14 days, predicted stays barely leave the 3–7 range. It flags 27% of predictions within one day of the truth and 54% within two, against the baseline’s 24% and 48%. This is a predictive ceiling: with only admission-time information — no lab activity, no medication regimen, no clinical trajectory — the model can rank patients by expected length of stay weakly and estimate the cohort-mean-conditional-on-covariates well, but it cannot predict an individual stay.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/fig3_predicted_vs_actual_hexbin.png" class="img-fluid figure-img"></p>
<figcaption>Actual versus predicted length of stay for the champion (log-scaled density, full test set). Actual stays run the full 1–14 days; predicted stays cluster in a narrow 3–7-day band — regression toward the conditional mean under a weak signal.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/fig4_decile_calibration.png" class="img-fluid figure-img"></p>
<figcaption>Calibration by predicted-length-of-stay decile. Mean actual (y) against mean predicted (x) within each of ten equal-count bins; the champion sits within about 0.1 days of the identity line across the whole range.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/fig5_residual_diagnostics.png" class="img-fluid figure-img"></p>
<figcaption>Champion residuals. Left: residuals versus fitted values (diagonal banding is the integer target). Right: the residual distribution — centred on zero but right-skewed, because long stays are systematically under-predicted. Calibrated on average, wide per patient.</figcaption>
</figure>
</div>
</section>
<section id="an-advisory-extended-stay-flag" class="level3">
<h3 class="anchored" data-anchor-id="an-advisory-extended-stay-flag">An advisory extended-stay flag</h3>
<p>Treating the champion’s continuous prediction as a risk score for a stay longer than a week (15% of the test set), the ranking AUC is <strong>0.65</strong> — real but modest (Figure 6). The Youden-optimal cutoff is a predicted length of stay of <strong>4.52 days</strong>, at which the flag reaches <strong>60% sensitivity and 63% specificity</strong> (1,772 true positives, 6,237 false positives, 1,198 false negatives, 10,605 true negatives). Roughly six in ten genuinely extended stays are flagged, at the cost of also flagging about a third of the patients who will not have one. That is a starting point for a discharge-planning review, not a precise clinical trigger.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/fig6_extended_stay_flag.png" class="img-fluid figure-img"></p>
<figcaption>The extended-stay flag (true length of stay over 7 days). Left: the ROC for the champion’s prediction as a ranking score (AUC 0.65) with the Youden-optimal operating point marked. Right: the predicted-length-of-stay distribution split by true extended-stay status, with the 4.52-day cutoff.</figcaption>
</figure>
</div>
<p>Error is not uniform across diagnosis groups (Figure 7, <strong>Table 2</strong>): from 1.62 mean absolute days for musculoskeletal admissions (the most predictable) up to 2.60 for neoplasms (the least). The spread looks like genuine differences in how predictable each condition’s stay is, not model-selection noise.</p>
<p><strong>Table 2</strong></p>
<p><em>Champion Mean Absolute Error by Primary Diagnosis Group (test set, groups with n ≥ 100)</em></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Diagnosis group</th>
<th>Mean absolute error (days)</th>
<th>n</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Musculoskeletal</td>
<td>1.62</td>
<td>1,003</td>
</tr>
<tr class="even">
<td>Genitourinary</td>
<td>2.09</td>
<td>1,013</td>
</tr>
<tr class="odd">
<td>Digestive</td>
<td>2.14</td>
<td>1,864</td>
</tr>
<tr class="even">
<td>Diabetes</td>
<td>2.18</td>
<td>1,693</td>
</tr>
<tr class="odd">
<td>Respiratory</td>
<td>2.22</td>
<td>2,842</td>
</tr>
<tr class="even">
<td>Injury</td>
<td>2.24</td>
<td>1,366</td>
</tr>
<tr class="odd">
<td>Circulatory</td>
<td>2.24</td>
<td>5,866</td>
</tr>
<tr class="even">
<td>Other</td>
<td>2.33</td>
<td>3,555</td>
</tr>
<tr class="odd">
<td>Neoplasms</td>
<td>2.60</td>
<td>605</td>
</tr>
</tbody>
</table>
<p><em>Note.</em> Overall MAE 2.21 days. A tiny “Missing” group (n = 5) is omitted.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/fig7_shap_and_diagnosis_error.png" class="img-fluid figure-img"></p>
<figcaption>Left: mean absolute SHAP for the champion — admitting specialty and age lead, then payer code and prior inpatient visits. Right: mean absolute error by primary diagnosis group — neoplasms are the least predictable, musculoskeletal admissions the most.</figcaption>
</figure>
</div>
</section>
<section id="fairness-and-drivers" class="level3">
<h3 class="anchored" data-anchor-id="fairness-and-drivers">Fairness and drivers</h3>
<p>The fairness audit compares per-subgroup error across race and gender. Only two subgroups have enough test rows for a confident claim — Caucasian (76% of the test set) and African American (18%) — and within them the error differences are small: Caucasian female 2.21 versus male 2.18, African American female 2.26 versus male 2.30, all under 0.15 days. The smallest subgroups show a wider apparent spread (Asian male 2.47 on 59 rows, Missing male 2.02 on 220) but are too thin to treat as findings. No meaningful disparity is surfaced among the groups that can be assessed with confidence.</p>
<p>SHAP attributions put <strong>admitting specialty and age</strong> at the top of the champion’s drivers (target-encoded specialty carrying most of the signal, as in the readmission model), followed by payer code, prior inpatient visits, and admission source and type (Figure 7). These are administrative and demographic proxies for case mix; the clinical detail that would sharpen the forecast is precisely what the leakage audit correctly withholds.</p>
</section>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<p><strong>Principal findings.</strong> From admission-time information alone, length of stay in this cohort is predictable only weakly: the champion reaches R² 0.09 and its predictions regress toward a narrow central band. It is, however, well-calibrated — residual mean near zero, decile calibration within 0.1 days — which is the property a planning signal needs. The methodological result is that MAE is the wrong criterion for selecting a count-regression model: the MAE-best model here carries a retransformation bias, has the worst Poisson deviance of the seven, and would have been crowned by an MAE-only comparison.</p>
<p><strong>Why the ceiling is low.</strong> The signal that actually determines a stay’s length — how the workup unfolds, what procedures are ordered, how the medication regimen changes, where the patient is discharged to — accumulates <em>during</em> the admission and is deliberately excluded here. What remains is case-mix proxies: specialty, age, payer, prior utilisation, primary diagnosis. Those carry enough information to estimate a covariate-conditional mean well and to rank extended-stay risk modestly, but not to forecast an individual duration. This is the length-of-stay counterpart of the readmission model’s diffuse-signal ceiling and the crime-severity regression’s context-only ceiling: when the causal drivers are withheld, the remaining context explains little.</p>
<p><strong>Operational read.</strong> The champion is usable today as a discharge-planning input, not a decision-maker. The extended-stay flag at a predicted 4.5 days is a defensible advisory threshold for triggering a planning review, appropriate to pilot alongside existing workflows rather than to drive bed allocation. What the notebook leaves behind independent of the specific champion: a reusable admission-time-safe feature audit, a documented case for deviance over MAE as the selection criterion for a count target, and a Youden-calibrated flag rather than an arbitrary cutoff.</p>
<p><strong>Limitations.</strong> Single train/test split on a historical cohort; the target encoder is in-sample; the extended-stay threshold and the fairness metrics are diagnostics on the same holdout. The 1–14-day boundary is a source inclusion criterion, so nothing here generalises to longer stays. SHAP was computed on 500 test rows on the model’s log-link scale.</p>
<p><strong>Conclusion.</strong> Admission-time length of stay is a low-ceiling forecast — calibrated but not accurate — and the honest way to select among count-regression models for it is on deviance, not MAE. The champion is a modest planning aid; its main contribution is the demonstration of a metric-selection trap that a leaderboard sorted by MAE would have fallen into.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<p>Bird, S., Dudík, M., Edgar, R., Horn, B., Lutz, R., Milan, V., … Walker, K. (2020). <em>Fairlearn: A toolkit for assessing and improving fairness in AI</em> (Technical Report MSR-TR-2020-32). Microsoft.</p>
<p>Breiman, L. (2001). Random forests. <em>Machine Learning, 45</em>(1), 5–32. https://doi.org/10.1023/A:1010933404324</p>
<p>Chen, T., &amp; Guestrin, C. (2016). XGBoost: A scalable tree boosting system. In <em>Proceedings of the 22nd ACM SIGKDD International Conference on Knowledge Discovery and Data Mining</em> (pp.&nbsp;785–794). https://doi.org/10.1145/2939672.2939785</p>
<p>Clore, J., Cios, K., DeShazo, J., &amp; Strack, B. (2014). <em>Diabetes 130-US Hospitals for Years 1999–2008</em> [Data set]. UCI Machine Learning Repository. https://doi.org/10.24432/C5230J</p>
<p>Duan, N. (1983). Smearing estimate: A nonparametric retransformation method. <em>Journal of the American Statistical Association, 78</em>(383), 605–610. https://doi.org/10.1080/01621459.1983.10478017</p>
<p>Ke, G., Meng, Q., Finley, T., Wang, T., Chen, W., Ma, W., … Liu, T.-Y. (2017). LightGBM: A highly efficient gradient boosting decision tree. In <em>Advances in Neural Information Processing Systems 30</em> (pp.&nbsp;3146–3154).</p>
<p>Lundberg, S. M., &amp; Lee, S.-I. (2017). A unified approach to interpreting model predictions. In <em>Advances in Neural Information Processing Systems 30</em> (pp.&nbsp;4765–4774).</p>
<p>McCullagh, P., &amp; Nelder, J. A. (1989). <em>Generalized linear models</em> (2nd ed.). Chapman &amp; Hall. https://doi.org/10.1007/978-1-4899-3242-6</p>
<p>Nelder, J. A., &amp; Wedderburn, R. W. M. (1972). Generalized linear models. <em>Journal of the Royal Statistical Society: Series A, 135</em>(3), 370–384. https://doi.org/10.2307/2344614</p>
<p>Strack, B., DeShazo, J. P., Gennings, C., Olmo, J. L., Ventura, S., Cios, K. J., &amp; Clore, J. N. (2014). Impact of HbA1c measurement on hospital readmission rates: Analysis of 70,000 clinical database patient records. <em>BioMed Research International, 2014</em>, 781670. https://doi.org/10.1155/2014/781670</p>
<p>Youden, W. J. (1950). Index for rating diagnostic tests. <em>Cancer, 3</em>(1), 32–35.</p>
<p>Zou, H., &amp; Hastie, T. (2005). Regularization and variable selection via the elastic net. <em>Journal of the Royal Statistical Society: Series B, 67</em>(2), 301–320. https://doi.org/10.1111/j.1467-9868.2005.00503.x</p>
<hr>
<p><em>Single-split regression on a historical extract, scoped to stays of 14 days or fewer; the target encoder and the operating-point diagnostics use the same holdout. The champion is calibrated on average, not accurate per patient; the reported R² of 0.09 is the leakage-controlled admission-time ceiling.</em></p>


<div id="contact" class="connect-section" style="text-align: center; padding: 50px 20px; background: #f9f9f9; border-radius: 15px; border: 1px solid #eaeaea; margin-top: 40px;">
<h3 style="color: #2c3e50; font-weight: 700; margin-bottom: 15px; border: none;" class="anchored">Let's Collaborate</h3>
<p style="color: #666; max-width: 650px; margin: 0 auto 30px auto; font-size: 1.05rem; line-height: 1.6;">Available for high-impact <strong>Business Intelligence, Power BI Engineering, and Advanced Data Analytics</strong> projects. Connect with me or hire me directly through the platforms below.</p>
<div style="display: flex; flex-wrap: wrap; justify-content: center; gap: 12px;">
<a href="https://www.linkedin.com/in/mkmuneer" class="btn btn-primary" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; text-decoration: none;"><i class="bi bi-linkedin"></i> LinkedIn</a>
<a href="https://github.com/mkhanmuneer" class="btn btn-dark" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; text-decoration: none;"><i class="bi bi-github"></i> GitHub</a>
<a href="https://www.kaggle.com/muhammadkhanmuneer" class="btn btn-info" target="_blank" rel="noopener" style="color: white; padding: 12px 25px; min-width: 150px; text-decoration: none;"><i class="bi bi-graph-up"></i> Kaggle</a>
<a href="https://www.upwork.com/freelancers/~018de8553286a1d00c" class="btn btn-outline-success" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; border-width: 2px; font-weight: 600; text-decoration: none;"><i class="bi bi-briefcase"></i> Upwork</a>
<a href="https://www.fiverr.com/neuronvision" class="btn btn-outline-success" target="_blank" rel="noopener" style="padding: 12px 25px; min-width: 150px; border-width: 2px; font-weight: 600; text-decoration: none;"><i class="bi bi-lightning-charge"></i> Fiverr</a>
</div>
</div>

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/mkhanmuneer\.github\.io\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 Muhammad Khan Muneer</p>
</div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://www.upwork.com/freelancers/~018de8553286a1d00c">
<p>Hire on Upwork</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="https://www.fiverr.com/neuronvision">
<p>Hire on Fiverr</p>
</a>
  </li>  
</ul>
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mkhanmuneer">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/mkmuneer">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>